### ISSUE TITLE
Dual interface for methods

### ISSUE THREAD

**Issue by agnellvj** [karmi/retire#1]
I would like to push this to the top of the queue.  I started digging into the source and it seems like the simplest solution would be to add another method like "method_hash".  I am not sure this is the best way to do it or maybe if you are calling it with  just a hash, set the type to be nil and do some logic in the method to signify this.

**Comment by karmi** [comment]
Hmm, I don't know if I understand correctly, but yes, I'd like majority of the methods to be able to just take a Hash and feed it down the line to ES. However, I'd like to do this _after_ the API is stabilized. Moreover, full ActiveModel compatibility (see `activemodel` branch) is _the_ ultimate priority for next couple of weeks.

**Comment by agnellvj** [comment]
ah, ok, the app I am working on doesn't use AR at all for the documents.

**Comment by karmi** [comment]
Mine neither :), but ActiveModel for sure (CouchDB in my case).

**Comment by karmi** [comment]
Implemented for `Slingshot.search` in karmi/slingshot@d1f75227fefb89759728488c841210714b22fe9c
