### ISSUE TITLE
Add "count" queries

### ISSUE THREAD

**Issue by lennartkoopmann** [karmi/retire#100]
From what I can see it is not possible to do real count queries, right? It would be great to have that.

I am now doing something like this with size 0 to avoid having the whole result set transferred to my application:

```
search do
  filter 'range', {
    :created_at => { :from => x.minutes.ago.to_i, :include_upper => true  }
  }
  size 0
end.total
```

A general suggestion: It would be great to have a mailing list for these kind of questions. I feel bad posting such issues without being totally sure if I am not doing the counting wrong! :)

**Comment by karmi** [comment]
Yeah, there's no support for `search_type=count`, yet. We're doing `size 0` queries as well, so far it has not been a pain for the documents in the range of tens of millions for the total index count.

As for the mailing list: I've got nothing in principle against creating a dedicated mailing list. However, I don't like Google Groups (the experience, the crappy and ugly GUI, etc), nor Librelist, nor anything else I've seen.

To me, discussing stuff via Github Issues is pleasant, it's easy to keep track of conversations, it keeps the discussion focused on code, it's very easy to reference commits or close issues from commits, etc.

Maybe folks who're watching the repo do mind the chatter, but I like it the way it is, in general.

So: don't hesistate and post questions and such via issues. The other option is the #elasticserch channel at Freenode (IRC.
