### ISSUE TITLE
Search a set of records

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#102]
Hi @karmi. I couldn't seem to find a way to search specific records only. What do I mean? This doesn't work, but it illustrates it pretty clearly:

```
Article.unpublished.search "string here"
```

Where `unpublished` is a scope that selects only articles whose `published_at` dates are in the future or nil.

Thanks!

**Comment by karmi** [comment]
Hi,

this is not possible, presently. I'm aware some search libraries, notably _ThingkingSphinx_ allow something like this, but not _Tire_. You have to specify the search conditions, manually, yourself. The support for `boolean` queries and the ability to extract them into blocks/lambdas/methods should help here -- see Readme.

I'll add more examples how to extract boolean search blocks into model/module methods, based on how the @ruby-amqp guys do it (http://rdoc.info/github/ruby-amqp/amqp/master/file/docs/GettingStarted.textile#Integration_with_objects).
