### ISSUE TITLE
MasterNotDiscoveredException when trying to import

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#106]
Hi Karmi,

I'm running into the error you see in the title when I try to import.

Tire version: `0.3.3`
ElasticSearch version: `0.17.5 (2011-08-12T12:13:16), JVM: 20.1-b02-383`
Mac OSX Lion

The error can be found here: https://gist.github.com/1231210

When I visit `localhost:9200`, I see that the ES server is up:

```
{
  "ok" : true,
  "name" : "Godfrey Calthrop",
  ... snip ...
  }
}
```

When I take a look at the log of ES I see these though:

```
Exception: Failed to deserialize response of type [org.elasticsearch.discovery.zen.membership.MembershipAction$JoinResponse]; org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.discovery.zen.membership.MembershipAction$JoinResponse]; java.io.IOException: Expected handle header, got [116]]
```

Based on the type of error it looks like it's trying to find other servers. However, I didn't configure ES differently -- I just did the `homebrew install elasticsearch`, copy-and-pasted the 3 or 4 lines you're asked to copy and paste for new installs, then tried to import.

Thanks for your help!

**Comment by karmi** [comment]
Hmm, that's kinda weird. I can run `bundle exec rake environment tire:import CLASS='Article' FORCE=true` in a test app just fine. Could you generate a fresh app with the command:

```
 $ rails new searchapp -m https://github.com/karmi/tire/raw/master/examples/rails-application-template.rb
```

to see if it fails as well? Note that I have my local ES set to `number_of_shards:1` and `number_of_replicas:1`.

**Comment by ramontayag** [comment]
@karmi, I edited my [elastic search config](https://gist.github.com/1234000) to match yours (but I'm not sure I did it right. I read [their config tutorial](http://www.elasticsearch.org/guide/reference/setup/configuration.html) and guessed the path for `number_of_shards` and `number_of_replicas` based on [another tutorial](http://www.elasticsearch.org/guide/reference/api/admin-indices-create-index.html) on the elastic search site. I hope it's right! Anyway, I restarted elastic search and then generated a new app with your template. I see:

```
[IMPORT] Starting import for the 'Article' class
--------------------------------------------------------------------------------
5/5 | 100% [ERROR] 500 > {"error":"MasterNotDiscoveredException[]","status":500}, retrying (1)...
[ERROR] 500 > {"error":"MasterNotDiscoveredException[]","status":500}, retrying (2)...
[ERROR] 500 > {"error":"MasterNotDiscoveredException[]","status":500}, retrying (3)...
[ERROR] 500 > {"error":"MasterNotDiscoveredException[]","status":500}, retrying (4)...
[ERROR] 500 > {"error":"MasterNotDiscoveredException[]","status":500}, retrying (5)...
[ERROR] Too many exceptions occured, giving up. The HTTP response was: 500 > {"error":"MasterNotDiscoveredException[]","status":500}
# 2011-09-22 12:02:47:L [BULK] ("articles")
#
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'

# 2011-09-22 12:02:47:L [500]
```

**Comment by ramontayag** [comment]
@karmi, with some help we found the problem! We were all using these settings:

```
cluster:
  name: mtraks2boracay
```

For some reason I assumed that to connect to a cluster I had to do more configuration -- but I was wrong! So it was trying to connect to the other computers already running elastic search. To fix it, we changed the name of the cluster.
