### ISSUE TITLE
0.3.3 breaks site if no ES is running

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#107]
For some dev machines, we don't have ES running. It just makes setup simpler. The problem is that when we upgraded to `0.3.3`, loading models that implement Tire broke the site:

```
NoMethodError in HomeController#index
undefined method `body' for nil:NilClass

Application trace:
app/models/artist.rb:33
app/models/artist.rb:32
app/controllers/home_controller.rb:13:in `index'
```

That is probably not Tire specific, but here are the lines 31-36 of `artist.rb`:

```
index_name(Rails.env)
settings(App.tire_index_settings) do
  mapping do
    indexes :name, :type => "string", :analyzer => "name_analyzer"
  end
end
```

[App.tire_index_settings](https://gist.github.com/1231270) is the hash config I just save somewhere else.

**Comment by karmi** [comment]
Hmm, Tire attempts to [create the index](https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L91-95) when you use `mapping` declaration, checking if it exist first.

That should not raise any exception, though, on application start. Only when you search, you should receive `Errno::ECONNREFUSED`. Just checked now.

I'm wondering what's the `undefined method 'body' for nil:NilClass` error. 

The main change in v0.3.3 is the "agnostic HTTP": https://github.com/karmi/tire/compare/v0.3.2...v0.3.3

Again, could you try it in the generated app first, please?

**Comment by changa** [comment]
I'm having the same problem, but the error actually is `'rescue in head': undefined method 'http_body' for #<Errno::ECONNREFUSED: Connection refused - connect(2)>`, triggered from https://github.com/karmi/tire/blob/master/lib/tire/http/client.rb#L36

**Comment by karmi** [comment]
@ramontayag: The issue is, of course, that I was checking an app launched in _development_ mode. In _production_, the model classes would be eagerly loaded by Rails and you'd see the exception immediately. Should be fixed no, can you check against current master?

**Comment by karmi** [comment]
@changa: Can you check the issue in your app against current master?

**Comment by changa** [comment]
@karmi : Yup, It's fine now! (Sorry for taking such a friggin' long time to answer.)

**Comment by karmi** [comment]
Cool.

**Comment by ramontayag** [comment]
Gosh - sorry I missed this one too.
