### ISSUE TITLE
Kaminari integration with empty result sets ends up dividing by zero

### ISSUE THREAD

**Issue by michaelklishin** [karmi/retire#110]
I am trying to use Tire with Mongoid and recently committed Kaminari support. Looks like if you have a chain like this

``` ruby
MyModel.page(1).per(10).tire.search(params[:q])
```

then Kaminari support ends up dividing by zero. The problematic line is [this one](https://github.com/karmi/tire/blob/master/lib/tire/results/pagination.rb#L24)

``` ruby
(@options[:size].to_i + @options[:from].to_i) / @options[:size].to_i
```

I am not sure I understand the intent here. If page is not known and result set is empty, the best we can do is to default to 1. Then it is 0 / 1 and things work as expected.

Is my understanding correct? I would be happy to submit a PR if someone can explain me what the :size option is.

**Comment by michaelklishin** [comment]
Also, changing #current_page to work like this

``` ruby
if @options[:size]?
  (@options[:size].to_i + @options[:from].to_i) / @options[:size].to_i
else
  1
end
```

makes the issue go away. I am not sure if there is a better way to solve it.

**Comment by karmi** [comment]
Hi, yeah, there's definitely a bug there.

The `:size` and `:from` options are valid, when you're searching with the block syntax, see this integration test: https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L229-234

Will look into that.

**Comment by michaelklishin** [comment]
Looks like will_paginate does not support mongoid so I am looking into this issue myself.

**Comment by mlitwiniuk** [comment]
Imo #current_page could be changed into something like this:

``` ruby
def current_page
  if @options[:page]
    @options[:page].to_i
  else
    from = @options[:from].to_i || 0
    (per_page + from) / per_page
  end
end
```

**Comment by karmi** [comment]
@mlitwiniuk: Yeah, that's the way to go, the code is insanely using all the instance var instead of the accessor method. Will change that all.

**Comment by karmi** [comment]
@michaelklishin: Please check the current master, the issue should be fixed.
