### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by lennartkoopmann** [karmi/retire#111]
Do I have to care about query escaping myself or is tire doing that? I am asking because I just noticed that doing a search with a bracket ([) in it, lead to a HTTP 500 from the elasticsearch server:

```
Caused by: org.apache.lucene.queryParser.ParseException: Encountered " "]" "] "" at line 1, column 12.
Was expecting one of:
    "TO" ...
    <RANGEIN_QUOTED> ...
    <RANGEIN_GOOP> ...

    at org.apache.lucene.queryParser.QueryParser.generateParseException(QueryParser.java:1818)
    at org.apache.lucene.queryParser.QueryParser.jj_consume_token(QueryParser.java:1700)
    at org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1455)
    at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1309)
    at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1237)
    at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1226)
    at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
    ... 18 more
```

**Comment by jsuchal** [comment]
See http://lucene.apache.org/java/2_4_0/queryparsersyntax.html#Escaping Special Characters - Lucene query language uses `[` for defining range queries.

**Comment by karmi** [comment]
@lennartkoopmann: Yeah, your query is invalid. ES expects closing `]`, and interprets your query as a range query.

_Tire_ isn't doing any automatic escaping, since that would mean we'd escape your range query -- and you don't want that :) So, you have to properly excape everything by yourself...

**Comment by lennartkoopmann** [comment]
Thanks for your answer! I now have a problem with the escaping itself. Imagine I have this term I want to search for: foo-bar

I have to escape the minus sign in it with a backslash. It somehow gets double escaped on its way through tire. This query string is sent to ElasticSearch: (using `term(:foo, 'foo\-bar')`)

```
{"query":{"bool":{"must":[{"query_string":{"query":"message:*"}},{"term":{"foo":"foo\\-bar"}}]}},"sort":[{"created_at":"desc"}],"size":100,"from":0}
```

ElasticSearch obviously does not like that and fails at parsing the query.

I already played around with different Ruby string notations like with single and double quoted, double and single escaping etc.

Am I doing something wrong? Thanks for any help!

EDIT: The double slashes are required because it's JSON I guess. Still not sure how I should escape it then. :)

**Comment by karmi** [comment]
_Tire_ does not do any escaping, so any escaping is done by the JSON gem you're using.

The weird thing is, I'm able to do all the queries you describe:

``` ruby
require 'rubygems'
require 'tire'

Tire.index 'test' do
  delete
  store :content => 'Foo-Bar Test'
  refresh
end

s = Tire.search 'test' do
  query { string 'foo-bar' }
end

puts s.to_curl

s.results.each do |document|
  p document
end
```

> I have to escape the minus sign in it with a backslash.

Why?

**Comment by lennartkoopmann** [comment]
I have to escape it, because it is a special character of Lucene: http://lucene.apache.org/java/2_4_0/queryparsersyntax.html#Escaping

Did you find your documents including 'foo-bar' with it? I don't get any results - Because of the special character I suppose.

**Comment by karmi** [comment]
Yeah, I did found the document -- just run the script.

The `-` has meaning only if preceded by a space, AFAIK. `foo-bar` is different then `foo -bar`, which does translate to `foo NOT bar`.

**Comment by lennartkoopmann** [comment]
But if I index two documents with a field `host` which is `foo-bar` and one which is `foobar` and term search for it, it will find the `foobar` but not `foo-bar`.

EDIT: (Using two searches. One for `foobar` that finds the document, one with `foo-bar` that does not)

**Comment by karmi** [comment]
Lennart, post a full Ruby snippet (eg. based on mine) so we can both _just launch it_ and not out-guess each other :)

**Comment by lennartkoopmann** [comment]
Sure! Here we go:

```
require 'rubygems'
require 'tire'

["foobar", "foo-bar"].each do |what|
  Tire.index 'escape-test' do
    delete
    store :host => what
    refresh
  end

  s = Tire.search 'escape-test' do
    query { term(:host, what) }
  end

  puts s.to_curl

  puts "FOUND #{s.results.count} documents for #{what}"

  s.results.each do |document|
    p document
  end
end
```

Thanks!

**Comment by karmi** [comment]
@lennartkoopmann: You're using a `term` query, which is not analyzed, ie. broken into tokens. Your document, on the other hand, is broken into tokens "foo" and "bar". Do a seach for `foo`.

As always in ES, there are many approaches to the situation -- best to ask on IRC.

**Comment by lennartkoopmann** [comment]
Ah! Thank you very much! :)

**Comment by fgrehm** [comment]
@karmi I've just came across escaping issues down here and I wasn't aware that I had to do it myself. do you think it is worth adding a note somewhere on the readme so that others don't run into it as well? maybe also mention `Tire::Utils.escape` too :-)

**Comment by karmi** [comment]
@fgrehm Unfortunately, we can't really escape it automatically, and it's generally known that Lucene query string has "special" characters... In any case, best to use the `match` query in Tire, and special queries such as `range` etc for special cases...

**Comment by fgrehm** [comment]
@karmi tks a lot for the quick answer :-)
