### ISSUE TITLE
Allow Manually Controlling Callbacks

### ISSUE THREAD

**Issue by Rio517** [karmi/retire#114]
Hi, 

I have a lot of ActiveModel documents I don't want indexed - almost 80% of my records.  I tried removing the `include Tire::Model::Callbacks`, but then get an undefined method error: 

<pre><code>`undefined method `_run_update_elasticsearch_index_callbacks' for ...</code></pre>

 from this line https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L128

Is there some way around this?  How can I disable callbacks and take control over when update_index is called?  Otherwise, is there some way to filter records that are getting indexed?  For instance, I only want articles with a state of published to be indexed.

Thanks!

-Mario

**Comment by karmi** [comment]
Hi, when do you get the exception? Because simply not including `Callbacks` should work. That's the initial reason for splitting the functionality. I cannot replicate the issue.

> I only want articles with a state of published to be indexed

No problem -- you have to solve it in your app, since it and only it knows the domain in that case. Something like:

``` ruby
    class Article

      after_save do
        self.update_index if self.state == 'published'
      end

      # ...

    end
```

**Comment by Rio517** [comment]
Yep.  That is exactly the behavior I was expecting and exactly what I wanted to do.

Here is a sample app. Run rake db:migrate then  db:seed and it will create data, index it and run the command to generate the error.   Console output of my error is in the readme.

https://github.com/Rio517/tire-sample-error

-Mario

**Comment by karmi** [comment]
Hi, thanks for the sample app, I figured out what's the problem. Please check on current master, should be fixed.

**Comment by karmi** [comment]
Ping, @Rio517. Any success with the fix?

**Comment by Rio517** [comment]
All working well! Thanks!

**Comment by karmi** [comment]
Pefect!
