### ISSUE TITLE
AND as default operator & Highlighting with Boosting -- need clarification on how to do

### ISSUE THREAD

**Issue by mikeg250** [karmi/retire#118]
Hi Karel,

Your Tire gem is very well documented and seems like a good alternative to Solr/Sunspot.   However, I am confused about a two items and wanted to get your advice:

What is the best way to set up a search box to default to AND (instead of OR)  for multiple keyword entries (similar to Google)?  I was looking for a way to set the default operator like you would in Solr's schema.xml, but can’t seem to find the right instructions for Tire/Elasticsearch.  Here is specifically what I’m confused about:

https://github.com/elasticsearch/elasticsearch/issues/1009 indicates that Elasticsearch doesn’t yet support a switch to AND (from OR) as a global setting.

This Pull Request on your github looks like it may work:
https://github.com/seejohnrun/tire/commit/55ed2409864664f81f26fe75bf1bb5a9143c37f8
but I’m not sure where to actually put the AND operator in the code (probably because I’m having to learn Ruby as my first language so I can set up a working a prototype).

In addition, down the line I would like to use the more advanced Query DSL, but your highly detailed and helpful  tire.rb overview seems to indicate that Tire doesn’t yet support the AND filter (not sure yet if this is the same as the AND operator). 

Can you suggest the best method for setting up Tire (or Elasticsearch) to default to AND instead of OR?

Also, will Tire allow Highlighting to work with custom_score or boosting?  I ask because I saw this open pull request on Elasticsearch https://github.com/elasticsearch/elasticsearch/pull/1315

Thank you,

Mike G

**Comment by vhyza** [comment]
Hello,

I think you can't set default operator as global setting in tire. But searching by string should support to change operator from OR to AND. Also AND filter should work. See following gist for examples: https://gist.github.com/1263816

Have a nice day

**Comment by karmi** [comment]
@mikeg250: Tire allows you to set default operator per query, via the [`:default_operator`](http://www.elasticsearch.org/guide/reference/query-dsl/query-string-query.html) option.

The commit https://github.com/seejohnrun/tire/commit/55ed24 is old and was superseded by new changes.

I am not aware if there's a way to set it globally in ElasticSearch, and probably wouldn't like such a global option myself...

> (...) seems to indicate that Tire doesn’t yet support the AND filter (...)

Tire does not support ["and filter"](http://www.elasticsearch.org/guide/reference/query-dsl/and-filter.html) but does support ["boolean queries"](http://karmi.github.com/tire/#section-Boolean_Queries).

See @vhyza's gist (thanks!!) for a complete overview.

**Comment by mikeg250** [comment]
Wow, thanks for the quick responses.  I'll take a look at those commits and see what I can figure out.

Thanks,
