### ISSUE TITLE
Support the :load option with custom/raw queries

### ISSUE THREAD

**Issue by nickhoffman** [karmi/retire#126]
In #61, support for the _:load_ option was added to Tire::Model::Search and Tire::DSL. However, if the _options_ arg that's given to Tire::DSL#search is a hash and includes the _:load_ option, the query to ES fails.

This is because the entire hash (including `:load => true`) is sent to ES as the request's payload, but `:load => true` invalidates the query. Thus, it's not possible to provide the _:load_ option when providing a hash.

**Comment by karmi** [comment]
Hmm, why would you pass `:load => true` to Tire DSL? It only makes sense to pass it to `MyModel.search`?

**Comment by nickhoffman** [comment]
`MyModel.search` doesnt support custom/raw queries. So if you want to perform a search that's not possible with Tire's DSL, `MyModel.search` can't be used. (If I'm wrong about that, please correct me, though!)

For example, I need to use `dis_max`, which isn't supported in the DSL. However, this works:

``` ruby
Tire.search(Product.tire.index_name,
    {
      :from   => from,
      :size   => @options[:per_page],
      :query  => {
        :dis_max => {
          :queries => [
            { :field => { 'name' => @term } },
            { :field => { '_all' => @term } },
          ]
        }
      }
    }
)
```

**Comment by karmi** [comment]
Yeah, raw queries are only possible on the DSL level. In most cases, there should be no pressing reason to use `load`.

Is there a reason you're not able to use a `string` query against specific `:fields`, in this particular case?

**Comment by nickhoffman** [comment]
Unfortunately, a `string` query is too basic for what my users require. If a user searches for a misspelled or partial word, a `string` query will return no hits.

**Comment by karmi** [comment]
Hmm, I wonder about that. You're doing a string query against fields, using the `field` query (http://www.elasticsearch.org/guide/reference/query-dsl/field-query.html).

But, on the topic -- the :load option really does not have any sense on the DSL level. The more appropriate feature request would be to support ‘raw queries” in the model search method....

**Comment by nickhoffman** [comment]
I've added basic support for extra options to be given to Tire::DSL#search in [this commit](https://github.com/nickhoffman/tire/commit/eaae26037446a98f13c46ad113a580f547410f1a).

I was unable to get the development environment working (RDoc and MiniTest are needed, but don't seem to be loaded or required), so I couldn't run the tests that I wrote. However, I'm confident that they'll pass.

Let me know what you think about my approach to the search, and to the commit. I'm happy to modify the search to work within Tire's DSL, but it needs to match misspellings and partial words.

**Comment by karmi** [comment]
I'm really lost as what problem we're trying to solve here :) The :load option for DSL search method does not make any sense... Why add a `raw_query` key? There must be a way to solve the problem you have.

**Comment by nickhoffman** [comment]
To be honest, I didn't build the query because that's specifically what I need. It's simply a modification of the query in [@clintongormley's nGram example](https://gist.github.com/961303). This is because I'm very new to ES and Tire, and am still learning how it all works as the days go by.

Is there a way to use Tire's DSL within a model search to achieve the same behaviour?

**Comment by aaronchi** [comment]
To tell the truth, I was confused by this at first as well. There seems to be a direct search method for ActiveRecord, a search DSL, and the ability to pass a hash - all of these methods support different types of functionality.

I think it would be simpler if there was a single search object that could be built as a hash or a block and shared the same set of global options on ActiveRecord objects (page, load, etc). I think this would make the library easier to understand and use.

**Comment by karmi** [comment]
@nickhoffman: I know you got the query from Clint, of course :) I still think a string query against specific fields is appropriate in your case, and I'm saying it for one last time :)

@aaronchi: What exactly are you confused by? Difference between the DSL and ActiveModel interface?

There is, indeed, a "single search object", shared between all the search methods. It's [Tire::Search::Search](http://rubydoc.info/gems/tire/0.3.5/Tire/Search/Search).

**Comment by nickhoffman** [comment]
@karmi I'm converting my raw query to a query-string query against specific fields. Unfortunately, it doesn't seem to work for embedded fields. For example:

``` ruby
s = Product.tire.search do
  query do
    string "mlock", :default_field => "items.props.character", :analyzer => "ascii_3_8_ngram"
  end
end

s.count
=> 0
```

To reference embedded fields, does ES require me to use a [nested query](http://www.elasticsearch.org/guide/reference/query-dsl/nested-query.html)?

**Comment by nickhoffman** [comment]
On IRC, kimchy just confirmed that a nested query is necessary for querying embedded fields:

`16:33 < kimchy> nick_h: you have to use nested query, in the future, hopefully, we will be able to automatically wrap this for you in a nested query`

Can nested queries be built using Tire? I've looked through the source, but the only mentions of nesting are for indexes.

**Comment by karmi** [comment]
@nickhoffman: No, nested queries are not supported at the moment. So, the problem got shifted from `dis_max` query against specific fields (doable) into a `nested` docs and queries (not doable), correct?

**Comment by nickhoffman** [comment]
@karmi It looks like that's what's happened now.

I think that I should take a step back from all of this and make sure that my settings, indexes, and query approach are ideal for the problem I'm trying to solve, though. I've [posted to the ES mailing list](https://groups.google.com/forum/#!topic/elasticsearch/kuy-nWUAn9k), asking how my approach can be improved.

**Comment by karmi** [comment]
Nick, what should we do with the issue then? Close, open another one, is there some workaround, etc?

**Comment by nickhoffman** [comment]
Sorry for the delay, Karel. Since model loading shouldn't occur within the DSL, I'll close this issue.

It'd be great if the model search method supported "raw" queries, as well as _dis_max_ .

**Comment by karmi** [comment]
Hmm... yes, it would be useful, definitely. Maybe there's even a way to support that -- inspecting the `query` object in `Tire::Model::Search.new` and it it's a Hash, sending it to ES via some `Tire::Search::Search#raw` method.

Not ideal, still kinda ugly, but tolerable. First the "raw queries" support must get much tougher, though, such as properly logging requests/responses, etc.
