### ISSUE TITLE
Tire returns no hits

### ISSUE THREAD

**Issue by ellmo** [karmi/retire#128]
I have an application that uses tire, and the communication works on co-worker`s computer and on a staging server. I have the same issue on two on my computers: one running Ubuntu, other one OSX.

Elasticsearch is working, I can communicate with it through curl commands. I can create indices and store data in them and I can retrieve them through curl or browser.

When I use Tire to take care of this:

``` bash
$ rake environment tire:import CLASS='Deal'
[IMPORT] Creating index 'deals' with mapping:
{"deal":{"properties":{}}}
#2011-10-17 19:47:47:251 [CREATE] ("deals")
#
curl -X POST "http://localhost:9200/deals" -d '{"mappings":{"deal":{"properties":{}}}}'

#2011-10-17 19:47:47:251 [200]

[IMPORT] Starting import for the 'Deal' class
--------------------------------------------------------------------------------
352/352 | 100% # 2011-10-17 19:47:50:783 [BULK] ("deals")#########
#
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'

#2011-10-17 19:47:50:783 [200]


================================================================================
Import finished in 3.53648 seconds
```

But still

``` ruby
ruby-1.9.2-p290-patched > Deal.tire.search '*'

2011-10-17 19:56:37:127 [_search] (["deals"])

curl -X GET "http://localhost:9200/deals/deal/_search?pretty=true" -d '{"query":{"query_string":{"query":"*"}}}'

#2011-10-17 19:56:37:127 [200] (17 msec)

 => #<Tire::Results::Collection:0x000001071417e0 @response={"took"=>17, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}, @options={:type=>"deal"}, @time=17, @total=0, @facets=nil, @wrapper=Tire::Results::Item> 
```

And:

``` bash
curl -XGET 'http://localhost:9200/deals/deal/1'
```

returns

``` bash
{"_index":"deals","_type":"deal","_id":"1","exists":false}
```

**Comment by vhyza** [comment]
Hello,

can you check what is in `deals` index using `curl -XGET 'http://localhost:9200/deals/_search?q=*'` after import is finished?

Can you gist `Deal` model please? Its hard to recreate the issue without it.

**Comment by karmi** [comment]
Hi,

it's probably some mis-configuration in your project, or some edge-case bug. Please do verify with curl or browser, that your index exists and data have been stored: http://localhost:9200/deals/_search?q=*, as @vhyza suggested.

Also, what type of model is Deal? ActiveRecord, ActiveModel (eg. Mongoid), etc.

**Comment by ellmo** [comment]
Hey, thanks for the replies.

Deal is an ActiveRecord base and, as far as I know, in every configuration we tried (both where it works and where it doesn't), it uses MySQL, so no funky databases.

https://gist.github.com/1295013

When I to use that url you suggested, I get hits all right. It says it got all 352 of them.
Since the models have a TON of fields, I'll just paste a fragment of it.

``` json
{"took":113,"timed_out":false,"_shards": {"total":5,"successful":5,"failed":0}, 
"hits":{"total":352,"max_score":1.0,"hits":
[{"_index":"deals","_type":"document","_id":"4","_score":1.0, "_source" : 
{"area":null, "building_address":null, "building_antique":null, "building_area":null, "building_built_date":null,  "building_common_percentage_rights":null, "building_condition_id":null, "building_condition_rating":null, "building_coord_system":null, "building_description":null, "building_functional_rating":null, "building_general_location_rating":null,  "building_ground_levels":null, "building_id":null, "building_infrastructure_known":null, "building_lat":null,"building_lon":null, "building_material_id":null, "building_mortgage":null, "building_mortgage_holder_id":null, "building_mortgage_value":null, "building_no":null, "building_percentage_rights":null, "building_premises_count":null, "building_premises_total_area":null,"building_price":null,"building_primary_purpose_id":null,"building_right_id":null,"building_roof_type_id":null,"building_secondary_purpose_id":null,"building_size":null,"building_underground_levels":null,"building_usable_area":null,"building_usage_percentage":null,"building_user_count":null,"building_vat":null,"building_volume":null,"buyer_type_id":null,"city":"G\u0142og\u00f3w","county_id":null,"created_at":"2011-10-
```

**Comment by karmi** [comment]
Hmmm, so http://localhost:9200/deals/_search?q=* actually returns all the docs, but `Deal.tire.search '*'` does not return anything? That's crazy :)

Your model looks alright to me. What if you try searching on the DSL level?

``` ruby
Tire.search("deals") { all }  # or similar
```

**Comment by ellmo** [comment]
``` ruby
t = Tire.search("deals") { :all }
```

Returns hits similar to those fetched with curl. I'm not sure however if it returned all data, tho' when I call for `t.results` it says:

``` ruby
 <Tire::Results::Collection:0x00000105783998 @response=
{"took"=>97, "timed_out"=>false, "_shards"=>
{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>
{"total"=>352, "max_score"=>1.0, "hits"=>
[{"_index"=>"deals", "_type"=>"document", "_id"=>"4", "_score"=>1.0, "_source"=>{"area"=>nil, "building_address"=>nil,
#(...and so on...)
```

But when I try to grab `t.results[0]` it goes

``` ruby
NameError: uninitialized constant Document
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/rake-0.9.2/lib/rake/ext/module.rb:36:in `const_missing'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/activesupport-3.1.0/lib/active_support/inflector/methods.rb:124:in `block in constantize'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/activesupport-3.1.0/lib/active_support/inflector/methods.rb:123:in `each'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/activesupport-3.1.0/lib/active_support/inflector/methods.rb:123:in `constantize'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/activesupport-3.1.0/lib/active_support/core_ext/string/inflections.rb:43:in `constantize'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/tire-0.3.3/lib/tire/results/item.rb:61:in `class'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/tire-0.3.3/lib/tire/results/item.rb:66:in `inspect'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/railties-3.1.0/lib/rails/commands/console.rb:45:in `start'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/railties-3.1.0/lib/rails/commands/console.rb:8:in `start'
    from /Users/ellmo/.rvm/gems/ruby-1.9.2-p290-patched/gems/railties-3.1.0/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

and the `t` itself becomes corrupted as from now on every call on this object will give a `NameError: uninitialized constant Document`

**Comment by karmi** [comment]
The correct syntax is: `Tire.search("deals") { all }`, beware.

The "uninitialized constant Document" is a nasty, known, issue, which I'm about to fix right now.

There's still something crazy with your model integration, the `Deal.tire.search "whatever"` should work. Lemme release a new version, and we'll continue debugging then.

**Comment by ellmo** [comment]
actually `Tire.search("deals") { all }` gives

``` ruby
[REQUEST FAILED] NameError 
NameError: undefined local variable or method `all' for #<Tire::Search::Search:0x00000105741840>
```

at least on my machine, that's why I tried `:all` instantly and got a result

Thanks for your help and time. I'll try the next release and tell you if anything has changed.

**Comment by karmi** [comment]
Grr, sorry, `Tire.search("deals") { query { all } }` (quite obviously :)

**Comment by karmi** [comment]
@ellmo: Could you rerun the tests with the newly releasesd 0.3.6? It will solve the `NameError`, at least.

Still, I don't understand why it's not returning results. Are you sure you're waiting the default 1sec, or refreshing the index? Is this not a part of a test suite?

**Comment by vhyza** [comment]
@ellmo: Thanks for info. I think there is problem with `_type` you have in index. It should be `deal` not `document`. Tire is looking only for documents with `_type` `deal`. For example, search url generated by Tire looks like this `http://localhost:9200/deals/deal/_search?pretty=true`

So I think there was some problem with document import. Its weird because I tried import now and everything works fine. Are you using last version of Tire?

**Comment by ellmo** [comment]
Hey,
- I upgraded tire to 0.3.7.
- Removed all ES indices through `curl -XDELETE ...`
- Imported them back again through `rake environment tire:import CLASS="Deal"`

``` ruby
Deal.tire.search "*"
```

still does not return any hits, however

``` ruby
t = Tire.search("deals") { query { string "*"} }
```

does seem to work. I guess it doesn't hurt to use it instead. However when I call `t.results.size` on the object (and yes, there's no more _NameError_, so thank you for that!), it's size is `10` and I have 352 objects indexed (allegedly).

What am I missing?

**Comment by vhyza** [comment]
Did you check http://localhost:9200/deals/_search?q=\* after new import? I think you still have `document` `_type` instead `deal`

Please, can you try following?
1. `curl -X DELETE http://localhost:9200/deals`
2. replace `Deal` model with basic one (https://gist.github.com/1299758)
3. `rake environment tire:import CLASS="Deal"`
4. see http://localhost:9200/deals/_search?q=\* to check if `_type` is `deal` now

If `_type` is correct `Deal.search "*"` should returns some hits

**Comment by karmi** [comment]
@ellmo: As suggested by @vhyza, double check your documents have the "deal" `_type`. You must be doing something funky if your documents end up with different `_type` in ES, or there's a grave bug somewhere.

> when I call t.results.size on the object it's size is 10 and I have 352 objects indexed

`results.size` gives you the size of returned collection, `results.total` will give you the total size of documents for your query.

**Comment by karmi** [comment]
@ellmo: Ping, any news?
