### ISSUE TITLE
Add support for custom_score

### ISSUE THREAD

**Issue by jfalk** [karmi/retire#133]
Would be nice if there was a way to set the custom_score property for a query.  This allows for some pretty complex result ordering that is useful for a lot of applications.

**Comment by karmi** [comment]
Jason, do you mean the [_custom_score query_](http://www.elasticsearch.org/guide/reference/query-dsl/custom-score-query.html)?

**Comment by jfalk** [comment]
Yes sir.

**Comment by karmi** [comment]
Should be easy to add, it's a straight-forward patch a la https://github.com/ralph/tire/commit/c2b496c, anybody got 20mins to do it? :)

**Comment by pacoguzman** [comment]
Hi,

 I take it

**Comment by karmi** [comment]
Great, Paco!

**Comment by pacoguzman** [comment]
I'm getting the following error throwing the next query:

``` shell
curl -X GET "http://localhost:9200/articles-test/_search?pretty=true" -d '{"custom_score":{"query":{"query_string":{"query":"title:T*"}},"script":"_score * doc['words'].value"}}
```

``` shell
[2011-10-25 22:38:33,312][DEBUG][action.search.type       ] [Torrent] [articles-test][3], node[qxUNFpjMSR2wgWa8_4UH7A], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@9e5e21]
jvm 1    | org.elasticsearch.search.SearchParseException: [articles-test][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"custom_score":{"query":{"query_string":{"query":"title:T*"}},"script":"_score * doc['words'].value"}}]]
jvm 1    |  at org.elasticsearch.search.SearchService.parseSource(SearchService.java:495)
jvm 1    |  at org.elasticsearch.search.SearchService.createContext(SearchService.java:407)
jvm 1    |  at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:230)
jvm 1    |  at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:134)
jvm 1    |  at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:80)
jvm 1    |  at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:205)
jvm 1    |  at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:192)
jvm 1    |  at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$2.run(TransportSearchTypeAction.java:178)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
jvm 1    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
jvm 1    |  at java.lang.Thread.run(Thread.java:679)
jvm 1    | Caused by: org.elasticsearch.search.SearchParseException: [articles-test][3]: from[-1],size[-1]: Parse Failure [No parser for element [custom_score]]
jvm 1    |  at org.elasticsearch.search.SearchService.parseSource(SearchService.java:481)
jvm 1    |  ... 10 more

```

I'm not pretty sure whats going on, I'm missing something

Any thoughts?

I think you could test it importing the articles fixtures

**Comment by danoph** [comment]
You need to wrap custom_score in query{ }

**Comment by pacoguzman** [comment]
@danoph thanks, I'll try but is strange to me the need to wrap in query{} and then have another query inside but I'll try thanks

**Comment by danoph** [comment]
@pacoguzman yes it's weird but required...kimchy posted why it's required somewhere in elasticsearch's issues...I hacked together custom score for my application with tire...

```
Tire::Search::Query.class_eval do

  def custom_score(options={}, &block)
    @value = { custom_score: { query: self.instance_eval(&block).to_hash }.merge(options) }

    @value
  end
end

search = Item.search page: 1, per_page: 30 do
  query do
    custom_score script: "random()" do
      all
    end
  end

  filter :term, status: 1
  filter :term, featured: 1
end

@items = search.results
```

...After looking at the code for a minute, the way I implemented it doesn't seem like a good way to do it at all, but until it's implemented in tire it works for me

**Comment by karmi** [comment]
Hi Paco, sorry for such a big delay with reply. Yes, you have to wrap all queries in a `query` JSON property. Have a look at `Tire::Search::Search#to_hash`, which does this "final" wrapping. It's a bit "strange", but I understand why it's so in ES's DSL.

That said, this curl works for me (against the `articles-test` index based on _Tire_ fixtures, as you suggested):

``` bash
curl -X GET "http://localhost:9200/articles-test/_search?pretty=true" -d '
{
  "query" : {
    "custom_score" : {
      "query"  : { "query_string":{"query":"title:T*"} },
      "script" : "_score * doc[\"words\"].value"
    }
  }
}
'
```

**Comment by pacoguzman** [comment]
Hi,

Maybe you could take a look to #139 , my first attempt to try to resolve this one. Excuse me but I don't know how to related that issue with this ;)

Any comments?

I'd tried to avoid the use of a query block inside the custom_score block

``` ruby
search = Item.search page: 1, per_page: 30 do
  query do
    custom_score script: "random()" do
      query { string "title:T*" }
    end
  end
end
```

And simply we can do

``` ruby
search = Item.search page: 1, per_page: 30 do
  query do
    custom_score script: "random()" do
      string "title:T*"
    end
  end
end
```

Everything inside the custom_score block is execute in a new query object context

**Comment by jfalk** [comment]
Interesting idea.  Being able to pass parameters into the script would be very useful though.  Sure you could insert args in the script string, but then ES has to recompile the script each time it's different.  Doing it the way described in the ES docs is more efficient.

**Comment by karmi** [comment]
@jfalk: The beauty of ES's API and Paco's implementation is that passing parameters to scripts is already working, see examples in the last referenced commit.

**Comment by VetriVellore** [comment]
Thank you for adding support for custom_score. It doesn't seem to work with highlight though - is it a known issue?
