### ISSUE TITLE
Can not get type => 'geo_point' to work

### ISSUE THREAD

**Issue by tcocca** [karmi/retire#137]
I am trying to set up my settings and mappings block to be able to create a geo_point.

I have the following set up in my model:

``` ruby
class Mls::Property
tire do
    settings :analysis => {
      :filter => {
        :prefix_edgengram => {
          "type"     => "edgeNGram",
          "min_gram" => 2,
          "max_gram" => 10,
          "side"     => "front"
        }
      },
      :analyzer => {
        :prefix_analyzer => {
          "tokenizer" => "lowercase",
          "filter"    => ["stop", "prefix_edgengram"],
          "type"      => "custom"
        }
      }
    } do
      mapping do
        indexes :id,                      :type => 'string', :index => "not_analyzed", :include_in_all => false
        indexes :lat_lng,                 :type => 'geo_point', :lat_long => true
        indexes :description,             :type => 'string', :analyzer => 'snowball'
        # REST OMITTED
      end
    end
  end

  def to_indexed_json
    {
      :id => self.id,
      :description => self.description,
      :lat_lng => "#{self.latitude},#{self.longitude}"
      # REST OMITTED
    }.to_json
  end
```

And the first time I index a property:

``` ruby
p = Mls::Property.first
p.tire.update_index
```

It sets up my lat_lng property as a string.

I have tried the following formats in my :lat_lng => def in the json:

``` ruby
:lat_lng => "#{self.latitude},#{self.longitude}"

:lat_lng => [self.longitude, self.latitude]

:lat_lng => {
  :lat => self.latitude},
  :lon => self.longitude
}
```

All of which create the field as a string.  Actually the last one created the field as a dynamic  i think with lat and lon values of type string.

How can I go about getting my lat_lng point in as a geo_point ?

Also, how can I go about querying on geo_polygon

Thanks,
~ Tom

---

**NOTE: Code shortened by @karmi**

**Comment by karmi** [comment]
Hi, the only issue I see is that the index is created with incorrect mapping. Notice that you have to either delete the index before loading the app (hence the index is created properly with _Tire_), or you have to take care about deleting/creating index into your own hands (model class methods, etc)

I have tried a simplified use case and the following code works for me. Could you try it and report on results?

``` ruby
require 'tire'
require 'active_record'

Tire.index('venues') { delete }

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Migration.verbose = false
ActiveRecord::Schema.define(version: 1) do
  create_table :venues do |t|
    t.string   :title, :latitude, :longitude
  end
end

class Venue < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  tire do
    mapping do
      indexes :title,   type: 'string', analyzer: 'snowball'
      indexes :lat_lon, type: 'geo_point'
    end
  end

  def lat_lon
    [latitude, longitude].join(',')
  end

  def to_indexed_json
    to_json(only: ['title'], methods: ['lat_lon'])
  end
end

Venue.create title: 'Pizzeria Pomodoro', latitude: "41.12", longitude: "-71.34"

Venue.tire.index.refresh

query = { query: { filtered: { query: { match_all: ''} }, filter: { geo_distance: { distance: '100km', lat_lon: "41,-71" } } } }

puts "", "The query:", '-'*80, query.to_json

s = Tire.search 'venues', query

puts "", "Results:", '-'*80, s.results.inspect
```

**Comment by tcocca** [comment]
Hi, I am debugging this now, what was incorrect about my original mapping?

**Comment by karmi** [comment]
The mapping was correct, I think the `:lat_long => true` part is not neccessary -- the issue is _somehow_ the index is created with incorrect mapping. Check it with http://localhost:9200/YOUR_INDEX/_mapping.

**Comment by tcocca** [comment]
AHHH! I'm an idiot, I had two problems in my mapping..

The first was this:

```
indexes :street_name,             :type => 'string', :analyzer => 'prefix_edgengram'
```

really needs to be:

```
indexes :street_name,             :type => 'string', :analyzer => 'prefix_analyzer'
```

After I fixed that it was creating lat_lng as a correct geo_point but then I realized I had this:

```
indexes :lat_lng,                 :type => 'geo_point', :lat_long => true
```

which should be:

```
indexes :lat_lng,                 :type => 'geo_point', :lat_lon => true
```

So I think this is all good now, I'm gonna index some data points and make sure this works correctly.

**Comment by karmi** [comment]
Hmm, the `street_name` eludes me. But, importantly, what's the purpose of passing `:lat_lon => true` to mapping? Why is not "geo_point" enough?

**Comment by tcocca** [comment]
The street_name was just the wrong thing.  I was passing my custom filter to the analyzer instead of my custom analyzer ... dumb mistake

For the geo_point.

http://www.elasticsearch.org/guide/reference/mapping/geo-point-type.html

lat_lon - Set to true to also index the .lat and .lon as fields. Defaults to false.

Which I believe would allow me to call doc[lat_lng].lat or doc[lat_lng].lon

**Comment by karmi** [comment]
> Which I believe would allow me to call doc[lat_lng].lat or doc[lat_lng].lon

Ah yes, sure. All OK now, then?

**Comment by tcocca** [comment]
All good just need to figure out how to do the geo_polygon queries with Tire.  Either off of the Tire.search or Mls::Property.tire.search.

I'll need to combine this with text queries and filters on a bunch of the other fields too.

**Comment by karmi** [comment]
Geo is not exposed right now, you have to use the `Tire.search` DSL, or other means... I've put some info here: https://github.com/karmi/tire/wiki/How-to-work-with-locations-(geo)-in-Tire, recently.

**Comment by skogsmaskin** [comment]
I was having problems with this as well, when testing with rspec.
To get .location recognized as a geo_point I had to do call `MyModel.create_elasticsearch_index` before tests, like this:

```
    before :each do
      Address.index.delete
      Address.create_elasticsearch_index
      Address.index.import [an_address, a_second_address, a_third_address, a_fourth_address]
      Address.index.refresh
    end
```

**Comment by jasonfb** [comment]
I am also having problems with a  "field [location] is not a geo_point field".  Will post to a new issue
