### ISSUE TITLE
Missing Facets

### ISSUE THREAD

**Issue by aaronchi** [karmi/retire#138]
In the most recent release of tire (0.3.8), when you search on multiple facets, only the first on shows up in the results object.

The last time this worked was in v 0.3.6, so something happened between 0.3.6 and 0.3.7 that seems to have broken this functionality.

**Comment by karmi** [comment]
I don't understand what you mean by "search on multiple facets".

I've added a test case for multiple facets.

Please, make sure you're attaching a relevant Ruby when something "does not work". In this case, making the test case fail would be the best code.

**Comment by aaronchi** [comment]
Hi. sorry for not providing more information. I narrowed down the issue in my code and it seems to have something to do with trying to apply additional nested options to a facet. In my code I am using a facet filter to update the facets based on what the user is searching for. From the elasticsearch guide:

```
"facets" : {
    "<FACET NAME>" : {
        "<FACET TYPE>" : {
            ...
        },
        "facet_filter" : {
            "term" : { "user" : "kimchy"}
        }
    }
}
```

Set in tire like:

```
facet 'category' do
    terms 'category_ids', :size => 100, :facet_filter => {:term => {:id => category_ids}}
end
```

This was working in 0.3.6, but afterwards, when I run the query, it only returns the results of the first facet if I have a facet_filter set on multiple facets.

I haven't looked deeper into this yet but I imagine the change happened here when the way that options passed to terms facets were changed:
https://github.com/karmi/tire/commit/d1f89e6cf230d80ec98792fcc241cc13f47c72ce

**Comment by aaronchi** [comment]
Ah I see.Just pass the :facet_filter options to the facet instead of the terms. :)

**Comment by karmi** [comment]
Hmm, yeah, thanks for the digging! That's certainly the point where it got "broken" for you. However, it was _broken_ for cases where you wanted to pass options to facets, such as the `:exclude` or `:value_field` (see tests karmi/tire@d1f89e6).

Lemme play with it a bit in the test suite for a moment.

**Comment by karmi** [comment]
OK, that was easy :) Thanks!, added couple of tests to tighten this up. And yes, you have to pass it to the `facet` method itself, see the rather lengthy commit message in karmi/tire@52fade0 for details.
