### ISSUE TITLE
Geo Filter Support

### ISSUE THREAD

**Issue by tcocca** [karmi/retire#140]
@karmi  I want to open this ticket to start discussing the options of Geo Filtering support,

geo_bbox
geo_distance
geo_distance_range
geo_polygon

I wouldn't mind trying to stab at the geo support for the gem, just want to discuss what the DSL should look like,

Looks like the geo_ options are only available as filters and not part of the query.  Have you thought about what that filter DSL would look like at all?

I'm thinking maybe something like the following:

```
filter :geo_bounding_box, :location, :top_left => [40.73, -74.1], :bottom_right => [40.717, -73.99]
filter :geo_distance, :distance => "200km", :location => [40.73, -74.1]
filter :geo_distance_range, :from => "20km", :to => "200km", :location => [40.73, -74.1]
filter :geo_polygon, :location, :points => [[40.73, -74.1],[40.73, -75.1], [41.73, -75.1], [41.73, -74.1]]
```

We would have to do some work in the #initialize method of the Tire::Search::Filter class to recognize these geo filters based on the type of filter, because they need to accept more arguments than the standard "terms" filter.

Or should we turn filter more into something like the Facet class that accepts a block and inside that block we could do a number of different things? maybe something like:

```
filter do
  geo_bounding_box :location, :top_left => [40.73, -74.1], :bottom_right => [40.717, -73.99]
end

filter do
  geo_distance :distance => "200km", :location => [40.73, -74.1]
end

filter do
  geo_distance_range :from => "20km", :to => "200km", :location => [40.73, -74.1]
end

filter do
  geo_polygon :location, :points => [[40.73, -74.1],[40.73, -75.1], [41.73, -75.1], [41.73, -74.1]]
end
```

Any thoughts on this?

Wondering what the best option to go with is.  I'd love to hear thoughts on the dsl.

~ Tom

**Comment by karmi** [comment]
Hi, first of all, notice that the following does work on current _Tire_ master:

``` ruby
require 'tire'

Tire.index 'venues' do
  delete
  create :mappings => { :venue => { :properties => { :lat_lon => { :type => 'geo_point' } } } }
  store :type => 'venue', :title => 'Pizzeria', :lat_lon => [41,-71]
  refresh
end

s = Tire.search('venues') do
  query  { all }
  filter :geo_bounding_box, :lat_lon => { :top_left => [40, -71], :bottom_right => [42, -72] }
end

puts s.to_curl
puts s.results.inspect
```

No need to add any "specific" geo support to filters I'm aware of, but I may be mistaken. What do you mean by "they need to accept more arguments than the standard "terms" filter"?

Second, I wouldn't go the blockish route as you suggest in the latter example.

The reason I was not so crazy about adding geo support directly is influenced by these facts: it's doable with the existing codebase, and there are many things to take into consideration regarding convenient interface. Also, I haven't had a _practical_ use case for geo handy, and it's much better to have one then to code against an illusion.

All that said, I think ultimately _Tire_ should expose a higher level abstraction for geo features, something along the lines of:

``` ruby
s = Tire.search('venues') do
  query  { all }
  geo    { distance :location, '200km', [40, -71] }
end

s = Tire.search('venues') do
  query  { all }
  geo    { polygon :location, [40, -70], [30, -80], [20, -90] }
end

s = Tire.search('venues') do
  query  { all }
  geo    { bounding_box :location, :top_left => [40, -70], :bottom_right => [30, -80] }
end
```

Ie. expose a top level `geo` method in the search DSL (via `Tire::Search::Search`), define methods for all the ElasticSearch's geo-specific [filters](http://www.elasticsearch.org/guide/reference/query-dsl/geo-bounding-box-filter.html), which would take document field as a first argument, and all the specific options for each filter as remaining arguments.

That way, the interface would be quite fluent, would match ES 1:1, and would be in tune with the rest of the API.

Given "enough time or money", it should be quite easy to implement that :)

**Comment by tcocca** [comment]
Thanks karmi I was mistaken about the extra arguments, the nested hashes work just fine, i wasn't nesting the stuff correctly.  I was using 0.3.8 and the filter options worked.  I was mistaken because the readme says that the geo stuff is not supported yet and you have mentioned to get geo support you had to use Tire.search directly.

Also, when i woke up this morning I had the same thought as you did.  Expose a top level geo dsl in the search.  Same as filter, facet, etc...

I may take a look into writing that geo class and adding that support.  It should basically act similar to #filter on the search class and just add the geo filters to the filter array.

Here is my last question, how do you go about doing "or" filters?  I know the default is to and all filters together, but how would I go about writing something like this:

```
filter :terms, :property_type => ["Single Family", "Condo"]
filter :terms, :status => ["Active"]
filter :or
  filter :geo_bounding_box, :lat_lon => { :top_left => [40, -71], :bottom_right => [42, -72] }
  filter :town => ['Boston'] 
end
```

so it ands everything and then there is an "or" condition on whether it is in the bounding box or it is in the town?

**Comment by karmi** [comment]
@tcocca: You can chain `:or` filters like this: http://github.com/karmi/tire/blob/master/test/integration/filters_test.rb#L27-28

**Comment by aaronchi** [comment]
Facets support should also be added. I monkey patched facet with this to get it working

```
def geo_distance(options={})
  @value = { :geo_distance => { }.update(options) }
end
```

**Comment by bobbytables** [comment]
Has anyone done any work on this yet?

**Comment by mleglise** [comment]
Ping.  Any forward movement on geo support?  @tcocca if you ended up deciding you could accomplish what you wanted without adding anything new, could you post your solution on the wiki?

Cheers!

**Comment by karmi** [comment]
@mleglise What do you mean by "geo support"?

(As said above, it is "supported" in a a sense "you can make geo queries". It is not supported on the DSL level, and since I haven't encountered the need to implement the outlined DSL yet, it's not scheduled to be supported on the DSL level.)

**Comment by mleglise** [comment]
@karmi I meant primarily within the DSL, so thank you for answering that.

I'm hoping to avoid having to build my full query as a Hash (as instructed here: https://github.com/karmi/tire/wiki/How-to-work-with-locations-%28geo%29-in-Tire) and instead go through the existing filter DSL as you suggested above.  If it works as described, I'd be happy to update the wiki page.  Thoughts?

**Comment by karmi** [comment]
Yeah, I've not authored the page, so go forward and update it with the solution from above, if it works. Eventually, it will be supported on the DSL level as outlined in my sketch...

**Comment by tcocca** [comment]
@mleglise I am doing a filtered query and am just passing a array of 'filters' to the .filtered dsl method in an and option.  Here is the simplified version of what I am doing:

So, I have something like the following:

``` ruby
query_filters = [
  {:terms => {:status_id => [1,2,3,4]}},
  {:terms => {:property_type_id => [1,2,3]}},
  {:geo_polygon => {:lat_lng => { :points => [-70, 40],[-80, 30],[-90, 20]}}}
]

Property.search do |search|
  search.query do |query|
    query.filtered do |filtered|
      filtered.query { |fq| fq.all }
      filtered.filter :and, query_filters
    end
    query.sort do |sorted|
      sorted.by :price, :desc
    end
  end
end
```

I found writing the 'conditions' or filters for the search to be much simpler to do it as an array of hashes as opposed to trying to make the dsl work for me.

Also, you can do a lot more. For example, nesting 'or' or 'bool' sets inside of the main 'and'.

Let me know if you have questions about this method.

**Comment by mleglise** [comment]
Thanks for the example @tcocca 

I worked out how to do it using the block syntax and posted a basic example on the wiki.  It seems like with these two options, there is little need to bake it into the DSL.  Cheers!

**Comment by karmi** [comment]
Closing this, since geo filter is doable, see also #169, opening new issue for the DSL extension.
