### ISSUE TITLE
Support for get api

### ISSUE THREAD

**Issue by nglx** [karmi/retire#141]
Is Tire supporting get api in the DSL:
http://www.elasticsearch.org/guide/reference/api/get.html

I couldn't find any snippet in the DSL example and in the code after a quick look.
Basically I need to get the specific document by id instead of search for it?
On the other hand is there a way to query documents by id? - it could be a quick workaround.

Thanks,
Marcin

**Comment by karmi** [comment]
Hi,

yes, you can get individual documents via the [`Index#retrieve`](http://rubydoc.info/gems/tire/0.3.9/Tire/Index#retrieve-instance_method) method. Also, you can query for multiple ids with the [`ids`](http://rubydoc.info/gems/tire/0.3.9/Tire/Search/Query#ids-instance_method) query in Tire.

**Comment by nglx** [comment]
Thanks a lot for quick response.
