### ISSUE TITLE
collection.rb throws error when the index does not exist

### ISSUE THREAD

**Issue by benzheren** [karmi/retire#145]
I am using DSL in Tire to do search, but when the index does not exist. The tire code throws error at line 14 of `collection.rb`

`undefined method `[]' for nil:NilClass`

**Comment by karmi** [comment]
Any code please? On current master it raises `Tire::Search::SearchRequestFailed`: 404 : {"error":"IndexMissingException[[zzarticles] missing]","status":404}`.

**Comment by benzheren** [comment]
I am using 0.3.7. I put my code as a gist: https://gist.github.com/1354764.

**Comment by karmi** [comment]
Oh yeah, you're using the "dumb" version of DSL, the issue should be fixed on master and newest Rubygems version, check the attached commit for info.

BTW, why not use the blocky, more semantic DSL version?

**Comment by benzheren** [comment]
Thanks for pointing it out. I started with 0.1.6, does the latest code fully support our need? What do u mean by more semantic DSL? We have complicated query like text, text phrase, on top of filtering. If the semantic DSL you mention supports it, I would love to use it.
