### ISSUE TITLE
Add "flush" command

### ISSUE THREAD

**Issue by raff** [karmi/retire#146]
Could it be possible to add the "flush" command to index ? I just "copied" the code from "refresh" in lib/tire/index.rb and changed the command to flush / _flush, like this:

```
def flush
  @response = Configuration.client.post "#{Configuration.url}/#{@name}/_flush", ''

ensure
  curl = %Q|curl -X POST "#{Configuration.url}/#{@name}/_flush"|
  logged('_refresh', curl)
end
```

**Comment by karmi** [comment]
Hey, sorry it took so long. Yeah, it would be better to have a proper method for that, but let's work on more important things, since it amounts to doing:

``` ruby
require 'tire'

p Tire::Configuration.client.post "#{Tire::Configuration.url}/#{Tire.index('articles').name}/_flush", ''
```

Closing for now, let's think about it when refactoring and adding features like aliases to `Tire::Index`...
