### ISSUE TITLE
id and type fields redundant in _source field when index data

### ISSUE THREAD

**Issue by ghost** [karmi/retire#147]
Hi, I import my data as follow:

``` ruby
articles = [
  { :id => '1', :type => 'article', :title => 'one'}
]

Tire.index 'articles' do
  import articles
end
```

What I get is a document with the following fields:

``` javascript
 {
  "_id": "1", 
  "_index": "articles", 
  "_source": {
    "id": "1", 
    "type": "article",
    "title": "one"
  }, 
  "_type": "article"
}
```

Why I get the _source.id and _source.type fields redundant? When I create a document by hand, I do not get these fields.

**Comment by karmi** [comment]
Because there were some cases where people complained that the id & type are missing from the JSON, and also, this makes it easier to instantiate records, etc. What's the real issue with this? The "duplication of data"?

**Comment by ghost** [comment]
Hi Karmi,

the real problem with this, is that I can't create a index document the elastic search way. The _\* fields have a defined semantic, and I see no reason to duplicate these fields in the _source field by default. For the "some cases" Tire could give a additional posibility to duplicate these fields.

I think, a default behaviour should be the elastic search way. Elastic search documents are well structured and every information has its own place.

When I want to create a "clean" elastic search document, I have to get around, break the abstraction, and use Net::HTTP::Put to create such as document. This can not be.

Please correct me, if Tire gives a possibility to create documents this way.

Best regards
Robert

**Comment by karmi** [comment]
Hi Robert,

I would gladly give you an answer or help you, but I still don't understand the problem at hand.

a) What is "the elastic search way" of creating documents?

b) I don't understand what are the _practical implications_ of having the `_id` and `_type` fields duplicated in the `_source` JSON document.

**Comment by ghost** [comment]
Hi Karel,

this is more a refinement, not a real problem with the functionality.

With "the elasticsearch way" I mean, a elasticsearch document has a couple of meta fields, like `_index`, `_type`, `_id` and so on. The semantic of these fields are well defined. Every redundancy of these fields in the `_source` field, could have a influence on the mapping definition and cause unneeded complexity.

What when I read the index with a different tool than Tire? I don't need the redundancy in the `_source` field.

My wish is to have full control over the creation of documents in elasticsearch. Tire is too cool not to allow it.

With curl I can do that:

``` bash
curl -XPUT http://localhost:9200/articles/article/1 -d '{
    "title": "one"
}'
```

Here I put the `index`, `type` name and `id` in the URL. Elasticsearch knows, I mean the `_index` _articles_, `_type` _article_ and `_id` _1_. There is no need, to repeat this information in the `_source` field. And when I have to repeat this information, this is more a smell for a architectural problem of my application. This is what I mean with the elasticsearch way.

Best regards
Robert

**Comment by karmi** [comment]
Hi Robert,

> this is more a refinement, not a real problem with the functionality.

once we have `search_type=count` implemented, once the `Tire::Results::Collection#results` is refactored from the current mess, once we have a nice DSL for geo features, once we have support for attachments, _then_ I'm all set for solving "refinements" like these :)

That said, feel free to submit patches solving the "duplicity"! (Mixing in the info from the options/URL to the attributes hash for Items, etc etc etc.)

Best,

Karel

**Comment by ghost** [comment]
Hi Karel,

I'm going to solve this and submit a patch when I'm ready :)

Best regards
Robert

**Comment by faceit** [comment]
Using tire 0.5.1 it seems that the id and type fields are still stored in the _source.

I can see how having type for example can make mongoid/ar integrations smoother, but IMO it wouldn't be wise for a ES client to enforce it.

May I suggest a schema like this:

```
 articles = [{:id=>"1", :type=>"article", :_source => { .. } }]
```

**Comment by rb2k** [comment]
I'd also like to see them gone :(
