### ISSUE TITLE
Failure output from search should output response body

### ISSUE THREAD

**Issue by joshdevins** [karmi/retire#149]
raise Tire::Search::SearchRequestFailed, response.to_s if response.failure?

uses the response object as the message, however it should use response.body.to_s

raise Tire::Search::SearchRequestFailed, response.body.to_s if response.failure?

**Comment by karmi** [comment]
I'm sorry, but I don't understand the problem. Could you be more specific as to what problem you have?

**Comment by joshdevins** [comment]
The error output is wrong. It's just printing the Ruby object .to_s instead of something helpful like the response body JSON.

As it is now with response.to_s:
[REQUEST FAILED] Tire::Search::SearchRequestFailed #Tire::HTTP::Response:0x007ff42e896aa0

With response.body.to_s:
[REQUEST FAILED] Tire::Search::SearchRequestFailed {"error":"IndexMissingException[[green] missing]","status":404}

**Comment by karmi** [comment]
I don't think it's the case on current master and version 0.3.11, this code behaves right:

``` ruby
require 'rubygems'
require 'tire'

extend Tire::DSL

s = search 'articles' do
  query { string '[x' }
end

p s.results
```

Are you using the latest version? Does the code above print an informative statement in the exception (response code and body)?

**Comment by joshdevins** [comment]
Sorry, looks like it works on master. Upgraded and all is good.
