### ISSUE TITLE
production deployment options

### ISSUE THREAD

**Issue by ryw** [karmi/retire#152]
Reviewing my deployment options for a small app I've written with an elasticsearch dependency...

I plan on putting the app on Heroku -- I found elasticsearchhq.com as a free hosted option (at least to get the ball rolling with the site). It [requires an authentication header](http://support.elasticsearchhq.com/entries/20341081-connecting-authentication) to be passed with requests.

Quick look through tire code suggests to me that this sort of thing isn't baked into tire at the moment.

Anyone hook tire up to elasticsearchhq using the auth header?

If not, anyone using Heroku + hand-rolled EC2/Elasticsearch server successfully?

**Comment by karmi** [comment]
AFAIK what they describe in a kinda complicated way is standard HTTP Auth, so you should be able to set _Tire_'s URL to something like `http://username:password@whatever.elasticsearchhq.com:9200`.

(If you would need to set custom headers, you need to subclass & customize the client. But I don't think this is the case.)

**Comment by aaronchi** [comment]
It's actually pretty easy. but you need to do some monkeypatching to make i work. Here's what I did in my tire.rb initializer

```
require 'base64'
TIRE_AUTH = "Basic #{Base64.encode64('username:password')}"

module Tire
  module HTTP
    module Client
      class RestClient

        def self.post(url, data)
          perform ::RestClient.post(url, data, :authorization => TIRE_AUTH)
        rescue ::RestClient::Exception => e
          Response.new e.http_body, e.http_code
        end

        def self.put(url, data)
          perform ::RestClient.put(url, data, :authorization => TIRE_AUTH)
        rescue ::RestClient::Exception => e
          Response.new e.http_body, e.http_code
        end

        def self.delete(url)
          perform ::RestClient.delete(url, :authorization => TIRE_AUTH)
        rescue ::RestClient::Exception => e
          Response.new e.http_body, e.http_code
        end

      end
    end
  end
end
```

I don't think it would be too hard to add a config variable to tire to make this work out of the box but I'll let karmi decide if it's something he wants to support. Also, so you know, elasticsearchhq doesn't currently support the _bulk operation (as least since I last used it) so you can't run a normal import using the rake task.

I ended up setting up a couple of elasticsearch servers on ec2 using a load balancer in front (the load balancer is probably unecessary for a small site but I wanted to test the clustering). There is a nice article here that will get you started and it's pretty easy to do:

http://www.elasticsearch.org/tutorials/2011/08/22/elasticsearch-on-ec2.html

**Comment by karmi** [comment]
But why monkey patch that? Why not create a custom [client](https://github.com/karmi/tire/blob/master/lib/tire/http/client.rb), and use that in `Tire.configure { client MyCustomizedClient }`?

**Comment by aaronchi** [comment]
You could use a custom client but since I was only adding an authorization key to a few methods, it seemed simpler to do it this way.

**Comment by karmi** [comment]
But also hard to maintain on longer run...

**Comment by ryw** [comment]
To close this out -- I couldn't get elasticsearchhq.com to work using any method above, it reported "couldn't find user ryw" -- I put in support request, haven't heard anything on it for a week -- I'll reopen this issue and update if I hear back from them.

I ended up building an elasticsearch server on EC2 and it's working fine for me.

**Comment by karmi** [comment]
@ryw: That's weird, adding the header should be trivial. But yeah, ES should run very fine on EC2.

**Comment by rajraj** [comment]
@ryw Hi, would you be kind enough to share the details on how to setup ES on Amazon EC2 and linking to your app on Heroku? Many thanks

**Comment by ryw** [comment]
@rajraj sorry I didn't respond quicker - I followed the tutorial @ http://www.elasticsearch.org/tutorials/2011/08/22/elasticsearch-on-ec2.html but I discovered during the process that the Elasticsearch wouldn't start on a micro instance, had to go up to Small

**Comment by rajraj** [comment]
@ryw thanks for the response. I will checkout the tutorial. How is the search performance for the app hosted on Heroku and ES on EC2? I have seen people mentioning the latency issues.

**Comment by ryw** [comment]
My app is small/low traffic, so I don't see any noticeable latency.

**Comment by jakeatwork** [comment]
@ryw (or anyone here for that matter) - From the conversation here, it seems you've figured this out and was wondering if you could give me the briefest of pointers.

I'm new to both Elasticsearch and rails, but I have both running and working locally (and everything but ES running on heroku) and just needed to know what file(s) i need to modify to point Tire to the ES instance on EC2...or something similar...feels like i'm just missing a key piece of information.

Any information would be greatly appreciated.

**Comment by karmi** [comment]
Hi, @jakeatln, what kind of information you need? You just point Tire to an IP a your master of your cluster in EC2 (best to use private IP, make sure your application and ES node are in the same security group), probably in an application initializer, you're done.

Also, notice that there's a http://bonsai.io/: hosted ElasticSearch as a Heroku addon, currently in beta.

Ping me here or at the #elasticsearch channel at Freenode if you need more help/advice.

**Comment by ryw** [comment]
Hi Jake-

I have a file:
     /config/initializers/elastic_search.rb 

with one line:
    Tire.configure { url 'http://instance_name.compute-1.amazonaws.com:9200' }

**Comment by jakeatwork** [comment]
THANK YOU. both of you. @karmi - appreciate the input AND the software. thanks. @ryw  - it's working now. i knew i was missing something simple. i've got data in ES on EC2. @karmi - i hit up bonsai on twitter for a test account...i'll give it a try.
