### ISSUE TITLE
Pagination using the Tire REST DSL

### ISSUE THREAD

**Issue by digitalplaywright** [karmi/retire#158]
We need to paginate some queries that require the REST DSL, but have not found a way to do so.  

The REST DSL queries are implemented like:
   https://github.com/karmi/tire/wiki/Using-elasticsearch-query-DSL-directly-%28or%3A-doing-queries-not-supported-by-the-DSL%29

We tried to paginate by applying the methodology described in the Tire unit tests:
  https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L83

However, this does not seem to work with a query hash (e.g ':query => {"match_all" => {}}') and as far as I know translating the query hash to a query string is not feasible for advanced queries that use geo, facets, filters etc. 

Any advice on how to paginate a  REST DSL query is greatly appreciated.

Best,
Andy

**Comment by karmi** [comment]
Hi, if you use the "raw" API by sending hashes over the wire, than you have to mix the `size` and `from` values into the hash, as describe in the ES [docs](http://www.elasticsearch.org/guide/reference/api/search/from-size.html).

Ping me again if you encounter any problems...

**Comment by digitalplaywright** [comment]
Thank you for the quick response. After looking at the Tire unit tests I see that it now supports geo filters, so I rewrote my queries in the native DSL like e.g:

```
 recommended_events = Event.search do |search|
    search.query do |query|
        query.boolean do
            must { range :start_time, {:to => DateTime.now} }
        end
    end
    search.sort { by :start_time, 'asc' }
    search.filter :geo_distance, :distance => "12km", :location => {"lat" =>37.7749295, "lon" => -122.4194155}
    search.from 3
    search.size 3
 end 
```

I have two questions with regards to this:
      -  I need a mechanism to show number of 'pages' for pagination. How do I determine the total number of search results?
      -  Does 'from' refer to the index in the search results after sorting?

**Comment by digitalplaywright** [comment]
I found the answer to the first question by looking at your code:
   https://github.com/karmi/tire/blob/master/lib/tire/results/pagination.rb

The total number of elements is fortunately returned by the 'total' variable. 

With regards to the second question it heuristically seems like the sorted results from the parameter @from@ offset in the result is returned. However, please let me know if you can confirm this as the intended semantics when an index is spread over many shards.

**Comment by karmi** [comment]
@digitalplaywright I think `from` and `offset` should behave just like you expect. Closing the issue for now, open new one if the problem persist please!
