### ISSUE TITLE
Tire/elasticsearch on shared host

### ISSUE THREAD

**Issue by amnesia7** [karmi/retire#167]
Question from a rails newbie. Not an issue but I couldn't find anywhere that I could just ask a question.

My app isn't big yet but I was looking to go down the elasticsearch route now if possible in case the app does grow.

Since the tire demo app installs elasticsearch into the vendor directory of the app does that mean that tire/elasticsearch could be rolled out as part of an app on a shared host?

**Comment by karmi** [comment]
Hi, it's absolutely OK to submit questions as issues.

Theoretically, yes -- you'd be able to do that, if you can launch java apps there. But on a shared hosting, you'd probably need to put some sort of proxy in front of ES with HTTP Auth, etc. It really depends on the host.

**Comment by karmi** [comment]
Ping, any news on this? Closing?

**Comment by amnesia7** [comment]
Interesting to know but I don't think I'll be going with a shared host in the end, but thanks for the reply.
