### ISSUE TITLE
Location sorting

### ISSUE THREAD

**Issue by amnesia7** [karmi/retire#169]
Your wiki page for working with locations [https://github.com/karmi/tire/wiki/How-to-work-with-locations-(geo)-in-Tire] has a filter on locations but I was just wondering whether the results can be ordered by location from a given point or not?

**Comment by karmi** [comment]
**_UPDATE**_

SEE https://github.com/karmi/tire/issues/417#issuecomment-7331381

---

Hi, they definitely could, I'm not sure about the proper mechanics, though, at the moment -- could you please ask on the ES mailing list or IRC channel?

**Comment by amnesia7** [comment]
I found on this page (http://www.elasticsearch.org/guide/reference/api/search/sort.html) a section called "Geo Distance Sorting" and one of the code examples is below:

```
{
    "sort" : [
        {
            "_geo_distance" : {
                "pin.location" : [-70, 40],
                "order" : "asc",
                "unit" : "km"
            }
        }
    ],
    "query" : {
        "term" : { "user" : "kimchy" }
    }
}
```

Can tire work with this type of sorting?

It would also be good to know whether tire can work with the geo distance filter as well (http://www.elasticsearch.org/guide/reference/query-dsl/geo-distance-filter.html).

Thanks

**Comment by al** [comment]
@amnesia7, It can do the geo_distance filter alright ...

```
tire.search(options) do |search|
  ...
  search.filter :geo_distance, {
    :location => [lat, lng],
    :distance => "#{range}km"
  }
}
```

but it looks to me like we've got to be a bit more manual for geo sorting. Am I wrong?

**Comment by al** [comment]
@amnesia7 So here's something that works, but it's not really cool ...

```
tire.search(options) do |search|
  ...
  search.sort {
    by :_geo_distance, {
      :location => [lat, lng],
      :order => 'asc'
    }
  }
end
```

**Comment by aaronchi** [comment]
Not sure why it's not 'cool'... have been doing this in my code for a while now:

```
sort do
  by :_geo_distance, 'addresses.location' => [lng, lat], :unit => 'mi'
end
```

**Comment by amnesia7** [comment]
Thanks guys, that's great to hear.

Is this kind of sorting/ordering processor intensive on the webserver? Is it slow to run or is it ok with indexes on lat and lng columns? 

I assume applying some kind of bounding box filter would be good if there are too many results coming back.

**Comment by karmi** [comment]
Yup, the example @al gives is straight from the ES docs, http://www.elasticsearch.org/guide/reference/api/search/sort.html.

@amnesia7: I believe the sorting is done on the final, small result set returned from ES, so I don't see a reason for much overhead there. Best to ask on `#elasticsearch`'s IRC, though.

So, issue sorted, closing, or... ?

**Comment by niuage** [comment]
When you sort by distance, I read that there is a way to get the computed distance of each document to the searched location. But looking at my raw results, I can't see it. I'd appreciate some help with this, thanks :)

**Comment by mattiassvedhem** [comment]
@niuage It should be in the `_score` field. You can do something like this in Rails
`number_to_human(result._score, :units => :distance, :precision => 0)`

**Comment by niuage** [comment]
Thanks :) My _score fields are `nil` though.
Does it have something to do with `track_scores`?
From the elasticsearch doc: `When sorting on a field, scores are not computed.
By setting track_scores to true, scores will still be computed and tracked.`

**Comment by mattiassvedhem** [comment]
According to the ElasticSearch documentation the order should be [lng, lat] for geopoint. But @aaronchi 's example says [lat, lng] Does Tire switch these?

**Comment by karmi** [comment]
_Tire_ does not mess with location/geo specifically, I cannot rule out a bug. I think maybe you could use a Hash instead of Array for the location definition (as per http://www.elasticsearch.org/guide/reference/query-dsl/geo-distance-filter.html).

**Comment by aaronchi** [comment]
That is a type on my point, I corrected it above.

More recently, I have been using a hash:

```
{:lat => latitude, :lon => longitude}
```

Which works as well

**Comment by mattiassvedhem** [comment]
Ok, cool =).

**Comment by karmi** [comment]
See https://github.com/karmi/tire/issues/417#issuecomment-7331381 in karmi/tire#417.

**Comment by WvanLelyveld** [comment]
I'm having difficulties getting the closest location when sorting objects (with multiple locations) by distance to a given point. See my issue [here](http://stackoverflow.com/questions/16984293/how-to-calculate-closest-location-with-elasticsearch-geo-distance-with-multiple). If anyone has any experience with this and can tell me what I'm doing wrong, any help would be greatly appreciated!

**Comment by karmi** [comment]
@WvanLelyveld Can you post the `to_curl` output of your query, so it's clear what is being sent to ES?

**Comment by WvanLelyveld** [comment]
@karmi.. Thanks for your reply and sorry for the late answer, I didnt see your message.

This is my output that actually gives me results (although with the wrong distance):

```
{"query":{"filtered":{"query":{"query_string":{"query":"other",
"default_operator":"AND","fields":["descriptions.name","group.name"]}}}},
"sort":[{"_geo_distance":{"mode":"min","geolocation":[52.51,5.47],"order":"asc","unit":"km"}}],
"size":20,"from":0}
```

This is how I expected it to work, but gives me an error:

```
{"query":{"filtered":{"query":{"query_string":{"query":"other",
"default_operator":"AND","fields":["descriptions.name","group.name"]}}}},
"sort":[{"_geo_distance":{"geolocation":[52.51,5.47],"mode":"min","order":"asc","unit":"km"}}],
"size":20,"from":0}
```

The error is: `nested: ElasticSearchIllegalArgumentException[No mapping found for field [mode] for geo distance sort];`

Do I need to add something to my mapping to make this work?
This currently is:

```
    indexes :locations do
      indexes :descriptions
      indexes :geolocation, type: "geo_point"
    end
```

Thanks for any help!

**Comment by oniram** [comment]
@WvanLelyveld Do you resolve your problem with "mode":"min" ?

**Comment by WvanLelyveld** [comment]
That's already in there, as you can see in the queries in my previous post. This is still not returning the closest location. Did you suggest something, or just wondering if it had already been fixed?

**Comment by bcackerman** [comment]
+1

**Comment by monfresh** [comment]
I'm running into this issue as well when I combine a keyword and location parameter. When location is the only parameter, it seems to be sorting correctly by distance, but once I add the keyword parameter, it doesn't. Here is the source code: https://github.com/codeforamerica/ohana-api/blob/master/app/models/location.rb#L181-L289

An example query would be: http://www.smc-connect.org/organizations?keyword=food&location=east+palo+alto
I expect the East Palo Alto entries to appear first, but there doesn't seem to be any meaningful distance sorting applied.

**Comment by monfresh** [comment]
In my case, it looks like the reason why sorting is not working is because the keyword search has boost associated with it, which seems to be overriding the sort. Is there a way to give priority to sort? I tried adding a boost to the sort, but that didn't change anything.

**Comment by bcackerman** [comment]
Here's how I got search and sorting by closest distance to work:

``` ruby
tire do
  mapping do
    indexes :lon_lat, type: 'geo_point'
  end
end

def self.search(params)
  # get coordinates
  params_longitude = params[:longitude]
  params_latitude = params[:latitude]
  center_point = [params_longitude, params_latitude]

  # perform search
  tire.search do |s|
    s.query { string params[:find_what], default_operator: "AND" } if params[:find_what].present?
    s.sort do 
      by :_geo_distance, {
        lon_lat: center_point ,
        order: "asc", 
        unit: 'mi'
      }
    end
  end
end

self.include_root_in_json = false # get rid of the root json element
def to_indexed_json
  {
    lon_lat: lon_lat,
    latitude: latitude,
    longitude: longitude,
  }.to_json
end

def lon_lat
  {
    lon: longitude,
    lat: latitude
  }
end
```

**Comment by monfresh** [comment]
Thanks @bcackerman, but that doesn't work for my use case. I need to be able to specify that distance sort should take precedence over any other boost. If the location parameter is present, it should sort by distance first, and then by relevance based on boost value.
