### ISSUE TITLE
Any advice on the best way to test one's setup?

### ISSUE THREAD

**Issue by joshcutler** [karmi/retire#173]
I am really liking this gem however I have a question about testing.  Here is my setup:

I have a number of different things that can trigger updates to the index and thus handle it manually.  I need to test that I am doing it properly however as far as a I can tell this isn't easily done given the async nature of the setup.

E.g. If object A is created, update index for object B.  This doesn't seem to work because I need to put it in my after_commit hook in the object (or elasticsearch won't see it) and the way that tests are setup (at least using shoulda and TestUnit) the transactions never complete until the test is over.

Any thoughts on a better way to do this?

Thanks.

**Comment by karmi** [comment]
Hey, I'm not sure I understand entirely the described issue, but here are my thoughts:

1/ In unit tests, I recommend stubbing Tire methods, or stubbing HTTP responses with Webmock/Fakeweb.
2/ In integration tests, I recommend letting everything bubble thru the stack.

If I understand correctly, you need to update the ES index (Tire method [`update_index`](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L129-143)) in the `after_commit` hook, not in the `after_save` hook, which is the default. So, calling `self.tire.update_index` in the `after_commit` block should be enough?

Lemme know if this advice is in the right direction, and please paste some simplified code so we can have a better understanding of what's going on...

**Comment by joshcutler** [comment]
The reason that I want to call the update_index in the after_commit vs. after_save hook is that because rspec and testunit wrap a whole test in a transaction calling update index will not help because the transaction never completes and thus ES doesn't see the update objects in the database when I would want to make assertions.  This is true for unit tests at least.

The reason I am testing this is because I have one indexed model, call it Document.  It has e.g. an array of authors.  Adding an author should trigger an update on the index for Document.  This needs to be triggered in the after_create/after_commit for author.

I will try just stubbing everything in my unit tests and seeing if I can make it work by just writing integration tests.

Thanks.

**Comment by karmi** [comment]
Hi, this is related to the mechanics of how transactions work in uni tests, then? Is this related to the `config.use_transactional_fixtures = true` setting?

**Comment by karmi** [comment]
@joshcutler: Ping, any news?
