### ISSUE TITLE
Is it possible to sort search by formula?

### ISSUE THREAD

**Issue by oleksify** [karmi/retire#174]
How can I write this on using tire and dynamic value for **factor**?

``` javascript
{
    "query" : {
        ....
    },
    "sort" : {
        "_script" : { 
            "script" : "doc['field_name'].value * factor",
            "type" : "number",
            "params" : {
                "factor" : 1.1
            },
            "order" : "asc"
        }
    }
}
```

**Comment by karmi** [comment]
You have to pass the raw JSON or Ruby Hash to Tire in these cases.

**Comment by karmi** [comment]
@devilcoders: Ping, any news?

**Comment by oleksify** [comment]
Sorry, have no time to chek this again. I guess will be working on that project after new year celebration. Will post how it goes.

**Comment by karmi** [comment]
Closing due to "too far for anybody to remember what was going on before New Year's Eve" factor :)

**Comment by aledalgrande** [comment]
For future reference, the syntax that worked for me is:

``` ruby
sort do
  by ({
    :_script => { 
      :script => "(doc['field1'].value + doc['field2'].value) / doc['field3'].value",
      :type => "number",
      :order => "desc"
    }
  })
end
```

Remember to include all of these fields in your mapping and to_indexed_json output.

**Comment by dedico** [comment]
@aledalgrande you just made my day! :+1: 

Different question - I have a little bit more complicated script - is there a way I can debug / test my script? Or some way to return the value which will be returned from the script so I can see if it works ok?

Thanks,
Marek

**Comment by aledalgrande** [comment]
Hey @dedico, if the script gets too complicated I would suggest to create a
precomputed sorting field in the to_indexed_json method of your model.

That way you can simply write a test for sorting in the controller and unit
tests for the conversion into JSON.

**Comment by joselo** [comment]
@aledalgrande your solution works perfect but I just wondering how can add another sort criteria in the same script, I mean sort search by formula but at the same time sort using another field.

Regards and thanks

**Comment by joselo** [comment]
@aledalgrande no problem I found the solution, anyway thanks!!

``` ruby
sort do
  by [
    {:position => 'asc'},
    ({
    :_script => { 
      :script => "(doc['field1'].value + doc['field2'].value) / doc['field3'].value",
      :type => "number",
      :order => "desc"
    }
  })
  ]
end
```

**Comment by karmi** [comment]
For posterity, if you want to debug the custom script, you can access the Elasticsearch log from the script with something like:

``` java
org.elasticsearch.common.logging.Loggers.getLogger("my_logger").info("hello there!")
```

See the [`logging_from_script.sh`](https://github.com/karmi/elasticsearch-test-scripts/blob/master/logging_from_script.sh#L24) example by @imotov.
