### ISSUE TITLE
Support for OR filters

### ISSUE THREAD

**Issue by ticketevo** [karmi/retire#177]
It looks like currently all filters run under "AND" mode. Is there any way to run query with "OR"

**Comment by karmi** [comment]
Hmm, no, I don't think there's any "default" in _Tire_ like that-. What exactly are you trying to do?

**Comment by ccocchi** [comment]
I think he was talking about the possibility to do this http://www.elasticsearch.org/guide/reference/query-dsl/or-filter.html

Right now if you use more than one filter in a search, you end up with an `and` query :

``` ruby
@articles = Tire.search 'articles' do
   filter :range, :price => { :gte => price } 
   filter :term, :tag => ['foo']
end
```

will send this query to _elasticsearch_

```
{"filter" :
  {"and" : [
    { "term" :
      { "tag" : "foo" }
    }, 
    { "range": 
      { "price" : { "gte" : "10" } 
      }
    }]
  }
}
```

**Comment by ticketevo** [comment]
Yeah we ended up having to just nest a bunch of OR queries under the "and"
