### ISSUE TITLE
Using the REST DSL within Tire DSL

### ISSUE THREAD

**Issue by dennybritz** [karmi/retire#179]
Hello,

I am trying to use a prefix query within a boolean query. Prefix doesn't seem to be supported by the DSL. I was hoping something like this would work:

`should { {:prefix => {:text => "test"}} }`

But it doesn't. Do I have any choice other than rewriting my **complete** query (which is very complex) using the REST DSL? I just want to use this single bit of custom REST DSL code within the Tire DSL.

**Comment by karmi** [comment]
@dennybritz: Hmm, I don't think you have to actually _fully rewrite_ the query -- you can convert it to hash, and then just update the portion of the hash. That is, until there's regular support for `prefix` queries.

**Comment by dennybritz** [comment]
Thanks, I didn't think about that solution :) If I have time I'll implement the prefix query support myself, seems like it should be straightforward.

**Comment by elfassy** [comment]
how does one go about and "convert" his query to a hash? Thx
