### ISSUE TITLE
Wildcard search for email

### ISSUE THREAD

**Issue by zirni** [karmi/retire#181]
Hello,

we're trying to do a wildcard search within email addresses.
Everything works well as long as the query string doesn't contain
a @.

irb(main):005:0> User.search('email:_user_100@_').results.count
=> 0

Do you have any suggestions how to solve this?
Our model mapping looks like this

  tire.mapping do
    indexes :id, :type => 'string', :index => 'not_analyzed', :include_in_all => false
    indexes :email, :type => 'string'
  end

Cheers,
zirni

**Comment by karmi** [comment]
This is ES-related, you have to make sure you have a proper analyzer set for the field in question. 

AFAIK, the "standard" analyzer should have detected e-mails and URLs, but it's not, check that out for yourself:

```
curl http://localhost:9200/<YOURINDEX>/_analyze?text=user@example.com&analyzer=standard
```

You have to define a custom analyzer which uses the [_UAX Email URL_](http://www.elasticsearch.org/guide/reference/index-modules/analysis/uaxurlemail-tokenizer.html) tokenizer.

**Comment by zirni** [comment]
That works :-) thx
