### ISSUE TITLE
does Tire work with Mongomapper?

### ISSUE THREAD

**Issue by digitalplaywright** [karmi/retire#183]
I'd like to use MongoMapper instead of Mongoid for a project. Does Tire support MongoMapper?

**Comment by balexand** [comment]
Yes, I'm using Tire with MongoMapper and so far I haven't had any issues. I'm using the ActiveModel integration as described in the README.

**Comment by digitalplaywright** [comment]
Thanks! It's good to hear that there are no known gotchas.
