### ISSUE TITLE
Index creation fails

### ISSUE THREAD

**Issue by zirni** [karmi/retire#187]
Hello,

we've got a different behavior when it comes to index creation.
Explicitly index creation ends in a different index schema.

```
class User
  tire.mapping do
    indexes :id, :type => 'integer'
    indexes :first_name, :type => 'string'
    indexes :last_name, :type => 'string'
    indexes :company, :type => 'string'
    indexes :street, :type => 'string'
    indexes :zip, :type => 'string'
    indexes :city, :type => 'string'
    indexes :country, :type => 'string'
    indexes :phone, :type => 'string'
    indexes :email, :type => 'string', :index => :not_analyzed
    indexes :created_at, :type => 'date'
    indexes :accepted_terms, :type => 'string'
    indexes :points, :type => 'integer'
  end
end
```

With User.index.create we get the following index schema

```
{
state: open
settings: {
index.number_of_shards: 5
index.number_of_replicas: 1
}
mappings: { }
aliases: [ ]
}
```

We get an empty mapping.

If i just start rails c and the index doesnt exist, the index will be created with the
correct mapping.

```
{
state: open
settings: {
index.number_of_shards: 5
index.number_of_replicas: 1
}
mappings: {
user: {
properties: {
zip: {
type: string
}
phone: {
type: string
}
street: {
type: string
}
city: {
type: string
}
country: {
type: string
}
id: {
type: integer
}
first_name: {
type: string
}
email: {
index: not_analyzed
type: string
}
company: {
type: string
}
last_name: {
type: string
}
created_at: {
format: dateOptionalTime
type: date
}
accepted_terms: {
type: string
}
points: {
type: integer
}
}
}
}
aliases: [ ]
}
```

Any ideas?

Thanks and best regards,
zirni

**Comment by karmi** [comment]
Yeah, you can't just call `User.index.create` and expect it to create the index with proper mappings/settings -- you're effectively just calling the bare `create` method of the bare `index` instance.

It would be nice to support the way you seem to be going here, though!

The documentation says it quite clearly: the index is created when the class loads, _only_ when it does not exist. If you want tighter control, just wrap the correct calls in your own methods, the Wiki has some info on that.

**Comment by squidfunk** [comment]
I have a similar problem: I am importing the data from a model into an index from inside a Rake task like this:

```
Article.index.import Article.all
```

However, when I first delete the index like this:

```
Article.index.delete
Article.index.import Article.all
```

...it doesn't work. I guess it's the same problem zirni experiences, isn't it? What's a good solution for that? I have to delete the index and rebuilt it, primarily because the mapping may have changed. Is it possible to implement this?

Thanks in advance!
Best, Martin

**Comment by zirni** [comment]
Hey, 

Article.index.create takes an options hash which accepts a mapping and settings.

```
Article.index.create(:mappings => Article.tire.mapping_to_hash, :settings => Article.tire.settings)
```

Theres a shorter way to do this with

```
Article.create_elasticsearch_index
```

In fact there the follow available calls i know right now

```
Article.index.delete # what works perfect
Article.index.create # needs the mapping as an optional argument, what IMO shouldn't be optional
Article.create_elasticsearch_index # is doing what Article.index.create should do IMO
```

Best regards,
zirni

**Comment by karmi** [comment]
@karmi @vhyza Bump!

**Comment by karmi** [comment]
So, to recap:
- `Article.create_elasticsearch_index` is the proper way to create an index for the model, with proper mapping
- There _is_ a usable Rake task to help you with import
- Always, always check your mapping, until _Tire_ does a better job here.
