### ISSUE TITLE
created_at and updated_at are returned as nil

### ISSUE THREAD

**Issue by mrjjwright** [karmi/retire#19]
I indexed a basic User ActiveRecord model and although the created_at fields and updated_at fields are indexed properly, as shown with the Elastic Search Head browser, they are being returned as nil from `User.search`.  A few other fields are coming back as nil as well.    This is probably a user error, my apologies.  I am using Rails 3.05.

**Comment by mrjjwright** [comment]
Nevermind, I decided to just search ElasticSearch directly with the other Tire methods.

**Comment by karmi** [comment]
Hi, this is definitely weird, could you check it in the app generated by the Rails template?

I have a simple app where `created_at`/`updated_at` are definitely returned.

Make sure you include them, if you define any `mapping`!

**Comment by karmi** [comment]
Hi, should I close the issue then? Was mapping without created_at/updated_at the culprit?

**Comment by mrjjwright** [comment]
Yes, and thanks for the followup.  I went ahead and went with writing my own hooks using net/http to communicate with ElasticSearch since it has such a well defined REST API already but thanks for Tire.

**Comment by karmi** [comment]
Great, thanks.
