### ISSUE TITLE
Search unable to use controller variables

### ISSUE THREAD

**Issue by ccocchi** [karmi/retire#197]
I'm trying to do a simple search in my controller 

``` ruby
def index
  @results = Article.search do
    filter :range, :price => { :gte => params[:price] }
  end

...
end
```

but I got this error

```
undefined local variable or method `params' for #<Tire::Search::Search:0x007fdc6634f860>
```

but if I add `p = params` before the block and use it inside the search, it works correctly. So is it a correct behavior or am I doing something wrong ?

**Comment by karmi** [comment]
You have to use the "blocks with arguments" syntax, a la `Article.search { |search| search.filter :.... }`, the Readme and http://karmi.github.com/tire/ has more info on that...

**Comment by ccocchi** [comment]
Thanks.

**Comment by elfassy** [comment]
```
@search.q = "test"
Bulletin.tire.search do |s|
  s.query do |q|
    q.boolean do |b|
      b.must {string @search.q}
```

Does not work.... neither does 

```
      b.must do |m|
         m.string @search.q
      end
```

Am i missing something?

**Comment by karmi** [comment]
@elfassy Don't know what you're missing, this is [valid](http://karmi.github.com/tire/#section-54).

**Comment by elfassy** [comment]
if i do `query = @search.q = "test"`
and then use `query` instead of  `@search.q` it works. 
Strange

EDIT:

got it to work with

Bulletin.tire.search do |s|
  s.query do |q|
    q.boolean do |b|
      b.must {|m|m.string self.query}
