### ISSUE TITLE
Rake task to drop all indexes

### ISSUE THREAD

**Issue by sandrew** [karmi/retire#199]
In development environment, I found such issue: when I rake db:create and rake db:seed and then rake db:drop, Elastic will remain all indexes. I made this temporary solution:

```
namespace :tire do
  desc 'Remove all app elastic indexes'
  task :drop => :environment do
    ['articles', 'users'].each do |index_name|
      index = Tire::Index.new index_name
      index.delete
    end
  end
end
```

But it is quite ugly. I think rake task, that drops all application indexes will be rather helpful in this gem.

**Comment by karmi** [comment]
@sandrew I'd be _very_ frightened to provide a task like that -- best leave those couple of minutes spent writing the task for meditation on possible consequences? :) Besides, it would be lots of introspection involved to discover which indices are defined "within the application"? Closing for now, is that OK?

**Comment by sandrew** [comment]
Well, if tasks of such type were really frightening, then we would not have a db:drop task in AR. There are many situations where you really need such tasks, at least during development. And it is hard to invoke it accidentally: you have to input "drop" in your console.

But if the main reason is difficulty with lots of introspections, then it's OK.

**Comment by karmi** [comment]
OK, thanks for kicking me in the butt. Yeah, a task like:

```
$ bundle exec rake environment tire:index:drop INDEX=articles
```

or:

```
$ bundle exec rake environment tire:index:drop INDICES=indexA,indexB,indexC
```

does make a _perfect_ sense. No introspection, no magic, just a convenient way how to delete couple of indices.
