### ISSUE TITLE
yajl-ruby conflicts with my existing JSON parser

### ISSUE THREAD

**Issue by djfobbz** [karmi/retire#20]
any proposed fixes for this? i'm on Rails 3.0.7 with MongoID 2.0.1 & BSON 1.3. i get a lexcial error parsing java using YAJL-RUBY. not sure what's going on. can you please help? thx

**Comment by karmi** [comment]
Not sure -- yajl is pretty much the defaul JSON gem? It sure is preferred in Rails. One option would be to use ActiveSupport JSON support.

Could you paste the errors you get?

**Comment by djfobbz** [comment]
<code>
Started POST "/users/4dca95338b53226b75000001/plans" for 75.58.68.47 at 2011-05-11 16:12:53 -0400
Error occurred while parsing request parameters.
Contents:
Yajl::ParseError (lexical error: invalid char in json text.
                                                    { plan : { intent : 1, privacy : 1, body : 'testing' } }
</code>

**Comment by karmi** [comment]
That's not a valid JSON. Check http://www.jsonlint.com/.

Notice:

```
require 'rubygems'
require 'yajl'

p Yajl::Parser.parse(%Q| { "plan" : { "intent" : 1, "privacy" : 1, "body" : "testing" } } |)
```

**Comment by djfobbz** [comment]
I actually get that error while trying to submit data via CURL command, this is what I send to server when I get the error. How do double quotes play along with JSON & CURL?

<code>
curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST http://staging.testingserver.com/users/4d6779338b53226d2c000001/plans -d "{ plan : { intent : 1, privacy : 1, body : 'testing' } }" -u username:password</code>

**Comment by floere** [comment]
Hi Rick

Try this:

```
curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST http://staging.testingserver.com/users/4d6779338b53226d2c000001/plans -d "{ \"plan\" : { \"intent\" : 1, \"privacy\" : 1, \"body\" : \"testing\" } }" -u username:password
```

Cheers

**Comment by karmi** [comment]
Yeah, or use single quotes to wrap the JSON:

```
curl -v -H 'Content-Type: application/json'
        -H 'Accept: application/json'
        -u username:password
        -X POST http://staging.testingserver.com/users/4d6779338b53226d2c000001/plans -d '
          { "plan" : { "intent" : 1, "privacy" : 1, "body" : "testing" } }
        '
```

**Comment by floere** [comment]
Good point!
