### ISSUE TITLE
percolate doesn't work with freshly installed ElasticSearch

### ISSUE THREAD

**Issue by wbzyl** [karmi/retire#202]
Let's begin with:

```
tar zxvf elasticsearch-0.18.6.tar.gz
elasticsearch-0.18.6/bin/elasticsearch -f
```

Next, run the [percolate-bug.rb](https://gist.github.com/1600728) script:

```
ruby percolate-bug.rb
'OMG i can has' matches queries nil                      # should be  ["memes", "newspeak"]
'OMG i can has' matches queries: ["memes", "newspeak"]   # or, ocassionally, [] (empty array)
'OMG i can has' matches queries ["memes", "newspeak"]    # ok
```

I use ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux] 

--Włodek Bzyl

**Comment by karmi** [comment]
You forgot to refresh the special `_percolator` index, as the docs say in http://karmi.github.com/tire/#section-142:

```
Tire.index('_percolator').refresh
```

Best,

Karel

**Comment by wbzyl** [comment]
Thanks.

Does it mean that

```
Tire.index('_percolator').refresh
```

should be added in [percolated-twitter.rb](https://gist.github.com/1596777#L94) in line 94.

Am I right?

**Comment by karmi** [comment]
Yes, definitely.
