### ISSUE TITLE
undefined method `model_name' for ClassName::Index:Module if tire in module 

### ISSUE THREAD

**Issue by danielschlegel** [karmi/retire#203]
When i try to outsource the tire code from my model to a module i get this error. Unfortunately i didn't find a proper solution to fix this.

**Comment by karmi** [comment]
Sorry, I don't understand the issue properly. Could you add a bit of code so it's more clear?

**Comment by danielschlegel** [comment]
Thank you so much for the fast reaction! 
Yes sure i can give you some more information. First, we use Mongoid and not ActiveRecord.

We have a Person model and a Person::Index module. Since my person.rb i pretty big i want to outsource the code for tire in a module. When i do this i get the model_name exception.

``` ruby
class Person
  include Person::Index

#### some other code
.....
end

module Person::Index

  include Tire::Model::Search

  tire do
    mapping do
      indexes :id, :type => 'string'
      indexes :first_name, :type => 'string', :boost => 100
      indexes :last_name, :type => 'string', :boost => 110
    end
  end
end
```

The exception happens in this method in naming.rb:
        def index_name name=nil, &block
          @index_name = name if name
          @index_name = block if block_given?
          @index_name || [index_prefix, klass.model_name.plural].compact.join('_') # klass.model_name is undefined
        end

i tried different approaches to get the model_name, even with nasty things like this: self.class.to_s.split("::").first
unfortunately i didn't find a good solution. 

Thanks you for tire, it's a great gem!

**Comment by karmi** [comment]
Hmm, that's interesting approach. However, AFAIK it can't be easily done this way, extracting _all_ the Tire-related functionality into a module. Tire depends on having the class where you mix the module into accessible as the `klass` object.

One way how to try to solve this would be to use some kind of `included` hook, or `def self.included(base)` logic in **your** Person::Index, which would then send it to Tire...

**Comment by danielschlegel** [comment]
Thanks again for your answer. I know what you mean. Currently i didn't get it to work but i will try later again. If i have the solution i will add it as comment here.

**Comment by danielschlegel** [comment]
is there a donate button for you somewhere?

**Comment by karmi** [comment]
@danielschlegel Saying "thanks" is absolutely enough :D
