### ISSUE TITLE
Boosting Entire Indices using Tire

### ISSUE THREAD

**Issue by rozumem** [karmi/retire#205]
Does Tire provide an wrapper method to boost entire indices? 

For example, if I have three indices and want to search across all of them, I want certain indices to be given greater preference. http://www.elasticsearch.org/guide/reference/api/search/index-boost.html

Couldn't find it in the Tire documentation, does a wrapper exist?

Thanks.

**Comment by vhyza** [comment]
Hello,

I'm afraid indices_boost option is not supported yet.

**Comment by karmi** [comment]
Maybe something like this would make sense from the _Tire_'s DSL point of view:

``` ruby
Tire.search 'index_1' => { boost: 1.5 }, 'index_2' => { boost: 2 }
```

**Comment by andruby** [comment]
I want this feature too. I'm going to look around in the Tire code to see if I can pull it off.
