### ISSUE TITLE
how to do exact match with elasticsearch Chinese analysis plugin?

### ISSUE THREAD

**Issue by hau** [karmi/retire#206]
I was using the https://github.com/elasticsearch/elasticsearch-analysis-smartcn plugin to perform full text search in Chinese, and the tire gem in a rails application.

I had a activerecord model `Article` which has a string content and many tags.  Tags could be written in Chinese and I want to do exact match on the tags.  I created this mapping inside of `Article`:

``` ruby
    class Article < ActiveRecord::Base
        include Tire::Model::Search
        include Tire::Model::Callbacks
        settings analysis: {
          filter: {
            smartcn_word: {
              'type' => 'smartcn_word'
            }
          },
          analyzer: {
            smart_chinese: {
              'tokenizer' => 'smartcn_sentence',
              'filter' => ['smartcn_word'],
              'type' => 'smart_chinese'
            }
          }
        } do
          mapping do
            indexes :content, type: 'string', analyzer: 'smart_chinese'
            indexes :tags, type: 'string', index: 'not_analyzed'
          end
        end
      end
```

where `Article`'s `tags` is an array of strings.

I had an `Article` with `tags`: `["irresistible"]` and another `Article` with `tags`: `["恭喜发财"]`.  I wanted to search by exact matching on the `tags`.  When I did

``` ruby
Article.search("resistible")
```

, it correctly returned zero match.  But if I searched by

``` ruby
Article.search("发财")
```

, it returned one match.  So, it's doing exact matching for English but a substring match in Chinese.  How can I make it also do exact matching for Chinese?

Thanks for your help.

**Comment by karmi** [comment]
@hau Sorry for long delay -- I think this is better suited for ES mailing list or IRC channel, closing here.

(`Article.search("resistible")` won't match "irresistible" -- `Article.search("*resistible")` would. For partial matches, Ngrams are the way to go.)

**Comment by hau** [comment]
Thanks.  Could you give me a bit more help?  I'm trying to index Chinese text.  It looks like I need to use the "smartcn_sentence" tokenizer.  In my model, I have

``` ruby
  settings analysis: {
    filter: {
      smartcn_word: {
        'type' => 'smartcn_word'
      }
    },
    analyzer: {
      smart_chinese: {
        tokenizer: 'smartcn_sentence',
        filter: %w[smartcn_word],
        type: 'custom'
      }
    }
  } do
    mapping do
      indexes :content, type: 'string', analyzer: 'smart_chinese'
      indexes :tags, type: 'string', index: 'not_analyzed'
    end
  end
```

how do I add another "ngram" tokenizer?

**Comment by karmi** [comment]
Hi, I think you may want to use "multi_field", have a look at https://gist.github.com/1160430 and http://dev.af83.com/2012/01/19/autocomplete-with-tire.html and https://github.com/karmi/railscasts-episodes/commit/03c45c365d1cc23c27ec67280b0fe315164ab116.
