### ISSUE TITLE
Wrong facets count

### ISSUE THREAD

**Issue by niuage** [karmi/retire#207]
I feel bad opening an issue for something that seem simple and documented, but I can't figure it out:

I'm trying to do a simple facet like in the doc: http://karmi.github.com/tire/#section-Faceted_Search

```
Event.search do
    query { string q[:keywords] } if q[:keywords].present?
    filter :range, from: { gte: Time.zone.now }
    facet("timeline") do
        date :from, interval: 'month'
    end
end
```

The timeline facet does not seem to depend on ~~my query and~~ filters, the counts are for the whole index. (ex: I have 2 results, but 3 facet entries, with counts like 28, 23 etc...)

What's wrong?

Thanks.

**Comment by karmi** [comment]
Hi, is it possible to create a gist recreation of the issue, so I can try it?

Some thoughts:
- Do note that filters do not affect facets, ie. they only restrict the _results_
- Inspect the HTTP requests Tire sends to ES with `Tire.configure { logger STDERR }` so you can make sure the query is actually sent etc

**Comment by niuage** [comment]
It think that's all I needed to understand: "filters do not affect facets"...
I feel like it's making facets less useful, at least to me.

I guess it's not possible to transform any filter into a query, right?

Thanks for your answer :)

**Comment by niuage** [comment]
Ok so after some time I realized that I could replace pretty much all my filters by queries:

Instead of

```
filter :range, from: { lte: bod + 1.day, gte: bod }
```

I have

```
query.boolean do
    must { range :from, { lte: bod + 1.day, gte: bod } }
end
```

So my last question is: is there any way to make my geo_distance filter affect my facets?

**Comment by karmi** [comment]
You can either pass the [filter to the facet](http://www.elasticsearch.org/guide/reference/api/search/facets/filter-facet.html), depends on what you're after. Closing for now, could you reopen if you still have the problem?

**Comment by niuage** [comment]
I'll try that.
Concretely, my problem is that is have a location field in my search form, which filters the results obviously, but dont affect the facet counts (because geo_distance is a filter), which make them seem wrong.
