### ISSUE TITLE
Tags strategy with ActiveRecord

### ISSUE THREAD

**Issue by amnesia7** [karmi/retire#212]
I am just creating an app that uses ActiveRecord and each [let's say] article has many tags. 

I want both the article and the associated tags to be searchable.

The easiest implementation of Tire looks to be to have the tags in a field on the Articles db table but ideally I would like to use an autosuggest for tags when a user is adding them to an article to help them use tags that have already been used (match spelling, hyphenating, etc). The autosuggest requirement makes me think that tags should be in their own article_tags db table and linked back to Articles using an article_id. However, this would require the search to use the "load" method (https://github.com/karmi/tire/commit/84f015da749245acc4f1d7bcb5851131c9efb582) between the Articles table and the Tags table.

Does the load method support joining tables if I didn't want to store the same tag, ie Articles, Tags and then a link table (article_id | tag_id)?

I suppose autosuggest may be overkill if ES/Tire can allow a user to search articles for "motorbike" and still find articles with "motorbiking", "motor bikes" or "motor-bike", is this done using fuzzy search & how much it affect search performance?

How does the load method affect the search performance because I will also be 'slowing' the search down by returning articles ordered using geo location?

Can anyone suggest a strategy for applying tags for ActiveModel that would be as straight-forward to implement as possible with ES and Tire and could still offer the option of autosuggest?

I haven't applied tags in any way yet so this section is a blank canvas at the moment...

**Comment by amnesia7** [comment]
I'm just wondering whether I should really just setup the tags model as I see fit and map a database view to ActiveRecord (http://books.google.com/books?id=thTju-4duY4C&lpg=PP1&ots=nFmsRSwKu0&dq=enterprise%20rails&pg=PA147#v=onepage&q&f=false) to gather all the information I need into one place for searching which would make sense.

Does Tire support searching against a database view mapped using ActiveRecord?

If so, are the search and callbacks still applied to each of the models used by the view or would they only be applied to the new ActiveRecord for the view?

Any code snippets would be much appreciated.

Thanks

**Comment by karmi** [comment]
Hey, sorry for not getting to this earlier, was kinda hoping one of several hundreds of _Tire_ users will step in :) -- the question is a nice one, will try to get you some answer today.

**Comment by karmi** [comment]
Hi, I think what you should do is to just store the tag list as `tags` property, and search it with a `terms` query.

As for autosuggestion, you can also keep an index of tags, and do prefix queries on them or analyze them with ngrams.

I think you should post your question to [StackOverflow](http://stackoverflow.com/tags/tire) where there's a bigger chance you get some reply...
