### ISSUE TITLE
How do you import in a Persistent model?

### ISSUE THREAD

**Issue by superplussed** [karmi/retire#214]
If I have a simple class like:

class Article
  include Tire::Model::Persistence

  property :title,        :analyzer => 'snowball'
  property :published_on, :type => 'date'
  property :tags,         :default => [], :analyzer => 'keyword'

end
It seems that I can only perform Article.import if there is a pagination method. But because this is a custom persistent model and I'm not using ActiveRecord, I am not able to use WillPaginate or Kaminari. So is there a custom method I can create to support pagination, and if so what requirements must it meet?

**Comment by karmi** [comment]
@redCashion Why do you consistently cross-post in Github issues and Stackoverflow?

So, cross-posting my SO comment:

> I don't understand the question: from which data store would you like to import Article when it's persisted in ES? 

and closing here...
