### ISSUE TITLE
Mix string and range in query block

### ISSUE THREAD

**Issue by zirni** [karmi/retire#215]
Hello,

i try to mix a string query with a range query.
it doesn't work for me right now.
it looks like that only one condition is allowed
in the query block, isn't it?

```
  Tire.search index_name, :load => true, :per_page => 33 do |s|
    s.query do |qu|
      # TODO: range wins here
      # range is the result of the query block
      qu.string query_string, :default_operator => 'AND'
      qu.range :points, points_range if points_range?
    end
  end
```

Thanks for help.

Best regards,
zirni

**Comment by karmi** [comment]
Yes -- you have to bind queries together eg. with a `boolean` query, http://karmi.github.com/tire/#section-Boolean_Queries

**Comment by karmi** [comment]
@zirni: Closing as solved, is that OK?

**Comment by zirni** [comment]
Yes, thats fine. thx
