### ISSUE TITLE
Default values are not saved into ES

### ISSUE THREAD

**Issue by aq1018** [karmi/retire#216]
When using `Tire::Model::Persistence`, default values declared on properties are not saved into ES. A null value instead of the default value is saved instead. I think the default value should be saved so it can be indexed and searched later.

**Comment by vhyza** [comment]
Hello,

I'm afraid in last version of `Tire` gem is not included commit db6e911e6cef1cbd10d233e374575a839efe0ca7 which allows to define default property for `Tire::Model::Persistence`. This https://gist.github.com/1759827 is working for me with master. So after @karmi release new version of gem it should be working properly.

**Comment by aq1018** [comment]
yes I was using the latest gem. Thanks for the reply.
