### ISSUE TITLE
Using Activerecord Observer on a model that uses elasticsearch/Tire slows down loading times

### ISSUE THREAD

**Issue by ReLrO** [karmi/retire#220]
I have implemented the Tire gem in my application and lately wanted to use an observer on some of the models I also have Tire/elasticsearch on. 
What happens is that because of the observer, elasticsearch is being invoked on each and every call when loading (not searching) a page. so for example, take a look at what's happening when getting an image:

```
Started GET "/assets/icons/landing-icons.png" for 127.0.0.1 at 2012-01-31 13:00:28 +0200
Served asset /icons/landing-icons.png - 304 Not Modified (2ms)
#2012-01-31 13:00:28:976 [HEAD] ("development::application-questions")
#
curl -I "http://localhost:9200/development::application-questions"

#2012-01-31 13:00:28:976 [200]

#2012-01-31 13:00:28:998 [HEAD] ("development::application-answers")
#
curl -I "http://localhost:9200/development::application-answers"

#2012-01-31 13:00:28:998 [200]
```

This really slows the loading time of a page. I want to keep using both features. Any idea how this could be solved?

**Comment by karmi** [comment]
Hey, this hints at your model being loaded at every call -- it checks the index existence. Why this should be happening? Is it related to the Obsever being used? Rails reloads classes in development mode, is it related to that?

**Comment by ReLrO** [comment]
Hey Karmi.

It is because of the Observer. Once I am not observing the specific model, it will not happen. Something about the observer makes Tire load on every call. Look at this post. I know it is unrelated but a comment posted there solved my problem for now 
https://github.com/mongoid/mongoid/issues/1360

I installed the gem mentioned there in the last post (https://github.com/thedarkone/rails-dev-boost) and it actually worked.
I now just hope it will not happen in production.

**Comment by karmi** [comment]
Hmm, then I see it as a problem with the Observer pattern either in Ruby or Rails... Could you try to isolate the problem, and try observing it with the plain Ruby [`Observable`](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/observer/rdoc/Observable.html)? If it works with it, then Rails is the culprit.

**Comment by ReLrO** [comment]
Ok, i'll try to check it. Thanks

**Comment by karmi** [comment]
Closing for now, please open a new issue or reopen if the problem persists!
