### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by ghost** [karmi/retire#221]
Is it possible to use cancan or other authorisation methods with elasticsearch or tire?

**Comment by karmi** [comment]
Don't know what you mean by that, sorry, could you be more specific?

**Comment by ghost** [comment]
In my current application i have build a simple search by querying the database directly. Authorisation is done by cancan (@articles = Article.accessible_by(current_ability) ) so i can define what a user is able to access (eg. User can only see tasks form projects he is involved). 

What is the concept with tire/elasticsearch, do i have to setup different indexes for different users/permissions?

**Comment by karmi** [comment]
Several concepts you can use:
- An index per user (has a performance penalty),
- a filtered alias per user (http://www.elasticsearch.org/guide/reference/api/admin-indices-aliases.html)
- filter by eg. `user_id` in the search block,
- etc.

So eg. something like this for the last option:

``` ruby
Todo.search do |search|
  search.query { |q| q.string params[:q] }
  search.filter :term, current_user.id
end
```

**Comment by ghost** [comment]
Thanks for your help. Will have a look into this concepts.
