### ISSUE TITLE
How to update an object?

### ISSUE THREAD

**Issue by shoshi-baron** [karmi/retire#229]
I use tire. 
I want  to add attributes to an existing object and to update attributes.

**Comment by karmi** [comment]
Hi, could you be more specific as to what kind of "object" you have? Could you post some example code?

**Comment by shoshi-baron** [comment]
Yes, thanks for the quick reply.

```
# this is my model 
class Product
  include Tire::Model::Search
  include Tire::Model::Callbacks
  def self.by_name(name)
    q = Tire.search "products" do
          query do
            string "name:#{name}"
          end
        size 2
    end
    return q.results
  end 
  end

#example of an object
Product.by_name("Pioneer")
 => #<Tire::Results::Collection:0xa4ac630 @response={"took"=>4, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>305, "max_score"=>4.409558, "hits"=>[{"_i
ndex"=>"products", "_type"=>"document", "_id"=>"VzeRgAg7RWuU-j0iHOiP7A", "_score"=>4.409558, "_source"=>{"retailer_id"=>4, "name"=>"Pioneer  (AVX505)", "brief_desc"=>"Pioneer  (AVX505)", "long_desc"
=>"Pioneer  (AVX505)", "price"=>"199.50", "url"=>"http://gan.doubleclick.net/gan_click?lid=41000000032151753&pid=AVX505&adurl=http%3A%2F%2Fwww.electronicexpress.com%2Fcatalog%2F6682%2FPioneer-AVX505
%3Fcpc%3D6&usg=AFHzDLtjm2C1PfwkTv9XHQzOTt0jeWZkjA&pubid=21000000000387855", "image_url"=>"http://images.electronicexpress.com/products-lg/photo_not_available.gif", "category"=>"\"Electronics\""}}, {
"_index"=>"products", "_type"=>"document", "_id"=>"44JCwIJ6QcuXCapTd1MeXA", "_score"=>3.741634, "_source"=>{"retailer_id"=>4, "name"=>"Pioneer Bluetooth Adapter for Compatible Pioneer (AS-BT100 / AS
BT100)", "brief_desc"=>"Pioneer Bluetooth Adapter for Compatible Pioneer Products (Black) (AS-BT100 / ASBT100)", "long_desc"=>"Pioneer Bluetooth Adapter for Compatible Pioneer Products (Black) (AS-B
T100 / ASBT100)", "price"=>"89.00", "url"=>"http://gan.doubleclick.net/gan_click?lid=41000000032151753&pid=ASBT100&adurl=http%3A%2F%2Fwww.electronicexpress.com%2Fcatalog%2F17983%2FPioneer-ASBT100%3F
cpc%3D6&usg=AFHzDLuGsILA829IB8cj9c70sv6ewJsJIw&pubid=21000000000387855", "image_url"=>"http://images.electronicexpress.com/products-lg/17983.jpg", "category"=>"\"Car Audio / Video & GPS > Car Audio 
Accessories\""}}]}}, @options={:size=>2}, @time=4, @total=305, @facets=nil, @wrapper=Tire::Results::Item>
```

**Comment by karmi** [comment]
OK -- when you have a plain old Ruby class as your model, you have to add some `attr_accessor` or something like that, and you should define a `to_indexed_json` method to translate your data for ES.

I still don't understand 100% what you're really after here.

**Comment by shoshi-baron** [comment]
I try to call update_attributes on this object. 

p = Product.by_name("Pioneer")
attr = {:suspend => true}
p.update_attributes(attr)
=> nil

but nothing updated.

**Comment by karmi** [comment]
Are you trying to use `Tire::Model::Persistence`? Or has your model some other ActiveModel implementation?

**Comment by shoshi-baron** [comment]
I added the persistence module, but how can it help me?
I try to see the method 'update_attribute' on query result item and it isn't there.
I think that ' Tire::Results::Item' is  not the same as my class Product instance, so it doesn't have 'update_attributes' method.
Am I right?

**Comment by karmi** [comment]
@shoshi-baron I'm sorry but I don't understand what you're trying to do at all :)

> I think that ' Tire::Results::Item' is not the same as my class Product instance

You are right. You have to use the `:load` option to load "real model instances", eg. ActiveRecord ones.

**Comment by karmi** [comment]
Closing for now, please open new issue if the problem persists...
