### ISSUE TITLE
Possible to acces both Item and AR instances in result set?

### ISSUE THREAD

**Issue by joshcutler** [karmi/retire#230]
First of all thanks for all of the work on this gem.  I was wondering if it is possible to access bot the Tire result Item as well as its ActiveRecord instance using the :load => true parameter.  I need to do this because ES is storing some aggregate information that is not contained in my AR instance.

Ideally I could do something like:

results = MyClass.search "test", :load => true

ar_instance = results.first
item_instance = results.items.first

Or something like that.  Is this supported?

Thanks,
-=Josh

**Comment by vhyza** [comment]
Hello,

I think is possible to `load` record when iterating

``` bash
>> articles = Article.search("lorem")
# 2012-02-07 14:16:54:372 [_search] (["articles"])
#
curl -X GET "http://localhost:9200/articles/article/_search?pretty=true" -d '{"query":{"query_string":{"query":"lorem"}}}'

# 2012-02-07 14:16:54:372 [200] (3 msec)

=> #<Tire::Results::Collection:0x007fe1e585fbc8 @response={"took"=>3, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>1, "max_score"=>0.040683318, "hits"=>[{"_index"=>"articles", "_type"=>"article", "_id"=>"6", "_score"=>0.040683318, "_source"=>{"content"=>"Lorem ipsum dolor sit amet.", "created_at"=>"2012-02-07T13:05:24Z", "published_on"=>"2012-02-07T13:05:24Z", "title"=>"One", "updated_at"=>"2012-02-07T13:05:24Z"}}]}}, @options={}, @time=3, @total=1, @facets=nil, @wrapper=Tire::Results::Item>
>> articles.each do |article|
?>    p article
>>    p article.load
>> end
<Item (Article) content: "Lorem ipsum dolor sit amet.", created_at: "2012-02-07T13:05:24Z", published_on: "2012-02-07T13:05:24Z", title: "One", updated_at: "2012-02-07T13:05:24Z", id: "6", _score: 0.040683318, _type: "article", _index: "articles", _version: nil, sort: nil, highlight: nil>
  Article Load (0.2ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" = ? LIMIT 1  [["id", "6"]]
<Article id: 6, title: "One", content: "Lorem ipsum dolor sit amet.", published_on: "2012-02-07", created_at: "2012-02-07 13:05:24", updated_at: "2012-02-07 13:05:24">
```

**Comment by joshcutler** [comment]
Thanks.  I did know about that option, but if I have 100 items then I'm doing 100 mysql calls that way.  Whereas the :load => true option does a bulk load and then reorders the AR objects appropriately.  I was hoping there was a way to take advantage of the bulk load and still access the items.

**Comment by vhyza** [comment]
I understand, but unfortunately I don't know about another option provided by `Tire`. You can still load it manually

Extracted from `Tire`:

``` ruby
article_items = Article.search("*")
ids = article_items.map(&:id)
articles = Article.find(ids)
# Reorder records to preserve order from search results
ids.map { |id| articles.detect { |article| article.id.to_s == id.to_s } }
```

**Comment by karmi** [comment]
@joshcutler I understand the requirement, however, I'm not sure it makes much sense... I think, mostly you need either the "optimized" JSON doc from ES, or the "real model instance" from the database... Of course, it would be trivially possible to leave the items in the result set, when you `:load` the models -- is it something you depend on in your app?

What does anybody else think?

**Comment by joshcutler** [comment]
In my particular app it is necessary but I understand that this may be a strange use case and I worked around it.  The situation is that in my ES index I store some composite values that are semi-expensive to compute which I would like access to and then I have some other functionality in AR that I want to use as well.  I could probably work around this by coming up with a scheme to index everything I need into ES.  It is not a deal break for me though, I mostly just wante to know if it was easily possible to do w/Tire or I should do it manually.

**Comment by karmi** [comment]
> in my ES index I store some composite values that are semi-expensive to compute

@joshcutler Yeah, that makes _perfect_ sense, and is also the reason why I recommend to go without `:load` if possible at all. I think this could be supported easily, since the data for `Item` instances are of course loaded from ES. Ping me here or at IRC in a week or two and I'll have a look into it, if nobody else picks it up...

**Comment by karmi** [comment]
@joshcutler Seems like _Sunspot_ has a [support](http://sunspot.github.com/docs/Sunspot/Search/AbstractSearch.html#each_hit_with_result-instance_method) for that. I still think it's kinda weird in ES, but would be very trivial to implement. Is it something you still need?

**Comment by joshcutler** [comment]
Don't do it just for me.  I have a good workaround for now (you are right it was trivial).  When I opened the ticket I just wanted to make sure there wasn't a way to do with with tire already before I did it myself.

**Comment by karmi** [comment]
@joshcutler Perfect, thanks! So let's close it for now and wait if the need for something like that arises again...
