### ISSUE TITLE
Support for versioning ?

### ISSUE THREAD

**Issue by shardnit** [karmi/retire#231]
Hi,
I am using Tire ES library for indexing as well as searching. ES indexer (which stores data into ES) relies highly on document version before performing any "store" operation.
I couldnt find any support for "version" option in "store" function. As of now, I have written my own Ruby function.
Version based storing is somewhere down the roadmap or just missed?

Cheers
Nitish

**Comment by karmi** [comment]
Hi, I think that's an easy feature to add... I'm planning processing pull requests and adding trivial features like this during February, ping me here or on IRC if I forget...

**Comment by karmi** [comment]
@nsa310 Should be closed in 2bf5585.
