### ISSUE TITLE
how to DSL?

### ISSUE THREAD

**Issue by dryaf** [karmi/retire#233]
i m using 

```
  VProducts.tire.search(@search, :per_page=>Kaminari.config.default_per_page, :page=>params[:page] || 1)
```

to do regular search with pagination and kaminari

Now VGroups have VProducts
and i would like to search within the products of a group too

```
  @v_products = Tire.search 'v-products' do
    query do
      string @search
      boolean do
        must { string 'v_group_id:' + @v_group.id.to_s }
      end
    end
    sort { by :name, 'desc' }
  end
```

This didn't work. Next problem will be (if somebody could help me with this):
how do I set page and per_page in the DSL

**Comment by vhyza** [comment]
Hello,

please can you gist your models and some example documents?

**Comment by dryaf** [comment]
i found the error. i can't access instancevariables in the query blocks (that sucks)
but 
search = @search 
did the trick

http://stackoverflow.com/questions/5150483/instance-variable-not-available-inside-a-ruby-block

thx vhyza

**Comment by karmi** [comment]
> i can't access instancevariables in the query blocks (that sucks)

@banditj I don't think that's true at all. This code:

```
@query = 'title:TEST'

s = Tire.search 'articles' do |search|
  search.query do |query|
    query.string @query
  end
end
```

works just fine. A test proving anything otherwise is very welcome!

**Comment by dryaf** [comment]
ok thx for your response

in my case

```
@v_group = VGroup.find(params[:id])
@search = params[:search] if params[:search]
group_id = @v_group.id.to_s
searchtxt = @search
page = params[:page]
#@v_products = @v_group.search_v_products(@search, params[:page])
@v_products = VProduct.tire.search :per_page => Kaminari.config.default_per_page, :page => page do
        query do
          string @search
        end
        filter :terms, :v_group_id => [group_id]
      end
```

results in 
......roducts][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":null}},\"filter\":{\"terms\":{\"v_group_id\":[\"4e78007f499dda9ef3000001\"]}},\"size\":10}]]];

and 

```
def show
 @v_group = VGroup.find(params[:id])
 @search = params[:search] if params[:search]
 group_id = @v_group.id.to_s
 searchtxt = @search
 page = params[:page]
 #@v_products = @v_group.search_v_products(@search, params[:page])
 @v_products = VProduct.tire.search :per_page => Kaminari.config.default_per_page, :page => page do
         query do
           string searchtxt
         end
         filter :terms, :v_group_id => [group_id]
       end
```

works just fine.
i only replaced @search by searchtxt
as the query error said the query_string is null

i m using ree and rails 3.1.3.
probably something goes wrong

**Comment by karmi** [comment]
@banditj Notice you're _not_ using the "blocks with arguments" syntax in your code. The Readme and docs have good explanation how it works and why you need it.

**Comment by dryaf** [comment]
@karmi ok. thank you. i guess my ruby skills in general need some improvement! wish you a nice weekend
