### ISSUE TITLE
How do Tire mappings in a class hierarchy

### ISSUE THREAD

**Issue by behrangsa** [karmi/retire#234]
Do a mapping call in a subclass override the mapping call in the superclass, or would it overwrite/append to it? For example if I have this class hierarchy:

``` ruby
  class Article < ActiveRecord::Base
      include Tire::Model::Search
      include Tire::Model::Callbacks

      mapping do
        indexes :id,           :index    => :not_analyzed
        indexes :title,        :analyzer => 'snowball', :boost => 100
      end
    end

  class SubArticle < ActiveRecord::Base
      include Tire::Model::Search
      include Tire::Model::Callbacks

      mapping do
        indexes :id,           :index    => :not_analyzed
        indexes :body,        :analyzer => 'snowball', :boost => 100
      end
    end
```

Would `SubArticle` have its `title` indexed as well, or would it only have its `body` and `id` fields indexed?

**Comment by vhyza** [comment]
Hello,

I'm not sure if I understand correctly. Both `Article` and `SubArticle` inherits from `ActiveRecord::Base` so mapping should not be overwritten. So `SubArticle` indexes only `id` and `body`. You can check your mapping in `elasticsearch` on URLs:

[http://localhost:9200/articles/_mapping?pretty=true](http://localhost:9200/articles/_mapping?pretty=true)

and

[http://localhost:9200/sub_articles/_mapping?pretty=true](http://localhost:9200/sub_articles/_mapping?pretty=true)

**Comment by behrangsa** [comment]
Sorry, SubArticle should extend Article.

**Comment by vhyza** [comment]
Ok then. According mapping its not overwritten/appended

**Comment by behrangsa** [comment]
Ok, thanks for the reply.
