### ISSUE TITLE
How to create an OR query?

### ISSUE THREAD

**Issue by behrangsa** [karmi/retire#235]
When I execute the following search from the shell:

``` bash
curl -XGET http://localhost:9200/documents/document/_search?q=content:Christopher
```

I get some search results.

However when I execute this:

``` ruby
    Tire.search 'documents' do
      query do
        boolean do
          should { string "title:*Christopher* " }
          should { string "content:*Christopher* " }
        end
      end
  end
```

I am not getting any results. The above query converts to the following curl query by the way:

``` bash
url -X GET 'http://localhost:9200/documents/_search?pretty=true' -d '{'query':
{'bool':{'should':[
{'query_string':{'query':'title:*Christopher* '}},
{'query_string':{'query':'content:*Christopher* '}}]}}}'
```

Any ideas what am I missing here?

**Comment by vhyza** [comment]
Hello,

I think `*` aren't necessary. Try something like:

``` ruby
Tire.search 'documents' do
  query do
    boolean(:minimum_number_should_match => 1) do
      should { string "title:Christopher" }
      should { string "content:Christopher" }
    end
  end
end
```

**Comment by vhyza** [comment]
@behrangsa please close the issue if it's solved.

**Comment by HenleyChiu** [comment]
Open it up again! This is flat out wrong. It should be:
boolean({:minimum_number_should_match => 1}) do
NOT boolean(:minimum_number_should_match => 1)

**Comment by emerak** [comment]
Is this working? I have this
boolean(minimum_number_should_match: 2) do
      should { string("e_name:#{search[:name]}") } unless search[:name].blank?
      should { string("e_name:#{search[:last_name]}") } unless search[:last_name].blank?
end

Even though I am only sending one param (name) it returns all of the matches, what I am doing wrong? Am i missing something?
