### ISSUE TITLE
Tire seems to clobber my instance methods

### ISSUE THREAD

**Issue by hraynaud** [karmi/retire#236]
I am trying to create an index during an observer call back as follows

``` Ruby
class SomeObserver < ActiveRecord::Observer

  def after_create(object)
    @object = object
     ...
     add_object_to_index
  end

  def add_object_to_index
      Tire.Index 'objects' do
        store :content => @object.content
      end
  end

end
```

This results in an:

``` Ruby
 undefined method `add_object_to_index ' for class `Tire::Index'? 
```

I have tried everything i can think of. The only that works is removing the references to tire completely from this class but of course the whole point is I need this functionality. 

 I know that the context/scope  inside the Tire.index  block refers to Tire itself. But how is it that it is affecting the scope of the observer instance?

In case you're wondering I'm doing it this way instead of using the active record integration because the model I want to index is part of a gem. I initially tried to reopen the class and add:

``` Ruby
include Tire::Model::Search
include Tire::Model::Callbacks
```

but I couldn't figure out how to do it. Any advice on how to use the AR integration with a model inside a gem would also be greatly appreciated if that is indeed supported.

Thanks

**Comment by vhyza** [comment]
Hello,

there is scope problem in `add_object_to_index`. This is working for me: https://gist.github.com/1767008

**Comment by hraynaud** [comment]
@vhyza 

Thanks for the assistance. You are right but I can't figure out what the scope problem is.  I wonder if it is related to the model  I'm observing being inside a gem.  Fortunately there's not much logic in the model. I suppose I can extract the whole model into my application and see if the problem goes away.  Unfortunately, I'm about out of my depth when it comes to the subtle interactions of gems and engines with the main rails app.

If you have any additional thoughts I would appreciate it. Thanks

Herby

**Comment by vhyza** [comment]
I'm glad its working.

To be honest, I'm not sure if I understand this scope problem correctly, but I think inside the `Tire.index 'objects' do` block should be accessible objects from `add_object_to_index` method, so this should be working too.

``` ruby
class SomeObserver < ActiveRecord::Observer
  observe :article

  def after_create(object)
    @object = object
    add_object_to_index
  end

  def add_object_to_index
    object = @object
    Tire.index 'objects' do
      store :content => object.content
    end
  end

end
```

I'm sorry, but I don't know what you mean by `subtle interactions of gems and engines with the main rails app`

**Comment by hraynaud** [comment]
@vhyza thanks for your help. I think i've resolved this issue.  There is definitely scope wonkiness under some circumstances when I have  more time I will document the behavior more accurately. For now everything works mostly as expected.

Thanks again.
