### ISSUE TITLE
indexes :as proc option runs in class context

### ISSUE THREAD

**Issue by trollybaz** [karmi/retire#239]
I'm somewhat new to tire and I can't seem to get the :as option working for my AR model.  I'm trying to specify the value for an indexed field using a proc:

```
indexes :comments, :as proc { comments.size }

or

indexes :comments do
  comments.size
end
```

Looking at the code in indexes() it does a yield, which runs the block in the context of the class instead of the instance.  Am I missing something?

**Comment by karmi** [comment]
Hi,

> I'm somewhat new to tire and I can't seem to get the :as option working
> for my AR model.

its not included in the released version yet -- you have to use the latest
Git version, eg. with Bundler.

Karel

**Comment by trollybaz** [comment]
Great, thanks.
