### ISSUE TITLE
Should support ELASTICSEARCH_URL for easier Heroku integration

### ISSUE THREAD

**Issue by nz** [karmi/retire#240]
Hi @karmi,

It would be awesome if Tire could configure its URL from the `ELASTICSEARCH_URL` environment variable for transparent integration with the [bonsai.io](http://bonsai.io) ElasticSearch addon over at Heroku.

Cheers!

**Comment by karmi** [comment]
Hi Nick,

that's quite easy to achieve. Just put the the configuration:

``` ruby
Tire.configure do
  url ENV['ELASTICSEARCH_URL']
end
```

in a Rails application initializer or some other appropriate location. Does it work for you?

**Comment by nz** [comment]
That definitely makes for an easy initializer, but in my experience it's much nicer for users if the client can auto-detect that. You'd be surprised how much friction even a simpler initializer can be on the scope of an add-on :)

Personally, I would tweak the `Tire::Configuration.url` method to look like this:

``` ruby
def self.url(value=nil)
  @url = (value ? value.to_s.gsub(%r|/*$|, '') : nil) || @url ||
          ENV['ELASTICSEARCH_URL'] || "http://localhost:9200"
end
```

In fact, I'll go ahead and send in a pull request for that :)

**Comment by karmi** [comment]
Hey, usually, I'd vote for putting stuff like this into _tire-contrib_, but yes, `ENV['ELASTICSEARCH_URL']` could be considered as much default as http://localhost:9200...

**Comment by aaronchi** [comment]
unfortunately, this is now called `ENV['BONSAI_INDEX_URL']` :P

**Comment by nz** [comment]
Also, it's a URL for an index, not a cluster. I think I missed that bit somewhere in between the configuration stuff and the actual live requests. Maybe @karmi will beat me to that fix?

**Comment by karmi** [comment]
So `ENV['BONSAI_INDEX_URL']` contains the full, composed URL to the index? Will probably work when you leave out the index name in `Tire.search`, not sure about other parts of the API.

**Comment by matthewrudy** [comment]
I ended up using this gist https://gist.github.com/2041121.
But did it slightly different.

``` ruby
if index_url = ENV["BONSAI_INDEX_URL"]
  # defer to the heroku env
  uri = URI(index_url)

  Tire.configure do
    "http://#{uri.host}"
  end

  TIRE_INDEX = uri.path[1..-1]
else
  # use the default url
  TIRE_INDEX = "refer-me"
end
```

**Comment by karmi** [comment]
@matthewrudy Yeah, this sucks right now. We're talking with @nz about making it more convenient -- allowing to use one index per app and put models in different indices. I'd like to do it without breaking existing apps.

**Comment by matthewrudy** [comment]
Perhaps a reasonable solution is;

``` ruby
Tire.configure do
  index_url ENV["BONSAI_INDEX_URL"]
end
```

This could in turn set a Tire.global_index variable.
Thereby

``` ruby
def MyModel.index
  Tire.global_index || MyModel.name.underscore
end
```

Something like that?

**Comment by Evan-M** [comment]
@karmi @matthewrudy How about just allowing for a tire config option to set a global index name? The global_index option could default to nil, reverting the index naming back to the default behavior of one index per model:

``` ruby
Tire.configure do
  # Load all models under one index; store model name in the document type?
  # Example:
  global_index "chunky_bacon" # or TIRE_INDEX, ELASTICSEARCH_INDEX, ENV['ELASTICSEARCH_INDEX'], etc...
end
```

This would maintain the existing functionality of Tire, but keep it agnostic of bonsai.io.  
Your bonsai.rb initializer file could look like this:

``` ruby
if ENV["BONSAI_INDEX_URL"]
  uri = URI(ENV["BONSAI_INDEX_URL"])

  Tire.configure do
    url "http://#{uri.host}"
    global_index uri.path[1..-1]
  end
end
```

Thoughts?

**Comment by karmi** [comment]
Hi, yes, something like that seems to me to be proper approach. The thing is to:
- Make sure models use `_type` to separate themselves, does not matter if in one index or multiple indices,
- multiple models can live happily within one index,
- you can set the index name globally (and don't have to set `index_name` in all your models one by one)

Only the third thing should be left to implement in current codebase,  and  yes, `Tire.configure { index "something }` as @matthewrudy suggest looks nice.

BTW, I like how in [redis-rb](https://github.com/redis/redis-rb) you can do:

``` ruby
Redis.connect url: redis://redis.example.com:6379/1
```

**Comment by matthewrudy** [comment]
@Evan-M that was my meaning.

``` ruby
Tire.configure do
  index_url ENV["BONSAI_INDEX_URL"]
end
```

should set the values of `global_index` and `url` automatically.

Notably, this makes the concept of `url` a bit wrong as well, what we really mean is `base_url` or something of that sort.

**Comment by Evan-M** [comment]
I came up with these unit tests for the above discussed features to add to the configuration_test.rb:

``` ruby

should "return default global_index_name of nil" do
  assert_nil Configuration.global_index_name
end

should "allow setting and retrieving the global_index_name" do
  assert_nothing_raised { Configuration.global_index_name 'unique_key_or_name' }
  assert_equal 'unique_key_or_name', Configuration.global_index_name 
end

should "return default index_url of nil" do
  assert_nil Configuration.index_url
end

should "allow setting and retrieving of the index_url" do
  assert_nothing_raised { Configuration.index_url 'http://es.example.com/chunky_bacon' }
  assert_equal 'http://es.example.com/chunky_bacon', Configuration.index_url
end

should "set the URL and global_index_name from index_url" do
  assert_nothing_raised { Configuration.index_url 'http://es.example.com/unique_key_or_name' }
  assert_equal 'http://es.example.com', Configuration.url
  assert_equal 'unique_key_or_name', Configuration.global_index_name
end 
```

I'll make these tests pass and send @karmi a pull_request.

**Comment by aaronchi** [comment]
As an aside, the current import methods will not work with Bonsai because of the use of the 'bulk' command

**Comment by Evan-M** [comment]
Heh @aaronchi, I was just running into that earlier today as I was trying to get things working with Bonsai... here is what I came up with:

Addition to the Tire::Index class:

``` ruby
# /lib/tire/index.rb
  ...
  def bulk_import_url
    url = Configuration.url
    url += "/#{Configuration.global_index_name}" if Configuration.global_index_name
    url + "/_bulk"
  end
  ...
```

Then the bulk_store method in the Tire::Index class posts to the bulk_import_url response message:

``` ruby
# /lib/tire/index.rb
  ...
  def bulk_store documents
    ...
    begin
      response = Configuration.client.post( bulk_import_url, payload.join("\n") )
      ...
    ensure
      curl = %Q|curl -X POST "#{bulk_import_url}" -d '{... data omitted ...}'|
      logged('BULK', curl)
    end
  end
  ...
```

Note that the global_index_name effectively becomes the default index for all models, if it is set:

``` ruby
# /lib/tire/model/naming.rb
  ...
  def index_name name=nil, &block
    @index_name = name if name
    @index_name = block if block_given?
    @index_name = Tire::Configuration.global_index_name if Tire::Configuration.global_index_name
    @index_name || [index_prefix, klass.model_name.plural].compact.join('_')
  end
  ...
```
