### ISSUE TITLE
OR filter with multiple same key values get mapped to single key

### ISSUE THREAD

**Issue by cwadding** [karmi/retire#243]
Just trying to duplicate an OR filter on as shown on the [elastic search site](http://www.elasticsearch.org/guide/reference/query-dsl/or-filter.html) in a rails app.

```
def self.search(params)
    tire.search(:page => (params[:page] || 1), :per_page => (params[:per] || 10)) do
        filter :or, {:filters => {:term => {"name.second" => "banon"}, :term => { "name.nick" => "kimchy" }}}
        raise to_json
    end
end
```

but the resulting json I get back is:

```
"filter": {
    "or": {
        "filters": {
            "term": {
                  "name.nick": "kimchy"
            }
          }
       }
    },
    "size": 10,
    "from": 0
}
```

I also tried with square brackets as follows

```
def self.search(params)
    tire.search(:page => (params[:page] || 1), :per_page => (params[:per] || 10)) do
        filter :or, {:filters => [:term => {"name.second" => "banon"}, :term => { "name.nick" => "kimchy" }]}
        raise to_json
    end
end
```

and I get the same result. It seems that the earlier `term` gets over written by the second one. Is there anyway to allow for multiple term filters in an OR filter?

**Comment by vhyza** [comment]
Please, could you check it on the current master?

Here is test with `or filter`: https://github.com/karmi/tire/blob/master/test/integration/filters_test.rb#L22-33

**Comment by cwadding** [comment]
Thanks, that syntax works great.

**Comment by cwadding** [comment]
Another related question. I am not even sure if elastic search allows for nesting `and`'s inside `or`'s and vice versa for filters but I was experimenting with a complex query like so:

```
def self.search(params)
    tire.search(:page => (params[:page] || 1), :per_page => (params[:per] || 10)) do

        filter :or, {:and => [:term => { "name.second" => "banon"}, :term => {"name.nick" => "kimchy"}]}, {:and => [:term => { "user" => "banon"}, :term => {"name.first" => "drew"}]}

        raise JSON.pretty_generate(to_hash)
    end
end
```

But I get the same problem or the first `term` being overwritten by the second.

```
"filter": {
    "or": [
      {
        "and": [
          {
            "term": {
              "name.nick": "kimchy"
            }
          }
        ]
      },
      {
        "and": [
          {
            "term": {
              "name.first": "drew"
            }
          }
        ]
      }
    ]
  },
  "size": 10,
  "from": 0
}
```

If it is even possible to process a nested query using elastic search how would I create the JSON using tire.

**Comment by karmi** [comment]
@cwadding Is the problem still on current master?

**Comment by shawndeprey** [comment]
@cwadding Your answer works. I've seen many solutions around the web that do not work, but you're invariably solves this problem. Thank you good sir.
