### ISSUE TITLE
Implement boosting and custom_boost_factor

### ISSUE THREAD

**Issue by mattiassvedhem** [karmi/retire#245]
Would be great if we could implement boosting and custom_boost_factor. As I see it there's no way to do it with the DSL today?

[Boosting](http://www.elasticsearch.org/guide/reference/query-dsl/boosting-query.html)
[Custom boost factor](http://www.elasticsearch.org/guide/reference/query-dsl/custom-boost-factor-query.html)

I guess it would go in Tire::Search::Query?

**Comment by karmi** [comment]
Hi, I think this is too special to pollute the main DSL, I'd suggest using Hash queries or doing a contrib for that.

**Comment by mattiassvedhem** [comment]
Ok, just to clarify, if I'm using hash queries I need to use it for everything, right? There's no way to mix in a hash query in an existing DSL query?

**Comment by karmi** [comment]
Correct. Though you can build your query with DSL, convert it to Hash with `to_hash`, update it how you wish and then fire it against ES.

**Comment by karmi** [comment]
@yeggeps If you manage to solve the issue, please post solution here and close it, thanks.

**Comment by mattiassvedhem** [comment]
Yes, ofcourse.

Wouldn't it be sensible to have a method in the DSL for hash queries? So we could easily mix them with our existing queries?

**Comment by karmi** [comment]
Hi, `custom_score` was implemented in 2eee39d, more docs in a2c7406 and 1b9b157.

I think the `boosting` query is easily achieved by increasing boost factor for queries, so closing for now...

**Comment by kshnurov** [comment]
What if boosted field is not used in query? For example, I need to boost results with virtual = true, how can I do this?

```
query do
      boolean do
        must {text 'name', s, :analyzer => 'word_analyzer_search', :fuzziness => 0.9, :boost => 5}
        should {text '_all', s, :analyzer => 'word_analyzer_search', :fuzziness => 0.9}
      end
  end
```

**Comment by karmi** [comment]
@zx0 Sorry, don't understand.

**Comment by kshnurov** [comment]
Can you implement `boosting` query (http://www.elasticsearch.org/guide/reference/query-dsl/boosting-query.html)?
I can't use boost factor for some reasons.
