### ISSUE TITLE
Filtering Terms with NOT

### ISSUE THREAD

**Issue by matsko** [karmi/retire#250]
In the documentation provided I can't seem to find out how to create a filter that performs a not operation for a given term. I am aware that this can be included into the query block, but I would like to include it into the filter block for performance reasons.

On the ElasticSearch website there is a feature that does this, but I'm not sure if its in the Tire Gem code. Can you please explain how to do this:

filter_not :term, :id =>  some_id

**Comment by karmi** [comment]
@matsko Probably with a `must_not` boolean filter. Could you please try it out and reopen the issue if the problem still stands?

**Comment by caueguerra** [comment]
I got it working with

``` ruby
filter :not, { :term => { :index_name => 'value' } }
```

**Comment by rdetert** [comment]
Had a similar question and got it working by going:

`filter :not, { missing: { field: 'email' } }`

Just documenting for someone in case they find it useful.
