### ISSUE TITLE
Update index when association changes?

### ISSUE THREAD

**Issue by mhenrixon** [karmi/retire#263]
Is it possible to update indexes when an association changes? I mean a blog post has comments and when comments are added it still says comment count is zero. Is that what facets should be used for?

**Comment by karmi** [comment]
Hi, depends on how exactly you define how records are stored in the index -- could you post some snippet of mapping/to_indexed_json, etc? (Normally, it should happen behind the scenes. Facets are a way to compute some aggregated values.)

**Comment by mhenrixon** [comment]
Please don't laugh out loud at this code... :)

``` ruby
  mapping do
    indexes :id
    indexes :title, boost: 200
    indexes :description,  boost: 55
    indexes :privacy
    indexes :pr
    indexes :prescribed
    indexes :workout_at, type: 'date'
    indexes :box_wod_id
    indexes :bench_id
    indexes :user_id
    indexes :username
    indexes :group_names, boost: 150
    indexes :photo_file_name
    indexes :email_notification?
    indexes :public?
    indexes :box_only?
    indexes :private?
    indexes :pr?
    indexes :rx?
    indexes :video_link
    indexes :comments_count
    indexes :result_time
    indexes :result_weight
    indexes :result_rounds
    indexes :result_reps
    indexes :result do
      indexes :time
      indexes :weight
      indexes :rounds
      indexes :reps
      indexes :twitter
      indexes :facebook
    end
    indexes :user do
      indexes :id
      indexes :username,  :type => 'string', boost: 99
      indexes :email
      indexes :username_migrated
      indexes :profile_pic_filename
    end
  end

  def to_indexed_json
    to_json(methods:
    [
      :username,
      :group_names,
      :comments_count,
      :stars_count,
      :starred_user_ids,
      :result_time,
      :result_weight,
      :result_rounds,
      :result_reps
    ], include: { result: { except: [:comparable_id, :comparable_type, :created_at, :updated_at] }})
  end

  def comments_count
    comments.size
  end

```

I also want to add that I never got the nested indexing to work properly meaning the user don't seem to be working as nested that's why I added the username and comment_count methods.

**Comment by karmi** [comment]
Nothing wrong with your code :)

Hmm, you seem to be properly indexing the `comments_count` method in the `to_indexed_json` method... This is really weird -- as soon as you add a comment, and then save the model instance, it should be propagated to ES.

One idea: maybe you've changed the mapping along the way, and there's a mismatch between the mapping and the data. AFAIK _Tire_ does not handle this situation well, doesn't raise, etc. Could you try it with a fresh, testing index?

**Comment by mhenrixon** [comment]
If I refresh the index it get's indexed properly. I think the problem here is how I create the comments.

``` ruby
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(params[:comment])
    @comment.user = current_user
    @comment.save

    respond_with @comment, layout: !request.xhr?
  end
```

Maybe I should save the @commentable instead of the comment or just add it to the @commentable array of comments?

**Comment by karmi** [comment]
Yes, I'm afraid the `@comment.save` won't bubble up to the `@commentable` instance. Firing the `@commentable.tire.update_index` method should be enough, no need to saving the whole thing.

**Comment by mhenrixon** [comment]
Works like a charm!
