### ISSUE TITLE
You have tried to eager load the model instances, but Tire cannot find the model class

### ISSUE THREAD

**Issue by sarmiena** [karmi/retire#264]
Tire::Results::Collection tries to infer class name when using `load: true`, but cannot do so if it's for a namespaced class.

For instance OnlineStore::Product results in _type == online_store_product, of which we cannot convert back to the appropriate constant.

I would like to add the option for specifying the classname when doing a `load: true`

**Comment by karmi** [comment]
Yes, it's a known bug, see issues. There are some patches trying to solve it floating around, haven't had time to review the issue and solve it, yet... (The problem is due to incorrect class name serialization.)
