### ISSUE TITLE
kaminari pagination

### ISSUE THREAD

**Issue by kapkaev** [karmi/retire#266]
rails 3.2
tire 0.3.12
kaminari 0.13.0

``` ruby
def self.search(params)
  options = {:page => (params[:page]||1), :per_page=> (params[:per_page] || 3), load: params[:load]}
  tire.search(options) do
```

when i pagination execure i have error

``` ruby
ActiveRecord::RecordNotFound (Couldn't find all Items with IDs (17, 6, 13, false) (found 3 results, but was looking for 4)):
```

in console

``` ruby
Item.tire.search("item", :page => 1, :per_page => 3)
```

in response of Tire::Results::Collection

``` ruby
@options={:page=>1, :per_page=>3, :size=>3, :from=>0}
```

**Comment by aaronchi** [comment]
This probably just means you need to reindex?

**Comment by karmi** [comment]
Yes, the records don't exist in your database, either reindex or save them.

**Comment by joemsak** [comment]
Hi I'm having this same issue but when I run the rake task with FORCE=true it still doesn't go away

It's because I'm using :load => true and I need access to the instance methods...
