### ISSUE TITLE
MoreLikeThis API

### ISSUE THREAD

**Issue by mereghost** [karmi/retire#273]
Is there any plans to implement the  [mlt api](http://www.elasticsearch.org/guide/reference/api/more-like-this.html) in the near future?

I'm almost done with the more_like_this and  more_like_this_field queries, but implementing the API might lead to some duplication/refactor (it would be nice to have it integrated with the model).

Cheers!

**Comment by karmi** [comment]
Hi, no immediate plans -- I think it would be a great thing to have!

I think this would again make a great extension to `tire-contrib`. I a method, such as `MyModel#more_like_this`, would return similar documents. Not sure about proper semantics, though...

**Comment by mereghost** [comment]
Nice. I'll get to work and see what I can get working.

The main "problem" is that the endpoint is different (_mtl) so it might duplicate some of the Query inner workings.

Thanks again.

**Comment by aaronchi** [comment]
In case anyone is interested, there is an easy way to hack this into the search DSL

```
module Tire
  module Search
    class Query

      def more_like_this(like_text, options={})
        @value = { :more_like_this => {:like_text => like_text}.update(options)}
      end

    end
  end
end
```

**Comment by mereghost** [comment]
Yeah. That's the mlt query. The API compares the index against a document, which is too nifty for those of use using any kind of DB Mapper.

**Comment by karmi** [comment]
Implemented in https://github.com/karmi/tire-contrib/blob/master/lib/tire/queries/more_like_this/more_like_this.rb
