### ISSUE TITLE
eager load and mongoid

### ISSUE THREAD

**Issue by benjaminbarbe** [karmi/retire#282]
Hi,

I just want to use the [mongoid eager loading](http://mongoid.org/docs/querying/criteria.html#includes) (includes) with tire.
But It does not work (subjects is the name of my relation)

```
#query = Product.includes(:subjects).tire.search :load => true do |search|
query = Product.tire.search :load => {:includes => :subjects} do |search|
...
end
p query.results
```

```
def load(options=nil)
      options ? self.class.find(self.id, options) : self.class.find(self.id)
end
```

How can I do to use both earger loading (thin and mongoid) ?

Thanks

**Comment by karmi** [comment]
Hi, I don't know anything about eager loading in _Mongoid_.

Could you please post an example of what are you trying to do and what is the error/bug/issue? It's hard to tell from the description...

**Comment by benjaminbarbe** [comment]
https://gist.github.com/a23fe333f0115d13be1e

Thanks

**Comment by karmi** [comment]
I'm sorry butI don't know enough about Mongoid to be of much help... Could you post the question to StackOverflow? http://stackoverflow.com/tags/tire
