### ISSUE TITLE
Indexing models with default_scope

### ISSUE THREAD

**Issue by plentz** [karmi/retire#284]
I think it's a good idea to ignore scopes while indexing entities thought the rake task. In this (illustrative) scenario:

```
class Customer < ActiveRecord::Base
  include Tire::Model::Search, Tire::Model::Callbacks
  default_scope lambda { where("active = ?", "true") }
end
```

The "inactive" customers will not be indexed. To workaround it, we could use Customer.unscoped

**Comment by karmi** [comment]
Hmm, I understand, but I'm wondering how to support that on the library level?

_Tire_ provides convenience utilities to import the data (either with the Rake task or the `MyModel.import` method), but for anything specific, you need to write your own wrapper. It's [very easy](http://karmi.github.com/tire/#section-Bulk_Indexing) with _Tire_...

**Comment by plentz** [comment]
Hum, I've looked at the code, but it wasn't very clear to me. Looks like something around [here](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L108-115), but I didnt find the exact point to add the `unscoped` call.

**Comment by karmi** [comment]
I think the solution here is to just write your code for the indexing, and not use the bundled Rake task...

There's definitely _no_ place to add a call to the unscoped call :) The right approach is to write your code around `Index#bulk_store`, using `find_each` in ActiveRecord, etc., not trying to hack the support in the model import support...

**Comment by plentz** [comment]
Thanks for the tips @karmi
