### ISSUE TITLE
Calling boolean a second time with options doesn't set options

### ISSUE THREAD

**Issue by timting** [karmi/retire#286]
Was scratching my head on this for a while. I was doing multiple boolean calls on a query, and on the last one, I added some options, but they would never go through to elasticsearch. The reason is because boolean only calls BooleanQuery.new with the options the first time we call boolean (this is in tire/search/query.rb:39). I guess it works alright if you're aware of the issue, but it's not entirely expected behavior.

**Comment by karmi** [comment]
Hi, please post a failing code example or/and a link to a test case in _Tire_ `test` directory which demonstrates the issue, and I'll reopen! Thanks.

**Comment by timting** [comment]
So, this is the way I'm using Tire - there's a variations index that I'm querying, and I have methods which return the lambdas required by Tire. With the code as it is below, the option :minimum_number_should_match won't get encoded because by that time the BooleanQuery is already created. If that option is moved to the data_status query, everything works. Is this intended behavior? Let me know if you need more information or a more detailed example.

```
  def search(params = nil)
    s = Tire.search 'variations' do |search|
      search.query do |query|
        query.boolean &data_status_query #need options on the first boolean query otherwise it gets overwritten
        query.boolean :minimum_number_should_match => 1, &color_query(params[:color]) unless params[:color].blank?  
      end
    end

    s
  end

  def data_status_query
    lambda do |boolean|
      boolean.must { term "data_status", "available"}
    end
  end

  def color_query(color)
    lambda do |boolean|
      boolean.must { term "base_color", color}
    end
  end
```

An example test case is below, modified from search_query_test.rb, line 96

```
  should "encode options when doing boolean twice" do
    query = Query.new do
      boolean do 
        must { string 'bar' }
      end
      boolean(:minimum_number_should_match => 1) do 
        must { string 'foo' }
      end
    end

    assert_equal 1, query[:bool][:minimum_number_should_match]
  end
```

**Comment by karmi** [comment]
Hi, I see what you mean, definitely an interesting use case.

In ES, you just issue one boolean query, but _Tire_ exposes it in Ruby, where you can build the query iteratively.

I think the https://github.com/karmi/tire/blob/master/lib/tire/search/query.rb#L50 line is the culprit, we need to update the options here...

**Comment by timting** [comment]
Yes, once I had determined that my code wasn't the issue, I checked the code and noticed that line, which made everything clear. What's not clear is what the best solution would be - would we just merge the options from subsequent boolean calls into the options hash, potentially overwriting the previous settings?

What helps a lot with understanding this is that, as you said, on ES's side, there's just one boolean query - with an iterative approach it's easy to think there's multiple queries and settings for each are independent, which was my initial understanding.

**Comment by karmi** [comment]
Yeah, also not entirely sure how to approach it... One way to look at it is that the "first wins" is as potentially bad as the "last wins" scenario -- and the "last wins" is maybe less surprising...

However given multiple `boolean <this> unless <something>` and `boolean <that> if <something else>`, there's always potential for surprise... We do the same thing in our app as well, though.

So, all in all, I'd vote for `boolean.options.update`... but who knows :) The blockish boolean syntax is awesomely convenient, but gives lots of rope.

**Comment by timting** [comment]
Yeah, I'd vote for that too - I was kind of surprised that there was no way to change options except the first time you called boolean.
