### ISSUE TITLE
Authorization with nested models

### ISSUE THREAD

**Issue by alx1** [karmi/retire#287]
I've got a parent model (A) with 2 child models (B and C).

Each model has a status of public or private.

I can search the A's for the contents of the B's and C's, by having the A model's to_indexed_json method defined as including B and C. This works fine.

I can prevent users with only the "public" access level from seeing the A's with a status of "private" by using a query filter on the A's status.

BUT I want to be able to do the following:

As a public user, a search on A's with a keyword found in one or more B or C's should only return A as a match if at least one of those matching B or C records' status is "public"

It seems to me this possible but I really cannot figure out how, or find any examples in the documentation. Any suggestions greatly appreciated.

**Comment by karmi** [comment]
Hi, my mind normally does not work well with synthetic examples -- could you post some examples modeled after your real use case, with real model names, real entities, real relationships?

**Comment by alx1** [comment]
Sorry :-) . Here we go:

The app is an incident reporting system which allows public users to submit reports. Reports are then validated and analysed by admins and then grouped into Incidents. Admins can also write an Analysis of an incident and these are grouped with the Incident. At some point the Incident may be published along with some of its associated Reports and Analyses, but not necessarily all of them.

The Incident records don't hold much data - it's mostly in the Reports and Analyses.

Public users can search the list of Incidents and should find matches based on any public Reports or Analyses within the Incident.

If a public user tries to view a Report which is not yet "public" they get access denied (using cancan, incidentally).
Searching on the contents of a report which is not yet "public" should not trigger a hit.

``` ruby
# /app/models/incident.rb
class Incident < ActiveRecord::Base
  has_many :reports
  has_many :analyses

  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id, type: 'integer'
    indexes :summary, boost: 10
    indexes :date, type: 'date'
    indexes :status
    indexes :created_at, type: 'date'
  end

  def self.search(params)
    per_page = params[:per_page] || 10

    tire.search(page: params[:page], per_page: per_page) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?
      sort { by :date, "DESC" } if params[:query].blank?
    end
  end

  def to_indexed_json
    to_json( include: { analyses: { only: [:narrative, :comments] }, reports: { only: [:summary, :narrative] } } )
  end
end
```

``` ruby
# /app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :incident

  has_many :factors

  accepts_nested_attributes_for :factors, :allow_destroy => true
end
```

``` ruby
# /app/models/analysis.rb
class Analysis < ActiveRecord::Base
  belongs_to :user
  belongs_to :incident
end
```

``` ruby
# /app/views/incidents/index.html.haml
%h1 Incidents
%hr.soften
= form_tag incidents_path, method: :get, :class => 'form-search', :id => "search_field", :remote => true do
    %p
        = text_field_tag :query, params[:query], :class => 'input-xlarge search-query'
        = submit_tag "Search", name: nil, class: 'btn'

%table.tablesorter{:class => "table table-striped"}
    %thead
        %tr
            %th ID
            %th Date
            %th Summary
            -   if can?(:update, :incidents) || can?(:destroy, :incidents)
                %th Actions
    %tbody
        = render @incidents

        = paginate @incidents, theme: "bootstrap", remote: true

- if can? :create, :incidents
    = link_to "New", new_incident_path, :class => 'btn btn-primary'
```

``` ruby
# /app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  def index
    per_page = params[:per_page] || 10
    if params[:query].present?
      @incidents = Incident.accessible_by(current_ability).search(params)
    else
      @incidents = Incident.accessible_by(current_ability).order('date DESC').page(params[:page]).per(per_page)
    end
  end
end
```

I would like to search the report Factors too but I'm trying to keep it simple at the moment.

``` ruby
# rails console
r1 = Report.find(1)
  => ...
r1.incident_id
  => 1
r1.summary
  => "Joe Bloggs had a problem"
r1.incident.summary
  => "a problem occured"
r1.status
  => "private"

r2 = Report.find(1)
r2.incident_id
  => 1
r2.summary
  => "something happened to a person"
r2.status
  => "public"
```

I can search for "problem" or "reports.summary:problem" in the incidents view and I get Incident 1 as the result as expected.

Desired behavior:

Admin users searching get a list of all Incidents where the keyword matches the Incident or its associated children
Public users searching only see an Incident in the list if their search matches a Incident or associated child which has status = "public"

Examples:

as an admin user: searches for "problem" or "Joe Bloggs" return Incident 1
as a non-admin user: searches for "problem" return Incident 1 (because the keyword is in the incident summary)
as a non-admin user: searches for "Joe Bloggs" return no matches (because Report 1's status is "private")
as a non-admin user: searches for "something" return Incident 1 (because Report 2's status is "public")

**Comment by karmi** [comment]
Hi, I'm sorry I didn't get back to you sooner, but I still don't understand the issue enough.

I think you could use a `term` filter on the _public_ field in a `filtered` query for non-admins, and possibly also a `term` filter on the _user_id_ field to limit the results for each user. Index aliases with filters work very well here, have a look here: http://www.elasticsearch.org/videos/2012/06/05/big-data-search-and-analytics.html

Closing the issue for now, feel free to submit new one.
