### ISSUE TITLE
Tire requires old version of rake

### ISSUE THREAD

**Issue by sandrew** [karmi/retire#29]
when I'm trying to install tire, it gives following error message:

<pre><code>Bundler could not find compatible versions for gem "rake":
  In Gemfile:
    tire depends on
      rake (~> 0.8.0)

    rails (>= 3.0.7) depends on
      rake (0.9.1)</code></pre>

"bundle update" of course solves the problem and installs rake-0.8, but if I'm not wrong, Rails 3.1 will be dependent of rake-0.9.  May be changing dependency will be possible?

**Comment by crx** [comment]
The rake dependency in the Gemfile was updated @ cde9d514e825cb8e55e49ce687bad64b6b477dce. This hasn't yet made it to the Tire gem but should be there in the next release. For now, you can require edge-Tire in your Gemfile:

```
gem 'tire', :git => 'git://github.com/karmi/tire.git'
```

**Comment by karmi** [comment]
Yes, it should be fixed in tire@v0.1.6...
