### ISSUE TITLE
Tire doesn't check if creation of ElasticSearch mapping was successful

### ISSUE THREAD

**Issue by christianhellsten** [karmi/retire#293]
When creating the ElasticSearch mappings on line 32 in gems/tire-0.4.0/lib/tire/index.rb, no warning or exception is issued if the POST request fails.

This could be an issue, for example, when a user has invalid mappings as explained here:
https://github.com/karmi/tire/issues/67

In this case ElasticSearch returns this and no mapping is created:
```#<Tire::HTTP::Response:0x1283b3958 @headers={}, @code=400, 
@body="{\"error\":\"MapperParsingException[mapping [product]]; 
nested: MapperParsingException[Wrong value for index [standard] for field [description]];
 \",\"status\":400}">   

```

It would make sense to throw an exception to avoid having no mapping (i.e. dynamic mapping), which is not desired.
```

**Comment by karmi** [comment]
I'm not sure about exception, but maybe at least display a warning as stated in #161...
