### ISSUE TITLE
Rake task not working with Namespaced model

### ISSUE THREAD

**Issue by timuckun** [karmi/retire#294]
rake tire:import CLASS="Chrysler::CustomerData" --Trace
*\* Invoke tire:import (first_time)
*\* Execute tire:import
rake aborted!
(eval):1: uninitialized constant Chrysler::CustomerData
/Users/timuckun/.rvm/gems/ree-1.8.7-2011.12/gems/tire-0.4.0/lib/tire/tasks.rb:42

The model does exist.

**Comment by karmi** [comment]
You have to load your application environment (as statet in docs and task help):

```
$ rake environment tire:import CLASS="Chrysler::CustomerData"
```
