### ISSUE TITLE
Date_Histogram Facet

### ISSUE THREAD

**Issue by ctbarbour** [karmi/retire#295]
Date_Histogram is not yet implemented as a facet. Any word on when this is expected to be complete?

**Comment by karmi** [comment]
@barbct5 It is, https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L62-77 ...

**Comment by ctbarbour** [comment]
Thanks. I just don't know how to read.

**Comment by karmi** [comment]
No problem! :), the docs are extensive, take your time to read it thru... It will pay off.
