### ISSUE TITLE
test failure with ActiveModel not destroy documents

### ISSUE THREAD

**Issue by erickt** [karmi/retire#296]
Hi Karmi,

Here's the error I mentioned in irc. I tracked this down to an issue with redis-persistence 0.0.6. The tests pass fine with 0.0.5. It looks like your removal of ActiveSupport::Concern is causing the problem. My Active\* foo is too weak to know what's really going on though.

```
 FAIL test: ActiveModel integration should remove document from index on destroy.  (0:00:10.837)
      <0> expected but was
      <1>.
    @ test/integration/active_model_searchable_test.rb:73:in `block (2 levels) in <class:ActiveModelSearchableIntegrationTest>'
      vendor/bundle/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in `call'
      vendor/bundle/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in `block in create_test_from_should_hash'
      vendor/bundle/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_201_to_222.rb:27:in `run'
```

**Comment by karmi** [comment]
Thanks for the report, should be fixed in https://github.com/Ataxo/redis-persistence/commit/7fb1b973e2320127c6e123099084b8be4d8bc323.
