### ISSUE TITLE
JSON encoding broken when using MultiJSON without Yajl?

### ISSUE THREAD

**Issue by crx** [karmi/retire#30]
This is an example request from my app, as generated by Tire:

```
"{"query":{"match_all":{}},"sort":[{"last_name":"asc"}],"size":10}"
```

Since the switch to MultiJSON, I now get a rogue "value" key in my sort param, which makes the whole thing invalid:

```
"{"query":{"match_all":{}},"sort":{"value":[{"last_name":"asc"}]},"size":10}"
```

This is with `MultiJson.engine == :json_gem`, the default. If I set the engine to `:yajl` in the debugger, it works. If I set it back to `:json_gem`, it breaks again. Oddly, if I restore the `require 'yajl/json_gem'` in lib/tire.rb (alongside the MultiJSON require), it works with _either_ engine value, as if Yajl is really doing the work even when it's set to `:json_gem`.

I have no problem just forcing the use of Yajl, but when using Tire in a Rails apps, what's the proper way to do that? `gem 'yajl-ruby'` alone in the Gemfile doesn't cut it. Should I put `MultiJson.engine = :yajl` in an initializer? Or is this better fixed in Tire?

**Comment by karmi** [comment]
Thansk for the report! The place to fix this is definitely in Tire, and should be fixed now; tests pass and apps run even on the "OKJSON". All these different JSON serialization libs are a bit of a pain.

The best is to really declare `yajl-ruby` in your Gemfile:

```
gem 'yajl-ruby'
```

and to require the "json_gem" compatibility layer somewhere in your app (initializer, application.rb, etc):

```
require 'yajl/json_gem'
```

Let me know if it works for you!
