### ISSUE TITLE
highlight _all doesn't seem to do anything.

### ISSUE THREAD

**Issue by timuckun** [karmi/retire#301]
``` ruby
search = Tire.search Settings.tire.prefix do
      query do
        string search_terms
      end
      highlight '_all'
      sort { by options[:sort], 'asc' } if options[:sort]
      page = (options[:page] || 1).to_i
      search_size = options[:per] || DEFAULT_SIZE
      from (page -1) * search_size
      size search_size
    end
```

does not return any highlights.

**Comment by vhyza** [comment]
Hello, please can you gist some data set and query example?

**Comment by timuckun** [comment]
See this gist

https://gist.github.com/2306099

The code is from above.

**Comment by karmi** [comment]
See http://www.elasticsearch.org/guide/reference/mapping/all-field.html, it depends on the ES version you use and you must set the `_all` field to be stored. See elasticsearch/elasticsearch#861.
