### ISSUE TITLE
Asynchronous Indexing

### ISSUE THREAD

**Issue by nvijayap** [karmi/retire#302]
Hello,

Can I make the indexing asynchronous?  In other words, I want to do the INSERT/UPDATE and make the indexing operation asynchronous.  The motivation in trying to do this is - rapid INSERT/UPDATE operations.  Please let me know.

Thanks

**Comment by karmi** [comment]
Yes, just don't include the `Model::Callbacks` module and handle the indexing yourself, preferably by running the `update_index` method in the background.

**Comment by lgs** [comment]
... any example code for that  ( handle the indexing yourself )?

**Comment by karmi** [comment]
@lgs, basically, with eg. [Resque](https://github.com/resque/resque), you'd do something like:

``` ruby
class IndexUpdater
  @queue = :tire

  def self.perform(record_id)
    MyModel.find(record_id).tire.update_index
  end
end

class MyModel
  include Tire::Model::Search

  # ...

  after_save    :enqueue_index_update
  after_destroy :enqueue_index_update

  def enqueue_index_update
    Resque.enqueue(self.class, self.id)
  end
end
```

**Comment by lgs** [comment]
@karmi very enlightening, thanks for clarifying

**Comment by lgs** [comment]
@karmi 
hey, did you see this one https://github.com/EvilFaeton/tire_async_index ? What do you think about ?
