### ISSUE TITLE
Configuring the port for Tire

### ISSUE THREAD

**Issue by matsko** [karmi/retire#304]
Is there anyway to instruct Tire.configure to set the port of the client to a different port than its default 9200? I've configured my elasticsearch daemon to use a different port for every project that I have using it.

**Comment by karmi** [comment]
Yeah, just pass the port as the URL, https://github.com/karmi/tire/blob/master/test/unit/configuration_test.rb#L36-39

**Comment by matsko** [comment]
So if you were to replicate the default url, then syntax ends up being:

``` ruby
Tire.configure do
  url "http://0.0.0.0:9200"
end
```
