### ISSUE TITLE
way to search for a value in an association

### ISSUE THREAD

**Issue by vpereira** [karmi/retire#306]
is the solution from this ticket actual (I mean, not move to solr 8-)) https://github.com/karmi/tire/issues/10

I have a class like:

```
class Book < ActiveRecord::Base
  belongs_to :author
  include Tire::Model::Search
  include Tire::Model::Callbacks

  def self.search(params = {})
  end
end
```

And I would ilke to search for Author's Name. Is it possible today? Any gist?

**Comment by karmi** [comment]
Yes, it's been solved long time ago.

In your class, define the `to_indexed_json` to include the author:

``` ruby
def to_indexed_json
  to_json( include: { author: { only: [:name]} } )
end
```

I recommend watching the relevant [Railscasts](http://railscasts.com) episodes on Tire, with these updates: https://github.com/karmi/railscasts-episodes/commit/03c45c3, https://github.com/karmi/railscasts-episodes/commit/ee1f6f3 relevant to your use-case.

**Comment by vpereira** [comment]
Thanks for your answer. To be honest. I did something like

https://gist.github.com/2342609

and i'm still not able to search by author. I'm doing a OR between two fields and filtering (almost like a scope) using filter. Is that the best way to do it? I saw in your examples. And I think you would add this "scope" in a must block. Right? I don't know if I read right, but at elastic search website it says that filter is faster then query.. is that right?

**Comment by karmi** [comment]
Hi, yeah, your approach seems one. Couple of things:

* unless you want to use _Lucene_ query syntax (boosting, ranges, etc), it's maybe best to use the `text` query,
- yes, filters are more performant then queries, an the `active=true` in your example is a good fit for filters. Beware of the interplay between queries, filters and facets, though.

Your definition of the term query is incorrect, though -- it should be:

``` ruby
 term :author, params[:author]
```

See https://github.com/karmi/tire/blob/master/test/integration/boolean_queries_test.rb.

**Comment by vpereira** [comment]
thank you for your help and the amazing gem. I owe you a beer :-)

**Comment by karmi** [comment]
Glad it's working. Maybe post the solution at the [Stackoverflow](http://stackoverflow.com/questions/10071634/tire-elasticsearch-search-for-association) as well?

**Comment by vpereira** [comment]
done!

**Comment by Rio517** [comment]
I'm having a similar issue.  After reviewing stackoverflow, tire source, etc.  I haven't been able to spot my issue.  

https://gist.github.com/2493477

Is there anything obvious that I'm doing wrong?

Thanks!
