### ISSUE TITLE
New to Tire

### ISSUE THREAD

**Issue by yousraHazem** [karmi/retire#311]
Hello,
I'm absolutely new to Tire and Ruby on Rails, so I don't know exactly where to start. 
I tried following this link: https://github.com/karmi/tire   but I don't seem to understand where I should be writing the code, for example for indexing a Model or mapping.  
Thanks,
Yousra Hazem

**Comment by karmi** [comment]
The best start is to generate and play with the example application bundled with Tire (see README):

```
$ rails new searchapp -m https://raw.github.com/karmi/tire/master/examples/rails-application-template.rb
```

The relevant Railscasts episodes should set you on a right track:

http://railscasts.com/episodes/306-elasticsearch-part-1
http://railscasts.com/episodes/307-elasticsearch-part-2
