### ISSUE TITLE
Integrate w/ Amazon cloudsearch

### ISSUE THREAD

**Issue by jhl-zest** [karmi/retire#312]
Any plans to integrate w/ amazon cloudsearch?  it seems like they have a json format (search data format), which looks a lot like the elasticsearch json format (or is it identical?).  Given this, what would it take to integrate tire with amazon cloudsearch?
http://aws.amazon.com/cloudsearch/

**Comment by karmi** [comment]
Hey,

interesting idea :)

Both take JSON as input and give it as output, but the _ElasticSearch_ and _CloudSearch_ search APIs seem to be very different to me.

Karel
