### ISSUE TITLE
Custom URL for Tire model

### ISSUE THREAD

**Issue by kennym** [karmi/retire#313]
Currently there is no API and documentation on how to set a custom URL for Tire::Persistence object.

Suppose, I create the class

``` ruby
class Post
  include Tire::Persistence
end
```

and I would retrieve all object for the Post model, Tire would query `http://localhost:9200/posts`, but instead I would like to use a URL such as `http://localhost:9200/owner/1/posts` instead.

Anyone smarter than me? Else I may provide a patch for this.

**Comment by karmi** [comment]
Why would you use a URL like `http://localhost:9200/owner/1/posts`, ie. index `owner`, type `1` and ID `posts` in _ElasticSearch's_ terms?

**Comment by karmi** [comment]
Any news?

**Comment by kennym** [comment]
Thanks for pointing that out, and sorry for the late response.

 I would like an index of `owner`, type `article` and id `1`. Is that possible?

**Comment by karmi** [comment]
``` ruby
class Post
  include Tire::Persistence
  index_name    "owner"
  document_type "article"
end
```

**Comment by kennym** [comment]
Thanks, this works!
