### ISSUE TITLE
Import rake task doesn't work in production enviroment 

### ISSUE THREAD

**Issue by palodelincak** [karmi/retire#315]
Hello,

When I run import task:
`rake environment tire:import CLASS='Product' FORCE=true RAILS_ENV=development`

I'll get:
[IMPORT] Deleting index 'products'
[IMPORT] Creating index 'products' with mapping:
{"product":{"properties":{}}}
[IMPORT] Starting import for the Product class

**4000/295512 | 1%**

So, it works very well - on development.

---

but when I run it on production server:
`bundle exec rake environment tire:import CLASS='Product' FORCE=true`
or (on my localhost) in production enviroment
`rake environment tire:import CLASS='Product' FORCE=true RAILS_ENV=production`

I'll get:
IMPORT] Deleting index 'products'
[IMPORT] Creating index 'products' with mapping:
{"product":{"properties":{}}}
[IMPORT] Starting import for the 'Product' class

**Import finished in 0.00169 seconds**

And the same task doesn't work (in production enviroment). Import finished in 0.00169 seconds and no indexes are created.

---

I'm using MongoDB and this is my mapping of Product class:

```
def to_indexed_json
    {
        :name => name,
        :codes => codes
    }.to_json
end
```

**Comment by karmi** [comment]
Hi, weird, does your production contain any data, ie. what does:

```
$ rails runner -e production 'puts Product.count'
```

return?

**Comment by karmi** [comment]
Any luck?

**Comment by palodelincak** [comment]
Hi, I'm sorry - problem was on my side. I tried to reinstall Mongo (my system/installation was probably broken) and everything is working now.

**Comment by palodelincak** [comment]
And yes, my production database contained same data as development database, but I could not make any query through application in production environment.

Thanks for your help!

**Comment by karmi** [comment]
Glad it's sorted out.
