### ISSUE TITLE
How to work with more than one cluster?

### ISSUE THREAD

**Issue by piavlo** [karmi/retire#318]
Hi,

I'm trying to copy index from one cluster to another using Tire, but can't figure out how to tell tire use more than one cluster
I've tried the following

<pre>
require 'rubygems'
require 'tire'

Tire::Configuration.url('http://source:9200')
source_search = Tire::Search::Scan.new('products')

Tire::Configuration.url('http://destination:9200')
destination_index = Tire::Index.new('xxxx')
destination_index.delete
.destination_index.create

search.each_document do |document|
  destination_index.store document
end
</pre>

but second configuration of url changes the connection url of previously defined object source_search.

Is there any trick to make this work?

Thanks
Alex

**Comment by karmi** [comment]
There's no easy way to work with multiple clusters, right now. Yes, it's bad.

For now, the only solution would be to laboriously inject URLs before different calls, etc. Doable, but ugly. The `Tire::Configuration.url` is a class method, and unfortunate design choice. I plan to have a look into that.

Nevertheless, it seems like what you're after is reindexing? In that case, does https://github.com/karmi/tire/blob/master/test/integration/reindex_test.rb help?
