### ISSUE TITLE
Please provide a CHANGELOG

### ISSUE THREAD

**Issue by rubiii** [karmi/retire#320]
Would be pretty handy to know what changed and how difficult it is to update.

**Comment by karmi** [comment]
First, I think the Github history makes for a better "changelog" then static files?

Second, every new version prints out important information in your terminal, when installed. See: https://github.com/karmi/tire/blob/master/lib/tire/version.rb and https://github.com/karmi/tire/commits/master/lib/tire/version.rb

**Comment by rubiii** [comment]
the changelog in the version file is great. maybe a link to the latest blob of that file in the readme would help others to find it.

**Comment by reiz** [comment]
A link in the README would be awesome :+1:
