### ISSUE TITLE
Problem with regexp in query_string

### ISSUE THREAD

**Issue by niuage** [karmi/retire#326]
I'm searching with this simple query (autocompletion feature)

```
{ query { string "title:#{keywords}*" } }
```

Let's say I have a document with the title: `Eliminate texting while driving`.
- If `keywords` is `elimin` then the document is returned.
- If `keywords` is `elimina` then it's not!

What am I missing?

Thanks!

**Comment by niuage** [comment]
I updated my question and made it simpler.

edit: if you want, you can answer on stackoverflow as well (http://stackoverflow.com/questions/10354002/elasticsearch-tire-regexp-in-query-string-not-returning-a-matching-document)

**Comment by niuage** [comment]
It was because of the snowball analyzer, when I use the standart one, it works fine.

**Comment by karmi** [comment]
@niuage For proper "autocomplete", best is to use ngram based analyzers, I think _StackOverflow_ has some nice resources on that from Clinton.

**Comment by niuage** [comment]
I actually tried to use a custom ngram analyzer based on one of your gist, but I had trouble adapting it to rails. But I realized there's an example in the readme ^^, so I'll definitely try that.

**Comment by niuage** [comment]
I followed the readme example and it works great :)
