### ISSUE TITLE
Conflict with ActiveAdmin?

### ISSUE THREAD

**Issue by niuage** [karmi/retire#330]
I have a strange conflict with Tire and ActiveAdmin...
- I have a Task model in my app
- I register this Task model with ActiveAdmin: `ActiveAdmin.register Task do [...] end`

I works fine: I get a Task entry in the top bar of the admin and I can access "admin/tasks".

When I include Tire though, the "Task" entry changes into "Rake Task" (in the top bar) and I don't have access to "/admin/tasks" anymore.

---

edit: I have a warning (rails 3.2), and I think it's coming from Tire:

```
WARNING: Deprecated reference to top-level constant 'Task' found at: 
Use --classic-namespace on rake command
or 'require "rake/classic_namespace"' in Rakefile
```

---

Do you have ANY idea of what Tire does that could cause that? It's basically like if when I try to register the Task model, it thinks it's inside the Rake namespace... But I have no idea why.

Thanks!

**Comment by niuage** [comment]
Turns out it's my fault, Task is actually a reserved keyword in Ruby on Rails...

http://oldwiki.rubyonrails.org/rails/pages/ReservedWords

**Comment by karmi** [comment]
Hi @niuage, sorry for the delay, yeah, `Task` clashes with _Rake_. _Tire_ does include _Rake_, I have been worried about that, but nobody reported any error.
