### ISSUE TITLE
specify columns to return

### ISSUE THREAD

**Issue by jhl-zest** [karmi/retire#331]
is there a way to specify which columns to return in the search results?   for example, i have a list of attributes i want to search _on_, but in the results i want only the id to be returned (and then use the load => true) property to load the active records associated with the search results.

**Comment by karmi** [comment]
If you want to return only specific document fields, use the `fields` method: https://github.com/karmi/tire/blob/master/test/integration/results_test.rb#L28

**Comment by karmi** [comment]
Please make sure you close the issue when the problem is solved :)
