### ISSUE TITLE
How not to exclude stop words?

### ISSUE THREAD

**Issue by niuage** [karmi/retire#335]
I defined my mapping like that:

```
settings :analysis => {
  :filter => {
    :title_ngram  => {
      "type"     => "edgeNGram",
      "side"     => "front",
      "max_gram" => 15,
      "min_gram" => 1
    }
  },
  tokenizer: {
    title_tokenizer: {
      "pattern" => "[^\\p{L}\\d]+",
      "type"    => "pattern"
    }
  },
  :analyzer => {
    :ngram_analyzer => {
      "tokenizer"    => "title_tokenizer",
      "filter"       => ["lowercase", "title_ngram"],
      "type"         => "custom"
    }
  }
} do
  mapping do
    indexes :id, type: 'integer'
    indexes :title, type: 'string', analyzer: 'snowball'
    indexes :description, type: 'string', analyzer: 'snowball'
    indexes :small_photo, index: :not_analyzed
    indexes :ngram_title, :type => 'string', :index_analyzer => "ngram_analyzer", search_analyzer: "standard"
  end
end
```

Let's say I have 2 documents with a title of "The tree" and "Isnogood".

When I search for `th`, then `The tree` is found. But not when I search for `the`.
When I search for `i`, then `Isnogood` is found. But not when I search for `is`.

So I'm pretty sure it's because stop words are not indexed.

What I don't understand is that I specifically set the index analyzer of the ngram_title to my custom `ngram_analyzer` whose filters are `lowercase` and `title_ngram`. Why are the stop words removed then?

Thanks!

**Comment by lumpidu** [comment]
If you say Title, which one do you mean: :title or :ngram_title ?

Your :title is set to the snowball analyzer which removes stopwords per default, whereas your :ngram_title uses your own defined analyzer.

**Comment by niuage** [comment]
I'm searching on ngram_title, and I'm 100% sure because otherwise, the autocompletion wouldn't work at all.

edit: ngram_title is actually just a method returning the document title.

**Comment by niuage** [comment]
It was actually my search analyzer... The "standard" analyzer removes stop words.
