### ISSUE TITLE
Use of blocks inside Mapping

### ISSUE THREAD

**Issue by hm-zestcash** [karmi/retire#336]
When integrating Tire with ActiveRecord, I would like to define a mapping such as

class Record < ActiveRecord::Base
    belongs_to :parent_record

```
include Tire::Model::Search
include Tire::Model::Callbacks

mapping do
    indexes :id, :index => :not_analyzed
    . . .
    indexes :parent_record do
        indexes :parent_id, :index => :not_analyzed
        . . .
    end
end
```

end

Do indexes support receiving do blocks like this?
I suppose I have to pass an :as => Proc.new option to the :parent_id index. In what context would this be evaluated?
Would I need to pass it :as => Proc.new( self.parent_record.id ) or will self.id work because it changes context to the association?

**Comment by karmi** [comment]
That should indeed be supported, is https://github.com/karmi/tire/blob/master/test/unit/model_search_test.rb#L382-392 what you're after?

**Comment by karmi** [comment]
@hm-zestcash Hello, I hope your problem was solved and you only forgot to close the issue.
