### ISSUE TITLE
Add count API to Tire

### ISSUE THREAD

**Issue by lumpidu** [karmi/retire#338]
At the moment the count API of ES is not exposed. It would come handy if Tire could catch up with this.

**Comment by karmi** [comment]
In fact, the `search_type=count` is supported: https://github.com/karmi/tire/blob/master/test/integration/count_test.rb

**Comment by lumpidu** [comment]
Ah,

came across this post here http://stackoverflow.com/questions/7969739/is-there-a-way-to-count-all-elements-of-an-index-in-elasticsearch-or-tire and could not find anything elsewhere.

Seems, you can earn yourself another bonus credit on SO in completing the answer ... ;)

Am 08.05.2012 um 15:36 schrieb Karel Minarik:
