### ISSUE TITLE
how to do unsupported queries

### ISSUE THREAD

**Issue by digitalplaywright** [karmi/retire#34]
I'd like to use the elastic search geo distance facet, but this search feature is not yet part of the Tire DSL. Is there a recommended way of doing an arbitrary elastic search query? Or to be more specific, to use the elastic search geo distance facet? Ideally I'd like a solution that can be combined in a single query with the elastic search features that are supported by Tire. 

Best,
Andy

**Comment by karmi** [comment]
Hi, you can just pass a Hash (or JSON) to the `Tire.search` DSL method, there's an example in the Readme. This is, however, kinda crude at the moment (for instance, no logging). You cannot easily -- without resorting to constructing your query from low level classes such as `Search::Query` mix & match it with the DSL methods, it's an either/or thing.

I intend to make this types of searches more convenient, once I get the Tire plate cleaner (percolator, proper ActiveRecord handling, etc).

Adding geo distance facet is easy, though, just a matter of another method in `Search::Facet` and couple of unit & integration tests.

**Comment by digitalplaywright** [comment]
Thanks! That gets me partially there. I stillneed to define a mapping definition within the index directory, so that the location field becomes a geo_point. 

I tried:
  mapping do
    indexes :title
    indexes :location, :type => "geo_point"
  end

but that doesn't seem to work. Any recommendation to how this should be done in tire?

This is a more lengthy description of my problem:

https://gist.github.com/ec4b27109e0e17e443fd

**Comment by digitalplaywright** [comment]
This was an interesting problem since I am generating the json using to_indexed_json, but still need to explicitly specify static types for the index in the mapping (like e.g geo_point).

The error described above happened because a type was omitted in the mapping for the title index. All fields mentioned in the mapping needed explicit typing. Adding the type fixes the problem.

**Comment by karmi** [comment]
Yes. Sorry for late reply.

I am still undecided if falling back to `string` as default is a good idea or not. Too much magic really can quickly hurt with ES, because you really need to understand what's going on.

In cases like this, always double-check the mapping, either with `Tire.index('events').mapping` or http://localhost:9200/events/_mapping.
