### ISSUE TITLE
Filter with :or

### ISSUE THREAD

**Issue by ghost** [karmi/retire#345]
Is there a way to do a filter search within a "filteredQuery" with :or instead of and? I see this, which seems like it's hardcoded to be or...

``` Ruby
      def filter(type, *options)
        @value[:filter] ||= {}
        @value[:filter][:and] ||= []
        @value[:filter][:and] << Filter.new(type, *options).to_hash
        @value
      end
```

I have something like:

``` Ruby
            if user.connected_to_fb?
              filter :terms, fb_user_id: user.fb_connections
            end

            if user.connected_to_linkedin?
              filter :terms, linkedin_id: user.linkedin_connections
            end
```

**Comment by karmi** [comment]
that is just a default, maybe this: https://github.com/karmi/tire/blob/master/test/integration/filtered_queries_test.rb#L43-60 is what you're looking for?

**Comment by ghost** [comment]
Ahh...I see what's going on here. Type is the actual :or setting. I thought :type would be the type of search like "string", "terms", ....

Worked great. Thanks!

**Comment by karmi** [comment]
Glad it's working :)
