### ISSUE TITLE
Errno::ECONNREFUSED - tire tries to update-index when ES down

### ISSUE THREAD

**Issue by chanil1218** [karmi/retire#346]
``` ruby
class Article
  include Tire::Model::Search
  include Tire::Model::Callbacks
  mapping do
    indexes :id, :type => "string", :index => "not_analyzed"
  end
end
```

Due to including Tire::Model::Callbacks, I understand, It will automatically update-index my Article class when I create Article.
but isn't there checking code that ES server is alive or am I cannot find yet?

What I want to do when ES is down is rescue Errno::ECONNREFUSED, and pass indexing process, creating article, and logging what article is failed to update-index. 

at this time, when Errno::ECONNREFUSED occurs then rails stop making article of cource updating index.

please give me an answer. unless i will disable callbacks feature and check ES state with api call...

**Comment by karmi** [comment]
Sorry, I probably don't understand the issue.
- Tire checks if the index exists in the `create_elasticsearch_index` method, but rescues errors and prints to STDERR.
- Tire saves documents in ES via callbacks on updates. You can choose to not `include Tire::Model::Callbacks` and index your data manually.

**Comment by chanil1218** [comment]
Rails server start is not a problem, because it rescues ES server status.
But Tire save phase via callback, I think it passes checking ES server status.
and thus, whenever I create article, it returns error above and creation fails.
I think when ES sever down, It should skip indexing and logging failed article.

Is Tire callback only do update-index when Article creation or Article modification?
That is, include Tire callback equivalent to 

``` ruby
after_save do
  self.update_index
end
```

**Comment by karmi** [comment]
> I think when ES sever down, It should skip indexing and logging failed article.

The included callbacks are for convenience, and 80% of use-cases. When other behaviour is desired, the solution is to handle indexing in your own code, possibly based on the [`update_index`](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L129-143) method.

**Comment by chanil1218** [comment]
Thanks, I will
