### ISSUE TITLE
Not updating index with Mongoid

### ISSUE THREAD

**Issue by jkdeveyra** [karmi/retire#347]
I was trying to use Tire with Mongoid but ElasticSearch keeps on throwing 
"ElasticSearchParseException: Failed to derive xcontent from..."

I had similar problem with this http://stackoverflow.com/questions/10592678/why-is-the-elasticsearch-index-not-updating-in-my-mongo-rails-app

**Comment by karmi** [comment]
Make sure your model is correctly setup. Hard to say without any code.

**Comment by jkdeveyra** [comment]
Here's my code: https://gist.github.com/2766825

**Comment by karmi** [comment]
Sorry -- you should use `to_json`, not `as_json`.
