### ISSUE TITLE
Undefined method facets

### ISSUE THREAD

**Issue by kbaum** [karmi/retire#35]
I have a feeling i am doing something wrong :-).  Trying to follow the faceted search example here:

http://karmi.github.com/tire/

My code looks like:

https://gist.github.com/33754cdc422b9dfb70eb

And from irb, i get:

```
irb(main):014:0* s.results.facets['tags']['terms'].each do |f|
irb(main):015:1*   puts "#{f['term'].ljust(10)} #{f['count']}"
irb(main):016:1> end
NoMethodError: undefined method `facets' for #<Array:0x00000003adc070>
from (irb):14
from /usr/bin/irb:12:in `<main>'
irb(main):017:0> 
```

Thanks!

**Comment by karmi** [comment]
Hi, you named your facet `commercial_type`, not `tags`, see https://gist.github.com/e2811c9f99b9be2b4f67

See also the docs on ES facets, http://www.elasticsearch.org/guide/reference/api/search/facets/index.html!

**Comment by kbaum** [comment]
Hi.  I fixed that... but i noticed that you don't need results anymore.  So the example should be:

```
s.facets['commercial_type']['terms'].each do |f|
   puts "#{f['term'].ljust(10)} #{f['count']}"
end
```

The above works.  I think the documentation needs some updating?

Thanks for your help!

**Comment by karmi** [comment]
Well, it's probably just some side effect, it should be accessed via `results`, see the integration tests...

**Comment by kbaum** [comment]
Strange though.. when i looked at the code, it makes sense that you would not need results.  The search method returns Results::Collection.

```
def search(indices, options={}, &block)
  if block_given?
    Search::Search.new(indices, options, &block).perform
  else
    payload = case options
      when Hash    then options.to_json
      when String  then options
      else raise ArgumentError, "Please pass a Ruby Hash or String with JSON"
    end

    response = Configuration.client.post( "#{Configuration.url}/#{indices}/_search", payload)
    json     = MultiJson.decode(response.body)
    results  = Results::Collection.new(json, options)
  end
```

Results::Collection has a facets attr_reader

```
module Tire
  module Results

  class Collection
    include Enumerable
    include Pagination

    attr_reader :time, :total, :options, :results, :facets
```

**Comment by karmi** [comment]
Yeah, but that's precisely why I wonder that you'd _not_ need accessing it via the `results` method :)

**Comment by kbaum** [comment]
Not sure what you mean... the search method returns Results::Collection and there is a method on their facets. 

Results::Collection#facets

Why would we need to call Results::Collection#results#facets?

thx

**Comment by karmi** [comment]
Sorry, not enough time right now, you're right.

**Comment by kbaum** [comment]
Cool.. just as long as i am not going crazy.  Thanks!
