### ISSUE TITLE
In ActiveModel integration, how do we create multiple types?

### ISSUE THREAD

**Issue by Silex** [karmi/retire#350]
The real problem behind this ticket I'm trying to solve is what http://www.elasticsearch.org/guide/reference/mapping/nested-type.html attempts to solve. See https://groups.google.com/forum/?fromgroups#!topic/elasticsearch/IaJpB1Ae-V4 for an explanation of what brought me to this.

Basically currently I have:

```
class User < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id,                 :type => :integer,       :index => :not_analyzed
    indexes :first_name,         :type => :string,        :analyzer => :snowball
    indexes :last_name,          :type => :string,        :analyzer => :snowball
    indexes :invoices, :type => object, :properties => 
    {
       :id => { :type => :integer },
       :value => { :type => :float }
    }
  end
end
```

Everything here belongs to the `users` type, including the `invoices`.

If I search all users named frank which have an invoice with value over 30, then I get that except I get the list of _all_ invoices those users have, and not only the ones which have value over 30.

If I move the mapping of invoices into the `Invoice` class, then it creates another index invoices with only one type, invoices.

It sounds a bit silly to create two indexes when you could store both in the same index no? Or I realise that maybe not, because either I want to search users or I want to search invoices.

Anyway, I can probably find a case where you'd want to search several different top-level types and display one result with a "type" column... so I think answering this ticket would probably help others anyway :)

**Comment by karmi** [comment]
Sorry, really don't understand the issue -- do you want to use `nested` type, or _parent/child_ feature, or what is the problem? Closing for now.
