### ISSUE TITLE
Tire creates shards that are unassigned

### ISSUE THREAD

**Issue by skogsmaskin** [karmi/retire#357]
Making Elastic server status yellow.

The shards are automatically created when loading the Rails environment with indexed models.

Any ideas?

**Comment by karmi** [comment]
That's the default setting of shards:5, replicas:1 in ElasticSearch. Just create your index with different settings,

``` ruby
Tire.index("myindex").create settings: { number_of_replicas: 0 }
```

**Comment by skogsmaskin** [comment]
I see, it respects the ElasticSearch settings if not defined. Goodie.
