### ISSUE TITLE
Is there a way to fetch a list of indexes from ES using Tire?

### ISSUE THREAD

**Issue by timuckun** [karmi/retire#359]
Each model creates it's own index so I would like to fetch a list and use that list to search all models.

Thanks.

**Comment by vhyza** [comment]
Hello,

I don't think there is some way to get a list of indexes by Tire. You can use `http://localhost:9200/_aliases` endpoint. For example:

``` ruby
require 'tire'
require 'yajl'

p Yajl::Parser.parse(Tire::Configuration.client.get("#{Tire::Configuration.url}/_aliases").body).keys
```

**Comment by karmi** [comment]
@timuckun Was the advice helpful?
