### ISSUE TITLE
facet counts of entire index

### ISSUE THREAD

**Issue by kbaum** [karmi/retire#36]
Not sure if this one is an issue, but i wanted to do a facet of commercial_type with no query.

```
s = EmailMessage.search do


    facet 'commercial_type' do
      terms :commercial_type
    end

end
```

The above results in this request failure:

```
[REQUEST FAILED] curl -X POST "http://localhost:9200/email_messages/_search?pretty=true" -d '{"query":null,"facets":{"commercial_type":{"terms":{"field":"commercial_type","size":10,"all_terms":false}}}}'
```

I am able to get it working by using a wildcard string search:

```
s = EmailMessage.search do
    query{ string '*'}

    facet 'commercial_type' do
      terms :commercial_type
    end

end
```

Thanks!

**Comment by karmi** [comment]
Yeah, in ES > 16.2 you don't need a query, this was fixed in karmi/tire@94da719.

**Comment by kimchy** [comment]
Btw, if you just want facet counts, without getting hits back, make sure to use search_type set to count.

**Comment by karmi** [comment]
Yeah, this is a huge performance debt in Tire, currently. I'd like to add `count` and `scan` soon, the ES API makes it very convenient to support.
