### ISSUE TITLE
Documentation for mapping ES DSL to tire? Configurations, analyzers, etc.

### ISSUE THREAD

**Issue by tim-vfiles** [karmi/retire#360]
I'm having trouble mapping the elastic search things I find online (configurations in JSON and such) to tire. Is there a listing?

For instance, following the example at http://karmi.github.com/tire/, I've edited a bit to play with options. Specifically, I'm trying to use the asciifolding filter to be able to search in an accent-insenstive way (ex. a search for "one" will match "Oné"

```
Tire.index 'articles' do
  # To make sure it's fresh, let's delete any existing index with the same name.
  #
  delete
  # And then, let's create it.
  #
  create

  # We want to store and index some articles with `title`, `tags` and `published_on` properties.
  # Simple Hashes are OK. The default type is „document”.
  #
  store :type => 'article', :title => 'Oné',   :tags => ['ruby'],           :published_on => '2011-01-01'
  # etc., truncated
  refresh
end

Tire.index 'articles' do
  create :mappings => {
    :article => {
      :properties => {
        :title    => { :type => 'string', :analyzer => { :type => "standard", :filter => "asciifolding" }, :boost => 2.0,       },
        #etc, truncated
      }
    }
  }
end

# Should find and display "Oné" because of asciifolding filter, no luck
s = Tire.search('articles') do
  query do
    string "title:One"
  end
end

s.results.each do |document|
  puts "* #{ document.title } [tags: #{document.tags.join(', ')}]"
end
```

This doesn't seem to work, indicating to me the filter is not getting set, although setting up ES configuration, you would do the JSON equivalent of that.

**Comment by karmi** [comment]
Hi, in a case like this (index settings), just send an exactly the same structure you would send as JSON string as a Ruby Hash.

Check the index settings: `curl localhost:9200/articles/_settings` and mapping: `curl localhost:9200/articles/_mapping` to see if your configuration has been correctly stored in ES.

Notice that you are creating a document without specifying type, thus it ends up being a `document`, but your mapping is set to a `article` type. Notice that the documentation is very clear on this, even _within the snippet you have pasted_.

**Comment by tim-vfiles** [comment]
Sorry, I copy and pasted from the initial example, not my modified code. So, I do have :type=>'article" specified in the store statements (original post edited).

Am I not sending the same structure? That is, analyzer with sub elements type and filter?

```
% curl localhost:9200/articles/_settings

{"articles":{"settings":{"index.number_of_shards":"5","index.number_of_replicas":"1"}}}

% curl localhost:9200/articles/_mapping

{"articles":
  {"article":
    {"properties":
      {"tags":{"type":"string"},
       "title":{"type":"string"},
       "published_on":{"format":"dateOptionalTime","type":"date"},
       "type":{"type":"string"}
}}}}
```

**Comment by karmi** [comment]
You're trying to  create the index after it has been already created. Turn on logging with `Tire.configure { logger STDOUT, level: "debug" }` to see what's going on.
