### ISSUE TITLE
Settings take locally, but not on Heroku with Bonsai

### ISSUE THREAD

**Issue by benevolentmadman** [karmi/retire#369]
I have code that works locally, but not on Heroku using bonsai as my ElasticSearch provider

I've been testing in Rails console and Heroku console.

``` ruby
UserProfile.search('steve') 
```

This works fine locally and on Heroku, providing the expected results

``` ruby
UserProfile.search('steve', :sort => 'first_name') 
```

This also works fine locally, and returns the expected results, however on heroku console it returns the following error:

``` ruby
Tire::Search::SearchRequestFailed: 500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], total failure; shardFailures {[REDACTED][REDACTED-1338992856][0]: RemoteTransportException[[Agent][inet[/10.76.250.31:9300]][search/phase/query+fetch]]; nested: QueryPhaseExecutionException[[REDACTED-1338992856][0]: query[_all:steve],from[0],size[10],sort[<custom:\"first_name\": org.elasticsearch.index.field.data.strings.StringFieldDataType$1@3ee5d230>]: Query Failed [Failed to execute main query]]; nested: IOException[Can't sort on string types with more than one value per doc, or more than one token per field]; }]","status":500}
```

One thing I've noticed is that if I run UserProfile.index.settings locally it returns the settings I've made, but if I do it on heroku, it errors out as follows:

``` ruby
NoMethodError: undefined method `[]' for nil:NilClass
from /app/vendor/bundle/ruby/1.9.1/gems/tire-0.4.2/lib/tire/index.rb:62:in `settings'
```

It seems that the way I'm making the settings for analysis aren't taking on heroku, and it's indexing with default settings.

I'm doing the settings directly in the model, as recommended in the README at https://github.com/karmi/tire. Is there an alternate way of doing this, perhaps in an initializer?

Here's the relevant bits of my UserProfile Model:

``` ruby
 class UserProfile < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks

  index_name BONSAI_INDEX_NAME if BONSAI_INDEX_NAME

  settings analysis: {
    analyzer: {
      my_start: {
        tokenizer: 'whitespace',
        filter: %w{asciifolding lowercase my_edge}, #no accent, downcase
        type: 'string'
      },
      my_sort: {
        tokenizer: 'keyword', #cut nothing, it's just for sorting
        filter: %w{asciifolding lowercase},
        type: 'string'
      }
    },
    filter: {
      my_edge: {
        type: 'edgeNGram', #1 to 10 letters, from the start
        min_gram: 1,
        max_gram: 10,
        side: 'front'
      }
    }
  } do 
    mapping do
      indexes :name
      indexes :first_name, :type => 'string', :analyzer => 'my_sort'
      indexes :first_name_start, :type => 'string', :analyzer => 'my_start'
      indexes :last_name, :type => 'string', :analyzer => 'my_sort'
      indexes :last_name_start, :type => 'string', :analyzer => 'my_start'
      indexes :completeness
      indexes :active
      indexes :skills do
        indexes :name
        indexes :rating
      end
      indexes :tools do
        indexes :name
        indexes :rating
      end
    end
  end

  def to_indexed_json
    {
      :name             => "#{first_name} #{last_name}",
      :first_name       => first_name,
      :first_name_start => first_name,
      :last_name        => last_name,
      :last_name_start  => last_name,
      :completeness     => aasm_state,
      :active           => account.blank? ? 'inactive' : account.aasm_state,
      :skills           => skills.map { |s| {:name => s.name, :rating => rating_for_subject(s) } },
      :tools            => tools.map { |t| {:name => t.name, :rating => rating_for_subject(t) } }      
    }.to_json
  end

end
```

**Comment by lgs** [comment]
Could you please `egrep "bson|mongo" Gemfile.lock` on your local machine and `> db.version()` too with mongo shell ?

**Comment by nz** [comment]
@benevolentmadman — Nick with Bonsai.io here. We do limit some index-level config options while we're in beta, which may be affecting you here. We're working to get most of that ironed out by the time we launch, so thanks for the extra use case. Feel free to follow up with me more directly at support@onemorecloud.com, and I'll also keep an eye on correspondence here.

**Comment by benevolentmadman** [comment]
egrep "bson|mongo" Gemfile.lock reports nothing, and no mongo shell, using MySQL locally and postgres on heroku

**Comment by lgs** [comment]
@benevolentmadman 
you're right sorry, I didn't look at your `class UserProfile < ActiveRecord::Base` model ...

**Comment by benevolentmadman** [comment]
Since this project has to launch on heroku, and bonsai is still in beta, I've moved to sunspot/Websolr for now.

I'll look into using this again when bonsai's out of beta.

**Comment by iterion** [comment]
Attempting to do something similar, here is my mapping that disappears on heroku:

``` ruby
settings :analysis => {
            :filter => {
              :name_ngram  => {
                "type"     => "nGram",
                "max_gram" => 8,
                "min_gram" => 2 }
              },
              :analyzer => {
                :name_analyzer => {
                  "tokenizer"    => "standard",
                  "filter"       => ["lowercase", "stop", "name_ngram"],
                  "type"         => "custom"
                }
              }
            } do
      mapping do
        indexes :id, type: 'integer'
        indexes :name, analyzer: 'name_analyzer'
        indexes :other_names, analyzer: 'name_analyzer'
        indexes :city
        indexes :state
        indexes :domain
      end
end
```

**Comment by lgs** [comment]
What do you get running heroku console ?

`heroku run rake environment tire:import CLASS='YOUR-MODEL-NAME'`

**Comment by iterion** [comment]
Everything appears normal when importing:

```
[IMPORT] Starting import for the 'University' class
--------------------------------------------------------------------------------
2415/2415 | 100% ###############################################################
================================================================================
Import finished in 4.06294 seconds
```

Yet, the mapping from `curl -X GET "http://index.bonsai.io/[hidden]/university/_mapping"`

```
{
  "university" : {
    "properties" : {
      "id" : {
        "type" : "long"
      },
      "name" : {
        "type" : "string"
      },
      "state" : {
        "type" : "string"
      },
      "domain" : {
        "type" : "string"
      },
      "other_names" : {
        "type" : "string"
      },
      "city" : {
        "type" : "string"
      }
    }
  }
}
```

On my local install of elastic search it appears correctly.

**Comment by lgs** [comment]
Please, notice you should open a new issue, because this one is closed since a wile and does't grant sufficent visibility to your problem. Anyway, you can have a check before : 
-   you should have config/initializers/bonsai.rb like the following :

<pre>
Tire.configure { logger $stdout, :level => 'debug' }
if ENV['BONSAI_INDEX_URL']
  Tire.configure do
    url "http://index.bonsai.io"
  end
  BONSAI_INDEX_NAME = ENV['BONSAI_INDEX_URL'][/[^\/]+$/]
else
  app_name = Rails.application.class.parent_name.underscore.dasherize
  app_env = Rails.env
  BONSAI_INDEX_NAME = "#{app_name}-#{app_env}"
end
</pre>

- in your University model you should have this line :

<pre> 
    index_name BONSAI_INDEX_NAME
</pre>


If you already set/config like the previous, you can try the following 3 steps :

<pre>
      1)  drop out `to_indexed_json` from your University model ( at the opposit of README indication )
      2)  remove & add back Bonsai.io/Heroku add-on ( this will remove your index on Heroku, be careful ! )
      3)  reindex ElasticSearch by running `heroku run:detached rake environment tire:import CLASS='University'`
           ( Heroku will bill this extra "run" process so know what you're doing )
</pre>


If that still doesn't work, open a new issue with more details on your stack and configs.

**Comment by iterion** [comment]
Issue #386 added with more detail.

**Comment by nz** [comment]
For posterity, this kind of issue has been fixed within Bonsai as of a rearchitecting we completed back in October 2012. We should work well with Tire's conventions these days, and launched our addon into production back in January 2013.
