### ISSUE TITLE
Naming conflict with document_type

### ISSUE THREAD

**Issue by edwinv** [karmi/retire#370]
I'm using Tire in an ActiveRecord model that already has an attribute `document_type`. After include `Tire::Model::Search` the `document_type` method is added by Tire, breaking the behavior of the model. `document_id` and `document_type` are two attributes used in a polymorphic relation on the model and cannot be changed.

To fix the behavior of the ActiveRecord model, I've redefined the method:

``` ruby
def document_type
    self[:document_type]
end
```

This causes Tire to store the index in index_name/RubyClassName, but when defining a mapping the class level document type is used, which doesn't correspond to `RubyClassName`.

I think the method `document_type` is a fairly common name for a method and Tire should not override this method when the search module is included. Tire is almost completely proxied and accessible through `Class.tire`, maybe there is a way to apply this architecture to the `document_type` method too?

**Comment by richarddong** [comment]
`Class.tire.document_type` works for me.

**Comment by karmi** [comment]
@edwinv Tire should definitely not stomp on your `document_type` method -- as @richarddong hints, Tire should use the `tire` proxy exclusively. If this problem persists, could you post your model definition?

**Comment by karmi** [comment]
@edwinv Did the advice we gave you helped? I hope so, and you only forgot to close the issue? Closing it for now.

**Comment by neutralino1** [comment]
This problem is still alive.
In my case, `document_type` is a `belongs_to` association.
Redefining the `document_type` function like @edwinv suggested doesn't work as `self[:document_type]` does not exist, only `self[:document_type_id]` does.

Shouldn't `document_type` be fully qualified in `Tire::Model::Search`?

**Comment by OpakAlex** [comment]
```
ClassMethodsProxy::INTERFACE.each do |method|
          base.class_eval <<-"end;", __FILE__, __LINE__ unless base.public_methods.map(&:to_sym).include?(method.to_sym)
            def self.#{method}(*args, &block)                     # def search(*args, &block)
              tire.__send__(#{method.inspect}, *args, &block)     #   tire.__send__(:search, *args, &block)
            end                                                   # end
          end;
        end

        # Alias _Tire's_ instance methods in the top-level namespace of the model,
        # unless there's a conflict with existing method
        InstanceMethodsProxy::INTERFACE.each do |method|
          base.class_eval <<-"end;", __FILE__, __LINE__ unless base.instance_methods.map(&:to_sym).include?(method.to_sym)
            def #{method}(*args, &block)                          # def to_indexed_json(*args, &block)
              tire.__send__(#{method.inspect}, *args, &block)     #   tire.__send__(:to_indexed_json, *args, &block)
            end                                                   # end
          end;
        end
```

Crazy. Maybe we need add method :xyi? why not @karmi ???

**Comment by OpakAlex** [comment]
@karmi, why you don't use some prefix? maybe `tire_document_type` ?  It's normal...

**Comment by OpakAlex** [comment]
@edwinv Thanks! I redefine all this crazy methods.
