### ISSUE TITLE
Using multiple fields for a terms facet

### ISSUE THREAD

**Issue by dongennl** [karmi/retire#371]
hi, sorry if this is a newby question, I need a facet to be using values from two fields that share the same list of values.
According to the elastic search documentation this should be possible:

Here under multi fields: http://www.elasticsearch.org/guide/reference/api/search/facets/terms-facet.html 

``` json
{
    "query" : {
        "match_all" : {  }
    },
    "facets" : {
        "tag" : {
            "terms" : {
                "fields" : ["tag1", "tag2"],
                "size" : 10
            }
        }
    }
}
```

I've tried this in my Rails 3 code:

``` ruby
facet "country" do
    terms [:geo_country1, :geo_country2]
end
```

but this returns no values for the facet. I've tried without brackets and just comma, but this gives error.

Is there another way to get this to work?? Many thanks for input

**Comment by karmi** [comment]
Hi, that's not a newbie question at all, thanks for the report -- it's a bug in current `terms` facet implementation, where you can't pass multiple fields, see https://github.com/karmi/tire/blob/master/lib/tire/search/facet.rb#L20

**Comment by dongennl** [comment]
Actually, and this is pure luck, by looking at some of the code I seem to have got this to get the same result:

```
facet('country') { terms fields: [:geo_country1, :geo_country2]}
```

not sure what I'm doing, but it seems to work, need to test it more. Does this make sense?

**Comment by karmi** [comment]
Yeah, nice loophole :), since effectively it's:

```
facet('myname') { terms 'WHATEVER', fields: [:field1, :field2]}
```

where the `fields` option is merged via options into the payload sent to ES. Certainly not an interface to enjoy, but something you can use at the moment for sure :)

**Comment by dongennl** [comment]
hi, I noticed that my 'workaround' messes up any other facets that are defined after it. Not sure how/why.
But anyway, I found a better way to achieve the same result

in the mapping:
  indexes :geo_country, :type => 'string', :index => 'not_analyzed', as: 'country_display_for_search'

and then:
  def country_display_for_search
    [self.geo_country1, self.geo_country2]
  end

this then gives you a single field in the index (which contains an array)
You can now use the facet as normal:
  facet 'country' do
      terms :geo_country
  end

This achieves the desired result. Just in case it helps someone else.
