### ISSUE TITLE
partial matching doesn't work

### ISSUE THREAD

**Issue by ReLrO** [karmi/retire#373]
Hi Karmi. 
First of all, I would like to thank you for your amazing job!

I've been trying for hours now to get the right settings to create a partial match for a word but haven't been able to do so until now. 
I've tried countless variations and non of them seem to work. Here is an example of what I tried to do:

tire.settings :analysis => {
                   :filter => {
                     :name_ngram  => {
                       "type"     => "nGram",
                       "max_gram" => 50,
                       "min_gram" => 2 }
                   },
                   :analyzer => {
                     :name_analyzer => {
                        "tokenizer"    => "lowercase",
                        "filter"       => ["name_ngram"],
                        "type"         => "custom" }
                   }
                 } do
          mapping {
             indexes :full_name,     :type => 'string', :analyzer => "name_analyzer"
             indexes :id,            type: 'integer',    index: :not_analyzed
             indexes :email,         type: 'string',     index: :no
             indexes :created_at,    type: 'date'
             indexes :profession,    analyzer: 'whitespace'
             }
  end

That didn't do the trick. Then I tried to take an inspiration from 
http://dev.af83.com/2012/01/19/autocomplete-with-tire.html
and from https://gist.github.com/1231602
but I cannot find the right combination to make it work. 

for example, I tried this code:

tire.settings analysis: {
           filter: {
              name_ngrams: {
                 side: "front",
                 max_gram: 10,
                 min_gram: 1,
                 type: "edgeNGram"
              },
              name_metaphone: {
                 replace: false,
                 encoder: "metaphone",
                 type: "phonetic"
              }
           },
           analyzer: {
              full_name: {
                 filter: [
                    "standard",
                    "lowercase",
                    "asciifolding"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              },
              name_metaphone: {
                 filter: [
                    "name_metaphone"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              },
              partial_name: {
                 filter: [
                    "standard",
                    "lowercase",
                    "asciifolding",
                    "name_synonyms",
                    "name_ngrams"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              }
           }
        } do
          mapping {
             indexes :full_name do
              indexes :fields do
                indexes :metaphone, type: "string", analyzer: "name_metaphone"
                indexes :partial, search_analyzer: "full_name", index_analyzer: "partial_name", type: "string"
                indexes :full_name, type: "string", analyzer: "full_name"
               end  
             end
             indexes :id,            type: 'integer',    index: :not_analyzed
             indexes :email,         type: 'string',     index: :no
             indexes :created_at,    type: 'date'
             indexes :profession,    analyzer: 'whitespace'
             }
  end

which didn't work. 
I am trying to create something that will enable me to take all the data from the user model and to update the indexes when the model is updated. Please help! :)

Thank you, 
Ariel.

**Comment by ReLrO** [comment]
I tried this option which didn't work either:

  tire.settings analysis: {
           filter: {
              name_ngrams: {
                 side: "front",
                 max_gram: 10,
                 min_gram: 1,
                 type: "edgeNGram"
              },
              name_metaphone: {
                 replace: false,
                 encoder: "metaphone",
                 type: "phonetic"
              }
           },
           analyzer: {
              full_name: {
                 filter: [
                    "standard",
                    "lowercase",
                    "asciifolding"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              },
              name_metaphone: {
                 filter: [
                    "name_metaphone"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              },
              partial_name: {
                 filter: [
                    "standard",
                    "lowercase",
                    "asciifolding",
                    "name_synonyms",
                    "name_ngrams"
                 ],
                 type: "custom",
                 tokenizer: "standard"
              }
           }
        } do
          mapping {
             indexes :full_name,     type: "string",     search_analyzer: "full_name", index_analyzer: "partial_name"
             indexes :id,            type: 'integer',    index: :not_analyzed
             indexes :email,         type: 'string',     index: :no
             indexes :created_at,    type: 'date'
             indexes :profession,    analyzer: 'whitespace'
             }
  end

**Comment by ReLrO** [comment]
these are my latest settings:

  settings :number_of_shards => 5,
           :number_of_replicas => 1, 
           analysis: {
             filter: {
                name_ngrams: {
                   side: "front",
                   max_gram: 10,
                   min_gram: 1,
                   type: "edgeNGram"
                },
                name_metaphone: {
                   replace: false,
                   encoder: "metaphone",
                   type: "phonetic"
                }
             },
             analyzer: {
                full_name: {
                   filter: [
                      "standard",
                      "lowercase"
                   ],
                   type: "custom",
                   tokenizer: "standard"
                },
                name_metaphone: {
                   filter: [
                      "name_metaphone"
                   ],
                   type: "custom",
                   tokenizer: "standard"
                },
                partial_name: {
                   filter: [
                      "standard",
                      "lowercase",
                      "name_ngrams"
                   ],
                   type: "custom",
                   tokenizer: "standard"
                }
             }
        } do
          mapping {
             indexes :full_name,  :type => 'multi_field', :fields => {
                      metaphone: { type: "string", analyzer: "name_metaphone" },
                      partial: { search_analyzer: :full_name, index_analyzer: :partial_name , type: "string" },
                      full_name: {type: "string", analyzer: :full_name }
                    }
             indexes :id,            type: 'integer',    index: :not_analyzed
             indexes :email,         type: 'string',     index: :no
             indexes :created_at,    type: 'date'
             indexes :profession,    analyzer: 'whitespace'
             }
        end

what do I need to write in the tire.search method in order for it to work?

**Comment by karmi** [comment]
Check out this StackOverflow answer, http://stackoverflow.com/a/9432450/95696, and maybe post your question there -- more exposure, more people willing to help.
