### ISSUE TITLE
How to set up mapping with boost for object array.

### ISSUE THREAD

**Issue by mhamrah** [karmi/retire#375]
I have two issues.  I am searching on items in an item model, which has many folders.  I am trying to store the folders as an object array.

Here is my mapping file:

```
tire.mapping do
  indexes :id, :index => :not_analyzed
  indexes :name, :boost => 10
  indexes :user_id
  indexes :description
  indexes :updated_at, :index => :not_analyzed
  indexes :folders, :type => 'object',
        :properties => {
          :id => { :index => :not_analyzed },
          :title => {
            :type => "multi_field", :fields => {
              :raw => { :type => 'string', :index => 'not_analyzed'},
              :title => { :type => 'string' }
            } 
          },
          :description => { :type => "string", :index => :not_analyzed },
          :user_id => { :index => :not_analyzed }
        }
end
```

and my to_json method:

```
def to_indexed_json
  to_json(:only => [:id, :name, :description, :user_id, :updated_at], :include => [{ :folders => { :only => [:id, :title, :description,  :user_id] } }] )
end
```

My problem is two fold:
- When I declare the :folders block in my mapping, the :boost value of name goes away when viewing http://localhost:9200/<my index>/_mapping/
- I cannot add a boost to folders.title and folders.description (I'm not sure if this is a limitation of elastic search, where boost can only be applied to the root object).

I suppose my first problem is mapping the object produced in to_indexed_json to my mapping, and elastic search is throwing away the boost.  

Any assistance is appreciated.  

Thanks.

**Comment by vhyza** [comment]
Hello,

It seems that `object` type should have explicitly defined `type` of each property.

Your mapping definition is not correct for ElasticSearch. When I tried to post generated `curl` command, ElasticSearch responded with 400 code and error `nested: MapperParsingException[No type specified for property [id]]`

So in this case mapping is created dynamically (when first document is saved), not by Tire definition. That's why `boost` attribute disappears.

Following code creates mapping correctly:

``` ruby
require 'tire'
require 'active_record'
require 'sqlite3'

ActiveRecord::Base.establish_connection( :adapter => 'sqlite3', :database => ":memory:" )

Tire.configure { logger STDOUT }

class ActiveRecordModel < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks


  tire do
    mapping do
      indexes :id, :index => :not_analyzed
      indexes :name, :boost => 10
      indexes :user_id
      indexes :description
      indexes :updated_at, :index => :not_analyzed
      indexes :folders, :type => 'object',
              :properties => {
                :id    => { :index => :not_analyzed, :type => "string" },
                :title => {
                  :type => "multi_field",
                  :fields => {
                    :raw   => { :type => 'string', :index => 'not_analyzed', :boost => 20 },
                    :title => { :type => 'string'                          }
                  }
                },
                :description => { :type => "string", :index => :not_analyzed },
                :user_id     => { :index => :not_analyzed, :type => "string" }
              }
    end
  end

end

ActiveRecordModel.index.delete
ActiveRecordModel.create_elasticsearch_index

puts ActiveRecordModel.index.mapping.inspect
```

Hope this helps...

**Comment by karmi** [comment]
@mhamrah Hope your problem was solved and you only forgot to close the issue.
