### ISSUE TITLE
Reindexing a whole Invoices table

### ISSUE THREAD

**Issue by deanpcmad** [karmi/retire#378]
Hi there,
I am currently working on an intranet for work and it has ElasticSearch attached using Tire. I have a list of 10,000+ invoices which I will be importing into the intranet directly to the database from a CSV file.

How do I go about reindexing the whole Invoices table for ElasticSearch & Tire to pick them up? Are they any commands which I haven't found?

Thanks and I hope you can help :)
Dean

**Comment by deanpcmad** [comment]
Looks like I can run `Tire.index('invoices').reindex('invoices')` and it reindexes. I couldn't see this in the documentation, maybe you could add it?

Thanks!

**Comment by karmi** [comment]
Yeah, this is probably possible :), but what'd the point of that? That would just put the same data in..

There's a Rake task (and API support) for easy importing, documented in the Readme:

```
 $ rake environment tire:import CLASS='Article'
```

Regarding the documentation -- it must be seriously improved...

**Comment by deanpcmad** [comment]
Well I need to import it directly into the database from our old invoicing system.

Ah ok, I didn't notice the rake task, thanks! :)
