### ISSUE TITLE
rake task :import fails when model groups in default scope

### ISSUE THREAD

**Issue by cseeger** [karmi/retire#380]
When a model groups (sql group by) in its default scope, #count may cause the following:

"ActiveSupport::OrderedHash can't be coerced into Float"

**Comment by karmi** [comment]
Hi, do you have a backtrace and possibly an example of the scope?

**Comment by cseeger** [comment]
whoops, didn't realize the pull request would open a new issue. closing this out

**Comment by karmi** [comment]
No problem, thanks :)
