### ISSUE TITLE
Sorting on Milliseonds

### ISSUE THREAD

**Issue by ericTsiliacos** [karmi/retire#382]
I am trying to sort on a date with the following format:

%Y/%m/%d %H:%M:%S,%L

However, tire gem seems to think that there is more than one value per doc, or that there is more than one token per field. 

I also tried %Y/%m/%d:%H:%M:%S:%L and other various ways of formatting it but none of them work. It only seems to sort on %Y/%m/%d %H:%M:%S where I leave out the milliseconds.

**Comment by vhyza** [comment]
Hello,

please can you gist your index mapping?

**Comment by ericTsiliacos** [comment]
Thanks, the following is what I currently have. I wasn't really using the mapping way of doing it.

```
class Log
    attr_reader :date

    def initialize(attributes={})
      @attributes =  attributes
      @attributes.each_pair { |name,value| instance_variable_set :"@#{name}", value }
    end

    def type
      'logs'
    end

    def to_indexed_json
       @attributes.to_json
    end
  end

  @conn = Mongo::Connection.new
  @db   = @conn['mydb']
  @coll = @db['test_collection']


  @coll.find.each do |doc| 
    row = JSON.parse(doc.to_json)
    log = Log.new :date => row.fetch("date")

    store log
  end

  refresh

end
```

And in another file, I query and sort on the date attribute:

```
@s = Tire.search( 'logs' ) do |search|
      search.query { |query| query.string q }
      search.sort do 
        by :date, 'desc' 
      end
end
```

**Comment by karmi** [comment]
@ericTsiliacos You can sort only on fields which have one token per field. `%Y/%m/%d %H:%M:%S,%L` is split at the space in the middle. If you want to use this date format, and not the ES default one, you have to correctly set up the mapping for this field: http://www.elasticsearch.org/guide/reference/mapping/date-format.html

**Comment by ericTsiliacos** [comment]
Thank you for your response. 

I am a little confused about why the space makes a difference between 
%Y/%m/%d %H:%M:%S,%L         and  
%Y/%m/%d %H:%M:%S. 

I would think the second format would also break because of the space but it doesn't, unless the space is part of the default. 

---

This is what I have so far but it still doesn't seem to be working. Thank you again for your help.

```
index = Tire.index 'logs' do

  delete 

  create :mappings => {

    :logs => {
      :properties => {
        :date             => { :type => 'date', :date_formats => 'basic_date_time'}
      }
    }
  }
end

@conn = Mongo::Connection.new
@db   = @conn['mydb']
@coll = @db['test_collection']


@coll.find.each do |doc| 
  row = JSON.parse(doc.to_json)

  log = {}
  log[:date] = Time.parse(row.fetch("date")).strftime('%Y-%m-%dT%H:%M:%S.%L')

  index.store log

end
```

**Comment by karmi** [comment]
> Since it is a default, then I wouldn't have to do a mapping for that format correct? But because mine has a space, then I have to create that mapping for the field. 

Exactly!

> Could you point me in the right direction where I can find what that mapping would look like.

Not entirely sure what you're up to here, but to use a custom date format, you need to setup your index somehow like this:

``` ruby
require 'tire'

Tire.configure { logger STDERR, level: 'debug' }

Tire.index 'my_special_date' do
  delete

  create mappings: {
    logentry: {
      properties: {
        date: {
          type: 'date',
          # See http://joda-time.sourceforge.net/api-release/org/joda/time/format/DateTimeFormat.html
          format: "Y/M/d k:m:s,SSS"
        }
      }
    }
  }

  store type: 'logentry', message: 'OK', date: '2012/01/01 01:00:00,100'
  store type: 'logentry', message: 'OK', date: '2012/02/01 01:00:00,100'
  store type: 'logentry', message: 'OK', date: '2012/03/01 01:00:00,100'

  refresh
end

s = Tire.search 'my_special_date' do
  query { all }
  sort  { by :date, 'desc' }
end

p s.results.map(&:date)
```

**Comment by ericTsiliacos** [comment]
works like a charm! Thank you for your help.

**Comment by ericTsiliacos** [comment]
Thanks again for helping earlier. Tire sorts the dates great.

I have another question. I am having trouble querying using date range with the above. I am thrown an error when I try the following via an input field. 

```
date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] 
```

Here is part of the error message that seems relevant:

```
nested: ParseException[Cannot parse 'date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] ': Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; nested: ParseException[Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; }{[3-yAuRASS5-eufkYlMUcpQ][logs][3]: SearchParseException[[logs][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] \",\"default_operator\":\"AND\"}},\"sort\":[{\"date\":\"desc\"}],\"highlight\":{\"fields\":{\"file\":{\"number_of_fragments\":0},\"date\":{\"number_of_fragments\":0},\"location\":{\"number_of_fragments\":0},\"level\":{\"number_of_fragments\":0},\"path\":{\"number_of_fragments\":0},\"lcid\":{\"number_of_fragments\":0},\"sid\":{\"number_of_fragments\":0},\"uid\":{\"number_of_fragments\":0},\"message\":{\"number_of_fragments\":0}},\"pre_tags\":[\"<em class=\\\"highlight\\\">\"],\"post_tags\":[\"</em>\"]},\"size\":500,\"from\":0}]]]; nested: QueryParsingException[[logs] Failed to parse query [date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] ]]; nested: ParseException[Cannot parse 'date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] ': Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; nested: ParseException[Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; }{[3-yAuRASS5-eufkYlMUcpQ][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] \",\"default_operator\":\"AND\"}},\"sort\":[{\"date\":\"desc\"}],\"highlight\":{\"fields\":{\"file\":{\"number_of_fragments\":0},\"date\":{\"number_of_fragments\":0},\"location\":{\"number_of_fragments\":0},\"level\":{\"number_of_fragments\":0},\"path\":{\"number_of_fragments\":0},\"lcid\":{\"number_of_fragments\":0},\"sid\":{\"number_of_fragments\":0},\"uid\":{\"number_of_fragments\":0},\"message\":{\"number_of_fragments\":0}},\"pre_tags\":[\"<em class=\\\"highlight\\\">\"],\"post_tags\":[\"</em>\"]},\"size\":500,\"from\":0}]]]; nested: QueryParsingException[[logs] Failed to parse query [date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] ]]; nested: ParseException[Cannot parse 'date:[2012-07-10 08:09:43,180 TO 2012-07-10 08:10:21,085] ': Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; nested: ParseException[Encountered \" \"TO\" \"TO \"\" at line 1, column 30.\nWas expecting:\n    \"]\" ...\n    ]; }]","status":500}
```

It seems to work when I put the individual date-times in quotes as seen below but I was under the impression that it should work without the quotes.

```
date:["2012-07-10 08:09:43,180" TO "2012-07-10 08:10:21,085"] 
```

Also, I noticed that the " \* " wildcard does not work when I try doing the following:

```
date:[2012-07-10* TO 2012-07-10*] 
```

I was wondering if there was anyway I could get help with understanding why the above is the case and how I could fix it. Thank you!

**Comment by karmi** [comment]
@ericTsiliacos Both questions are interesting, but I'm afraid I don't have an ultimate answer.

For first, I think the space after the day throws the query parser off, hence the `ParseException`.

For second, I'm not sure why wildcards wouldn't work here -- but I suspect your query `[2012-07-10* TO 2012-07-10*]` is incorrect. Both would probably be expanded to the same day (midnight?). Try something like  `[2012-07-10* TO 2012-07-11*]`.

**Comment by ericTsiliacos** [comment]
Thank you for your help. I also tried: 

```
date:[2012-07-03* TO 2012-07-04*]
```

and was given the following error message as well:

```
ElasticSearchParseException[failed to parse date field [2012-07-03*], 
tried both date format [Y-M-d H:m:s,SSS], and timestamp number]; 
nested: IllegalArgumentException[Invalid format: \"2012-07-03*\" is malformed at \"*\"]; }]",
"status":500}
```

Just as a confirmation and so that someone else may be able to recreate the problem, the following is the index mapping I used:

```
#!/usr/bin/env ruby

require 'tire'

class Index_mapping 
  def initialize
    Tire.index 'logs' do

      create :mappings => {

        :log => {
          :properties  =>  {
            :id       => { :type => 'string', :index => 'not_analyzed', :include_in_all => false },
            :date     => { :type => 'date', format: "Y-M-d H:m:s,SSS"                            }
          }
        }
      }
    end                                                    
  end 

end
```

I'll let you know if something comes up. Thanks again for your help.

**Comment by karmi** [comment]
AFAIK, the problems you mention are related to the custom date format, the wildcard expansion included.

Note, that searching for ranges is absolutely fine with your format -- given we have the data indexed as in my [comment above](https://github.com/karmi/tire/issues/382#issuecomment-6477049):

``` ruby
s = Tire.search 'my_special_date' do
  query { range 'date', gte: "2012/01/01 01:00:00,100", lte: "2012/01/02 01:00:00,100" }
end

p s.results.map(&:date)
```
