### ISSUE TITLE
Tire::Model::Callbacks not working right with index_name

### ISSUE THREAD

**Issue by zacksiri** [karmi/retire#387]
when i am setting the index_name manually, it seems that the Callbacks are not being run when the object is deleted from the database for some reason

if i remove the index_name setting in my model everything works fine. I am getting a 500 error when doing this, since when i delete the object elastic search still has the object hence its returning the json data in the search and since i am using load: true active record is trying to load the object and failing 

giving me a 500 error as a result

**Comment by felipegs** [comment]
I have the same problem here

**Comment by felipegs** [comment]
Sorry I was calling model.delete not model.destroy. model.delete doesn't call the callbacks

**Comment by karmi** [comment]
@zacksiri Are you sure you've been calling `destroy` and not `delete` as @felipegs?

**Comment by karmi** [comment]
@zacksiri Closing.
