### ISSUE TITLE
Scanning and Scrolling Documentation

### ISSUE THREAD

**Issue by ericTsiliacos** [karmi/retire#389]
Hi, I was looking around and I was not able to find documentation on "scan" or "scroll" in the Tire DSL. I am looking to load results as a user scrolls at the end of the page and was wondering what that would look like. Thanks you for your help!

**Comment by karmi** [comment]
See https://github.com/karmi/tire/blob/master/test/integration/scan_test.rb for documentation on scan/scroll. This has nothing to do with "scrolling" the page. In that case, just load the next batch of results, based on pagination -- Railcasts.com has a nice screencast on that.
