### ISSUE TITLE
{"error":"InvalidTypeNameException[mapping type name [_bulk] can't start with '_']","status":400}

### ISSUE THREAD

**Issue by mdoroudi** [karmi/retire#390]
Hi,
I installed Elastic search and tire on my development box and also on our staging box. 
Indexing/import works fine on my development machine. I have the same setup on the Staging machine.  But on Staging When I try to index data either from ActiveRecord or from a plain array I get
{"error":"InvalidTypeNameException[mapping type name [bulk] can't start with '']","status":400}
However I did tried to do it from curl http://www.elasticsearch.org/guide/reference/api/bulk.html and it did work.
curl -s -XPOST http://localhost:9200/_bulk --data-binary @request

Any ideas what could be the problem? I feel like maybe tire does't send the right data format?

thanks!
mina

**Comment by borisruf** [comment]
I ran into the same problem and noticed that homebrew tricked me: It was not auto-updating itself (version 0.8) and kept installing and outdated version of elasticsearch. Enforcing updates of both fixed the issue.

**Comment by brunzino** [comment]
I had this problem too and also fixed it by updating homebrew. However, when I updated to Mountain Lion, my indexes were gone and when trying to re-index, got this same problem again.

**Comment by angusd** [comment]
I hit this earlier today with the latest (0.4.2) gem. Saw the freshness of the above comment and tried rolling back to 0.3.12 and it indexed fine.

**Comment by karmi** [comment]
This is strange, can't replicate on current master. Please try out the Rails application template which uses bulk to import:

```
rails new searchapp -m https://raw.github.com/karmi/tire/master/examples/rails-application-template.rb
```

Closing for now, reopen or submit new issue when you hit the problem.

**Comment by beunwa** [comment]
Hi, same problem here, I use Tire 0.4.3 without rails and I bulk import plain array on a remote server. 

[ERROR] 400 > {"error":"InvalidTypeNameException[mapping type name [_bulk] can't start with '_']","status":400}, retrying (1)...

**Comment by karmi** [comment]
@beunwa That's really too little information :) Open a separate issue with details, please.

**Comment by mubix** [comment]
Having this same issue with https://gist.github.com/953072

Turns out I was using an old version of elasticsearch
