### ISSUE TITLE
Be more verbose - tire:import

### ISSUE THREAD

**Issue by iterion** [karmi/retire#392]
I've noticed that on index creation the tire:import task is pretty silent, even when the index settings or mappings don't get saved

I'll get a pull request up in the next few days with what I'm thinking:

For now, I plan to check if `index.create` returns `false`. If so, print out `index.response`

Anyone else have any desires?

**Comment by JamesHarrison** [comment]
Speed is a major issue, at least for me, with tire:import. More information on progress and an ETA would be good. A truly verbose 'here's what I'm doing now' mode would rock, too.

**Comment by andrew** [comment]
I've been caught out by this a number of times, tire says its indexed 100% of the documents, but that doesnt mean it has put all (or any) of them into the index.

Thinking sphinx has quite a detailed output from its rake task: http://freelancing-god.github.com/ts/en/rake_tasks.html

**Comment by karmi** [comment]
@iterion Thanks!, embarrasing oversight -- should be fixed now.

@JamesHarrison Don't really follow -- the task prints out the number of documents been indexed vs. total, as well as percentage and progress bar. ETA would be guesswork -- nobody knows what can happen in your cluster all of a sudden.

@andrew Don't really follow that as well -- I'd like to see the case where Tire said docs were indexed while they actually were not. See https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L105-122
