### ISSUE TITLE
STI bug with geo_point field

### ISSUE THREAD

**Issue by elfassy** [karmi/retire#394]
> QueryParsingException[[venue] field [location] is not a geo_point field];

but it is!

```
[IMPORT] Deleting index 'venues'
[IMPORT] Creating index 'venues' with mapping:
{"venue":{"properties":{"location":{"type":"geo_point"}}}}
[IMPORT] Starting import for the 'Venue' class
```

If i do 

> curl -XGET 'http://localhost:9200/venues/_mapping' 

I get (for Venue and Venue::Type > Venue)

```
{"venue":{"venue/type":{"properties":{"location":{"type":"string"}}}}
```

Which might confirm that there's something wrong with tire
Thanks for your suggestions.

**Comment by elfassy** [comment]
Turns out this is a bug with STI (single table inheritance for those searching)

With the fix below everything works as expected. Keep in mind this removes the ability to search child classes individually. (we need a fix for that please)

``` ruby
module Tire
  module Model
    module Naming
      module ClassMethods
        def document_type name=nil
          @document_type = name if name
          @document_type || klass.model_name.underscore.split("/")[0]
        end
      end
    end
  end
end
```

**and in all subclasses**

``` ruby
tire.index_name 'venues'
```

**Comment by karmi** [comment]
Hi, so is this about Tire getting incorrect `document_type`s for the STI models? Note that issues karmi/tire#80, karmi/tire#218 and karmi/tire#277 all seem to be fixed now... Could you post your model definitions somewhere?

**Comment by elfassy** [comment]
``` ruby
require 'active_record'
require 'tire'

ActiveRecord::Base.establish_connection( :adapter => 'sqlite3', :database => ":memory:" )

ActiveRecord::Schema.define(:version => 1) do
  create_table :venues do |t|
    t.string   :title, :lat, :lon
    t.datetime :created_at, :default => 'NOW()'
  end
end

class Venue < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks

  tire do
    mapping do
      indexes :title
      indexes :location, type: 'geo_point'
    end
  end

  def location
    [lon, lat]
  end

  self.include_root_in_json = false
  def to_indexed_json
    self.to_json(only: ['id', 'title', 'created_at'], methods: ['location']) 
  end

end

class Venue::Type < Venue
end

# -----

p Venue.new.document_type
# => "venue"

p Venue::Type.new.document_type
# => "venue/type"
```

---

NOTE: Updated by @karmi

**Comment by karmi** [comment]
I've updated your example above to be able to run and understand your issue at all. Notice the missing `include_root_in_json` directive in your original code, for example.

Clearly, `Venue::Type` is serialized as `"venue/type"` in _Tire_. Why is that so? Because _Tire_ does not know you're using STI (single class inheritance), namespacing, etc. etc., and uses just the regular ActiveModel compatible serialization (`klass.model_name.underscore`). If you have some better suggestion, please clearly state what is it and why is it preferable.

The simple solution for single table inheritance problems with _Tire_ is just to set proper naming in your models:

``` ruby
class Venue::Type < Venue
  tire do
    index_name    "venues"
    document_type "venue"
  end
end
p Venue.new.document_type
# => "venue"

p Venue::Type.new.document_type
# => "venue"
```

With the code as updated above, the following works as expected:

``` ruby
Tire.configure { logger STDERR }

p Venue::Type.create title: "Test", lat: 45, lon: 45
p Venue::Type.index.refresh
p Venue::Type.tire.search { filter 'geo_distance', distance: '12km', location: [45, 45] }.results.first

# => <Item created_at: "2012-07-26T09:56:06+02:00", id: "1", title: "Test", location: [45, 45], ...>
```

**Comment by karmi** [comment]
Closing the issue for now. If you feel there's something _Tire_ could do better for you, please don't hesitate to comment further. (Do not, however, that eg. the proposed fix for `document_type` does not really fixes anything...?)
