### ISSUE TITLE
Syntax for :not filter

### ISSUE THREAD

**Issue by elfassy** [karmi/retire#395]
It's just not clear to me what is the syntax with tire. Thanks

http://www.elasticsearch.org/guide/reference/query-dsl/not-filter.html

> filter :not , ids: ["3515"] 

EDIT:

ok figured it out, it's:

> filter :not , {:ids => { :values => ["3515"] }}

**Comment by thoughtpunch** [comment]
Have you had any success filtering on other fields other than ID? I keep getting a `QueryParsingException[[users] No filter registered for [first_name]]; }]","status":500` error.

Any ideas?

**Comment by elfassy** [comment]
There might be something wrong with your syntax (post the line for us to have a look). To answer your question, i haven't tried it with anything other than ids but it should work.
On the elasticsearch site they write "Can be placed within queries that accept a filter."
http://www.elasticsearch.org/guide/reference/query-dsl/not-filter.html
