### ISSUE TITLE
Mapping definitions in Mongoid model class don't make it through to index creation

### ISSUE THREAD

**Issue by christopherdbull** [karmi/retire#396]
Hey,

I'm finding some weird behaviour with Tire where mapping definitions I've created, eg the canonical 

```
mapping do
  indexes :id, type: 'string', :index => :not_analyzed, :include_in_all => false
  indexes :locale, type: 'string', :index => :not_analyzed
end
```

get changed somewhere in the index creation process and end up as

```
locale: {
type: string
}
```

etc.

The weird thing is though, when I run the data migration rake task, the mapping appears correctly with the right attributes (:index etc).

Happy to provide any more details, my env details: Ruby 1.9.3, ElasticSearch 0.19.4 - installed with homebrew.  Rails 3.2.3, mongoid 2.4.11, OSX Lion (up to date), mongo 2.0.0

Thanks,
Chris

**Comment by karmi** [comment]
@te-chris I think the culprit is `:index => :not_analyzed` here -- see karmi/tire...
