### ISSUE TITLE
Different facet count with different facet size and the same query

### ISSUE THREAD

**Issue by dedico** [karmi/retire#398]
Hi,

I get different facet counts for the same query when I set size parameter for that facet and when I use default size parameter.
For example I have

``` ruby
...
facet 'models' do
  terms :model_id
end
...
```

and 

``` ruby
...
facet 'models' do
  terms :model_id, :size => 1000
end
...
```

For exactly the same query I get different facet counts... 
What means :size?
Does  it mean the max number of facet elements returned or it has something to do with the number of documents for which the facet counts are calculated?

Hope it makes sense.

Thanks,
Marek

P.S. What is the best place to ask questions how to use tire?

**Comment by karmi** [comment]
> For exactly the same query I get different facet counts... 

Yes, it's dependent on the index shard count, some issues in the `elasticsearch` repo are floating around related to this.

> What means :size?

Check out http://www.elasticsearch.org/guide/reference/api/search/facets/terms-facet.html, it's the number of terms you want have returned in the facet.

> P.S. What is the best place to ask questions how to use tire?

Posting issues is fine, asking on the [#elasticsearch](irc://irc.freenode.net/elasticsearch) IRC channel is preferable (much shorter feedback loop)...

**Comment by dedico** [comment]
Hi,

thanks for the answer. 
To get this correct I understand I should use some huge :size number?
I'm passing :all_terms => true but not sure if that should include all terms?

Thanks,
Marek

**Comment by karmi** [comment]
> To get this correct I understand I should use some huge :size number?

Yes, exactly like that, that's the current workaround on the elasticearch level.

> I'm passing :all_terms => true but not sure if that should include all terms?

Yes, that [should](http://www.elasticsearch.org/guide/reference/api/search/facets/terms-facet.html), but beware of frying ES and your app when there are thousands terms to facet on.

Is the problem solved? Closing the issue?
