### ISSUE TITLE
rspec 2 empty result with capybara dsl

### ISSUE THREAD

**Issue by khoan** [karmi/retire#40]
i've setup rspec with capybara dsl. When running integration spec, i keep on getting empty search result from tire search. But when i use the same curl in a shell, i'm able to pull back result. Anyone else seeing this phenomenon?

``` sh
[REQUEST FAILED] curl -X POST "http://localhost:9200/test_events/_search?pretty=true" -d '...'
```

Indexing appears to be fine.

gist of my spec_helper.rb looks like:

``` ruby
require 'capybara/rspec'
require 'capybara/rails'

RSpec.configure do |config|
    config.before :all do
      # namespace  elastic search index with test_
      # to avoid clashing with development data
      SuperDuperModel.index_name('test_' + SuperDuperModel.model_name.plural)
    end

    # clear DB before scenario
    config.before :each do
      Tire.index(SuperDuperModel.index_name).delete
    end
end
```

**Comment by karmi** [comment]
Are you sure you're refreshing your index between inserting test data and querying it? There's a 1sec delay by default. See all those `refresh`es in the _Tire_ integration test suite...

**Comment by khoan** [comment]
thanks! an index refresh does the trick.
