### ISSUE TITLE
facet_filter is causing query filter stop working...

### ISSUE THREAD

**Issue by dedico** [karmi/retire#400]
Hi,

created following gist and comment with links to other gists:
https://gist.github.com/3070738

I'm not getting it, looks like the query completely ignoring filters when I use a filter on a facet...

Could you advice me what I'm doing wrong?

I'd like to achieve something like that:
- when no facets are selected user should see two facets with independent counts: power and capacity
- when user selects one facet, eg. power, the capacity facet should be filtered so the terms and counts depend on query and selected power facet.

Here my search action without facet filter:
https://gist.github.com/3070955

and here with facet filter:
https://gist.github.com/3070963

The second version is giving me results as I would not have any filters / facets selected.

Thanks,
Marek

**Comment by karmi** [comment]
Hi, the problem was with the incorrect nesting of the `facet_filter` option.

The correct syntax is:

``` ruby
Tire.search('articles') do
  facet('tags', facet_filter: { terms: ['foo', 'bar'] }) do
    terms :tags
  end
end
```

See https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L49-60

See http://pastie.org/4231884 for full controller implementation.
