### ISSUE TITLE
Best way to search multiple indices?

### ISSUE THREAD

**Issue by joshcutler** [karmi/retire#404]
I have seen the numerous examples of doing multisearch over many models, but I wanted to know if it was possible to search multiple indices with the same model.  I would like to be able to break up my indices to keep query times low (and eventually drop old/unneeded ones), e.g. an index represents 1 weeks worth of data, then I can delete/archive the index after it is a month old.  However, I would like to be able to search over the last 4 week's worth of indices.

Any suggestions on how to proceed?

**Comment by karmi** [comment]
Hi, the best solution for this use case is using aliases in elasticsearch, see eg. https://github.com/karmi/tire/blob/master/test/integration/index_aliases_test.rb#L66-118

**Comment by joshcutler** [comment]
beautiful thank you!
