### ISSUE TITLE
how to access _score

### ISSUE THREAD

**Issue by elfassy** [karmi/retire#406]
How do i access the score of my results (to display it for example) from my Tire::Results::Collection.
Thanks

**Comment by vhyza** [comment]
Hello,

I think each `Item` has property `_score`

``` ruby

require 'tire'

s = Tire.search('mentions') do
  query { string 'ruby' }
end

p s.results.first._score
```

**Comment by elfassy** [comment]
``` ruby
Job.tire.search("test").results[0]._score
```

does work, but my problem is when i try to do:

``` ruby
Job.tire.search("test",load:true).results[0]._score
```

which returns

```
NoMethodError: undefined method `_score' for #<Job:0xfb11c28>
```

Is there a way to use load:true and still get the score?

**Comment by vhyza** [comment]
Unfortunatelly not yet, I think this issue is related to #261

**Comment by karmi** [comment]
Yeah, @vhyza is right, we have to augment your AR/AMo models with the hits to support something like Sunspot's `each_with_hit`.
