### ISSUE TITLE
Dynamic Index From Instance Relationship

### ISSUE THREAD

**Issue by jwaldrip** [karmi/retire#408]
I have a multitenant system and I would like the index names to be dynamic and based on a relationship to the tenants account (`belongs_to :account`). A simple index name could be `"#{account_id}_#{model_name}"`, what would be the easiest way to do this with tire?

**Comment by karmi** [comment]
Hi, you may wanna check out these examples, https://github.com/karmi/tire/pull/92#issuecomment-6929988
