### ISSUE TITLE
Activerecord bulk import with paging issue

### ISSUE THREAD

**Issue by zunger** [karmi/retire#409]
Hi

I have a Region model which contains an id and a name field. The regions table in the Postgres db contains 50047 records. The ID is a sequence-generated unique primary key - there are no duplicates.

I defined the mapping in the Rails region model definition as follows:

mapping do
    indexes :id, :index => 'not_analyzed', :include_in_all => false
    indexes :name, :analyzer => 'snowball'
end

I then ran:

rake environment tire:import CLASS='Region' FORCE=true

The import finds all 50047 records and reports them as imported. However, when searching, I noticed several results that were missing. Checking in ElasticSearch Head revealed that only about 28k of the records were present in the index. I ran the import task again with the same result. Closer examination in Head revealed that some records were marked "_version: 2" - even though the index had been deleted prior to import (I ran once with a manual delete to confirm) and all id values were guaranteed unique.

After much hair pulling, I ran an import via the Rails console, using:

Region.index.import Region.all

When it completed, all 50047 records were present in the ES index.

I have other models which are indexed and all records there are imported via the rake task perfectly, though those tables all have less than 1000 records. (the default pagination size)

My app uses will_paginate for paging which is definitely working and returning the correct results. Is this an issue with tire or should I be looking elsewhere?

**Comment by karmi** [comment]
>  Closer examination in Head revealed that some records were marked "_version: 2"

The only possible explanation is that some records overwrote other ones. If you're absolutely sure your IDs are unique, there may be a bug in _Tire_, however, I've never encountered it. Check your `STDERR`, _Tire_ should print out a warning when records don't have an ID.

> `Region.index.import Region.all`

So everything was imported correctly from the console, but not from the Rake task?

**Comment by zunger** [comment]
ID's are definitely unique. I'm importing from a PostgreSQL table where the ID is a unique primary key. I even ran a "group by id having count(*) > 1" query on the table in PGSQL to make sure I wasn't going batty, which obviously confirmed they were unique.

I believe the issue occurs when paging is used to break the recordset into chunks.

From the console, after manually deleting the index:

"Region.import" will result in the missing record scenario. 
"Region.index.import Region.all" imports as expected, all records are present. 

The rake task:

"rake environment tire:import CLASS='Region' FORCE=true" will result in missing records.

The only common thread between the two failing imports are that they both use paging. I'm using will_paginate 3.0.3.

I read an old issue which involved paging not automatically sorting by any field, resulting in skipped records on import. This sounds like the case I'm experiencing, however the issue was marked as closed with a commit to auto sort by ID and I'm using the latest version of Tire, so it sounds unlikely.

Neither there are no errors from either Tire or elasticsearch during or post import. Records in elasticsearch contain the correct ID's for those records that were imported, so the field is present - some records are just skipped and others imported more than once by the looks of it - which again points to the closed pagination issue.

Obviously I can use the import method that works, and past the initial import it is no longer an issue assuming I don't need to bulk import again so I could live with it - but if a bug exists I'd love to help track it down and fix it, I'm just not sure what else to look for.

**Comment by karmi** [comment]
@zunger Thank you very much for such a detailed bug report. It definitely looks like there's something wrong with the pagination support for import -- I'll run some tests with couple of tens of thousands of data.

The [`MyModel.import`](https://github.com/karmi/tire/blob/master/lib/tire/model/import.rb#L18) method just calls the [`Tire::Index#import`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L127-136) method, so something fishy must be there, but nothing sticks out for me right now...

**Comment by zunger** [comment]
@karmi I've been busy with other development for a while, but recently had to reimport this table and encountered the issue again.

As an update to the above, running the following command from the console works as expected, WITH paging:

Region.order('id').import

Whereas "Region.import" doesn't.

Is it possible there was a regression reversing the "default sort order by id" issue fix?

**Comment by scotthelm** [comment]
@zunger I have experienced this as well.  I'm using your workaound for a large index import from postgres.

**Comment by alan** [comment]
I also found this bug. I have no `will_paginate` in my Gemfile so I don't think it has any effect.

**Comment by karmi** [comment]
OK, I'm afraid this slipped through cracks. In order to be on the same page, could you all please generate a fresh Rails app with Tire support:

```
rails new searchapp -m https://raw.github.com/karmi/tire/master/examples/rails-application-template.rb
```

Then add this to your `db/seeds.rb` file:

``` ruby
puts "Creating 10,000 articles:"
(1..10_000).each_with_index do |title, i|
  Article.create :title => "Title #{title}", :content => 'Lorem', :published_on => i.days.ago.utc
  print '.'
end
```

Next, run:

```
rake db:drop
rake db:migrate
rake db:seed
```

And then import them with the Rake task:

```
rake environment tire:import CLASS='Article' FORCE=1
```

In my case, all 10,000 records are imported:

```
curl http://localhost:9200/articles/_count
```

Based on the outcome in your case, we can start debugging that.

**Comment by karmi** [comment]
I would like to solve this issue. When you have time, try the steps outlined above, and we can re-open the issue.

**Comment by alan** [comment]
I'll take a look at reproducing it with a new Rails app, it's on my list of things to look at so hopefully I'll get around to do it in the next few days.
