### ISSUE TITLE
Paginating with a block query

### ISSUE THREAD

**Issue by kbaum** [karmi/retire#41]
Trying to paginate over the results of this query:

https://gist.github.com/a62d41aec655fa790afb

But when i increment the page, the same 10 documents are returned.  Looking at the code for search, it does not look like page and per_page are considered when a block is passed.  

https://gist.github.com/72c85a0fac25798db07d

Am i missing something?  Is there a better way to iterate over results of a query?

Thx!

**Comment by karmi** [comment]
Hi,

the "will_paginate" style of pagination with `:page`, `:per_page` is only supported in the "parameter" style of searches, see: https://github.com/karmi/tire/blob/4c97d0e40f6f0e4da469fd1b6ffe4f6aa8b539d6/test/integration/active_record_searchable_test.rb#L92.

For block searches, you have to specify paging yourself inside the block, see:

https://github.com/karmi/tire/blob/4c97d0e40f6f0e4da469fd1b6ffe4f6aa8b539d6/test/integration/active_record_searchable_test.rb#L150-155

**Comment by kbaum** [comment]
Ok.  Thx!

**Comment by aaronchi** [comment]
how about a page helper for the block syntax?
