### ISSUE TITLE
Searching for string using both fuzzy and boolean terms

### ISSUE THREAD

**Issue by rbeene** [karmi/retire#410]
Karmi -  I am attempting to use a fuzzy search in conjunction with a boolean must search. For example, I may search for a particular first name, last name and zip code. I would like zip code to be a boolean must search while first and last name will be fuzzy. However, when attempting to do a search in the following manner, the last search criteria stomps on the previous. 

``` ruby
search = Tire::Search::Search.new('members')
search.query {|search| search.string search_criteria[:query], default_operator: "OR"} unless search_criteria[:query].blank?
search.query {|search| search.boolean{|boolean| boolean.must{string search_criteria[:boolean]}}} unless search_criteria[:boolean].blank?
# search_criteria[:query] and search_criteria[:boolean] are both strings in the format of field_name:searched_value
```

After the first search criteria is added the object appears as such:

``` ruby
 #<Tire::Search::Search:0x007f7fc0b23a58
 @indices=["members"],
 @options={},
 @path="/members/_search",
 @query=
  #<Tire::Search::Query:0x007f7fc23e6ea0
   @value={:query_string=>{:query=>"_all:Jerell~", :default_operator=>"OR"}}>,
 @types=[]>
```

After the second, it appears below.

``` ruby
#<Tire::Search::Search:0x007fea8e6b5ca8
 @indices=["members"],
 @options={},
 @path="/members/_search",
 @query=
  #<Tire::Search::Query:0x007fea8e6b4d08
   @boolean=
    #<Tire::Search::BooleanQuery:0x007fea8e6b48f8
     @options={},
     @value={:must=>[{:query_string=>{:query=>"zip_code:76065"}}]}>,
   @value={:bool=>{:must=>[{:query_string=>{:query=>"zip_code:76065"}}]}}>,
 @types=[]>
```

After seeing the first query was being stomped, I looked at search.rb in the gem and altered the search instance method query. It should be noted that the query that only retained the boolean search criteria worked as one would expect.

``` ruby
  def query(&block)
        @query||= Query.new #don't stomp existing queries
        block.arity < 1 ? @query.instance_eval(&block) : block.call(@query)
        self
   end
```

The result with this adjustment is the following:

``` ruby
#<Tire::Search::Search:0x007f7fc0b23a58
 @indices=["members"],
 @options={},
 @path="/members/_search",
 @query=
  #<Tire::Search::Query:0x007f7fc23e6ea0
   @boolean=
    #<Tire::Search::BooleanQuery:0x007f7fc0eb3f88
     @options={},
     @value={:must=>[{:query_string=>{:query=>"zip_code:76065"}}]}>,
   @value=
    {:query_string=>{:query=>"_all:Jerell~", :default_operator=>"OR"},
     :bool=>{:must=>[{:query_string=>{:query=>"zip_code:76065"}}]}}>,
 @types=[]>
```

Unfortunately, this query renders an error when results are retrieved:

``` ruby
 nested: SearchParseException[[members][4]: query[_all:Jerell~0.5],from[-1],size[-1]: Parse Failure [No parser for element [must]]]; }]","status":500}
```

I looked at the above solution, but in both cases, it results in a boolean must search. Also, I attempted to use boolean.should and didn't get the results I expected. 

Any pointers?

**Comment by mszyndel** [comment]
@rbeene you should simply put each of your conditions in boolean query must block. Is that solution not working for you? (and why?)

**Comment by karmi** [comment]
Allright, several remarks to your issue.

First, you're right that the `query` method does "stomp" on the previous calls, breaking chaining. This should be fixed, but does not prevent the behaviour you're after.

Second, @hajder is right that the correct approch would be to build your query **inside the `boolean`** block. To slightly adapt your example, this would probably get you where you wanna go:

``` ruby
require 'tire'
require 'active_support/core_ext/string'

Tire.index 'members' do
  delete
  create

  store type: 'member', first_name: 'John', last_name: 'Smith',       zip: 40202
  store type: 'member', first_name: 'Mary', last_name: 'Smithsonian', zip: 40303
  refresh
end

search_criteria = {}
search_criteria[:names] = "Smith~"
search_criteria[:zip]   = "zip:40202"

s = Tire.search 'members' do |search|
 search.query do |query|
   query.boolean do |b|
     b.must { string search_criteria[:names] } unless search_criteria[:names].blank?
     b.must { string search_criteria[:zip] }   unless search_criteria[:zip].blank?
   end
 end 
end

p s.results.map(&:last_name)
# => ["Smith"]
```

Third, notice how we might clean up  — and, moreover, _decompose_ the query definition –, when we define the boolean queries as `lambda`s, sometimes overlooked, yet very powerful feature of _Tire_:

``` ruby
# This is our Rails's params
#
params = {}
params[:name] = "Smith"
params[:zip]  = "40202"

# Define query for names
#
name_query = lambda do |b|
  b.must { string "#{params[:name]}~" }
end

# Define queries for ZIPs
#
zip_query = lambda do |b|
  b.must { term :zip, params[:zip] }
end

# Combine our queries
#
s = Tire.search 'members' do |search|
  search.query do |query|
    query.boolean &name_query unless params[:name].blank?
    query.boolean &zip_query  unless params[:zip].blank?
  end
end

p s.results.map(&:last_name)
# => ["Smith"]
```

So, the sum up: you started on a right track with multiple calls for “something”, but that something should be the `boolean` method, not the `query` method.

Is this sufficient for you to solve the issue you had?

**Comment by karmi** [comment]
@rbeene Ping, any luck?

**Comment by rbeene** [comment]
I ended up doing the following.

```

    search          = Tire::Search::Search.new(self.name.downcase.pluralize)
    search.query {|search| search.boolean{|boolean| boolean.should{string search_criteria[:query], fuzziness: 0.5, default_operator: "OR"}}} unless search_criteria[:query].blank?
    search.query {|search| search.boolean{|boolean| boolean.must{string search_criteria[:boolean]}}} unless search_criteria[:boolean].blank?
    search.results
```

I did however need (I believe) to make a small change in the tire gem in search.rb.

```
def query(&block)
  @query ||= Query.new
   block.arity < 1 ? @query.instance_eval(&block) : block.call(@query)
   self
end
```

I believe when I didn't have this in place, the second piece stomped on the first.

Thoughts?

**Comment by karmi** [comment]
@rbeene Yes. I'm not entirely sure you've catched my reply [above](https://github.com/karmi/tire/issues/410#issuecomment-7250998)? :)

**Comment by karmi** [comment]
@rbeene Ping, any news?

**Comment by karmi** [comment]
@rbeene Closing the issue for now. I hope your problem was solved and you just forget to close it yourself.

**Comment by rbeene** [comment]
Karmi - sorry for the extreme delay in reply. You were right. The problem was resolved after following your example. Thanks for all your hard work.

**Comment by karmi** [comment]
No worries -- good it's working.
