### ISSUE TITLE
Highlighting breaks when including associations

### ISSUE THREAD

**Issue by ghost** [karmi/retire#413]
Hi,

I'm having some trouble with highlighting. I started a thread here (https://groups.google.com/forum/?hl=en&fromgroups#!topic/elasticsearch/a_6SdQV1QPc), but haven't gotten much feedback, so I'm hoping you might know.
### Mapping

``` Ruby
      mapping do
        indexes :id, index: :not_analyzed
        indexes :first_name
        indexes :last_name
        indexes :headline
        indexes :jobs, type: "object"
        indexes :educations, type: "object"
        indexes :skills
        indexes :linkedin_summary
        indexes :linkedin_groups
        indexes :linkedin_certifications

        indexes :fb_user_id, index: :not_analyzed, include_in_all: false
        indexes :fb_connections, index: :not_analyzed, include_in_all: false
        indexes :linkedin_id, index: :not_analyzed, include_in_all: false
        indexes :linkedin_connections, index: :not_analyzed, include_in_all: false

        indexes :is_active, type: "boolean", include_in_all: false
        indexes :is_email_confirmed, type: "boolean", include_in_all: false
      end
```
### Query

``` Ruby
    User.search do
      query do
        filtered do
          query do
            string "#{query}"
          end

        end
      end
      fields :id
      highlight(
        fields: {
          "_all" => {},
          "jobs.industry" => {},
          "jobs.employer" => {},
          "jobs.position" => {},
          "educations.school" => {},
          "educations.major" => {},
          :skills => {},
          :headline => {},
        },
        pre_tags: ['<span class="highlight">'],
        post_tags: ['</span>']
      )
      size 10
```
### Relationships

``` Ruby
class User < ActitveRecord::Base
    has_many :educations
   has_many :jobs
end

class Education < ActitveRecord::Base
    belongs_to :user
end

class Job < ActitveRecord::Base
    belongs_to :user
end
```

Highlighting works fine with this base setup. But without overriding `to_json`, I don't get the `:educations` and `:jobs` relationship indexed. So I added the following to `User.rb`:

``` Ruby
  def to_indexed_json
    to_json(include: [:educations, :jobs])
  end
```

Using the Head plugin, I'm able to query the `:educations` and `:jobs` relatinoships, however my original query with highlighting, now longer shows any highlighting.

Any idea why including the associations breaks highlighting for me?

**Comment by karmi** [comment]
Hi, this sounds strange.

First, when overriding `to_indexed_json`, you're effectively taking care of the serialization yourself, so do check that the JSON makes sense (eg. compare to JSON without the override).

Second, based on the Google Group discussion, you need to set `include_root_in_json = false`.

Third, how is the highlighting “broken” in fact? As in no highlighting is returned, for any field?

The bad news is that this sort of complex object relationships are hard to debug -- I'd need effectively to recreate the full picture of your app to be able to run it...

**Comment by ghost** [comment]
You're right. include_root_in_json was it. Thanks for the feedback.
