### ISSUE TITLE
A question about mapping

### ISSUE THREAD

**Issue by timuckun** [karmi/retire#418]
I have a model and if I leave out the mapping parameter tire does a great job of creating the index with the proper types. If I specify the mapping like this.

``` ruby
tire do
  mapping do
    indexes :id, :type => 'string', :index => :not_analyzed
    # ...
 end
end
```

it only indexes the ID field. 

It would be very handy to have Tire configure the mapping automatically and then be able to add and remove from that. Something like.

``` ruby
mapping.add ....
mapping.remove ....
mapping.change ...
```

So if I wanted to set the ID to be non analyzed I could do
mapping.change :id, :type => 'string', :index => :not_analyzed

I can also see this use case.

``` ruby
mapping.remove :driver_id
mapping.add :driver, :type => "string"
```

The driver would be a method.

Some tables have a lot of fields and mostly you want them indexed in the default way but you may not want to

**Comment by karmi** [comment]
Hi, there are several issues going on with your question.

First, this [answer at _StackOverflow_](http://stackoverflow.com/questions/11672072/elasticsearch-tire-using-mapping-and-to-indexed-json/11700251#11700251) gives a good overview of decisions behind the `mapping`/`to_indexed_json` method combo.

Second, I don't feel that adding _more_ API to the mapping DSL would help here -- as previously stated, let's not pretend the library will solve _every_ problem for you. It tries _very_ hard to provide convenient starting point and sane API to work with, but it can't anticipate every need.

(As a side note: what you're after _is_ in fact achievable in _Tire_. Just rip open the class and access the `@mapping` variable and do whatever you feel is right.)

Lastly, and more importantly, the `mapping` method serves one purpose only: to express mapping definitions.

The JSON serialization is a completely different thing. You can start with the provided defaults, and once you gain confidence and need more advanced stuff, you're free to define whatever JSON serialization makes sense for your documents with a custom `to_indexed_json` method.

For instance, ActiveRecord's `to_json` provides you with a [_very_ rich API](http://apidock.com/rails/ActiveRecord/Serialization/to_json) to express complex object serialization rules with all the `:except` and `:only` and `:methods` options, which take a simple Array as value.

**Comment by karmi** [comment]
@timuckun Ping, is the comment helpful?

**Comment by timuckun** [comment]
Yes and no. to_index_json works great for most uses but the mapping still has to take place in one shot. I was hoping I could incrementally define the mapping so that base mappings could be set in a module that is mixed in (id etc) and others could be added by the class.

For now I have decided to avoid manual mapping and just rely on to_index_json.

**Comment by karmi** [comment]
> the mapping still has to take place in one shot.

Yes, absolutely, which is inline with how elasticsearch works.

> I was hoping I could incrementally define the mapping (...)

I'd be quite scared about “incremental” mapping scattered around in many files, somehow joined to form a mapping for the index...

> For now I have decided to avoid manual mapping and just rely on to_index_json.

Again, I don't understand that -- you have to use both to effectively control _what_ and _how_ gets into your index.

Closing this issue or?

**Comment by timuckun** [comment]
I'll close the issue. Is there a mailing list? Seems like a better forum for these types of conversations.

**Comment by karmi** [comment]
There isn't -- issues are perfectly fine for a discussion like this. For more conceptual questions, there's also StackOverflow.
