### ISSUE TITLE
how to search through terms with whitespaces?

### ISSUE THREAD

**Issue by dementrock** [karmi/retire#424]
I am using mongoid and I have a model with a tag field. If I have a tag called "hello world", then searching "hello" and "world" both return the result, but "hello world" doesn't. I've already set the index to not_analyzed but it's still not working. What should I do?

Here's a piece of code to test: http://pastebin.com/n1rUtK3e

**Comment by ifesdjeen** [comment]
Try keyword analyzer:

``` ruby
{ :type => 'string', :analyzer => 'keyword' }
```

It will work.
Btw, we used it exactly for tags.

**Comment by dementrock** [comment]
Thank you! It seems that I set up indexing the wrong way before. It works now.

**Comment by karmi** [comment]
@dementrock Why duplicate the question at Github and StackOverflow (http://stackoverflow.com/questions/11822019/using-elasticsearch-to-filter-through-tags-with-whitespace)?

**Comment by ifesdjeen** [comment]
@karmi probably he really needed an answer urgently :)
