### ISSUE TITLE
UTF-8 IDs break tire

### ISSUE THREAD

**Issue by JamesHarrison** [karmi/retire#427]
TIre doesn't URI escape UTF-8 IDs. For databases that use UTF-8 identifiers (for instance, a tag äccentedtag could have a DB ID of simply äccentedtag) this is awkward and yields the following error:

bad URI(is not URI?): http://localhost:9200/test_tags/tag/äccentedtag

Identifiers should be escaped within tire to ensure that ElasticSearch gets a well-formed request.

**Comment by karmi** [comment]
Hi, sounds probable -- is it possible to add a failing unit & integration test for the behavior?

**Comment by JamesHarrison** [comment]
Had a look but I'm unsure where to put it/how to structure it - not quite that sorted yet with regards to getting familiar with tire's codebase!

**Comment by karmi** [comment]
No worries, I will look at it myself; basically the ID needs to be URL-escaped in [`Index#store`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L77) and then deserialized in proper places (retrieve, search, etc.)

**Comment by karmi** [comment]
Not enough time to solve this particular issue right now, I'm afraid. Will leave it open.

The workaround for the type being is:

``` ruby
require 'tire'

Tire.index 'testutf' do
  delete
  create

  store id: Tire::Utils.escape('äccentedtag'), content: 'UTF'
end
```

**Comment by karmi** [comment]
Closed, at last...
