### ISSUE TITLE
max_score

### ISSUE THREAD

**Issue by mahemoff** [karmi/retire#428]
Is there any way to access max_score? It's not defined in https://github.com/karmi/tire/blob/master/lib/tire/results/collection.rb.

I can work around it using results.map(&:_score).max, but would like to access the result directly if possible.

**Comment by karmi** [comment]
Hi, yeah, that seems to be missing. Normally the `max_score` would be the score of the first result item?

**Comment by mahemoff** [comment]
Good point, depends on sort order of course, but should normally be first result by default.

(Thanks for a great library and great support btw.)

**Comment by karmi** [comment]
Normally, when sorting, the `_score` is not accessible, but I forgot you can force the `_score` to be computed anyway. I'll look into this, that'll be an easy change.

Thanks for the kind words!!

**Comment by demetrios** [comment]
Any news on this issue? I have a need to access max_score as well...  this kluge seems to work, for time being: 

Document.search({query: "apple"}).instance_variable_get(:@response)["hits"]["max_score"]

**Comment by karmi** [comment]
Done, should work on master.
