### ISSUE TITLE
update_index being called even if the Tire::Model::Callbacks are not included

### ISSUE THREAD

**Issue by balaji-chronus** [karmi/retire#429]
I have an index with a simple mapping

include Tire::Model::Search
index_name SOME_INDEX_NAME

mapping do
    indexes :id, :type => 'integer', :index => :not_analyzed
    indexes :full_name, :type => 'string', :analyzer => "keyword"
  end

I face an error where the update_index callback is being called with improper arguments. This continues to happen even if i don't include the Tire::Model:Callbacks. Why is the call back being invoked even if i am not subscribed for it ? Attached the backtrace.

just to cover all the facts, there is another Thinking Sphinx Index in the model. When i debugged i found that in tire/model/search.rb the update_index doesn't accept any args while in the same file line 290 calls the methods with args. Attached the stacktrace,

ArgumentError: wrong number of arguments (3 for 0)

[GEM_ROOT]/gems/tire-0.4.2/lib/tire/model/search.rb:290:in `update_index'
[GEM_ROOT]/gems/tire-0.4.2/lib/tire/model/search.rb:290:in`**send**'
[GEM_ROOT]/gems/tire-0.4.2/lib/tire/model/search.rb:290:in `update_index'
[GEM_ROOT]/gems/thinking-sphinx-2.0.10/lib/thinking_sphinx/active_record/attribute_updates.rb:23:in`update_attribute_values'
[GEM_ROOT]/gems/thinking-sphinx-2.0.10/lib/thinking_sphinx/active_record/attribute_updates.rb:16:in `each'
[GEM_ROOT]/gems/thinking-sphinx-2.0.10/lib/thinking_sphinx/active_record/attribute_updates.rb:16:in`update_attribute_values'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:472:in `_run__1147672153__save__4__callbacks'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in`send'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in`_run_save_callbacks'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `send'
[GEM_ROOT]/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in`run_callbacks'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/persistence.rb:104:in`save!'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/validations.rb:56:in `save!'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:33:in`save!'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in `save!'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in`with_transaction_returning_status'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in`transaction_without_trace_ActiveRecord_self_name_transaction'
[GEM_ROOT]/gems/newrelic_rpm-3.4.0.1/lib/new_relic/agent/method_tracer.rb:491:in `transaction'
[GEM_ROOT]/gems/newrelic_rpm-3.4.0.1/lib/new_relic/agent/method_tracer.rb:242:in`trace_execution_scoped'
[GEM_ROOT]/gems/newrelic_rpm-3.4.0.1/lib/new_relic/agent/method_tracer.rb:486:in `transaction'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in`with_transaction_returning_status'
[GEM_ROOT]/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in `save!'
lib/salesforce_scrapper/contacts.rb:99:in`populate_contact'
lib/salesforce_scrapper/contacts.rb:18:in `scrap'
lib/salesforce_scrapper/contacts.rb:17:in`each'
lib/salesforce_scrapper/contacts.rb:17:in `scrap'

**Comment by karmi** [comment]
I wonder if Tire's `update_index` method clashes with ThinkingSphinx? I see the trace begins in `thinking_sphinx/active_record/attribute_updates.rb`? Try to include Tire _after_ ThinkingSphinx.

**Comment by karmi** [comment]
Any news on this? Closing the issue for now, please try to get back to the issues you have submitted.
