### ISSUE TITLE
possible remove single documents from index?

### ISSUE THREAD

**Issue by fwoeck** [karmi/retire#43]
Hi, is there an option to destroy single documents, that were indexed before?
--Frank

**Comment by karmi** [comment]
Hi, yeah, definitely, just call `Tire.index('myindex').remove('docID')`, see integration tests: https://github.com/karmi/tire/blob/master/test/integration/index_store_test.rb#L38

**Comment by fwoeck** [comment]
Ahh great, thank you!

**Comment by fwoeck** [comment]
Hallo, I tried it and it doesn't work in my situation - maybe because of stringy ids? 
We have a document d with an _id that was stored as in the index:

``` ruby
ruby-1.9.2-p180 :011 > d._id.to_s
 => "4e033331e8e68720c0006797" 
ruby-1.9.2-p180 :012 > Tire.search(Mongoid.database.name) { query { string '*' } }.results
 => #<Tire::Results::Collection:0x00000101baeb20 @options={}, @time=1, @total=1, @results=[<Item id: "4e033331e8e68720c0006797", _score: 1.0, _type: "dokument", _index: "livesein_ng_devel", _version: nil, sort: nil, highlight: nil>], facetsnil 
ruby-1.9.2-p180 :013 > Tire.index(Mongoid.database.name).remove(d._id.to_s)
 => nil 
ruby-1.9.2-p180 :014 > Tire.search(Mongoid.database.name) { query { string '*' } }.results
 => #<Tire::Results::Collection:0x00000101b80d88 @options={}, @time=2, @total=1, @results=[<Item id: "4e033331e8e68720c0006797", _score: 1.0, _type: "dokument", _index: "livesein_ng_devel", _version: nil, sort: nil, highlight: nil>], facetsnil 
```

After the remove it's still there. I'd be grateful for any hints on this!
--Frank

**Comment by fwoeck** [comment]
could it be that it's because remove(*args) assumes :document as type

``` ruby
(document = args.pop; type = :document)
```

whereas my used type is doKument?

**Comment by fwoeck** [comment]
yes, confirmed, when I use 'doCument' as type it works.

**Comment by karmi** [comment]
Ha!, yes, sorry, in your case you have to call `Tire.index('myindex').remove('my-document-type', 'my-document-id')`.

The whole passing of `type` into store/remove stinks a lot, I have to really make it infer the type from the document itself, there's a TODO for that. I'll submit an issue for this.

**Comment by ike-bloomfire** [comment]
This still doesn't work btw ie this syntax

```
 Tire.index('myindex').remove('docID')
```

PS: is it possible to make the syntax for this match the update_index syntax so you could just do something like ...

```
 post.tire.remove
```

... for example?

**Comment by reiz** [comment]
Thanks. That worked for me.
