### ISSUE TITLE
Shouldn't Collection.to_ary() return an array?

### ISSUE THREAD

**Issue by mahemoff** [karmi/retire#432]
Slightly pedantic, but shouldn't to_ary() itself be returning Array or a subclass of Array? (to_a() does the job of converting to array, but I wasn't expecting to_ary() to return self.)

**Comment by karmi** [comment]
Hmm, good question. Not sure myself :) It just returns the collection, which is Enumerable-based/compatible, basically just because Rails calls `to_ary` in views, as far as I remember. It could probably return the underlying `@results`. Fancy a test case / run withing Rails?

**Comment by karmi** [comment]
The [ActionView::PartialRenderer#collection](https://github.com/rails/rails/blob/master/actionpack/lib/action_view/renderer/partial_renderer.rb) calls `to_ary` when you `render :collection => @results`. I think it's safer here to return the wrapper, not the raw results array in case we need to decorate that. Also, don't have time to test it extensively in real-world apps.
