### ISSUE TITLE
Can't use helpers such as dom_id, div_for

### ISSUE THREAD

**Issue by joemsak** [karmi/retire#433]
Hi, don't know what I'm doing wrong, but I can't use dom_id or div_for

Here's an example with div_for

``` ruby

  def self.search(query)
    results = []

    [Page,ResourceGuide,Story,BlogPost].each do |model|
      results << model.search(query, :load => true)
    end if query.present?

    results
  end
```

Yes, @results below is == to the returned above

``` erb
    <% @results.each do |result| %>
      <% div_for result, :class => 'result clearfix' do %>
        <h3><%= link_to result.title.gsub(/(#{params[:query]})/i,'<strong>\1</strong>').html_safe, result_url(result) %></h3>
        <p><%= truncate(strip_tags(result.body).try(:gsub, /(#{params[:query]})/i,'<strong>\1</strong>'), :length => 300, :preserve_html_tags => true) %></p>
      <% end %>
    <% end %>
```

Error:

undefined method `model_name' for Tire::Results::Collection:Class

**Comment by joemsak** [comment]
Haha please never mind the crap code i wrote 2 years ago (i am replacing acts as indexed with bonsai / tire)

**Comment by joemsak** [comment]
The issue here was not fixed, this issue shouldn't be closed. Two comments appear to be missing from the history, as well.

**Comment by joemsak** [comment]
My comment was just me being embarrassed about my code example

**Comment by karmi** [comment]
Try to generate a fresh application:

```
rails new searchapp -m https://raw.github.com/karmi/tire/master/examples/rails-application-template.rb
```

and see if/how it works for you, so we are on the same page.

Since you're using `load: true`, you receive back instances of your models. Hard to say what's wrong without a gist/pastie/etc of your model and the line which triggers the error from backtrace.

**Comment by joemsak** [comment]
Gotcha, thanks, I will try it out!
