### ISSUE TITLE
Tire::Results::Item cannot load activemodel model

### ISSUE THREAD

**Issue by crazed** [karmi/retire#435]
In my case, I've got a model inheriting from ActiveRecord::Base (3.2.7) inside of a Sinatra application. I've found that when you try to use the load method, I get the following error:

```
>> Model.search('foo:bar').first.load
NoMethodError: undefined method `find' for Tire::Results::Item:Class
        from /Library/Ruby/Gems/1.8/gems/tire-0.4.2/lib/tire/model/search.rb:198:in `load'
        from (irb):26
```

Looking at [search.rb](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L199-201), it appears .load just tries to use self.class to get the model's class. In this case it's returning <code>Tire::Results::Item</code> rather than <code>Model</code>. Below is an example of my model definition:

```
class BaseModel < ActiveRecord::Base
    self.abstract_class = true
end

class Model < BaseModel
    include Tire::Model::Search
    include Tire::Model::Callbacks
end
```

**Comment by karmi** [comment]
In that case, it's probably due to the subclassing...

**Comment by crazed** [comment]
I removed the subclassing and received the same result

**Comment by karmi** [comment]
Argh, I know why that is... The “masquerading” `Item` does is only performed within Rails, so `@search.results.first.load` works only when a `Rails` constant is defined...

``` ruby
require 'tire'
require 'active_record'

Tire.index('articles') { delete }

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Migration.verbose = false
ActiveRecord::Schema.define(version: 1) do
  create_table(:articles) { |t| t.string :title }
end


class Article < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  tire do
    mapping do
      indexes :title,   type: 'string', analyzer: 'snowball'
    end
  end
end

Rails = nil

Article.tire.create_elasticsearch_index

p Article.create title: 'Testing...'
Article.tire.index.refresh

results = Article.tire.search('title:test').results

p results.first
p results.first.load(nil)
```

Not nice...
