### ISSUE TITLE
10 models are working fine and just 1 can Index but can't search

### ISSUE THREAD

**Issue by andrelip** [karmi/retire#436]
I have done a similar approach as showed at Railscasts. Now a strange thing happens, the same code I have used and worked fine in above 10 models, isn't working for my Document model. When I ran "rake environment tire:import CLASS="Document" FORCE=true" it load 100% of the items without errors. Now when I search it always display empty data. I tryed delete all my mapping and just work with the includes + default search method and still with zero items.

http://localhost:9200/documents/_search? display the items.

What could be happening?

**Comment by andrelip** [comment]
I deleted everything and created a new item without carrierwave integration. It doesn't work.

I have discovered something: Document.tire.search('_').total_count results => 0 
but doing...
s = Tire.search 'documents' do
      query do
        string '_'
      end

then s.results gives me:
 => #<Tire::Results::Collection:0xa3b1b40 @response={"took"=>4, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>1, "max_score"=>1.0, "hits"=>[{"_index"=>"documents", "_type"=>"Declaração de IR", "_id"=>"1", "_score"=>1.0, "_source"=>{"id"=>1}}]}}, @options={}, @time=4, @total=1, @facets=nil, @wrapper=Tire::Results::Item> 

What could be happening?

**Comment by karmi** [comment]
In the first case, you're sending an empty query (as far as I can see in the incorrectly formatted code). Should be the same in newer ES versions.
