### ISSUE TITLE
as_json not working with mongoid (to_json does)

### ISSUE THREAD

**Issue by Datesta** [karmi/retire#438]
Just trying out Elasticsearch and Tire, however, i stumbled into a initial hurdle. Getting a "org.elasticsearch.ElasticSearchParseException: Failed to derive xcontent from ...."-error when creating a new entry. Changing my to_indexed_json to use self.to_json, however, seems to resolve the problem. This is of course not a real "fix" since i don't know whether this will ruin stuff later or why i have this problem.

A compacted model project.rb:
class Project
include Mongoid::Document
field :t, as: :title, type: String
include Tire::Model::Search
include Tire::Model::Callbacks

  def to_indexed_json
    self.as_json
  end

end

Therefore: Is this fix viable?
Gems: Rails 3.2.8, ruby 1.9.3, Mongoid 3.0.4, Tire 0.4.2

**Comment by karmi** [comment]
I believe you have to set `include_root_in_json = false` -- see README.

**Comment by Datesta** [comment]
It's not working and it doesn't seems like it's a include_root_in_json problem. In rails console: 
Project.last.to_json
 => "{\"_id\":\"503627b6d672600a0b000006\",\"c\":null,\"ci\":null,\"created_at\":\"2012-08-23T12:53:10Z\",\"deleted_at\":null,\"f\":null,\"fa\":null,\"l\":null,\"t\":\"herp22\",\"ta\":null,\"updated_at\":\"2012-08-23T12:53:10Z\",\"user_id\":null,\"votes\":{\"up\":[],\"down\":[],\"up_count\":0,\"down_count\":0,\"count\":0,\"point\":0}}" 

And:
Project.last.as_json
 => {"_id"=>"503627b6d672600a0b000006", "c"=>nil, "ci"=>nil, "created_at"=>Thu, 23 Aug 2012 12:53:10 UTC +00:00, "deleted_at"=>nil, "f"=>nil, "fa"=>nil, "l"=>nil, "t"=>"herp22", "ta"=>nil, "updated_at"=>Thu, 23 Aug 2012 12:53:10 UTC +00:00, "user_id"=>nil, "votes"=>{"up"=>[], "down"=>[], "up_count"=>0, "down_count"=>0, "count"=>0, "point"=>0}} 

Seems like there is something going on with the formatting that is satisfying Elasticsearch with to_json and not as_json.

**Comment by karmi** [comment]
True, the README is probably incorrect for Mongoid.

**Comment by Datesta** [comment]
So, are there any downsides to use to_json? Will this break something later down the chain?

**Comment by canadaduane** [comment]
I think it's safe to use to_json. See http://stackoverflow.com/questions/11275714/haml-rendering-as-json-with-hash-rocket-instead-of-colon

**Comment by Datesta** [comment]
Thanks @canadaduane, it seems to work so i'm just gonna roll with this

**Comment by aledalgrande** [comment]
Confirmed this with MongoMapper as well: only _to_json_ works. I made a pull request for the README.
