### ISSUE TITLE
missing / patchy data - creative advice appreciated

### ISSUE THREAD

**Issue by finalarena** [karmi/retire#441]
Hello. I'm dealing with a data source with patchy data coverage, so when i order on fields such as :price,  I get lots of empty results at the top as empty < 0.

I'm wondering:
1. how I can push these to the end using Tire. With ES directly i would use {"missing" : "_last"} on the sort option
2. I'd potentially like to do something funky and and penalize the _score for items missing data. So assume that i have fields of :price, :colour, and :size I'd like to boost documents containing all 3 values more than those with 2. I'm just looking for some creative advice on achieving that. At the moment, I'm adding a new field called :completeness that contains a pre-generated value of 0,1/3, 2/3, 1 etc.
3. In some cases, where an item has a missing :price, I'd like to omit it altogether. If there support for "exists" : { "field" : "price" } within booleans? such as `boolean.must { :_exist , :price }`

Thanks so much!

**Comment by finalarena** [comment]
In case anybody finds it useful, I found the way to achieve 1)

``` ruby

required_sorts = [{field: "title.exact", order: :desc}, {field: :popularity, order: :desc}]

query.sort do |s|
  required_sorts.each do |one_sort|
    options = {"order"=>one_sort[:order]}
    options.merge!({"missing" => "_last"}) if field_is_numeric?(one_sort[:field])
    s.by one_sort[:field], options
  end
end
```
- you can only use "missing" => "_last" on numeric fields (and only sort on :not_analyzed fields / sub_fields).
- in my use case I'm pushing all missing to the end

**Comment by karmi** [comment]
Maybe [StackOverflow](http://stackoverflow.com/tags/tire) is a better forum for questions like these...
