### ISSUE TITLE
Filter by `published == true` (Boolean)

### ISSUE THREAD

**Issue by mrrooijen** [karmi/retire#444]
Hi,

I'm trying to figure out how I can filter queries based on whether a certain field is `true` or `false`.

``` ruby
class Article
  include Mongoid::Document
  include Tire::Model::Search

  field :published, type: Boolean, default: false

  mapping do
    indexes :published, type: "boolean"
  end
end
```

``` ruby
Article.search do
  query do
    boolean do
      must { string "some keyword", default_operator: "AND" }
      must { string "published:true" }
      # must { string "published:T" }
      # must { boolean :published, true }
    end
  end
end
```

I think you can guess what I'm trying to do here ( `must { string "published:true" }` ). I tried a few other things but I can't figure it out. I'm trying to filter out anything that isn't `published`.

Any help much appreciated!

**Comment by mrrooijen** [comment]
After a good night rest I wake up to this:

``` ruby
after_save do
  update_index if published?
end
```

Seeing as in my tests I initially have `published` true, but then set it to `false` and expect it not to be there, it is. This is because it never updates the index when it isn't published. This is what I ended up doing, for anyone that might have this questions in the future:

``` ruby
class Article
  include Mongoid::Document
  include Tire::Model::Search

  field :published, type: Boolean, default: false

  mapping do
    indexes :published, type: "boolean"
  end
end
```

``` ruby
Article.search do
  query do
    boolean do
      must { string params[:query] }
      must { term :published, true }
    end
  end
end
```

Passing specs, good times.

Closing issue.

**Comment by amencarini** [comment]
Just to chime in, I've had a similar issue, although I'm using ActiveRecord: in my app there a boolean flag that's false by default in the database; searching with a term would be alright on development and production, but somehow failing in test environment filtering by that boolean.
Adding an `after_create` callback with an `update_attributes` on the model made the problem go away.
