### ISSUE TITLE
Production deployment: best practices ?

### ISSUE THREAD

**Issue by m4tm4t** [karmi/retire#447]
I just switched from thinking sphinx recently.

After a lot of search, I found nothing about deployment in production.

I'm using http://nadarei.co/mina/ to deploy my app.
But there is no "magic" like TS for creating/redo/drop index, we need to pass differents args etc...

Here is what I've done to execute tire tasks from Mina:

``` ruby
namespace :tire do
  task :drop do
    %w(actus ga_games).each do |klass|
      ENV['INDEX'] = klass
      task("tire:index:drop").execute
    end
  end

  task :index do
    %w(Ga::Game Actu).each do |klass|
      ENV['CLASS'] = klass
      task("tire:import").execute
    end
  end

  task :reindex do
    # task("tire:drop").execute

    # Drop or force index ?

    # ENV['FORCE'] = true

    task("tire:index").execute
  end
end
```

Advices would really appreciated, thanks !

**Comment by m4tm4t** [comment]
nobody deploy with tools in production ?!

**Comment by karmi** [comment]
@foohey I don't understand your question at all, I'm afraid. Could you explain _what_ are you trying to do?

**Comment by m4tm4t** [comment]
I'm trying to deploy in production as most DRY way.
So above, this is just a simple rake task that is called from Mina.

That work, yeah. My question is: This is a best practice ?
Because there is no docs/article on Tire for production environment,I ask the question.

**Comment by karmi** [comment]
> Because there is no docs/article on Tire for production environment,I ask the question.

What kind of documentation for what kind of problems?
