### ISSUE TITLE
analyzer not working when passing a variable to query

### ISSUE THREAD

**Issue by AlainPilon** [karmi/retire#448]
Given this mapping: 

```
mapping do
  indexes :title,       boost: 10, analyzer: 'snowball'
  indexes :description, boost: 5,  analyzer: 'snowball'
  indexes :community_id
end
```

and this query:

```
  def self.search(query_string)
    tire.search(load: true) do
      query do
        string query_string, default_operator: "AND"
      end
    end
  end
```

if I search for 'girl' it will only find records with girls in the title/description. 

On the other hand, if I replace the string line with this one:

```
      string "title:#{query_string}", default_operator: "AND"
```

and have the same query, it will find records with _girls_ and _girl_. This is not what I would expect.

**Comment by mauricio** [comment]
_if I search for 'girl' it will only find records with girls in the title/description._

"girls" or "girl" ?

What analyzers are configured for the `_all` field?

It would be nice if you posted the full mapping for this type.

**Comment by mereghost** [comment]
You need to either set the analyzer for the query or make it the default one for that index.

**Comment by karmi** [comment]
@AlainPilon Others are right -- in other words, when you're searching with `field:query`, your query is parsed with an analyzer matching the field, and thus stemmed. When you're searching for a `query`, it is parsed with an analyzer for the `_all` field, which by default does not do any stemming.

**Comment by karmi** [comment]
As always, check your mappings, gentlemen, and beware of the magical `_all` field...
