### ISSUE TITLE
Nested `boolean` query

### ISSUE THREAD

**Issue by finalarena** [karmi/retire#455]
Hello. Firstly, thanks for Tire!

Given the mapping below, when a users submits my search form for the keyword "football" and has selected one or both of region="south england" and country="england" for example, I'm struggling to work out with Tire how to generate a query equivalent to `( name:football~0.5 AND (region:south OR country:south) )`

Any help would be much appreciated as I'm sure I'm missing something simple :-p

Currently I'm building up a bool query like (simplified):

``` ruby
 search = tire.search(load: false, page: 1, per_page: 10, explain: true) do | s |
          s.query do | q |
            q.boolean(:minimum_number_should_match => 1) do | b |
                b.must{ string "football~0.5", fields: [:name], default_operator: 'AND', fuzzy_min_sim: 0.5, analyze_wildcard:true, analyzer: :snowball, auto_generate_phrase_queries: true, lenient:true, use_dis_max: true, minimum_should_match: '60%', tie_breaker: 0.2}
                b.should { term "region.exact", param[:region] } if param[:country]
                b.should { term "country.exact", param[:country] } if param[:country]
         end
      end
end
```

This achieves something like what I need for now but is not very extensible (what if I want to add another must and shoulds to make the query something  more like `( name:football~0.5 AND (region:south OR country:south) ) OR (region:south AND country:south)`.

So that I'm really looking for is the correct way to do nested/grouped booleans please :-)

MAPPING in an AR model: http://pastie.org/5078506

**Comment by karmi** [comment]
Hi, not absolutely sure what you're trying to do, but nesting booleans is indeed possible:

``` ruby
require 'tire'

Tire.configure { logger STDOUT }

Tire.index 'games' do
  delete
  create

  store title: 'football', region: 'south' 
  store title: 'football', country: 'south'

  store title: 'baseball', region: 'west'

  refresh
end


s = Tire.search 'games' do

  query do

    boolean do
      must   { string 'title:football' }
      should { boolean {
                 should { term :region,  'south' }
                 should { term :country, 'south' }
               }
             }
    end

  end

end

p s.results.map { |r| "#{r.title} (country: #{r.country}, region: #{r.region})" }

```

Closing the issue for now, feel free to reopen if you have further questions.
