### ISSUE TITLE
Tire #index causing =~ comparison to fail in Rspec

### ISSUE THREAD

**Issue by sirn** [karmi/retire#456]
Since `Tire::Model::Search` alias Tire's class methods to the top-level namespace of the model, this caused Tire's `index` to breaks `match_array` (or `=~`) comparison in RSpec.

MatchArray comparison in RSpec will call `index`. When object on the lefthand side of `should` is an `ActiveRecord::Relation` (such as scope), it will delegate `index` to Tire's `index` instead of Array's `index` causing comparison to fail.

I have been able to reproduce this problem by creating a new Rails 3.2 project with the following model and spec. 

``` ruby
class Book < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessible :title
  scope :titled, where("title IS NOT NULL")
end
```

…and the spec:

``` ruby
require 'spec_helper'

describe Book do
  it "should not raise any error" do
    Book.create(:title => "Blah")
    Book.create(:title => "Asdf")
    Book.titled.should match_array Book.all
  end
end
```

This will fails with:

```
  1) Book should not raise any error
     Failure/Error: Book.titled.should match_array Book.all
     ArgumentError:
       wrong number of arguments (1 for 0)
     # ./spec/models/book_spec.rb:7:in `block (2 levels) in <top (required)>'
```

When `index` is removed from ClassMethod in model:

``` ruby
  class << self
    remove_method :index
  end
```

The test will passed without any problems. This could also be workaround by using `Book.titled.to_a.should =~` but I'm not sure if it is the best solution.

**Comment by karmi** [comment]
Tire tries hard to not overload any existing methods, see https://github.com/karmi/tire/blob/master/test/unit/model_search_test.rb#L777-788

Don't know what we could do better here?

**Comment by sirn** [comment]
Is it possible to make Tire's `index` call `Array#index` if argument is present? It feels somewhat hack-ish, but I suspect this might work.

**Comment by karmi** [comment]
Why? If the method exists, Tire won't overload it. If it does not exist, Tire will happily step in. This is something RSpec must deal with in lots of cases? Ie. what happens when you define a method `index` on your class?

**Comment by sirn** [comment]
The method does not exist in the model because it is delegated to Array by ActiveRecord (from within Rspec context).

``` ruby
Book.titled.method(:index)
#=> #<Method: ActiveRecord::Relation(ActiveRecord::Delegation)#index>
```

But Tire overloading `index` to the model breaks this since it will delegate to the model class instead. Defining `index` in my own class would presumably breaks RSpec too, I guess. The workaround I'm using currently is to manually remove `index` from all models (with `remove_method`).

I'm not really sure how this problem could be fixed. Maybe put a note somewhere? :\

**Comment by karmi** [comment]
Could you try it with defining your own `index` method in the model so we are sure it will break RSpec in the same manner?

If so, yes, putting up a Wiki page would be nice -- the `remove_method` trick is nice.

**Comment by sirn** [comment]
I just tested, it breaks when I manually define `index` too.

``` ruby
class Book < ActiveRecord::Base
  attr_accessible :title
  scope :titled, where("title IS NOT NULL")

  class << self
    def index
      "Blah"
    end
  end
end
```

Same error as including `Tire::Model::Search` to model. I will put up a Wiki page about this later.

**Comment by karmi** [comment]
@sirn Thanks for the testing!! Please close the issue when you put up the Wiki page with the `remove_method` solution...

**Comment by sirn** [comment]
Not sure if this is good enough, but I've posted on at https://github.com/karmi/tire/wiki/Troubleshooting-RSpec-issues

Closing this issue. Thanks!

**Comment by karmi** [comment]
That is cool, thanks!
