### ISSUE TITLE
Using Security Plugin

### ISSUE THREAD

**Issue by azitabh** [karmi/retire#457]
I want some sort of security on my elasticsearch index. I am using asquera(https://github.com/Asquera/elasticsearch-http-basic) plugin for simple http authentication. I am able to connect to the server using command line curl call:

curl -v --user my_username:my_password localhost:9200/index/type/id

Is there a way to make this call(with username-password) using tire? Or, does tire support any other security plugin I can switch to?

**Comment by karmi** [comment]
Just put the credentials into the URL:

```
Tire.configure { url: "http://USERNAME:PASSWORD@example.com" }
```

**Comment by karmi** [comment]
@azitabh Please make sure you close the issue when your problem is solved...

**Comment by azitabh** [comment]
Sorry about that.

**Comment by thbar** [comment]
Thanks, I was looking for that exact information!
