### ISSUE TITLE
How to import index with condition

### ISSUE THREAD

**Issue by frankel** [karmi/retire#458]
I have a model named Article in my Rails 3, and I use `rake environment tire:import CLASS='Article' FORCE=true` to do index. But I only want the articles with field `deleted` equals to `false` be indexed. How can I implement it?

**Comment by karmi** [comment]
Best with something like:  

```
Article.tire.import( Article.scoped(:deleted) )
```

**Comment by frankel** [comment]
Thanks, I will have a try
