### ISSUE TITLE
Default date value for on published_on

### ISSUE THREAD

**Issue by amir20** [karmi/retire#459]
I have been reading the code for how a property default value is defined. It seems like something like:

`property :published_on, type: 'date', default: Date.new`

Would not work because it would cache the default value to now at that time. Is this the correct assumption?

**Comment by karmi** [comment]
Exactly. I've added the ability to define the default value as lambda (see the closing commit):

``` ruby
class MyModel
  include Tire::Model::Persistence

  property :created_at, :default => lambda { Time.now }
end
```

Note though, that the lambda is evaluated when you create the object, not when you access the property.

**Comment by amir20** [comment]
Great! Will try.
