### ISSUE TITLE
:page param in the README doesn't work

### ISSUE THREAD

**Issue by aledalgrande** [karmi/retire#463]
Hi,
I managed to get pagination working by using `size` and `from`, but the README just refers to a `:page` parameter that is passed to `Article.search` and, as I witnessed, is then forwarded to ES.

This parameter though, doesn't have any effect on ES, the results obtained are exactly the same as if :page wasn't passed.

Regards

**Comment by karmi** [comment]
That would be indeed weird -- have a look at integration tests for the feature, https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L179-195

**Comment by aledalgrande** [comment]
I'm using MongoMapper and not ActiveRecord for my model, could that be the source of the problem? All the rest works though: filtering, sorting etc.

**Comment by parmarg** [comment]
I am also using MongoMapper and was finally able to get the pagination working by doing the following

```
query = Tire.search('assets',{:page => page , :per_page=>25, :size=>25, :from=>from})  do
```

Without the :from it did not work, where from is the offset.

**Comment by aledalgrande** [comment]
Yeah my current code is:

``` ruby
MediaChannel.search do
  # ...
  size per_page
  from page
end
```

While initially I tried:

``` ruby
MediaChannel.search :page => page do
  # ...
end
```

Additionally: I've not found word of a `page` parameter in the ES documentation, they just talk about `from` and `size`.

**Comment by raldred** [comment]
Same here, the :page and :per_page options don't exist
It should be :from and :size

**Comment by karmi** [comment]
The `:page` and `:per_page` parameters are sugar provided by _Tire_, since that is how will_paginate-style of pagination works.

Again, please have a look at the test at https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L179-195, run it. Try to model your code based on that.

Closing this for now, feel free to reopen or submit another issue if you indeed encounter a bug. A failing test would be very cool in that case.

**Comment by karmi** [comment]
_UPDATE_: The sugar only works when you're using the “simple” form of search -- as evident from the README. For block searches, use size/from.

**Comment by raldred** [comment]
Ahh yes, good spot. I suppose the ideal is that it's consistant, but at least we know now :) Thanks @karmi

**Comment by aledalgrande** [comment]
@karmi FTW

**Comment by axsuul** [comment]
Curious, why wouldn't this sugar also be available for block searches?

**Comment by karmi** [comment]
@aledalgrande Added integration tests for the feature -- should work the same way for "simple" searches and "block" searches. I wonder if you see the same results because of scoring/ordering issue?

**Comment by jredburn** [comment]
I recently ran into this and it turned out the problem was that I'd assumed that -- like will_paginate -- Tire had a default per_page setting. It appears that if you don't specify a per_page value then page has no effect. Easy to solve, but threw me off for a bit.

**Comment by karmi** [comment]
@jredburn Could you elaborate? The default `per_page` is 10, and `:page` should definitely work with whatever setting?

**Comment by jredburn** [comment]
@karmi I'll write up a failing test later today, but the short version is:

```
results = Relation.search 'label_id:1', :page => 2
results.first.id == "2417"

results = Relation.search 'label_id:1', :page => 2, :per_page => 10
results.first.id == "19713"
```

**Comment by karmi** [comment]
@jredburn Cool, a failing unit/integration test would be very cool.

**Comment by jredburn** [comment]
@karmi Here's a failing test. I'm new to github, so let me know if you prefer this in a different form (e.g. pull request):

```
--- a/test/integration/active_record_searchable_test.rb
+++ b/test/integration/active_record_searchable_test.rb
@@ -212,6 +212,24 @@ module Tire
             assert_nil results.first
           end

+          context "without an explicit per_page" do
+
+            should "find not find missing (second) page" do
+              results = ActiveRecordArticle.search 'test*', :sort => 'title', :page => 2
+              assert_equal 0, results.size
+
+              # WillPaginate
+              #
+              assert_equal 1, results.total_pages
+              assert_equal 2, results.current_page
+              assert_equal 1, results.previous_page
+              assert_equal nil, results.next_page
+
+              assert_nil results.first
+            end
+
+          end            
+
         end

         context "and block searches" do
```

**Comment by jredburn** [comment]
Taking a look at the code, it appears `lib/tire/model/search.rb` only changes `from` if both `page` and `per_page` are set:

```
page     = options.delete(:page)
per_page = options.delete(:per_page)

s.size( per_page.to_i ) if per_page
s.from( page.to_i <= 1 ? 0 : (per_page.to_i * (page.to_i-1)) ) if page && per_page
```

If we change:

```
per_page = options.delete(:per_page)
```

to:

```
per_page = options.delete(:per_page) || 10
```

that solves the problem though I suspect there's a better way to leverage the logic you already have in `lib/tire/model/pagination.rb`.

**Comment by karmi** [comment]
Good catch!, that's the spot. I don't think there's a nice, clean way to get the `per_page` from the pagination module, but that's easily fixable by refactoring the magic number into a constant or module method.

**Comment by aledalgrande** [comment]
Thanks for your work guys, sorry I haven't been to reply lately. Tire is one of the coolest gems I know.

**Comment by karmi** [comment]
@jredburn Added the test & the implementation, should be working now.
