### ISSUE TITLE
Class method to destroy & recreate index discards defined mappings, specifically: dropping :not_analyzed

### ISSUE THREAD

**Issue by Rio517** [karmi/retire#465]
Hi, 

I wrote a class method to help eliminate n+1 queries when importing documents w/ nested objects.  Here is a simplified example.

```
def self.fast_import
  Tire.index('articles').delete
  Article.index.create
  Article.includes(:author).find_in_batches{|batch| Article.index.import batch}
end
```

However, it would seem that after calling the method above removes `:not_analyized` mappings on my model.  If i comment out the first two lines of the above method and delete and receate my index manually before calling this method: no issue.  

Full simplified example code here:  https://gist.github.com/3785108

This is probably enough of an edge case that it might not warrant further investigation. I just wanted to post in case other people run into this issue, as it took me a lot of time to realize what was going on.

-Mario

**Comment by karmi** [comment]
Hi, thanks for the report. This is pretty specific to ActiveRecord -- I think we could expose some ENV variable so you'll be able to pass the options to the `includes` method from the Rake task / `import` method?

**Comment by Rio517** [comment]
I think that would be really valuable for folks w/ similar use cases.  The time saving from being able to include nested records is rather considerable with larger datasets.

Thanks!

-Mario

**Comment by karmi** [comment]
@Rio517 Mario, just use `Article.create_elasticsearch_index`, which will create the index with proper mapping, as defined in the model. Closing it for now, OK?

(I'm not really sure how to deal with these special cases for ActiveRecord in the Rake task... Maybe that's the point where you're better off writing your own importing procedure...)

**Comment by karmi** [comment]
Cross-check karmi/tire#530 for example with `ActiveRecord#find_in_batches`.
