### ISSUE TITLE
Facet behavior changes between development and production

### ISSUE THREAD

**Issue by zackfern** [karmi/retire#466]
This isn't specifically a Tire issue, however I don't know where else I could possibly ask for help.

My site is using a facet for Tags, and I'm using the following line in my mapping:

``` ruby
indexes :tags, type: 'string', index: :not_analyzed
```

After a lot of searching I've [found](http://stackoverflow.com/questions/11917835/multi-word-facets-elasticsearchtire) that in order to allow facets with multiple words (such as a tag "web design") you must not analyze the facet.

This works fine in development, however in my production environment I am running into the same issue. I've reset the server, reset the instance of ElasticSearch, even deleted and reindexed my data.

As I said, this isn't Tire-specific, however I would greatly appreciate any help you could offer. Thanks!

**Comment by karmi** [comment]
Hi, this depends on how exactly you put data in. So, I imagine, your model serialized as JSON looks somehow like this:

```
{
  "title" : "10 Best jQuery Plugin for Web Design",
  "tags"  : ["web design", "javascript", "jquery"],
  //...
}
```

Then your mapping is correct with `index: not_analyzed`. Faceting on the `tags` field should work fine, `terms` queries/filters should work fine.

It seems to me that your mapping is not properly applied -- do check the mapping for your index both in development and production  (`curl localhost:9200/<YOURINDEX>/_mapping`) and report back here.

(Notice that the correct mapping is (re)applied when the using the `tire:import FORCE=1` task, or when the application is loaded and the index does not exist.)

**Comment by zackfern** [comment]
After comparing both mappings I noticed they were different. 
Using the `tire:import FORCE=1` rake task solved this for me (although oddly enough I had been trying `Article.index.import` over and over). 

Thanks for your help and creating such an awesome Gem. :smiley:

**Comment by karmi** [comment]
Cool!, the problem was obviously that you have kept around the index with incorrect mapping -- when debugging/developing, it's best to just delete/create repeatedly, which the `FORCE=true` option does for you...

**Comment by zackfern** [comment]
That sounds good. Do you have any tips for keeping the mapping up to date as I begin to roll this app out to production?

**Comment by karmi** [comment]
For lots of cases, it makes sense to define the mapping and serialization inlined in the model, see https://github.com/rubygems/rubygems.org/pull/455 for inspiration.

For many other cases, it's good to define the mapping externally, eg. in a Ruby `module` defined in a separate file, and create the index manually, before deploying the app for the first time.

Have a look at the ["index alias"](http://www.elasticsearch.org/guide/reference/api/admin-indices-aliases.html) feature, which would allow you to recreate the index without downtime...
