### ISSUE TITLE
No error when failing to create index from mapping

### ISSUE THREAD

**Issue by simoncozens** [karmi/retire#469]
I just spent a good hour or so trying to track down why my terms where being analyzed even though I had `:index    => "not_analyzed"` not set in the mapping for my AR class. The reason turned out to be that a completely different field in the mapping had `:type => "geopoint"` (which of course ought to be `geo_point`).

Every time I rebuild the index, Tire made an attempt to re-create the index from the mapping, **failed silently** and left me with an empty mapping which it then filled dynamically from the import data, and so all the options in the mapping I had specified were ignored.

Please could we have an error, or at least a warning, if `create_elasticsearch_index` or its moral equivalent fails?

**Comment by karmi** [comment]
Absolutely -- though we also need to have some backwards compability, so it must be configurable. I agree the current default is painful...

(In cases like this one, always check your mapping.)

**Comment by axsuul** [comment]
Any suggestions on how to debug this? I'm currently experiencing this and no mapping is being created but I have no idea what could be causing it.

For my case, only the `type` is getting set and everything else like `index: "not_analyzed"` seems to be getting dropped.

**Comment by simoncozens** [comment]
What I did was to turn on logging and try creating the index manually in `rails console`

```
Tire.configure { logger 'elasticsearch.log' }
YourClass.create_elasticsearch_index
```

If you don't get an error from that, copy the index creation command from the bottom of the log file ( `curl -X ...`) and run it, and look at the errors from elasticsearch.

**Comment by karmi** [comment]
@axsuul Sure -- just consult the ES logs and get the mapping and check it, either with Tire, curl or in your browser.

@simoncozens is right, just enable logging, best with level set to _debug_, you'll see the error:

```
Tire.configure { logger STDERR, level: "debug" }
```

**Comment by axsuul** [comment]
@simoncozens @karmi Thanks for your help, that was it :+1:

**Comment by karmi** [comment]
Sorry about that. Notice that karmi/tire@352c208 and karmi/tire@65cd994 improve the situation here.

(Until I figure out how to deal with warnings vs. exceptions, there's just a warning being displayed.)
