### ISSUE TITLE
JsonParseException[Numeric value (9223372036854775807) out of range of int]

### ISSUE THREAD

**Issue by danielschlegel** [karmi/retire#474]
Hi Karmi
We have a problem while bulk indexing with import since we updated to tire 0.4.3. As far as i didn't  overlook something we have no change in the code related to the tire mapping or the to_indexed_jon method in the model. 

What i found out so far: 
1. hashr was upated (seams not to be the problem)
2. There is a Problem related to the JSON parser in elastic.
   http://jira.codehaus.org/browse/JACKSON-642
   http://stackoverflow.com/questions/7535779/date-parsing-problem-with-jackson-1-8-5

I know that the exception is on java side. I post this here because there was no change at all on elastic side.

Model code:

```
  tire do
    mapping do
      indexes :person_id,      :type => 'long',   :index => :not_analyzed, :store => false 
      indexes :labels,          :type => 'string',    :analyzer => 'snowball'
    end
  end

  def to_indexed_json
    {
        :person_id => person_id,
        :labels => labels,
    }.to_json
  end
```

Would be very happy to get help about this. Will try to debug further in elasticsearch source.

Thanks
Dani

**Comment by karmi** [comment]
@danielschlegel My first hunch would be that the mapping isn't really used for your index.

Can you get the mapping and make sure the `person_id` is, in fact, a `long`? Get back to me here and we'll try to debug it further.

**Comment by danielschlegel** [comment]
Im very sorry i didn't post any further(since i found the problem). actually the mapping and all in tire was ok. One of the replicas in our cluster was in initialzing state and didn't come up correctly. since the cluster is green again the error disappeared. 
I'm still unhappy with the situation because i think a yellow state should not lead into an exception but i know this is not a tire problem.
Thanks you very much!

**Comment by karmi** [comment]
@danielschlegel No worries!, I'm glad the issue went away... The "yellow" state should not result in the error, AFAIK, maybe you can submit the issue to elasticsearch/elasticsearch? There may be an underlying problem there...
