### ISSUE TITLE
Tire accesses the `_type` field directly in `update_index`

### ISSUE THREAD

**Issue by bogn** [karmi/retire#477]
The line [v0.4.3/lib/tire/model/search.rb#L139](https://github.com/karmi/tire/blob/v0.4.3/lib/tire/model/search.rb#L139) overwrites the model's `_type` attribute to the value returned by elasticsearch. This won't cause obvious issues on the first call to save(create) as the field is not persisted (because it's set after_save), but on a second call to save without a reload inbetween the field is persistent causing data layers (in my case MongoMapper) to not return this record in any queries but through the root class.

Here's a brief gist:
https://gist.github.com/3872667

**Comment by karmi** [comment]
I really don't understand what you're trying to do here and what is the issue.

When I look at http://localhost:9200/sub_things/_search, I can see correct number of documents and correct types for documents.

When I query:

```
SubThing.tire.search { query { all } }.results.size
```

I see everything correctly once again.

So, please try to clear up the issue or close it -- `SubThing.count` is a _MongoMapper_, not a _Tire_ thing, so I don't understand what's going on.

P.S.
If you try to stay away of inheritance, your life in Ruby and Rails will be easier.

**Comment by karmi** [comment]
Closing due to no ping reply. Please re-open if you have more information.

**Comment by bogn** [comment]
The issue is that Tire overwrites the _type column. ActiveRecord, MongoMapper and supposedly other mappers use that column for Single-Table-Inheritance. It should always return the class name as a string, e.g. "SubThing" for SubThing models, but Tire overwrites it with sub_thing which is done by the line that I referenced above. That is the reason MongoMapper's #count doesn't find it, ActiveRecord wouldn't be able to find it through the SubThing model either. _type is set to the response of elasticsearch which is not a good thing. In short _type has special meaning and it might be more safe if tire used more unique column names for its information. Something like:

``` ruby
instance._elasticsearch_index = response['_index'] if instance.respond_to?(:_elasticsearch_index=)
instance._elasticsearch_type = response['_type'] if instance.respond_to?(:_elasticsearch_type=)
instance._elasticsearch_version = response['_version'] if instance.respond_to?(:_elasticsearch_version=)
```

**Comment by karmi** [comment]
Thanks for the clarification -- that is indeed very unfortunatel behaviour. Tire should use the `instance.tire` proxy in this case, and not access the model directly. I'll reopen the issue to keep it as a reminder.

**Comment by bogn** [comment]
Wow, you are fast. Thanks for a great gem!

**Comment by karmi** [comment]
Hi, this has been a tricky one. Should be fixed on current master, the `update_index` method has been extracted and refactored. No breaking changes should be introduced.
