### ISSUE TITLE
Broken rake import in edge

### ISSUE THREAD

**Issue by jockee** [karmi/retire#479]
Running `rake environment tire:import CLASS=Opportunity FORCE=true`

tasks.rb:55: `mapping = MultiJson.encode(klass.tire.mapping_to_hash, :pretty => Configuration.pretty)`

```
[IMPORT] Deleting index 'opportunities'
rake aborted!
uninitialized constant Configuration
/Users/joakimekstrom/.rvm/gems/ruby-1.9.3-p194-perf/bundler/gems/tire-ed887f00da29/lib/tire/tasks.rb:55:in `block (2 levels) in <top (required)>'
```

   ...

**Comment by karmi** [comment]
Argh, sorry!, should be fixed.
