### ISSUE TITLE
undefined method `paginate' for MyClass:Class, when importing

### ISSUE THREAD

**Issue by jpsilvashy** [karmi/retire#48]
So I'm using mongo, but I'm not sure thats the problem here, when I try to run `tire:import` on my model it fails with `undefined method`paginate' for Recipe:Class`

``` ruby
rake environment tire:import CLASS='Recipe' PARAMS='{:page => 1}' FORCE=1 --trace
```

``` ruby
** Execute environment
** Execute tire:import
# ...
--------------------------------------------------------------------------------
rake aborted!
undefined method `paginate' for Recipe:Class
```

And here is the stack trace for that:

``` ruby
rake aborted!
undefined method `paginate' for Recipe:Class
/Users/jpsilvashy/.rvm/gems/ruby-1.9.2-p180/gems/tire-0.1.14/lib/tire/index.rb:136:in `import'
Tasks: TOP => tire:import
```

Any ideas? I've tried it with and without `will_paginate` installed also with no success.

**Comment by karmi** [comment]
OK, this was a tricky one. Yet, the solution is very simple:

``` bash
$ rake environment tire:import CLASS='Article.all' INDEX='mongo-articles' FORCE=true
```

Apparently, Mongoid does not support `Article.paginate`, but `Article.all.paginate`, for reasons beyond my understanding :)

Ping me if this works -- it does in my example app. _Tire_ does not care _what_ has the `paginate` method, only that _something_ in the app has it :)

**Comment by karmi** [comment]
Ping, any news?

**Comment by wulffeld** [comment]
With mongoid 2.0.2 will_paginate is no longer supported. That's what's causing this error in case that's not clear to anyone new coming here.

I've personally removed will_paginate and replaced it with kaminari which seems better. However, it has different semantics so it doesn't work with tire and stuff like:

``` ruby
Article.import :per_page => 100
```

breaks. I can't figure out if there's a better way around doing this:

``` ruby
Article.all.each do |conf|
  Article.elasticsearch_index.import [conf]
end
```

**Comment by aaronchi** [comment]
This library needs a kaminari adapter... See
https://github.com/karmi/tire/issues/14

import just needs to use model.page if kaminari is installed for this to work correctly

**Comment by karmi** [comment]
> I can't figure out if there's a better way (...)

Yes, there is:

``` ruby
Article.elasticsearch_index.import Article.all
```

as documented in the Readme.

> With mongoid 2.0.2 will_paginate is no longer supported. That's what's causing this error (...)

No, I don't believe this is the case. I have a Mongoid 2.0.2/Tire test application and I am able to import data the way I posted above:

``` bash
$ rake environment tire:import CLASS='Article.all' INDEX='mongo-articles' FORCE=true
```

And I am able to paginate the results with eg. `Article.all.paginate :per_page => 1, :page => 2`.

**Comment by wulffeld** [comment]
Article.all I obviously don't want to use with millions of records :)

See:
https://github.com/mongoid/mongoid/issues/1000

I agree that Article.all.paginate works (if you happen to use will_paginate) but if you're trying to use Article.import it fails because it wants Article.paginate. I guess I can just create my own kaminari pagination loop around the import command but it feels icky.

**Comment by karmi** [comment]
> (...) if you're trying to use Article.import it fails (...)

Ah, yes, of course it does. That's why I was referring to the Rake task at all times, which was the original issue. (It _is_ easy to pass random object to the Rake task like this.)

Do not use the `Article.import` interface then, use the `Article.elasticsearch_index.import` one! You can pass any Enumerable compatible object to the `Index#import` method (which in turn uses `Index#bulk_store`), see http://karmi.github.com/tire/#section-Bulk_Indexing.

This way, you have to provide your own pagination, of course. This has no relation to _kaminari_ support, though, I tend to think. If you decide _not_ to use `will_paginate`, it's no problem, you just have provide your own pagination...

**Comment by karmi** [comment]
> Article.import it fails because it wants Article.paginate (...)

In fact, you can pass any method, "paginate" is only default: `Article.import :method => "whatever_pagination_i_have"`. It may well work in your case?

**Comment by aaronchi** [comment]
Actually, at least for activerecord, this should probably be using the batched 'find_each' method. Then you can remove the dependency on paginate here.

http://apidock.com/rails/ActiveRecord/Batches/ClassMethods/find_each

**Comment by wulffeld** [comment]
```
def my_paginate(options = {})
   Article.page(options[:page]).per(options[:per_page])
end

Article.import :method => "my_paginate"
```

The above ought to work however I think I've discovered a mongoid related bug. The document.empty? check: https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L137 always returns false. I think you should do .length == 0 instead here. Or maybe it's a kaminari bug - not sure:

```
>> Article.page(3).per(1000).length
0
>> Article.page(3).per(1000).empty?
false
>> Article.page(3).per(1000).to_a.empty?
true
```

**Comment by karmi** [comment]
@aaronchi: Yeah, but that only applies for ActiveRecord... And ActiveModel has no common `find_each`/`find_in_batches` semantics I am aware of... (For me, personally, ActiveModel-based models are the real important target. Don't know about other people.)

**Comment by karmi** [comment]
@wulffeld: Hmm, yes. I've spent some time fiddling with this in the console, and all this stuff is somehow too weird.

I was able to implement `Article.paginate` proxy to `Article.page(options[:page]).per(options[:per_page])`, as you suggest. After changing the `empty?` check to `size` check, the Rake task works fine out-of-the-box, as the `Article.import`. I'll commit the changes neccessary so you can check them out in your app?

**Comment by wulffeld** [comment]
Yup, I'll check out master.

**Comment by wulffeld** [comment]
master checked and verified to work fine! Thanks!

**Comment by karmi** [comment]
Great! So, for posterity, here's how to roll import with _Tire_ and _Mongoid_:

1/ You're using the `will_paginate` gem with _Mongoid_ — just follow the instructions in the [docs](http://karmi.github.com/tire/) and in the Readme.

2/ You're using the `kaminari` gem with _Mongoid_ — you have to provide the `paginate` method in your model, like this:

``` ruby
    class Article
      # ...
      def self.paginate(options = {})
         page(options[:page]).per(options[:per_page])
      end
    end
```

Then just follow the instructions in the [docs](http://karmi.github.com/tire/) and in the Readme.

**Comment by coffeencoke** [comment]
This is still an issue for me.

When I run the import rake task I get `undefined method`paginate' for MyModel:Class`

Can someone please provide some light on the following question:

Since MongoDB uses cursors to retrieve queries in batch mode natively, why is there a need to paginate for this task?  

I would like to be able to override the method, 'paginate', used in the rake task.  I understand the last thing you may want to do is introduce another ENV variable to the task but the task does not work for an application unless it is using will_paginate or kaminari... That seems a bit off.

**Comment by karmi** [comment]
> When I run the import rake task I get `undefined method 'paginate' for MyModel:Class`

Of course -- the `paginate` method does not exist in your model, when you're not using `will_paginate`. If you don't want to use `will_paginate`, you have to implement it yourself, as in the example above...

> Since MongoDB uses cursors to retrieve queries in batch mode natively, why is there a need to paginate for this task?

What MongoDB has to do with this? The import task makes an **assumption** that `paginate` will be implemented in most cases, MongoDB or not.

> I would like to be able to override the method, 'paginate', used in the rake task.
> I understand the last thing you may want to do is introduce another ENV variable to the task but the task does not work for an application unless it is using will_paginate or kaminari... That seems a bit off.

If it helps you, OK, why not make the method configurable. But I don't think it will help you -- the method would have to have the same interface as the  `will_paginate` method, and the only benefit you're gaining is different name.

_Tire_ makes the following assumption: if your application is not using some sort of pagination,
the amount of data you probably have is so small, that you shouldn't bother with Rake tasks and just write:

``` ruby
Article.tire.index.import Article.all
```

Again: everything about this is about assumptions and 80/20 ratio. The thinking behind the reliance on pagination method is this:
- When you have nontrivial amounts of data, you _are_ using some sort of pagination.
- When you are using pagination, there's high chance you're using the `paginate` method of `will_paginate` -- problem solved. So we don't care about ActiveRecord's `find_each` and every crazy batch finder out there. We focus on _one_, quite common pattern.
- When you're not using `will_paginate`, you know what you're doing and probably can emulate the `paginate` method, see code above -- problem solved, again.
- When you have a highly specific use case, it's better for you to handle the import yourself anyway, and `Tire::Index#import` makes it very easy for you.

Makes sense?

**Comment by coffeencoke** [comment]
I understand, thanks for your input. We will figure something out. 

Thanks!

Matt

**Comment by karmi** [comment]
> Since MongoDB uses cursors to retrieve queries in batch mode natively
> 
> > We will figure something out.

I don't know anything about how to practically use cursors in Mongo -- if you'll give an example, I can help you with the _Tire_ side of things. Catch me here or on #elasticsearch's IRC.

If it behaves like ActiveRecord's `find_each`, you can load batches of records (say by 1000) and feed them to `Tire::Index#import` method. Or, you can just wrap it in the `paginate` method and use the Rake task :)

**Comment by plentz** [comment]
Hey guys, I think we should re-open this issue, since kaminari isn't fully supported yet. Some errors like this aren't expected.

```
ActionView::Template::Error (undefined method `first_page?' for #<Tire::Results::Collection:0x007fc7d27ed0a0>):
    1: <% if @customers.first_page? %>
```

**Comment by rodrigoalvesvieira** [comment]
This error happens in my app using Rails 3.2.6 and Tire 0.4.2 and the weird thing is that I am not using any pagination gem/technique.

**Comment by timuckun** [comment]
Same as @rodrigoalvesvieira but I have kaminari loaded.
