### ISSUE TITLE
Add attributes while indexing

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#482]
Is it possible to add attributes (Thinking Sphinx context http://sphinxsearch.com/docs/current.html#attributes) to the index fields? I mean, if we are indexing all the articles, can I add an attribute to the index such that it takes into consideration the user id too. So, if a user is logged in, and performs a search on articles that would be faster I guess...

Consider, the articles actually has a belongs_to association with user.

```
class User < ActiveRecord::Base
    has_many :articles
end

class Article < ActiveRecord::Base
    belongs_to :user
    mapping do
        indexes :title, :boost => 2
    end
    def to_indexed_json
        { :title => title }.to_json
    end
end
```

In this case, I want the indexing to consider the user_id too, along with the normal mapping we do in the Article model. I don't want to create a separate index for each user.

**Comment by karmi** [comment]
Please see the http://stackoverflow.com/questions/11692560/elasticsearch-tire-and-nested-queries-associations-with-activerecord/11711477#11711477 StackOverflow answer. You can then use a filtered query with a `terms` filter on the `user_id`.
