### ISSUE TITLE
Working with czech diacritic

### ISSUE THREAD

**Issue by palodelincak** [karmi/retire#483]
Hi. I'm little confused about working with czech diacritic.

My mapping:

```
mapping do
  indexes :name
end
```

Product.create(name: "svetlo")
Product.create(name: "světlo")

When I seach for `svetlo` I'll get records matching to `svetlo`, but not `světlo`. I should expect records  matching to `svetlo` and `světlo`.

**Comment by karmi** [comment]
For this use case, you need to create a [custom analyzer](http://www.elasticsearch.org/guide/reference/index-modules/analysis/custom-analyzer.html) with [ASCII filter](http://www.elasticsearch.org/guide/reference/index-modules/analysis/asciifolding-tokenfilter.html) to transliterate Czech characters to ASCII versions.

**Comment by karmi** [comment]
Two points regarding this:
1. Make yourself familiar with the ["Analyze API"](http://www.elasticsearch.org/guide/reference/api/admin-indices-analyze.html) and use it to play around with the analysis process.

In this case, we can construct ad-hoc combinations of tokenizers and filters and see the impact:

http://localhost:9200/_analyze?text=Světlo&tokenizer=whitespace&filters=lowercase,asciifolding
http://localhost:9200/_analyze?text=Español&tokenizer=whitespace&filters=lowercase,asciifolding

Do note, that tokens won't be stemmed in this case.
1. You may get better results by using the [_Hunspell_](https://github.com/jprante/elasticsearch-analysis-hunspell) analyzer for elasticseach, which would provide both stemming and ASCII transliteration.

See a complete example for the former approach below:

``` ruby
require 'tire'

Tire.index 'test-ascii-folding' do
  delete
  create \
  settings: {
    analysis: {
      analyzer: {
        ascii: {
          type: 'custom',
          tokenizer: 'whitespace',
          filter: ['lowercase','asciifolding']
        }
      }
    }
  },
  mappings: {
    document: {
      properties: {
        title: { type: 'string', analyzer: 'ascii' }
      }
    }
  }
end

Tire.index 'test-ascii-folding' do
  store title: 'Světlo'
  refresh
end

puts "ANALYZE:"

p Tire.index('test-ascii-folding').analyze('Světlo', tokenizer: 'whitespace', filters: 'lowercase,asciifolding')
p Tire.index('test-ascii-folding').analyze('Světlo', analyzer: 'ascii')
p Tire.index('test-ascii-folding').analyze('Světlo', field: 'title')


puts '-'*80, "SEARCH:"

s = Tire.search('test-ascii-folding') do
  query { string 'title:svetlo' }
end

p s.results
```

**Comment by rubydev** [comment]
Hi,

I have this setting:

<pre>
 ES_SETTINGS = {
      analysis: {
          analyzer: {
              new_czech: {
                  type: 'custom',
                  tokenizer: 'standard',
                  filter: %w(standard lowercase czech_stop czech_stemmer asciifolding)
              }
          },
          filter: {
              czech_stemmer: {
                  type: 'stemmer',
                  name: 'czech'
              },
              czech_stop: {
                  type: 'stop',
                  stopwords: ['_czech_']
              }
          }
      }
  }
</pre>

and I have problem with searching word "medvěda" and "medveda". For example:

<pre>
  it "searches with and without diacritics should by same" do
    Post.tire.index.delete
    Post.create_elasticsearch_index
    Post.make!(name: "velkého plyšového medvěda")
    Post.make!(name: "medveda nenazraneho australskeho mazliveho")
    Post.make!(name: "Nic tu neni!")
    Post.tire.index.refresh
    get :index, query: "medved", type: "post"
    json_response.should_not be_empty
    json_response.count.should eq(2)
    get :index, query: "medvěd", type: "post"
    json_response.should_not be_empty
    json_response.count.should eq(2)
  end
</pre>

<pre>
    indexes :name, type: 'multi_field', fields: {
        english: {type: 'string', analyzer: 'snowball', boost: 10},
        czech: {type: 'string', analyzer: 'new_czech', boost: 10}
    }
</pre>

Json response count is always eq 1, why? If I removed "czech_stemmer" from settings and change words (in name fields) "medvěda" and "medveda" to "medvěd" and "medved" everything works fine. Why "czech_stemmer" probably has collision with "asciifolding"?

**Comment by karmi** [comment]
hey, don't know what's going on here, tried it and it works for me with the analyze API:

``` ruby
# encoding: utf-8

require 'elasticsearch'

client = Elasticsearch::Client.new

client.indices.delete index: 'czechtest' rescue nil

client.indices.create index: 'czechtest', body: {
  settings: {
      analysis: {
          analyzer: {
              new_czech: {
                  type: 'custom',
                  tokenizer: 'standard',
                  filter: %w(standard lowercase czech_stop czech_stemmer asciifolding)
              }
          },
          filter: {
              czech_stemmer: {
                  type: 'stemmer',
                  name: 'czech'
              },
              czech_stop: {
                  type: 'stop',
                  stopwords: ['_czech_']
              }
          }
      }
  }
}; sleep 0.25

client.indices.analyze index: 'czechtest', text: 'medvěda', analyzer: 'new_czech'
# => {"tokens"=>[{"token"=>"medved", "start_offset"=>0, "end_offset"=>7, "type"=>"<ALPHANUM>", "position"=>1}]}
```

BTW, Tire is retired and you should migrate to the new -ruby and -rails gems.

**Comment by rubydev** [comment]
You are right, this works. Analyzer return token "medved".

But for this:

<pre>
Tire.index(ES_INDEX_NAME).analyze('medveda', analyzer: 'new_czech')
</pre>

Analyzer return token "medvd".

But that does not change the fact, that query "medvěd" not return post with "medveda nenazraneho australskeho mazliveho".

<pre>
  it "searches with and without diacritics should by same" do
    Post.tire.index.delete
    Post.create_elasticsearch_index
    Post.make!(name: "velkého plyšového medvěda")
    Post.make!(name: "medveda nenazraneho australskeho mazliveho")
    Post.make!(name: "Nic tu neni!")
    Post.tire.index.refresh
    get :index, query: "medvěd", type: "post"
    json_response.should_not be_empty
    json_response.count.should eq(2) # return only one post
  end
</pre>

mapping for name:

<pre>
 indexes :name, type: 'multi_field', fields: {
        english: {type: 'string', analyzer: 'snowball', boost: 10},
        czech: {type: 'string', analyzer: 'new_czech', boost: 10}
    }
</pre>

Query:

<pre>
    search_fields = %w(name title keywords description terms about)
    search_fields.map!{|field| "#{field}.czech"}
    Tire.search(ES_INDEX_NAME, load: true) do
      query do
        boolean({:minimum_number_should_match => 1}) do
          ...
          must { string params[:query], fields: search_fields }
          ...
        end
      end
    end
</pre>

Thanks for any advice!

I use ruby 2.1.1, Rails 4.0.3, Tire 0.6.2, ES 0.90.10

**Comment by karmi** [comment]
Congratulations, I think you just found an inconsistency in the Czech stemmer :) Compare:

```
http://localhost:9200/czechtest/_analyze?text=žluťoučký&analyzer=new_czech
=> zlutouck
http://localhost:9200/czechtest/_analyze?text=zlutoucky&analyzer=new_czech
=> zlutouck
```

You might want to have a look at the Hunspell-based analyzers, http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-hunspell-tokenfilter.html#analysis-hunspell-tokenfilter.

**Comment by rubydev** [comment]
Is any option for configuring hunspell for ES on the Heroku (bonsai)? I did not find any help. Thanks!

**Comment by karmi** [comment]
You should try it out locally, following the docs, verifying it works as you need and then contact support for your provider, if you're not hosting Elasticsearch yourself.

**Comment by rubydev** [comment]
Now I've found, that depends on the filter order. This setting:

<pre>
ES_SETTINGS = {
      analysis: {
          analyzer: {
              new_czech: {
                  type: 'custom',
                  tokenizer: 'standard',
                  filter: %w(czech_stop asciifolding standard lowercase czech_stemmer)
              }
          },
          filter: {
              czech_stemmer: {
                  type: 'stemmer',
                  name: 'czech'
              },
              czech_stop: {
                  type: 'stop',
                  stopwords: ['_czech_']
              }
          }
      }
  }
</pre>

returns expected results.

**Comment by nz** [comment]
> Is any option for configuring hunspell for ES on the Heroku (bonsai)?

@rubydev we don't currently have the Hunspell analysis plugin deployed, but are willing to consider it for a future release. We're very customer-driven in our approach to supporting for plugins, so drop us a line at support@bonsai.io if you decide you need Hunspell support.
