### ISSUE TITLE
Should searching with `:load => true` use `to_i` for the ActiveRecord find?

### ISSUE THREAD

**Issue by ches** [karmi/retire#485]
Heya @karmi,

So this is a pretty obscure case, I'm not sure if it would be the right thing for Tire to do or not but I thought I'd explain how I ran into this to see what you think:

In `Tire::Results::Collection`, with `:load => true` Tire [ends up calling `find` on ActiveRecord classes](https://github.com/karmi/tire/blob/v0.4.2/lib/tire/results/collection.rb#L58-L59) in a form like this (assuming there is only one result here):

``` ruby
Company.find(['2'])
```

Now, in our database we have a company with ID 2, I'll say its name is "Acme". We're using [friendly_id](https://rubygems.org/gems/friendly_id) for company URL slugs, and it so happens that there is actually a company with the name "2" (seriously...). This company got a slug of "2", and `friendly_id` overrides `find` such that the call in the line above actually returned the company named "2" instead of Acme. Calling it as `Company.find([2])` does the right thing.

I realize full well that you wouldn't make changes because of some crazy pathological case involving another 3rd party library that overrides `ActiveRecord`, but do you think it might just be the right thing to do generally to do something like `ids = items.map { |h| h['_id'].to_i }`? Since `Tire::Results::Collection` isn't necessarily dependent on AR or even integer IDs for that matter, probably not, but hey, thought I'd ask, because c'mon, if nothing else it's a pretty funny bug story right? :wink:

**Comment by ches** [comment]
Oh, one thing that _maybe_ is actually worth talking about here: this ultimately blew up because of the next line, the return value of `results`:

``` ruby
@response['hits']['hits'].map { |item| records[item['_type']].detect { |record| record.id.to_s == item['_id'].to_s } }
```

If you won't take offense to me saying so, that's kind of a nasty one-liner :innocent:  `detect` returns `nil` if there's no match, so basically I ended up with a `Results::Collection` which reported a `size` of one (because there was in fact one legit result from ES, and `inspect` of the collection rightly showed it), but the `Array` part of the object (`@results`) was `[nil]`. `nil` is evil. Would you be open to raising an exception here if `<result of line above>.compact.length != @response['hits']['hits'].length`?

**Comment by karmi** [comment]
Ha!, now that is a lovely edge case -- _absolutely love it_ :)

My consience isn't really clear here: if the `results` method in the `Collection` class wouldn't be such a mess of >40LOC, it would be trivial for you to patch a single method, stick the patch in your `lib` and you'd be set...

Now, calling `to_i` would obviously solve it, but Tire is designed from the outset to work with _any_ ActiveModel compliant ORM/ODM/OxM, be it for MongoDB, CouchDB, Redis, etc. Converting to Integer would almost definitely break stuff for those adapters...

Let me try some extraction first...

**Comment by karmi** [comment]
@ches See the attached commit, you should be now be able to override `Tire::Results::Collection#__find_records_by_ids` with something like:

``` ruby
def __find_records_by_ids(klass, ids)
  @options[:load] === true ? klass.find(ids.map(&to_i)) : klass.find(ids.map(&to_i), @options[:load])
end
```

About raising the exception -- I need to think more about that in the larger scheme of the entire codebase.

I agree `nil` is pure evil, but don't see immediately an easy way here -- try the override, it should solve both problems, and ping me with results, please.

**Comment by karmi** [comment]
@ches, please check out the the `refactoring/results` branch if it's OK for you to override the behaviour. Closing.

**Comment by ches** [comment]
Yay, thank you!
