### ISSUE TITLE
Scoped ActiveModel mapping and/or ignoring certain records

### ISSUE THREAD

**Issue by maxim** [karmi/retire#486]
I'm trying to figure out how to only create index for scoped records. I can easily use a scope for initial import.

```
rake environment tire:import CLASS="Product.store_products" FORCE=true
```

This works for initial import, but what about Callbacks? New/updated records will not be filtered anymore. You could add all the records into index and always filter on search, but that's just wasteful.

I think a good way would be to call a method on the model, something like the following.

``` ruby
def indexable?
  published? # => true/false
end
```

If the method exists and returns false - mapping should skip the record. Why not implement something similar?

Another way would be something like the following.

``` ruby
class Product < ActiveRecord::Base
  mapping do
    ignore_if: '!published?'
  end
end
```

Any thoughts? Perhaps there is already a good way to do this?

**Comment by karmi** [comment]
Hi, I think once you have special requirements like this one, it's better to take matters into your own hands then to rely on complicated behaviour and vast DSLs.

In this case, just don't `include Tire::Model::Calbacks` and store the record only when the condition is true:

``` ruby
class Product < ActiveRecord::Base

  after_save do
    self.update_index if published?
  end

end
```

**Comment by maxim** [comment]
Yeah this makes sense. I feel like there needs to be another abstraction on top of tire, which focuses on rails integration and popular use cases. Something worth considering. Appreciate your effort on this project.

**Comment by karmi** [comment]
>  I feel like there needs to be another abstraction on top of tire, which focuses on rails integration and popular use cases.

That sounds interesting -- could you give any examples? I mean, I _am_ genuinely interested :)

(The thing is, I feel Tire brings a lot of “sugar” to Rails/ActiveModel world already. Based on my experience, it's usually much better to instruct people to “just use Ruby” instead of trying to cover any imaginable use case, eg. your example with `ignore_if`...)

**Comment by maxim** [comment]
I'm just talking off the top of my head, but what the hell.

Tire gives you the kind of sugar that follows ElasticSearch very closely. In ElasticSearch query is sort of an AST — so that's what tire gives you. A DSL to build the query as an AST.

So you have the following.
- `mapping` which defines rules by which your models are loaded into index
- `to_indexed_json` which defines what your model looks like when serialized and cached in json format
- `Search` methods that build the query AST based on user input, and send it to ElasticSearch
- `Callbacks` that are required to keep index in sync

However, if you step away from ElasticSearch, and look at the popular web app use cases, you get something like following.
1. I want to have a smart, flexible search across multiple text fields and associated models.
2. If I have a field which is translated to multiple languages, I want my search query to find results across all possible translations of the field.
3. I want to define facets on certain fields.
4. I want search to stay in sync.
5. I want to chain scopes.
6. I want virtual fields to work just as well as persisted ones.

Perhaps it could be done with syntax like this.

``` ruby
# The index here has a name :store_search which also defines a method
# Product.store_search, and does one more thing (see `include_index`)
define_index :store_search do
  # Primary key field (e.g. id) should be indexed implicitly by default

  # All fields are automatically mapped to appropriate ElasticSearch types
  # based on ActiveModel type, but overridable with options.
  field :title
  field :description

  # This would allow you to tell tire which code to run to get translations
  # of the field
  multilang_field :product_type, locales: [:en, :ru] do |locale|
    I18n.translate("product_types.#{product_type}", locale: locale)
  end

  # Perhaps you could include indexes of other models with specific names,
  # this would automatically do the right thing, make them objects for
  # this index, etc
  include_index :user, :store_search
  include_index :comments, :store_search

  facet :product_type
end
```

This declaration would give us a method like `store_search(options = {})` which returns a scope. You see - all args in the method are optional. You could call it with store_search(query: 'foo', product_type: 'bar') or you could omit all options and get all results. This builds the query AST on the back end. 

For people who want to avoid loading models from the db we could autogenerate another method: `store_search_results`.

How does `store_search` act as a scope? Simple, it gets all the results with `store_search_results` (accepting the same options), and does something like `where(id: store_search_results(options).map(&:id))`. This isn't the best, but it's sufficient, and could be improved.

Callbacks would also be automatically generated for all involved models.

So all of the above considered, 
1. Combine `mapping`, `to_indexed_json`, `Search`, and `Callbacks` in one place with sane conventions that work for 80-90% of cases.
2. Address specific use cases with helpers like `multilang_field`.
3. Provide an ActiveModel scope.
4. Still allow for results to be accessed without hitting the database.
5. Still allow to bypass this entirely and go for pure tire.

**Comment by karmi** [comment]
Thanks for elaborating on that, Maxim. It's an interesting point of view. I'd add couple of things:
1. The `mapping`/`to_indexed_json` combo is miserable, agreed on that. What's _more_ miserable is that `to_indexed_json` is not needed in most cases -- the `mapping` alone will do. See eg. https://github.com/karmi/rubygems.org/commit/fa7d1cd. I did the mistake to put it too prominently into the documentation.
2. Disagree that Tire gives you the equivalent of elasticsearch DSL .) The ActiveRecord/ActiveModel integration is the sugar on top of the DSL. The integration should be _more_ elegant, absolutely.
3. What you're describing sounds like a bit like the approach ThinkingSphinx took. I did a lot of bad decisions when starting Tire, but still think that taking a different approach was good. See, with elasticsearch, what you've hit are "tip of iceberg" issues. When somebody is using elasticsearch, she must understand what the analysis process does, how tokenizers + token filters play together, how the queries, filters and facets play together, etc. I'd rather lace these bitter issues with a bit of Ruby sugar, then try to supress their taste altogether...

That said, I understand what you're saying and consider it interesting take!

**Comment by maxim** [comment]
I actually appreciate tire's approach a lot, and prefer its philosophy over the likes of ThinkingSphinx. It gives you enough flexibility to use ruby to say pretty much anything in ElasticSearch's "language". This is why I feel that tire shouldn't try to be anything more than that. It should act more as ElasticSearch's ruby bindings, and could even be called elasticsearch-ruby or something. An official ES-ruby driver if you will.

I'd go further to suggest that it should be framework-agnostic and have no rails bindings. ActiveModel stuff should be extracted into a separate project. However, that separate project should be much more than mapping and a couple of modules. It should be something that builds on top of ruby bindings to resolve frequent web-app use cases. It could even provide view helpers for facets, sorting, and such. It could be opinionated on what type of analyzer you would need for a typical search field, it could take advantage of model relationships, etc. Similar libs could then be built on top of elasticsearch-ruby for sinatra, and other popular frameworks.

**Comment by karmi** [comment]
Spot on :) What you're describing is how the future should be shaped.
