### ISSUE TITLE
Filter out items in indexed association?

### ISSUE THREAD

**Issue by mhenrixon** [karmi/retire#487]
I have searched long and hard but haven't been able to find a good way of doing this. We are letting users add custom numbers and emails to their contact and these are then indexed with elasticsearch. However the user should be able to hide/show the number by setting a `visible` flag to on/off.

The mapping currently looks like this:

``` ruby
mapping do
  indexes :id,          index: :not_analyzed
  indexes :firstname,   boost: 50
  indexes :lastname,    boost: 55
  indexes :street,      boost: 10
  indexes :zip,         boost: 30
  indexes :city,        boost: 25
  indexes :region
  indexes :country,     boost: 0
  indexes :picture_uri,       index: :not_analyzed

  indexes :phone_numbers do
    indexes :number,  boost: 100
    indexes :caption
    indexes :visible, index: :not_analyzed
    indexes :system_managed, index: :not_analyzed
  end

  indexes :email_addresses do
    indexes :address,  type: 'string', boost: 99
    indexes :caption
  end
end
```

Now for search results I would like to skip the phone_numbers that are not visible and I am wondering if anyone have any recommendations? I can see myself solving this in a few different ways. 
1. Let the client filter it (then every client would have to do it which isn't really necessary if it's done once on the server)
2. Remove it manually from the json the server returns (still not ideal)
3. Fillter them out in the query somehow (this would be my preferred way)
4. Don't index numbers that should not be visible (not sure how to skip indexing specific rows based on a specific value.

**Comment by karmi** [comment]
I'm afraid I'm not 100% sure what you wanna accomplish here, but:
1. It's possible to [`exclude`](http://www.elasticsearch.org/guide/reference/api/search/fields.html) certain fields from the returned JSON
2. However, in your case, you can just not display it?
3. I don't know if you wanna exclude these items from search (ie. a match on this number _won't_ add the document to results), or something else altogether.

**Comment by mhenrixon** [comment]
Ok now we are certainly getting somewhere, I am the first one to admit that I am not always very good at explaining what I am after but here goes.

What I want is to only include phone_numbers that are supposed to be visible in the query result but I don't want to hide the entire (contact) document from the search result if you know what I mean.

So if it's possible to exclude phone_numbers with the exclude filter without loosing the entire document I am a very happy with that solution. Is this supported by Tire or do I need to hack together a straight elasticsearch query?

**Comment by karmi** [comment]
Still not sure I got you -- but if the only you want to do is to exclude the `phone_numbers` part of JSON, then use `exclude`. If you don't want your query to _match_ on these phone numbers, use a nested query preferably.

Notice that you're not giving any example of documents, example of results you'd like to see, etc. Also take note that this kind of high-level, open ended questions usually fits better at [StackOverflow](http://stackoverflow.com/tags/tire).
