### ISSUE TITLE
Human readable time

### ISSUE THREAD

**Issue by reyjexter** [karmi/retire#488]
I'm trying to implement something but not sure how to do that. I have a field that needs to return a human readable time. For example "1 minute ago" or "1 minute and 2 seconds" ago.

The problem is I cannot modify Tire::Results::Item and add a non-persistent field just before it is serialized  using:

format.json { render json: @somelist}

I'm basically using created_at and updated_at which is generated by Mongoid::Timestamps and need to understand if this is something that should be done on elasticsearch or by rails.

If you could just point out the stuff I need to look at since I started working on elasticsearch few weeks ago.

Thanks

**Comment by karmi** [comment]
>  I have a field that needs to return a human readable time. 

To clarify: you have eg. `created_at` field stored in elasticsearch, let's say `2012-10-23T12:00:00Z`, and you want to display it in "time ago in words" format?

a) In a Rails application, that's the responsibility of a view layer -- you use the appropriate helper in your HTML template.

b) If you want to return that as part of JSON API response, my first question would be why do that? The API should return _data_, not arbitrary strings.

c) If you really wanna do that, create your own [wrapper](http://karmi.github.com/tire/#section-66) class which will wrap and decorate the "raw" `created_at` field.

**Comment by reyjexter** [comment]
We initially thought of returning raw data and processing it on client but because time will be different per timezone, i think its best to do that on server for the following reasons:
- It would save a little bit of battery on mobile phone to simply display human readable time than processing it. We thought of giving the server workload that could save battery time as much as we can.
- We can change format anytime we want.

Thanks

**Comment by karmi** [comment]
Not sure it makes good sense, but I think what you want then is just:
- calling `map` on results and injecting the humanized property into `Item`
- using a custom wrapper which would automatically decorate the raw field (preferable)
