### ISSUE TITLE
Implement "Update Mapping" feature

### ISSUE THREAD

**Issue by karmi** [karmi/retire#490]
So far, _Tire_ can only create or retrieve mapping for an index or model.

An ["update mapping"](http://www.elasticsearch.org/guide/reference/api/admin-indices-put-mapping.html) feature should be implemented:
- `Tire::Index#update_mapping` should be the low level API/DSL method to handle the feature.
- The method should handle response errors consistently as all other methods
- The method should handle response error due to conflicts -- at present, probably just returning `false`
- A bang format of the method should be added, which would re-raise any exception (eg. due to conflicts)
- The method should take options such as `ignore_conflicts`
- In the ActiveModel integration, the `create_elasticsearch_index` method should possibly display a diff of mappings in the error response

**Comment by cjbottaro** [comment]
Here's the pull request... https://github.com/karmi/tire/pull/520

**Comment by karmi** [comment]
Closed by 8fc5060.
