### ISSUE TITLE
{"error":"InvalidTypeNameException[mapping type name [_bulk] can't start with '_']","status":400}

### ISSUE THREAD

**Issue by beunwa** [karmi/retire#491]
Hi,

I use ruby 1.9.3-p194 (using rbenv) with tire 0.4.3, my remote elasticsearch instance run 0.17.2

I've just tried to bulk import simple arrays with Tire, I have just launch the file '
02_import_documents.rb' of your conference (Three node, one cluster, https://gist.github.com/2874702)

then I get that error for each documents import (Tire.index('my_index') { import documents })

[ERROR] 400 > {"error":"InvalidTypeNameException[mapping type name [_bulk] can't start with '_']","status":400}, retrying (1)...

**Comment by karmi** [comment]
That's quite an old version of elasticsearch -- please upgrade or use newer version locally, don't really remember the API changes. Ping back after testing with a more recent elasticsearch version!

P.S.
The script runs fine locally for me...

**Comment by beunwa** [comment]
It's ok now with a newer version of elastic search, thank you karmi

**Comment by karmi** [comment]
@beunwa Cool!
