### ISSUE TITLE
jruby support

### ISSUE THREAD

**Issue by thomasmhr** [karmi/retire#493]
Hi,

More a question than an issue. Do you plan to support jruby ? I had a look at the dependencies : rake, rest-client, multi_json, activemodel, hashr. Not sure about it but I thinks all these gems run on jruby.

Maybe you could add jruby to travis ? And see how it works ... The development dependencies are going to give more troubles ...

Adding jruby now may be not so hard ... adding it later could be much harder.

What do you think about it ?

**Comment by karmi** [comment]
AFAIK Tire should run fine on JRuby. On the other hand, I have absolutely no intention to make the test suite work, accomodating the gemfile for the different platforms (eg. SQLite), etc. There was a time I played with that (see karmi/tire@9f97d3f and other commits), but decided against it. You can always run the tests locally on JRuby, Rubinius, etc.
