### ISSUE TITLE
Exclude an indexed field from search results alone.

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#494]
Is it possible to do something like below:

```
  include Tire::Model::Search
  settings :analysis =>{
            :analyzer => {
              :whole_email => {
                'tokenizer' => 'uax_url_email'
              }
            }
    } do
    mapping do
      indexes :name, :boost => 10
      indexes :email, :analyzer => 'whole_email', :boost => 10
      indexes :account_id
    end
  end


  def to_indexed_json
    to_json( :only => [:name, :email, :account_id], 
           )
  end
```

Search query:

```
  User.tire.search do
     query { string 'querystring' }
     filter :term, :account_id => '1'
  end
```

**I want the search query to be filtered based on :account_id field, but I don't want the search query to return any result when the value in account_id is searched...**

```
  User.tire.search '1'
```

**Comment by karmi** [comment]
I don't understand what you want to do.

**Comment by vamsi-krishna-E0029** [comment]
account id based search in a multi-tenant application. Sorry if I asked it in the wrong way...

**Comment by karmi** [comment]
Sorry, don't really understand. You're filtering on `account_id`, which is fine for multi-tenant app. You may want to use a filtered alias (see "Filtered Aliases" in http://www.elasticsearch.org/guide/reference/api/admin-indices-aliases.html), so the filter is applied automatically.
