### ISSUE TITLE
Dynamic mapping is indexing all fields even when I explicitly map certain fiields

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#495]
Why is dynamic mapping happening even when I explicitly state I only want some fields indexed?  The only thing I want indexed is the name and description fields.  The rest I don't want indexed.  I'm assuming this is a bug. 

teacher.rb
class Teacher
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :name, type: String
  field :description, type: String
  field :address, type: String

  embeds_many :categories, cascade_callbacks: true

  index_name "locations-#{Rails.env}"

  mapping do
    indexes :name, :boost => 10
    indexes :description
    indexes :address, :index => :not_analyzed
  end
end

console tests:
Location.tire.search "4th Ave"
results in a a hit because one of the documents has "4th Ave" in the address field

Location.tire.search "Calculus"
results in a hit because one of the categories is "Calculus"

**Comment by karmi** [comment]
Hey, when closing the issue, maybe update it with the explanation of what was wrong in your code or approach...

**Comment by cameronkendall** [comment]
It was because my to_indexed_json was referencing all fields.  But explicitly stating which fields to index this fixed the issue.
