### ISSUE TITLE
search with boolean

### ISSUE THREAD

**Issue by richardrails** [karmi/retire#498]
Hi, I have problem with search in indexed recipes on my site. You have written this:

``` ruby
Tire.search 'articles' do
      query do
        boolean do
          should   { string 'tags:ruby' }
          should   { string 'tags:java' }
          must_not { string 'tags:python' }
        end
      end
    end
```

and I have this:

``` ruby
def self.search q
    tire.search(load: true) do
      query do
        string q, default_operator: "AND"
        boolean do
          should {string "is_public:1"}
        end
      end
    end
  end
```

What I really want, is that I want only display public recipes in results. column is_public is boolean, and I dont know how to do it with should ... 

my mappings are:

``` ruby
mapping do
    indexes :title, boost: 10
    indexes :content, boost: 6
    indexes :id, index: :not_analyzed
    indexes :is_public
    indexes :approved_on
  end
```

THANKS A LOT!

**Comment by karmi** [comment]
Hi, I think a [`filtered`](http://www.elasticsearch.org/guide/reference/query-dsl/filtered-query.html) query is best in your case -- maps nicely to the field type, can be cached in elasticsearch, etc.

``` ruby
tire.search(load: true) do
  query do
    filtered do
      query { string q, default_operator: "AND" }
      filter :term, is_public: 1
    end
  end
end
```

P.S. Your original query was almost correct -- notice the `bool` query wraps multiple queries, like this:

``` ruby
tire.search(load: true) do
  query do
    boolean do
      must { string q, default_operator: "AND" }
      must { should {string "is_public:1"}     }
    end
  end
end
```

---

UPDATE: Fixed incorrect `filter` syntax.

**Comment by richardrails** [comment]
Thx! It works. And this works also:

``` ruby
tire.search load: true, page: p, per_page: pp do
      query do
        string q, default_operator: "AND"
      end
      filter :term, :is_public => true
    end
```

What do you think is the best way? Maybe that you have written.

**Comment by karmi** [comment]
The `filtered` query is the right approach (filters run first, then queries) -- unless you need facets on filtered fields, which in your case you most probably don't.
