### ISSUE TITLE
geospatial search producing an error

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#499]
I'm followed various examples (issue 417, 169) running the following in the console but its producing an error:
s = Tire.search 'stores-development' do
  #query { all } # added this but still producing error
  filter 'geo_distance', distance: '100km', location: [40, -70] 
end

Error:
[REQUEST FAILED] curl -X GET "http://localhost:9200/stores-development/_search?pretty=true" -d '{"filter":{"geo_distance":{"distance":"100km","store":[40,-70]}}}'
Tire::Search::SearchRequestFailed: 500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[VZhQ3SdXSOG2Z9FQ64JE6Q][stores-development][0]: SearchParseException[[stores-development][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"filter\":{\"geo_distance\":{\"distance\":\"100km\",\"store\":[40,-70]}}}]]]; nested: QueryParsingException[[stores-development] failed to find geo_point field [store]]; }{[VZhQ3SdXSOG2Z9FQ64JE6Q][stores-development][1]: SearchParseException[[stores-development][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"filter\":{\"geo_distance\":{\"distance\":\"100km\",\"store\":[40,-70]}}}]]]; nested: QueryParsingException[[stores-development] failed to find geo_point field [store]]; }]","status":500}

store.rb
class Stores

  #...

  mapping do
    indexes :name, boost: 100
    indexes :coordinates, type: 'geo_point'
  end
end

**Comment by karmi** [comment]
Notice the error `failed to find geo_point field [store]` -- something is not right in your setup. Please post index mapping, how you index documents, etc. Please post it to somewhere else, not the issue body.

**Comment by karmi** [comment]
Crosspost from StackOverflow [http://stackoverflow.com/questions/13215295/why-is-the-geospatial-search-using-tire-for-elasticsearch-producing-a-searchphas], closing.

**Comment by cameronkendall** [comment]
Sorry, I didn't know where to post it so I posted on both stackoverflow and here.  But I've followed the examples and it still doesn't work.

Here is where the 
store.rb
class Store
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :name, type: String
  field :coordinates, type: Array

  #...

  index coordinates: "2d"  # mongoid index

  index_name "stores-development" # elasticsearch index

  mapping do
    indexes :name, boost: 100
    indexes :coordinates, type: 'geo_point'
  end
end

**Comment by karmi** [comment]
Please post your index mapping. (http://localhost:9200/stores-development/_mapping)
