### ISSUE TITLE
Tire + paperclip = no such file or directory

### ISSUE THREAD

**Issue by rcalderon** [karmi/retire#502]
I have a model Entry and I use Paperclip to attach a file document to it. I keep getting a no such file or directory error when I try to access the file for encoding. Anyone else run into this?

```
Errno::ENOENT in EntriesController#create
No such file or directory - /var/www/capsf-web/public/assets/entries/test.pdf
```

**entry.rb**

``` rubyonrails
class Entry < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :subcategories
  belongs_to :entry_type
  has_attached_file :document,
                    :url  => "/assets/entries/:basename.:extension",
                    :path => ":rails_root/public/assets/entries/:basename.:extension"

  before_post_process :image?

  validates_presence_of :entry_type

  attr_accessible :description, :title, :url, :category_ids, :subcategory_ids, :entry_type_id, :document

    mapping do
      indexes :title
      indexes :description
      indexes :categories do
        indexes :name
      end
      indexes :subcategories do
        indexes :name
      end
      indexes :entry_type
      indexes :document, :type => 'attachment'
    end

  def to_indexed_json
    {
    :title          => title,
    :description    => description,
    :categories     => categories.map { |c| { :name => c.name}},
    :subcategories  => subcategories.map { |s| { :name => s.name}},
    :entry_type     => entry_type_name,
    :document       => attachment
    }.to_json
  end

  def attachment
    if document.present?
      path_to_document = Rails.public_path+"/assets/entries/#{document_file_name}"
      Base64.encode64(open(path_to_document) { |file| file.read})
    end
  end


end
```

**Comment by karmi** [comment]
Debug the `Rails.public_path+"/assets/entries/#{document_file_name}"` path in console, or use `puts` within the method. Are you sure the file is there? Are you using some kind of asynchronous processing in Paperclip?

**Comment by rcalderon** [comment]
The path returned is the correct path. You're right, the file isn't there (yet). If I comment out the call to encode the file there is no error and Paperclip will save the file. I'm not telling Paperclip to do anything else with the attachment except encoding it so that it's indexed.

**Comment by karmi** [comment]
Check if Paperclip is handling the file save in synchronous/asynchronous way -- if it's the latter, you'll need to use some kind of observer, publish/subscribe mechanism to intercept when the file is saved and _then_ call `update_index`.

_UPDATE:_ Cf. https://github.com/thoughtbot/paperclip#events

**Comment by karmi** [comment]
@rcalderon Ping, any news?

**Comment by rcalderon** [comment]
@karmi sorry I missed your last update. I replaced paperclip with carrierwave and its working just fine. I might go back and troubleshoot paperclip asper your update, but for now, Tire is all good. Thanks for the help and the speedy replies!!
