### ISSUE TITLE
Keep getting connection refused error in dev mode

### ISSUE THREAD

**Issue by abitdodgy** [karmi/retire#503]
I installed Tire and managed to run it successfully. But, after restarting my computer, I keep getting a connection refused error. I searched for this and it seemed most people have that problem in production mode.

Errno::ECONNREFUSED in DiscussionsController#index
Connection refused - connect(2)

Any idea why this could be happening? I tried this in console, and I got the same error:

1.9.3p194 :017 > Discussion.tire.search
Creating scope :open. Overwriting existing method Discussion.open.
Errno::ECONNREFUSED: Connection refused - connect(2)

**Comment by karmi** [comment]
Most probably your elasticsearch server is down or unreachable. What did you searched & found? Is elasticsearch running at http://localhost:9200 or on the URL you have passed to `Tire.configure`?

**Comment by abitdodgy** [comment]
I tried a curl command and got:

$ curl http://192.168.1.138:9200
curl: (7) couldn't connect to host

Does Tire not start it up manually?

**Comment by karmi** [comment]
Tire is not elasticsearch -- you have to start the server either manually or at system start (with `launchd` on Mac OS X, `/etc/init.d` scripts on Linux, etc).

**Comment by abitdodgy** [comment]
Yeah, that was it. I guess because Tire automatically installed and started Elastic Search for me when I added it, I expected it would start ES when I started my Rails app.

**Comment by karmi** [comment]
No, only the example template does this, for convenience.
