### ISSUE TITLE
How to achieve Custom Routing using _routing field in elasticsearch

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#504]
I'm trying to use elasticsearch via tire gem for a multi-tenant app. The app has many accounts with each account having many users.

User Model:

```
  include Tire::Model::Search
  mapping do
    indexes :name, :boost => 10
    indexes :account_id
    indexes :company_name
  end

  def to_indexed_json
    to_json( :only => [:name, :account_id, :company_name], 
       )
  end
```

I would like to add the routing based on account_id. Please help how this can be achieved. I see that there are two ways to specify the routing.
1. during Mapping using the routing field
2. Using aliases

I'm interested in the first option. I see that _routing can be added to mapping section as a hash.

```
  mapping :_routing => { :required => true, :path => :account_id } do
    indexes :name, :boost => 10
    indexes :account_id
    indexes :company_name
  end
```

Search Query:

```
  User.tire.search do
    query do
      filtered do
          query { string('ovamsikrishna@gmail.com') },
          filter :term, :account_id => 2
      end
    end
  end
```

Do we need to specify anything in the search query? The indexing is not happening when I specify the mapping as specified above (with routing). Without routing it works fine.

**Comment by karmi** [comment]
Try `User.tire.search :routing => 2` and check back. Also, please post your mapping in a gist/pastie/etc to see if the `_routing` value has been picked up.

**Comment by karmi** [comment]
See the full code for an ActiveRecord model with routing below (use the _master_ branch):

``` ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'tire'
require 'active_record'

ActiveRecord::Base.establish_connection( adapter: 'sqlite3', database: ":memory:" )
ActiveRecord::Schema.define(version: 1) do
  create_table :my_models do |t|
    t.string   :title
    t.string   :account_id
  end
end

Tire.index('my_models').delete

class MyModel < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping _routing: { required: true, path: 'account_id' } do
    indexes :title
    indexes :account_id, type: 'string', analyzer: 'keyword'
  end
end

p MyModel.create( title: 'Doc for account 1', account_id: 1 )
p MyModel.create( title: 'Doc for account 2', account_id: 2 )

MyModel.index.refresh
# Tire.configure { logger STDERR }

puts "Doc 1:", MyModel.search(routing: 1) { query { all } }.first.inspect

puts "Doc 2:", MyModel.search(routing: 2) { query { all } }.first.inspect

puts "<nil>",  MyModel.search(routing: 3) { query { all } }.first.inspect
```

**Comment by vamsi-krishna-E0029** [comment]
The account_id is not included in all field in my actual index. Would that cause any problem? I'm actually getting zero hits.

```
indexes :account_id, :include_in_all => false
```

My mapping:

```
{
    "users":
        {"user":
            {"_routing":
                {"required":true,
                 "path":"account_id"},
                 "properties":
                     {
                      "account_id":
                         {"type":"string",
                          "include_in_all":false
                         },
                      "name":
                         {"type":"string",
                          "boost":10.0
                         },
                      "company_name":
                         {"type":"string"}
                     }
            }
        }
}
```

**Comment by karmi** [comment]
No, and the `account_id` should _not_ be in the `_all` field.

Please try out the code I posted and work from there.

Beware of a query like you do (e-mail adress), could be analyzed in a surprising way. Also, the `match` query -- newly added -- is better as a general purpose query.

**Comment by vamsi-krishna-E0029** [comment]
Thanks for the suggestion. Yes. I do know that it would be analyzed as ovamsikrishna, gmail.com. I have set the default analyzer with uax_url_email tokenizer and applied the standard analyzer filters to it.

I'm getting the following error:    "error":"RoutingMissingException[routing is required for [users]/[user]/[1]]","status":500
when I try to add routing. This is the reason I was getting zero hits I guess. As suggested I have added the routing option in the search query too. Not sure why I'm getting this error.

This error occurs when I try to import my users using

```
rake environment tire:import CLASS='User'
```

**Comment by karmi** [comment]
> rake environment tire:import CLASS='User'

The Rake task does not append any routing info to the requests, and at the moment `bulk_store` does not support routing, should be fixed soon.

To try it out, just save the records individually, working with the example I posted.

**Comment by karmi** [comment]
Your setup with a `required` mapping declaration and automatic path extraction is the right way to go.

The bulk support in Tire has been significantly improved in the 0.5.1 release, see changes: https://github.com/karmi/tire/compare/4e85109...1c0d043. You can now use the `Index#bulk` method to store documents with parent/child relationships.

Use the new support to write your own indexing logic, possibly taking inspiration from the `import` infrastructure. Closing this issue, open a new one if you hit any problems.

Once again, please pay close attention to the working code with an isolated example I have posted above.
