### ISSUE TITLE
What is the best possible way to index in a Multi-tenant app?

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#506]
I see that these are the possible options.
- Index per account
- a filtered alias per account
- filter by term in search query

Please help if there are any other options.

The app has many accounts with each account having many users. The users of each account should not be visible to other accounts.

Is the option Index per account scalable? (The number of indices is say around 30k)
How can this be achieved?

But, if I go for the last option I see that the number of shards must be more which hits the search performance. (Single index for all the users, say a million, and filter based on account).

**Comment by karmi** [comment]
Filtered alias with routing is you best option. You can combine it with a “sliding window” scenario, where you don't keep all the data, but only eg. last three months. See the http://www.elasticsearch.org/videos/2012/06/05/big-data-search-and-analytics.html video for explanation of possible approaches.

**Comment by vamsi-krishna-E0029** [comment]
How do I create an alias for automatically created index?

My index for user model is created using:

```
  include Tire::Model::Search
  mapping do
    indexes :name, :boost => 10
    indexes :account_id
    indexes :company_name
  end

  def to_indexed_json
    to_json( :only => [:name, :account_id, :company_name], 
       )
  end
```

How do I access add_alias method in this case?

**Comment by karmi** [comment]
1. Do not rely on automatic index creation for advanced workflows & situations.
2. Prepare index in advance, create alias, use `MyModel.index_name` to use the alias.

**Comment by vamsi-krishna-E0029** [comment]
Creating a filtered alias for each account. How different is it from index per each account?

**Comment by karmi** [comment]
Less resource intensive then having an index for each account.

**Comment by vamsi-krishna-E0029** [comment]
I have actually created an alias and filtered using account id (filtered alias). If I apply routing as specified below will that hit the specific shard or all the shards?

User model:

```
      include Tire::Model::Search

      Tire.index('users') do
        create(
          :mappings => {
            :user => {
              :properties => {
                :name => { :type => :string, :boost => 10 },
                :account_id => { :type => :integer, :include_in_all => false }
              }
            }
          }
        )

        add_alias "index_users_2", :filter => { :term => { :account_id => 2 } }, :routing => 2
      end
```

Or do I have to specify the routing option in the search query also for hitting the specific shard?

Search query:

```
       Tire.search ['users'], :load => true do
          query do
            filtered do
                query { string search_string },
                filter :term, :account_id => 2
            end
          end
        end
```

One more question, this being a multi-tenant app, the account_id is varies. So, how do I create alias which varies as per current account id? I have excluded the callbacks inorder to support rails 2.3 ( as per https://github.com/loe/tire/commit/53d851098c86ba210a6b9d4168e65693941ce51b ). Will index_name work for me in that case?

**Comment by karmi** [comment]
1. once you start using routing, you have to use the `routing` parameter _everywhere_: indexing, searching, ...
2. I hope you're using `add_alias` in your model only as an example. In a real situation, you'll create an alias when a new account is succesfully created (paid/etc), and you _can't_ use `MyModel.index_name` for searching. 

The discussion in the karmi/tire#92 is relevant to the problem you're having.
