### ISSUE TITLE
Using missing filter

### ISSUE THREAD

**Issue by azitabh** [karmi/retire#507]
Is http://www.elasticsearch.org/guide/reference/query-dsl/missing-filter.html supported in Tire?

I have a list of documents. I want to pick ones where ((the tag 'a' has value 'abcd' or the tag 'a' doesn't exist) and (the tag 'b' has value 'wxyz' or the tag 'b' doesn't exist)).

I need missing filter to form this query.

And, Is this the right place to ask questions?
I usually don't get answers at stackexchange and we don't have a google group.

Thanks
-Azitabh

**Comment by karmi** [comment]
All filters should be supported, they're just tiny wrapper around hashes, see https://github.com/karmi/tire/blob/master/test/integration/filters_test.rb

This is a good place to ask questions, StackOverflow works fine as well, though it's better for higher-level questions in my opinion.

Tire questions can absolutely be also sent to the main ES mailing list, https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch

**Comment by karmi** [comment]
@azitabh Hello, any news?

**Comment by azitabh** [comment]
@karmi sorry for not closing the issue on time... got my answer.

**Comment by karmi** [comment]
@azitabh No worries, good it's resolved!
