### ISSUE TITLE
Documentation regarding pagination could use improvement

### ISSUE THREAD

**Issue by daveworth** [karmi/retire#508]
Hello,

We use TS/Tire in production in a medium sized application but with LOADS of records we index across.  Of course we ran into memory issues during indexing, then found that batching them manually was possible, then we found the documentation about pagination being used automagically by Tire.  What was not clear, until we dug into the issues history and patches was that Kaminari is supported out of the box by simply adding it to the Gemfile of a Rails app.  I would happily write this up and add to the documentation but rather than just forking and adding a pull-request, I wanted your blessing first.

Regards,
Dave

**Comment by karmi** [comment]
Dave, a rare foresight these days, thanks! :) You're right, I think the it would be sufficient to just mention Kaminari in the relevant README paragraph:

> Note that Tire search results are fully compatible with will_paginate (...)

What do you think?

**Comment by daveworth** [comment]
@karmi, my pleasure!  The less thinking I have to do as a developer, as a side effect of documentation, the easier my life is!

I am a huge fan of over-communication in these cases.  I might say 

"Tire search results (and indexing) are fully compatible with common pagination libraries including [`will_paginate`](https://github.com/mislav/will_paginate) and [`Kaminari`](https://github.com/amatsuda/kaminari).  To use `will_paginate` [current example here].  To use Kaminari [new example here]."

Then the section below on indexing requires no changes at all.

Let me know how I can help.

Thanks!
Dave

**Comment by karmi** [comment]
I like the wording! I'm not sure about the examples -- the Rake task injects the `paginate` method when it detects Kaminari... Definitely go forward with it.

**Comment by daveworth** [comment]
Excellent.  Will do!  I didn't realize that the rake task did that so I will make sure I understand this more thoroughly when writing the docs.  Thanks!

**Comment by karmi** [comment]
@daveworth One of the things I'm working right now is re-considering and re-writing the _Tire_ documentation. I'll keep this discussion in mind -- should we close this issue?

**Comment by daveworth** [comment]
Sure, or you can hold me accountable to write this.  I should be able to do it this week.
