### ISSUE TITLE
Unable to get Custom routing to work with existing code

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#512]
For custom routing, I have tried this for my user model (multi tenant app - account based with many users per account).

```
  mapping :_routing => { :required => true, :path => :account_id } do
    indexes :name, :boost => 10
    indexes :account_id
    indexes :company_name
  end
```

The search query is given as follows:

```
       Tire.search ['users'], :load => true, :routing => 2 do
          query do
            filtered do
                query { string search_string },
                filter :term, :account_id => 2
            end
          end
        end
```

That doesn't seem to work for me. I have forked the repo and made the changes as per  https://github.com/loe/tire/commit/53d851098c86ba210a6b9d4168e65693941ce51b as I'm using rails 2.3.x.

On investigating I found that, the indexing itself is failing to get the routing value.

In the store method of index.rb (https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L65)

```
id       = get_id_from_document(document)
```

and

```
url  = id ? "#{self.url}/#{type}/#{id}#{params_encoded}" : "#{self.url}/#{type}/#{params_encoded}"
```

No where in this method the routing option is considered. How would the custom routing be applied if I choose to apply one?

Am I missing something here? The params_encoded in my case seems to be empty and id always exists.

I see only the percolate option being set in update_index method of search (https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L143)

I have made a change in index.rb to achieve custom routing and changed the url like,

```
url  = id ? "#{self.url}/#{type}/?routing=document.#{custom_routing_parameter}
```

This worked. Let me know if this change is really necessary for custom routing to work.

**Comment by karmi** [comment]
Sorry about this -- it is now possible to pass the `routing` value explicitely:

```
Tire.index('myindex').store( {:id => 1, :title => 'Test'}, {:routing => 'abc'} )
```

When you use the `mapping :_routing => { :required => true, :path => :account_id }` configuration, the routing information is parsed from the document itself, no need to pass it in URL params.
