### ISSUE TITLE
loaderror

### ISSUE THREAD

**Issue by cpuguy83** [karmi/retire#513]
I have an AR model called "Tracker::DB::Service", which is located in tracker/db/service.rb
This 100% works (and runs in production).

In doing some dev work to integrate tire/elasticsearch I am able to build my index, but when I search I get the following behavior:
- I can run the search and get a tire search object back.
- If I store the search object in a variable and call a method on it, such as to_json, it returns the json results but am no longer able to access the data from the variable at all with a LoadError:
  `LoadError: Expected .../tracker/db/service.rb to define Tracker::Db::Service`
  (notice the lowercase "b" in "Db"
- If I try to pull results it gives the same load eeror

**Comment by karmi** [comment]
Hmm, this sounds tricky. Namespaced models are always a bit tricky with Rails.
1. Could you please pastie a full backtrace of the error, so I can see where it's being triggered?
2. Could you just manually `require` that file in your app initializer etc., so it's already loaded when the Rails auto-loading mechanism tries to access it?

There may be an error in the [`camelize.constantize`](https://github.com/karmi/tire/blob/master/lib/tire/results/item.rb#L71) code in the `Item` class.

**Comment by cpuguy83** [comment]
Full Trace:

``` rube
LoadError: Expected /Users/bgoff/dev/emp2/app/models/tracker/db/service.rb to define Tracker::Db::Service
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:503:in `load_missing_constant'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:192:in `block in const_missing'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:190:in `each'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:190:in `const_missing'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/ext/module.rb:36:in `const_missing'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:230:in `block in constantize'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `each'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:229:in `constantize'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/tire-0.5.1/lib/tire/results/collection.rb:118:in `block in __get_results_with_load'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/tire-0.5.1/lib/tire/results/collection.rb:112:in `each'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/tire-0.5.1/lib/tire/results/collection.rb:112:in `__get_results_with_load'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/tire-0.5.1/lib/tire/results/collection.rb:27:in `results'
    from (irb):19
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/bgoff/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'1.9.3p194 :020 >
```

**Comment by cpuguy83** [comment]
Yeah, it looks like that's the issue.
The results have "tracker/db/service"  and when you do a camelize it changes it to 'Tracker::Db::Service'

**Comment by karmi** [comment]
@cpuguy83 Hey, any news on the issue? Solved, or should we continue debugging it?

**Comment by cpuguy83** [comment]
Setting cache_classes to true in my development.rb seems to work.
So it looks like when tire goes to reload my class (since it's not cached by default in dev) it's giving the error.  Not a issue in production.

**Comment by cpuguy83** [comment]
I lied, results are still not working.

**Comment by karmi** [comment]
@cpuguy83 I'm afraid not much can be done in Tire here -- `Item` uses the default `constantize` to get the class name from the document `_type`. It could be possible to override `Tire::Collection#__find_records_by_ids`. Catch me in #elasticsearch on Freenode so we can debug it in realtime.

**Comment by karmi** [comment]
@cpuguy83 Hello, any news on the situation?

**Comment by cpuguy83** [comment]
I'm probably just going to rename my classes to Tracker::Db::, instead.
Did a simple replace in my project and it seems to work just fine.  

Seems a better solution than monkey patching code.  

## 

Brian Goff

**Comment by karmi** [comment]
@cpuguy83 So, in favour of closing?

**Comment by cpuguy83** [comment]
Yep, sorry.
