### ISSUE TITLE
Multiple model single index approach

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#514]
In my multi-tenant app (account based with number of users per account), how would I update index for a particular account when a user document is changed.

Rails 2.3 app applied changes as per https://github.com/loe/tire/commit/53d851098c86ba210a6b9d4168e65693941ce51b

**Account Model**

```
      include Tire::Model::Search

      Tire.index('account_1') do
        create(
          :mappings => {
            :user => {
              :properties => {
                :name => { :type => :string, :boost => 10 },
                :company_name => { :type => :string, :boost => 5 }
              }
            },
            :comments => {
              :properties => {
                :description => { :type => :string, :boost => 5 }
              }
            }
          }
        )
      end
```

As you can see above, there are two models here user and comments. Is it the correct way to address single index with multiple models.

In that case how do I update index when a user document or comment document alone is changed.

**Comment by karmi** [comment]
> In my multi-tenant app (account based with number of users per account), how would I update index for a particular account when a user document is changed.

I can't say I understand 100% what are you trying to do, but basically, for models, just call `update_index`, it does honor the `index/type` structure, or just use `Tire.store` with a proper index name and document type.

**Comment by vamsi-krishna-E0029** [comment]
How do I update an index based on it's name? I mean if I want to update an index like users, how can I do something like tire.update_index 'users'. The index name may vary in my case. Is that possible? The index name isn't  dynamically generated one in my case.

**Comment by karmi** [comment]
Since you have a separate index for each model, just call `@record.tire.update_index`. It will pick up whatever index name you've set in the class.

Otherwise, use `Index#store` to roll your own indexing strategy. If this is still about the "multi-tenancy" aspect, I really don't understand what you're doing, if you have an index for each account, if you use aliases, etc.

> The index name may vary in my case. (...) The index name isn't dynamically generated one in my case.

I don't know what you mean. You're refering to dynamic index names by passing a block to `index_name`, eg. `ActiveRecordClassWithDynamicIndexName` in `test/models`?

**Comment by vamsi-krishna-E0029** [comment]
Thanks for the reply.

I don't have a separate index for each model. I have a separate index for each account, in which the mappings for each model (user and comments) are specified. In this case if any change has been done for user model or comment model, the index that has been created for the related account has to be updated. Is this possible? Please let me know if yes.

I guess this is the way I specify the mappings in my case. Correct me if I'm wrong.

**Account Model:**

```
  include Tire::Model::Search

  Tire.index('account_1') do
    create(
      :mappings => {
        :user => {
          :properties => {
            :name => { :type => :string, :boost => 10 },
            :company_name => { :type => :string, :boost => 5 }
          }
        },
        :comments => {
          :properties => {
            :description => { :type => :string, :boost => 5 }
          }
        }
      }
    )
  end
```

The index is getting created correctly with both the mappings for account index. But, I don't see a way where I can update the index when any model specified in the mappings are changed.

Whenever a new user is added or if an user is updated the index created for the corresponding account has to be updated.

**Comment by karmi** [comment]
Hello, sorry for the delay.

>  I have a separate index for each account, in which the mappings for each model (user and comments) are specified. In this case if any change has been done for user model or comment model, the index that has been created for the related account has to be updated. Is this possible? Please let me know if yes.

This is a tricky thing to do, the only real solution I have found in several projects is to just "switch" the index/database name based on some criteria in your application (logged-in user, etc).

Please see the karmi/tire#92 issue for a lot of _Tire_ historical trivia, there is a [solution](https://github.com/karmi/tire/pull/92#issuecomment-6929988) outline at the end as well.

> Whenever a new user is added or if an user is updated the index created for the corresponding account has to be updated.

Yes, this is something you need to handle in your application.

**Comment by karmi** [comment]
Hello, had a look at the solution?

**Comment by vamsi-krishna-E0029** [comment]
Oops sorry...Will look into it. Thanks for the reply.

**Comment by karmi** [comment]
@ovamsikrishna Hello, any news? Closing?
