### ISSUE TITLE
Index does not update

### ISSUE THREAD

**Issue by yeehaa123** [karmi/retire#516]
Hi all,

Probably missing something very obvious, but I cannot figure it out. I have tire on several models. All of them update automatically after save, except for one. I added the following lines manually: 

after_save do
   Tire.index(INDEX_NAME).import(Reference.all)
end

It works, but I don't think this is the right way to do this. Can anyone help me with this problem?

Best,

JH

**Comment by karmi** [comment]
> It works, but I don't think this is the right way to do this. 

It's not :) You're effectively reindexing the whole index on each save. Either use the `include Tire::Model::Calbacks` support, or just trigger `update_index` manually in the hook -- see Readme.

(Post more code+info if the situation is more complex.)

**Comment by yeehaa123** [comment]
Thanks for the quick reply! 

I tried both already, but neither one of them seem to work.

My entire model looks like this:

```
class Reference
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field   :title, type: String
  field   :publication_date, type: DateTime
  field   :tags, type: Array
  field   :author_list, type: String
  slug    :to_s

  attr_accessible :sessions, :title, :authors, :translators, :editors, 
              :publisher, :publication_date, :tags, :set_tags, :tags

  has_and_belongs_to_many   :authors
  has_and_belongs_to_many   :translators, class_name: "Author"
  has_and_belongs_to_many   :editors, class_name: "Author"
  has_and_belongs_to_many   :sessions

  validates_presence_of :title

  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name INDEX_NAME

  before_save :generate_author_list
  before_save :set_tags 
  after_save do
    Tire.index(INDEX_NAME).import(Reference.all)
  end 


  def to_indexed_json
    self.to_json
  end

  def self.search(params={})
    tire.search(load: true, per_page: 50, type: nil) do
      query do 
        boolean do
          must { string params[:query], default_operator: "AND" } if params[:query].present?
          must { term :tags, params[:tags] } if params[:tags].present?
          must { terms :_type, ["reference", "chapter", "magazine_article", "journal_article", "monograph"] }
       end
     end
     facet('tag_list') { terms :tags, order: 'term' }
   end
end

def set_tags
  if tags
    tags.each do |tag|
      begin
        Tag.find_by(name: tag)
      rescue
        Tag.create(name: tag)
      end
    end
  end
end

def to_s
  title.titleize
end

def generate_author_list
  self.author_list = if authors.size > 0
    authors.map(&:to_s).join(". ")
    else
      ""
    end
  end
end
```

What am I missing here?

**Comment by karmi** [comment]
Hi, are you sure the `after_save` callback is triggered? Also, definitely switch from the `import` call to just updating the index for that specific model.

And finally, could you describe the error in more detail? All of your records are indexed, but one is not? What if you try to save that record eg. in a IRB session / Rails console, does it trigger any error?

I don't see any obvious error in your code -- for most people/situations, just `include Tire::Model::Callbacks` is enough to get it working.

**Comment by karmi** [comment]
@yeehaa123 Hello, any news?
