### ISSUE TITLE
Multi Tenancy

### ISSUE THREAD

**Issue by amejiarosario** [karmi/retire#519]
How do I use Multi Tenancy with Tire? I have multiple tenants in my application and need to index their data in multiple namespaces. Let's say I have this model in Rails.

```
class Article < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end
```

 How do I keep the index of the articles of the different users separated? Because if I index as it is right now, they will see results from other users... 
(BTW, I'm using https://github.com/influitive/apartment gem for multi-tenancy)

**Comment by karmi** [comment]
Hi, that's really a complicated question:

1/ You have several strategies for multi-tenancy, depending on the volume of your data and use-case. You can separate users by indices, or use a document property such as `account_id`.

2/ You can use index _aliases_ to handle the situation opaquely to the application -- and index alias can contain routing and filters, so it's a "logical" index. Please search Tire's issues, test suite, and the web for context.

3/ You can use the "required routing" feature to embed the routing factor in the document, see eg. issue #506

Also, make sure to see the following video: http://www.elasticsearch.org/videos/2012/06/05/big-data-search-and-analytics.html

**Comment by karmi** [comment]
@amejiarosario Hello, any news?

**Comment by karmi** [comment]
Closing as abandoned.
