### ISSUE TITLE
URL with slash breaks tire

### ISSUE THREAD

**Issue by wulffeld** [karmi/retire#52]
Doing

``` ruby
Tire.configure do
  url "http://localhost:9200/"
end
```

results in a bunch of:

```
[ERROR] 500 Internal Server Error:{"error":"ElasticSearchException[String index out of range: 0]; nested: StringIndexOutOfBoundsException[String index out of range: 0]; ","status":500}, retrying (1)...
```

Given the error looks javaish I wasn't suspecting it to be the configuration - also because I could see it did connect to ES.

So I propose tire checks the format of the string or URI.parse's it.

**Comment by karmi** [comment]
Hi, is this really something worth additional three lines of code and unit tests? :)

**Comment by wulffeld** [comment]
Entirely up to you :) I managed to waste a couple of hours figuring out the error. Probably would suffice to just add a comment in the README about it?

**Comment by karmi** [comment]
>  I managed to waste a couple of hours figuring out the error. 

Then it's definitely worth it :)
