### ISSUE TITLE
Problem with bulk indexing with Tire 0.5.1

### ISSUE THREAD

**Issue by danielschlegel** [karmi/retire#522]
Hi Karmi
I've updated to Tire 0.5.1 from 0.4.3. Since this update some tests fail with:  NoMethodError: undefined method `serializable_hash' for #MyClass:0x007f9e9a656b80

MyClass is not an active record Model.
MyClass defines to_indexed_json.

```
class MyClass

  include Tire::Model::Search 

  attr_accessor :id, :name 

  tire do
    mapping do
      indexes :id,      :type => 'long',   :index => :not_analyzed, include_in_all: false
      indexes :name,           :type => 'string', :analyzer => 'snowball'
  end

  def to_indexed_json
    {
        :id => id.to_s,
        :name
    }.as_json
  end

Tire.index(MyClass.tire.index.name) do
        import(array_of_myclass_objects, :raise => true)
        refresh # commit immediately
end
```

Any Idea?

**Comment by nitsujw** [comment]
I use datamapper and ran into this with 0.5.1, if you "include ActiveModel::Serialization" that solves serializable_hash issue.

**Comment by danielschlegel** [comment]
Thanks! Unfortunately i just get another error:

NameError: undefined local variable or method `attributes' for #<MyClass:0x007f941dfa99a8>
/Users/user/.rvm/gems/ruby-1.9.3-p194-perf/gems/activemodel-3.2.8/lib/active_model/serialization.rb:74:in`serializable_hash'

**Comment by karmi** [comment]
@danielschlegel What kind of ActiveModel integration is your class using?

**Comment by danielschlegel** [comment]
Normally we have mongoid but this is not a "Database Model". There is no ActiveModel integration, just a PORO.

**Comment by karmi** [comment]
@danielschlegel Then you have to bring the stuff provided by ActiveModel in, manually. Have a look eg. at the [`ActiveModelArticle`](https://github.com/karmi/tire/blob/master/test/models/active_model_article.rb) PORO in the test suite.

Also, do note, that you don't have to work with Tire via the full model integration -- you can just use `Tire.search` and use a custom `wrapper`. It could be a viable solution for your use-case, maybe?

**Comment by danielschlegel** [comment]
Thanks alot, the ActiveModel stuff made my tests running.

**Comment by karmi** [comment]
@danielschlegel Cool!
