### ISSUE TITLE
Persistence module creates wrong mapping

### ISSUE THREAD

**Issue by lasssim** [karmi/retire#523]
hi,

i'm not quiet sure if i'm missing something or if it is a bug in your gem.

i tried to create a model that uses your Persistence module:

``` ruby
class ElasticPoint
  include Tire::Model::Persistence

  mapping do
    property :parent_id, type: 'string'
    property :parent_type
    property :location, type: 'geo_point'
  end
end
```

the mapping that i get from the elasticsearch api is this:

``` json
{
  "elastic_points" : {
    "elastic_point" : {
      "properties" : {
        "location" : {
          "type" : "string"
        },
        "parent_id" : {
          "type" : "long"
        },
        "parent_type" : {
          "type" : "string"
        }
      }
    }
  }
}
```

which seems wrong for the properties location and parent_id.

i further tried to figure out what my mistake was and played around with your tests in "test/unit/model_persistence_test.rb". (sorry for the ugly debug stuff, but i think it demonstrates my problem well enough)

``` ruby
should "create the index with mapping" do
  expected = {
    :settings => {},
    :mappings => { :persistent_article_with_mapping => {
      :properties => { :title => { :type => 'geo_point', :analyzer => 'snowball', :boost => 10 } }
    }}
  }

  Tire::Index.any_instance.stubs(:exists?).returns(false)
  Tire::Index.any_instance.expects(:create).with(expected)

  class ::PersistentArticleWithMapping

    include Tire::Model::Persistence
    include Tire::Model::Search
    include Tire::Model::Callbacks

    mapping do
      property :title, :type => 'geo_point', :analyzer => 'snowball', :boost => 10
    end

  end

  require 'tire/http/clients/curb'

  puts "mapping before creation from elasticsearch api"
  puts Curl.get("http://localhost:9200/persistent_article_with_mappings/_mapping?pretty").body_str

  PersistentArticleWithMapping.create(title: "48,14")
  sleep 1

  puts "mapping after creation from elasticsearch api"
  puts Curl.get("http://localhost:9200/persistent_article_with_mappings/_mapping?pretty").body_str

  puts "mapping after creation from tire gem"
  puts PersistentArticleWithMapping.mapping.inspect

  assert_equal 'snowball', PersistentArticleWithMapping.mapping[:title][:analyzer]
  assert_equal 'geo_point', PersistentArticleWithMapping.mapping[:title][:type]


end
```

this is the output that i get:

``` json
mapping before creation from elasticsearch api
{
}
mapping after creation from elasticsearch api
{
  "persistent_article_with_mappings" : {
    "persistent_article_with_mapping" : {
      "properties" : {
        "title" : {
          "type" : "string"
        }
      }
    }
  }
}
mapping after creation from tire gem
{:title=>{:type=>"geo_point", :analyzer=>"snowball", :boost=>10}}
```

it seems as if the options hash is not propagated to elasticsearch.  

would be great if you could take a look and give me feedback.

thx, simon

**Comment by karmi** [comment]
It is more like a violation of "principle of least surprise" then bug .) I think your index has been created previously, with a different mapping. Then you have changed the mapping, but you have to recreate the index in this case.

Try out the following code, which works for me:

``` ruby

require 'tire'

Tire.index('my_documents').delete

class MyDocument

  include Tire::Model::Persistence
  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    property :title, type: 'string', analyzer: 'snowball', boost: 10
    property :location, type: 'geo_point'
  end

end

puts RestClient.get( "http://localhost:9200/my_documents/_mapping?pretty" )
```

We can work from there.

**Comment by ches** [comment]
I was tripped up at first by the difference between these:

``` ruby
MyDocument.index.create
MyDocument.create_elasticsearch_index
```

The former simply creates the index, the latter creates _and applies your mapping config_. If you do the former and add some documents, you'll end up with dynamic mapping.

**Comment by karmi** [comment]
@lister Hello, any news on the issue?

@ches Yes -- the former is just a reference to the `Tire#index` for the model, without any settings. I do agree it'd be nice to take any settings and mappings set in the model into account.

**Comment by pangkalizer** [comment]
im getting same issue .. trying to work geo_distance search with Tire::Model::Persistence .. 

one thing i noticed is when you wrap the properties inside mapping -- your geo_point fields will be mapped with proper type BUT you can't query/filter or even sort them

any idea?

**Comment by karmi** [comment]
@pangkalizer What "same issue"? Please see the code I posted above, try it out, and try to replicate with your codebase. Then please post info + code here. (To reiterate: make sure you re-create the index, make sure you post your index mapping.)

**Comment by karmi** [comment]
@lister Has the issue been successfuly resolved for you?

**Comment by lasssim** [comment]
sorry for my late reply. 

i was in kind of a hurry because i had to release the feature i was working on so i came up with this solution: i manually created my index by a method that i manually run a shell before the first start of the server of an environment. i also use this in my tests.
here is the snippet that creates the mapping for MyDocument.

``` ruby
Tire::Configuration.client.put(
  "#{Tire::Configuration.url}/my_index/#{MyDocument.document_type}/_mapping",
  MyDocument.mapping_to_hash.to_json
)
```

i had no time to investigate further, sry. but i might look at the issue again in the next weeks.

**Comment by karmi** [comment]
@lister You can just drop the index and then call `MyDocument.create_elasticsearch_index`.

**Comment by lasssim** [comment]
i know. sry, i didn't want to over complicate things in this ticket, which might have caused more confusion than i intended.

the index of MyDocument is actually a child index of another model. i didn't find any other solution for creating such a index without creating the index with my last snippet. the problem is, that if i create the index of my parent model first and then use create_elasticsearch_index to create the child type withing the parent index i get an IndexAlreadyExistsException from elasticsearch. modfying the index using the put method worked for me.

**Comment by pangkalizer** [comment]
@karmi its all good... dynamic mapping causes the problem... i thought i was recreating the mapping by calling MyModel.index.delete alone before populating the data... so i have to call MyModel.create_elasticsearch_index after index.delete to make sure everything is reset. however once you populate the index and pass hash value to one field causes dynamic mapping, causing weird behaviour on ES searching (tested outside tire). 

what is the proper way to disable dynamic mapping when using Persistence? i tried   :mapper => {  "dynamic" => "false"  }  but doesn't seems to work... it still generates dynamic mapping. i got rid of it by saving it as YAML or string. that good for now. Persistence model with geo_distance filter and sorting is now working.. 

Really cool gem you got there btw..

**Comment by karmi** [comment]
>  however once you populate the index and pass hash value to one field causes dynamic mapping

Yes, that is the default behaviour. You can disable dynamic mapping with [`index.mapper.dynamic:false`](http://www.elasticsearch.org/guide/reference/mapping/dynamic-mapping.html).

Something like this should do it:

``` ruby
require 'tire'

Tire.configure { logger STDERR }

class MyDoc
  include Tire::Model::Persistence

  settings index: {
    mapper: {
      dynamic: false
    }
  }

  property :title, type: 'string', analyzer: 'english'
end

MyDoc.index.delete
MyDoc.create_elasticsearch_index

MyDoc.create title: 'Test'

# Check:
#
# * http://localhost:9200/my_docs/_mapping
# * http://localhost:9200/my_docs/_settings
#
```

**Comment by karmi** [comment]
@lister @pangkalizer So, problems solved? Closing?

**Comment by pangkalizer** [comment]
Solved...

**Comment by karmi** [comment]
Closing as solved.
