### ISSUE TITLE
Include as_json in Tire::Results::Item

### ISSUE THREAD

**Issue by tbk303** [karmi/retire#527]
Please include an override of `as_json` in the `Tire::Results::Item` class like this:

```
def as_json options = {}
    @attributes.as_json options
end
```

(along the lines of the overriden `to_json` method)

This will enable proper JSON rendering Rails 3 style (see http://stackoverflow.com/questions/2572284/how-to-override-to-json-in-rails/2574900#2574900 as reference, for example)

**Comment by karmi** [comment]
Hi, could you provide more context here, so I know what is the exact issue and maybe even what kind of test add for this?

---

Notice I can easily do:

``` ruby
def search
  @articles = Article.search do
    # ...
  end

  respond_to do |format|
    format.html { render :action => "index" }
    format.json { respond_with(@articles.to_a) }
  end
end
```

**Comment by tbk303** [comment]
I want to customize the JSON returned by my contoller, like this:

```
 render json: search.results.as_json(except: [:foo, :bar])
```

I know this is possible by passing those options to `to_json` as well, but the whole JSON-rendering-thing in Rails has changed (see the link I mentioned) and customizing the structure of JSON is now done through `as_json` while the actual rendering (i.e. producing a string) is done by `to_json`

**Comment by karmi** [comment]
@tbh I understand the difference between `to_json` and `as_json`. We can add a custom `as_json` implementation as you suggest, but the serialization is handled by [`ActiveModel::Serialization`](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/serialization.rb) module. We should make it work with that, possibly supporting the XML serialization as well...?

**Comment by karmi** [comment]
@tbh Could you please either shed more light on the issue or post some code so I can uderstand you better?

**Comment by tbk303** [comment]
Sorry, I kind of lost this. I directly feed the elasticsearch results through our REST API to the outside world. Hence I want to exclude some of the data (i.e. mostly the _\* stuff like _score or _version). Through that overloaded `as_json` method, I am able to take control of the structure of the JSON returned by my API but leave the actual rendering to Rails (as explained in the link above, starting with Rails 3), like so:

```
search = Foo.tire.search ...
render json: search.results.as_json(except: [:_score, :_version, :_explanation])
```

**Comment by karmi** [comment]
@tbh Had a look at this today. I understand your problem -- the `Tire::Results::Collection` and `Tire::Results::Item` instances should be now 100% Rails `as_json`-compatible, so you can do something like:

``` ruby
    def search
      @articles = Article.search do ... end
      respond_to do |format|
        format.html { render :action => "index" }
        format.json { render json: @articles.as_json(only: ['id', 'title']) }
      end
    end
```

I did the implementation in Tire, not leveraging the `ActiveSupport::Serialization` infrastructure. The `as_json` methods proxy down to _ActiveSupport_ implementations.

**Comment by tbk303** [comment]
Great! Thank you!
