### ISSUE TITLE
Bulk import MYSQL table using Tire

### ISSUE THREAD

**Issue by visasquare** [karmi/retire#530]
Hi Karmi, 

Is there a way that I can bulk import my documents(part of mysql table) into elastic search. Till now I have been using river-jdbc but I really want to do it using tire as I get lot of flexibility in defining multi field indexes using Tire.

Thanks!

**Comment by visasquare** [comment]
Got the answer by reading through the documents. we can set the pagination and acheive bulk import

:per_page => 1000

Thanks Karmi!

**Comment by karmi** [comment]
Hi, yes, you can pass specific `:per_page` on the command line:

```
rake environment tire:import CLASS='Article' INDEX='articles-2011-05' PARAMS={per_page:10000}
```

When you want to index a specific subset of records, with a specific SQL query, it may well pay off to write your own, custom indexing code. [`ActiveRecord#find_in_batches`](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches) makes it very convenient:

``` ruby
Article.where("published_on > ?", Time.parse("2012-10-01")).find_in_batches do |group|
  Tire.index('myindex').import group
end
```
