### ISSUE TITLE
Can't get highlight to work

### ISSUE THREAD

**Issue by filiptepper** [karmi/retire#533]
Hey everyone,

I'm having some issue getting highlight response from elastic search.

Here's my model:

```
class Post < ActiveRecord::Base
  include Tire::Model::Search

  settings :number_of_shards => 1, :number_of_replicas => 1,
    :analysis => {
      :analyzer => {
        :default => {
          :type      => "custom",
          :tokenizer => "standard",
          :filter    => "standard, lowercase, morfologik_stem, unique, lowercase"
        }
      }
    }

  mapping do
    indexes :id,    :index => :not_analyzed
    indexes :title, :analyzer => "snowball", :boost => 100
    indexes :body,  :analyzer => "snowball"
  end

  after_save do
    update_index if deleted_at.nil?
  end
  def to_indexed_json
    {
      :title => self.title,
      :body  => self.body,
      :id    => self.id
    }.to_json
  end
```

And here's the query:

```
@results = Post.search do
  query do
    string q
  end
  page = current_page
  per_page = 20
  highlight :body, :title
end
```

The issue here is that in the response from elasticsearch I'm always getting nil for higlights. Is this an error on my end?

**Comment by ike-bloomfire** [comment]
What code are you using to out put your highlights?

**Comment by filiptepper** [comment]
Right, forgot about this. _eh_

Tried a couple of options, including inspecting the objects and HTTP requests. Always highlight was nil. Is that an issue with tire request or elasticsearch response?

```
@results.each do |result|
  p result.highlight
end
```

**Comment by ike-bloomfire** [comment]
I'm really not sure why that would happen, have you taken a look at the responses Tire logs

you can use this to set it up

```
Tire.configure { logger 'elasticsearch.log', :level => 'debug' }
```

the responses are logged as well (see the docs) that should help you go a little further, I should think.

**Comment by ike-bloomfire** [comment]
Also happened across this in the Elasticsearch documentation

Highlighting http://www.elasticsearch.org/guide/reference/mapping/all-field.html
_For any field to allow highlighting it has to be either stored or part of the _source field. By default _all field does not qualify for either, so highlighting for it does not yield any data_

Then from the Source page http://www.elasticsearch.org/guide/reference/mapping/source-field.html
_The _source field is an automatically generated field that stores the actual JSON that was used as the indexed document_

So it would appear that your to_indexed_json method might not be working the way you want

**Comment by karmi** [comment]
@ike-bloomfire Thanks for the assistence!

@filiptepper OK, sorry for the delay, on it now!

First, let's start with a working piece of code:

``` ruby
require 'tire'

Tire.index 'highlight' do
  delete
  create

  store id: 1, body: "The quick brown fox jumps over the lazy dog", author: "Johnny Fox"
  store id: 2, body: "Lazy dog jumps over the quick brown fox", author: "Fox Vicious"
  store id: 3, body: "A Fox one day fell into a deep well and could find no means of escape. A Goat, overcome with thirst, came to the same well, and seeing the Fox, inquired if the water was good. ...", author: "Aesop"
  refresh
end

s = Tire.search 'highlight' do
  # query { string 'fox' }
  query { match :body, 'fox' }
  highlight 'body', 'author', options: { tag: '***' }
end


s.results.each do |document|
  puts "Document #{document.id} highlights: #{document.highlight.inspect}"
end
```

Actually, that would be my first advice: whenever stuck like this, it's a good idea to drop down and create a working bare-bones code and work up from that.

Second, notice that the `match` query is generally preferred. Elasticsearch tries hard to make this query generally both useful and peformant, and Tire wraps it in a nice interface (tire@9a6e00e).

Third, be careful with the `string` query. By default, it runs on the dynamic `_all` field, which uses a different analyzer then your `title` and `body` properties. So you may get tricky results/highlights, or no results/highlights at all.

Your invocation of `highlight` is correct in the `search do ... end` block, try highlighting just one field, make sure the index is refreshed, etc etc etc. Use the (multi)match query, or an equivalent `string "body:#{q} OR title:#{q}"` fully qualified query.

Do notice that the `page` and `per_page` methods do not belong to the block -- either use `size`/`from` or `page`/`per_page` as arguments. The integration tests have a lot of examples.

Finally, do check the highlight [integration tests](https://github.com/karmi/tire/blob/master/test/integration/highlight_test.rb), if they run for you, there may be some  bug I'm not aware of.

Ping back with results!

**Comment by filiptepper** [comment]
Thanks @karmi and @ike-bloomfire, fixing the query actually solved my issue!

Here's the working query:

``` ruby
@results = Post.search :page => current_page, :per_page => 20 do
  query do
    match [:body, :title], q
  end
  highlight :body, :options => { :fragment_size => 50 }
end
```

Thank you again for all your hard work!
