### ISSUE TITLE
Issue with offset while using pagination via Kaminari

### ISSUE THREAD

**Issue by shreyas-satish** [karmi/retire#536]
I have the following code in a class, lets say, Repo. 

``` ruby
def search
  # The params hash is accessible to this method
  q = params[:q]
  return Kaminari.paginate_array([]).page(params[:page]).per(0) if q.blank?

  options = {page: params[:page], per_page: 5, load: true}
  search = Tire.search 'articles', options do
    query {string q}
  end
  search.results
end
```

``` ruby
results = Repo.new("world").search
```

The results array does not get offset when I navigate to the second page. The results that were being shown in the first page continue to be shown on the 2nd page, even though the 2nd 'tab' in the pagination tabs is highlighted. 

I would appreciate it if you could throw some light on where I might be going wrong. I am using Tire (0.5.1) and Kaminari (0.14.1).

**Comment by karmi** [comment]
Please run the [pagination tests](https://github.com/karmi/tire/blob/master/test/unit/results_collection_test.rb#L201-L315) and see what you get.

**Comment by shreyas-satish** [comment]
All the tests in unit/results_collection_test.rb pass.

**Comment by karmi** [comment]
Then try running your app with the current master from Github, in you Gemfile:

```
gem 'tire', :git => 'git://github.com/karmi/tire.git'
```

**Comment by shreyas-satish** [comment]
Fixed now. I had to change the options hash and set the 'size' and the 'from' values to

``` ruby
options = {page: params[:page], from: offset, size: 10, load: true}
```

and had to define an offset method for the 'from' in the options hash.

``` ruby
  def offset
    POSTS_PER_PAGE = 10
    page = (params[:page] || 1).to_i - 1
    (POSTS_PER_PAGE  * page)
  end

```

Should I mention this in the docs for Tire?
Thanks.

**Comment by karmi** [comment]
This should really work out of the box... Wondering why are you having the problem..

**Comment by lorgio** [comment]
I think the issue is that you may be passing in params[:page] as a string.

**Comment by mhui** [comment]
I have the same problem. Passing params[:page] as string or integer makes no difference
