### ISSUE TITLE
queries not respecting :include_in_all or :index instructions per mapping

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#538]
this is my index setup

```
{
  "settings":{
    "index":{
      "analysis":{
        "analyzer":{
          "default":{
            "type":"custom",
            "tokenizer":"keyword",
            "filter":[
              "lowercase",
              "my_ngram"
            ]
          }
        },
        "filter":{
          "my_ngram":{
            "type":"nGram",
            "min_gram":2,
            "max_gram":20
          }
        }
      }
    }
  }
}
```

I am running queries like this

```
    Tire.search('typeahead', :size => 10) do
      query { string query, :default_operator => "AND" }
      sort { by :count, 'desc' }
      filter_args.each do |term, match|
        filter :term, term => match
      end
      highlight :name, :media_type, :options => { :tag => "<strong>" }
    end
```

problem is that fields that have been specifically indexed like this

```
    indexes :count, :as => 'viewings.count', :index => 'not_analyzed', :include_in_all => false
```

are till showing up in results (I looked at the index and found an item with a count of 95, so I did a search for '95' and that item came up). Is this a bug, or am I doing something wrong?

**Comment by karmi** [comment]
`include_in_all` just means, that the field is not copied to the convenience `_all` field (which is default eg. for `query_string` query), not that the field is not searchable.

**Comment by ike-bloomfire** [comment]
what about the 'not_analyzed' setting?

**Comment by karmi** [comment]
> what about the 'not_analyzed' setting?

Sorry, don't understand. (How is the mapping for the `count` field set?)

**Comment by ike-bloomfire** [comment]
My understanding is that query does a search on the _all field by default,
why I'm confused is that even though I tell elasticsearch not to include it
in _all or analyze it, it is still searching against it.

**Comment by karmi** [comment]
But how are you searching for it? Can you post an example query?

**Comment by ike-bloomfire** [comment]
I posted the query above

the actual json looks like this  

```
{
   "query":{
      "query_string":{
         "query":"95",
         "default_operator":"AND"
      }
   },
   "sort":[
      {
         "count":"desc"
      }
   ],
   "filter":{
      "term":{
         "active":true,
         "_type":null
      }
   },
   "highlight":{
      "fields":{
         "name":{

         }
      },
      "pre_tags":[
         "<strong>"
      ],
      "post_tags":[
         "</strong>"
      ]
   }
}
```

**Comment by karmi** [comment]
So you're searching for `"query": "95"` and that finds a doc with `count:95`? Is it possible another field gets analyzed in such a way that it has a `95` token? Can you post the resulting doc?

**Comment by ike-bloomfire** [comment]
> So you're searching for "query": "95" and that finds a doc with count:95?

exactly

Here's the result returned when I run the query from the command line, the count has increased now, so its 98 not 95 (I adjusted the query accordingly)

```
{
   "took":2,
   "timed_out":false,
   "_shards":{
      "total":5,
      "successful":5,
      "failed":0
   },
   "hits":{
      "total":1,
      "max_score":null,
      "hits":[
         {
            "_index":"typeahead",
            "_type":"membership",
            "_id":"1",
            "_score":null,
            "_source":{
               "active":true,
               "organization_id":1,
               "user_id":1,
               "name":"Mr West",
               "count":98,
               "membership_id":1
            },
            "sort":[
               98
            ]
         }
      ]
   }
}
```

**Comment by karmi** [comment]
Understood. Unfortunately, I can't replicate the problem. Check the index mapping -- maybe you need to recreate the index?

``` ruby
require 'active_record'
require 'tire'
require 'oj'

ActiveRecord::Base.establish_connection( adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Schema.define(version: 1) do
  create_table :books do |t|
    t.string    :title
    t.integer   :count
    t.timestamps
  end
end

Tire.index('books').delete

class Book < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :title, analyzer: 'snowball'
    indexes :count, include_in_all: false
  end
end

Book.create title: "War and Peace", count: 123
Book.index.refresh

# Tire.configure { logger STDERR }

s = Book.search do
  query { string 'peace' }
end

puts '-'*80
puts s.results.to_a.map(&:title).inspect

s = Book.search do
  query { string '95' }
end

puts '-'*80
puts s.results.to_a.map(&:title).inspect

puts '-'*80
```

**Comment by ike-bloomfire** [comment]
> Check the index mapping -- maybe you need to recreate the index?

I've done that at least 100 times in the last week :D (been testing different tokenizers and search combos).

I'm using elasticsearch 19.2 and have an index_name 'xxxx' set inside the mapping block, dunno if that has anything to do with it. I guess I'll try and isolate the problem a little bit more when I have time, but its good to know I'm not crazy.

**Comment by karmi** [comment]
`index_name` should be outside of the mapping block, but it makes no difference in this case -- the example still runs. I wonder what's the problem in your case...

**Comment by karmi** [comment]
Hello, any news?

**Comment by karmi** [comment]
Closing, please reopen when you have any new info and/or an isolated test case which I can run...

**Comment by ike-bloomfire** [comment]
> The mapping declaration creates the index when the class is loaded or when the importing features are used, and only when it does not yet exist

Question about this ... 
for legacy reasons, I am actually creating the index outside of tire, but I'm only sending in a settings hash/object, the mappings part of the index is empty. 

so basically 

```
curl -X PUT localhost:9200/myindex -d '
{
  "settings" : { bunch of awesome settings },
}
```

however, none of the settings I set in my mappings for ActiveRecord Objects (this is a Rails app) are respected, not even :type settings, myobject.tire.update_index still works though.

My question ... is tire ignoring the mapping block I specify because the index exists (so-to-speak)?

PS: I should mention I'm using one index to hold several activerecord types as opposed to one index per model that is the normal Tire usecase

**Comment by karmi** [comment]
@ike-bloomfire I'm sorry, it's too many questions I guess :) Whatever you set in your model is ignored if an index with the corresponding `index_name` exists.

**Comment by ike-bloomfire** [comment]
Thank you, this explains a lot.

Just to be clear, an unfortunate side effect of this is that if you're using a single index for all your models, then there is a chance that all the settings/mappings that you have in all the other models (except the first one to get indexed) will _not_ make it into the index ... right?

**Comment by ike-bloomfire** [comment]
Also, where do you prefer people ask questions that are not technically issues? here or stackoverflow?

**Comment by karmi** [comment]
>  there is a chance that all the settings/mappings that you have in all the other models (...)

Yes, that is true. You can either manage your index manually, or use different index for each model.

> Also, where do you prefer people ask questions that are not technically issues? here or stackoverflow?

Github issues is fine for me, but there might be a delay depending on my workload. Stackoverflow has the advantage that sometimes other people tend to help there. So, both are fine.
