### ISSUE TITLE
Count per Index on multi index query 

### ISSUE THREAD

**Issue by visasquare** [karmi/retire#539]
Hello, I want to do a multi index search query using tire gem and perform a facet search. tire gem works great in consolidating the facets. However I want to know the number of results fetched from each index to display it to user. How can I do it?

``` ruby
s = Tire.search ['Index 1', 'index2'] , :search_type => 'count' do
  query do
    string 'NAME:xxxx'
  end
  facet 'city'  do
   terms :'CITY.exact'
  end
  facet 'state' do 
    terms :'STATE.exact'
  end
  end
end
```

In this example, I want the no of hits for index1 and index2.

**Comment by karmi** [comment]
There are two ways around this, I think:
1. If you're only interested in getting/displaying the index name of each result, use the `Item#_index` method.
2. If you somehow need to "segmentize" or group the results, a good approach might be the [`multi_search`](https://github.com/karmi/tire/blob/master/lib/tire/dsl.rb#L33-L86) query.

Also, please start moving away from the `string` query :), the `match` query should do _everything_ you need and is the preferred way of elasticsearch. I need feedback on it, so it can be improved.

**Comment by visasquare** [comment]
Thank you for your response Karmi, we will try the multi_search query and let you know how it goes. 

What we are trying to achieve though is some way to get the total number of hits per index. If we run the query we mentioned above, we get following results (and facet counts)

``` ruby
 @response = {
             "took" => 3898,
        "timed_out" => false,
          "_shards" => {
                 "total" => 10,
            "successful" => 10,
                "failed" => 0
        },
             "hits" => {
                "total" => 244,
            "max_score" => 0.0,
                 "hits" => []
        },
```

What we are looking for is total counts for each index, so in this case can be 4 hits on index 1 and 6 hits on index2.

Our apologies, if we are asking very basic questions but we are just getting started with elastic search and are finding tire gem very very helpful. 

We will also change from string query to match and let you know if we run into any issues.

Thanks for all your help.

**Comment by karmi** [comment]
No worries with questions etc.

Well, if you're after the _total_ count of matched documents in `index1` and `index2`, my option 1) is useseless.

Without issuing another request, one solution is to facet on the `_index` property:

``` ruby
require 'tire'

Tire.configure { logger STDERR }

s = Tire.search '/', :search_type => 'count' do
  query()           { all }
  facet(:per_index) { terms :_index }
end

p s.results.facets['per_index']['terms'].map { |item| { item['term'] => item['count'] } }
```

**Comment by visasquare** [comment]
Thank you so much! Works great! Thats exactly what we were looking for. The
facet on _index helped us with issuing multiple queries to elastic search.

Thanks again for all your help.

**Comment by karmi** [comment]
Glad it worked -- just please close the issue you have opened...
