### ISSUE TITLE
The "extract the routing value from documents" in test `BulkIntegrationTest` fails

### ISSUE THREAD

**Issue by karmi** [karmi/retire#540]
On Linux, the [`"extract the routing value from documents"`](https://github.com/karmi/tire/blob/a804d0f/test/integration/bulk_test.rb#L28-L35) test was consistently failing, as reported in issue karmi/tire#537.

This is because the index `bulk-test` is created with only 1 shard, so the filtering with the `routing` parameter can't work.

**Comment by karmi** [comment]
@vsespb See the closing commit, the test indeed _should not_ have been passing. More info coming soon.

**Comment by vsespb** [comment]
Yes, I had the issue when this test failing with the following elasticsearch config:

```
index.number_of_shards: 1
index.number_of_replicas: 0
```

it was working fine with default (empty) config file.

I confirm that this fix fixes the issue. Now the test passes always. Thanks!

**Comment by karmi** [comment]
OK, so to make sure:
1. The _Tire_ suite is consistently passing for you?
2. Your application tests are consistently passing?

**Comment by vsespb** [comment]
1 - yes, but it depends on config or environment. I answered in https://github.com/karmi/tire/issues/537
