### ISSUE TITLE
Missing Security

### ISSUE THREAD

**Issue by reiz** [karmi/retire#542]
I am missing security here. 
I found this project here: https://github.com/Asquera/elasticsearch-http-basic to secure an ES server. How does Tire support this? Is there anything for security in the Tire project?

**Comment by karmi** [comment]
You can pass an URL with HTTP Auth credentials to `configure`:

``` ruby
Tire.configure { url "http://USERNAME:PASSWORD@myserver.com" }
```

Another option is to use [Nginx with HTTP Auth](https://gist.github.com/986390) as a reverse proxy. The Chef cookbook [`karmi/cookbook-elasticsearch`](https://github.com/karmi/cookbook-elasticsearch) comes with it out of the box.

**Comment by reiz** [comment]
OK. Will try. Many Thanks for the fast response.

**Comment by karmi** [comment]
Please close the issue when it's resolved.

**Comment by reiz** [comment]
OK. Will do. I am experimenting with some ElastisSearch providers. As soon as I did a successful test with authentification I will close this ticket.

**Comment by karmi** [comment]
@reiz Any success?

**Comment by reiz** [comment]
@karmi Give me one more day to test this out. It is on my ToDo list.

**Comment by reiz** [comment]
@karmi I just tried it. It works fine.

**Comment by reiz** [comment]
@karmi Happy Christmas to you and your family.

**Comment by karmi** [comment]
@reiz Thanks -- all the best!
