### ISSUE TITLE
The requested URL /elasticsearch/60fasfgasbdf940515 was not found on this server

### ISSUE THREAD

**Issue by reiz** [karmi/retire#544]
I have a simple mapping like this: 

``` ruby
Tire.index Settings.elasticsearch_product_index do
      delete
      create :mappings => {
        :product => {
          :properties => {
            :_id                => { :type => 'string', :index => 'not_analyzed', :include_in_all => false },
            :name               => { :type => 'string', :analyzer => 'snowball', :boost => 100  },
            :description        => { :type => 'string', :analyzer => 'snowball'                             },
            :description_manual => { :type => 'string', :analyzer => 'snowball'                            },
            :language           => { :type => 'string', :analyzer => 'string_lowercase', :index => 'not_analyzed'}
          }
        }
      }
    end
```

By executing the code I am getting a: 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /elasticsearch/60f87XXXX515 was not found on this server.</p>

</body></html>

Any ideas what is wrong ?

**Comment by karmi** [comment]
Please turn on logging with `Tire.configure { logger STDERR }` and paste the output. Be sure to sanitize the index names (your private token) on eg. Bonsai.

**Comment by reiz** [comment]
OK. I just turned loggin on. Here is the complete output: 

``` bash
# 2012-12-11 11:37:42:790 [CREATE] ("gasfasgfasgfasfga")
#
curl -X POST https://www.indexdepot.com/elasticsearch/gasfasgfasgfasfga -d '{"mappings":{"product":{"properties":{"_id":{"type":"string","index":"not_analyzed","include_in_all":false},"name":{"type":"string","analyzer":"snowball","boost":100},"description":{"type":"string","analyzer":"snowball"},"description_manual":{"type":"string","analyzer":"snowball"},"language":{"type":"string","analyzer":"string_lowercase","index":"not_analyzed"}}}}}'

# 2012-12-11 11:37:42:790 [404]

 => #<Tire::Index:0x007fb2a4174dd8 @name="gasfasgfasgfasfga", @options={:mappings=>{:product=>{:properties=>{:_id=>{:type=>"string", :index=>"not_analyzed", :include_in_all=>false}, :name=>{:type=>"string", :analyzer=>"snowball", :boost=>100}, :description=>{:type=>"string", :analyzer=>"snowball"}, :description_manual=>{:type=>"string", :analyzer=>"snowball"}, :language=>{:type=>"string", :analyzer=>"string_lowercase", :index=>"not_analyzed"}}}}}, @response=404 : <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /elasticsearch/gasfasgfasgfasfga was not found on this server.</p>
</body></html>
> 
```

**Comment by reiz** [comment]
I am able to store some documents into the index, but I can't create a mapping. And for the search I am getting a similar result.

**Comment by karmi** [comment]
No, this index `https://www.indexdepot.com/elasticsearch/gasfasgfasgfasfga` does not exist. You're getting a 404 response from some kind of proxy.

**Comment by reiz** [comment]
this here "gasfasgfasgfasfga" is not really the index name. The index name I am using does exist. I can send you the index name via email or skype.

**Comment by karmi** [comment]
I believe this is a problem with the IndexDepot provider, maybe they don't allow you to create an index via regular Elasticsearch API?

**Comment by reiz** [comment]
I shoot them the link to this issue. Hope they will respond today and help me out.

**Comment by reiz** [comment]
OK. Problem found. The problem was that a slash at then end of the indexname was missing. This here works: 

https://www.indexdepot.com/elasticsearch/gasfasgfasgfasfga/
