### ISSUE TITLE
Add support for the index status API of elasticsearch

### ISSUE THREAD

**Issue by tbk303** [karmi/retire#545]
Would it be possible to add support for the status API of elasticsearch? See http://www.elasticsearch.org/guide/reference/api/admin-indices-status.html

If there's any chance to have this integrated, I'd like to write some code for this.

**Comment by karmi** [comment]
I'd like to really focus more on tightening up the gem, re-writing documentation, and possibly re-thinking everything in the near future, then adding features. But go for it, if you think it's worthwhile.

**Comment by karmi** [comment]
Closing for now -- this is a simple feature addition, which just calls the API and returns the JSON. Would be call to wrap it in `Hashr` instance, but would be also cool to research other Hash-like implementations such as `Mash` etc.

We can reopen for further discussion, code review, etc!
