### ISSUE TITLE
update_index with parent option

### ISSUE THREAD

**Issue by kenshin54** [karmi/retire#546]
[store](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L80) method accept a 'parent' option as params, but [update_index](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L148) didn't provide any chance to pass the parent value.

**Comment by karmi** [comment]
Yes. If you need to work with parent/child in models, please write your own indexing using the `Index#store` method...
