### ISSUE TITLE
Multiple Models Query

### ISSUE THREAD

**Issue by matteomelani** [karmi/retire#547]
I have 3 models, and I create 3 indexes, one index per model:

Post           --> posts index
Comment --> comments index
Membership    --> memberships index

Is is possible to query all 3 indexes and gets back total hits per index with one query?

I can do 3 separate queries and merge the results but that is a bit inefficient.

I can do something like:

s = Tire.search(["#{Rails.env}_posts","#{Rails.env}_comments", "#{Rails.env}_memberships"], { :size => size, :from => from }) do ...

but I do not get the hits per index.

Thanks for the great gem and for any help.

**Comment by karmi** [comment]
Hi, first, let's review the options and possibilities you have here:

1/ You want to query these separate indices, and display the results segmented accordingly. In this case, possibly the best option is to use the [`multi_search`](https://github.com/karmi/tire/blob/master/test/integration/multi_search_test.rb)  request.

2/ You want to query these indices and display the results in one listing: in this case, just search normally, every result item will have an `_index` and `_type` property to separate it from others.

3/ You want to query these indices, but display some counts based on whichever indexes got matches. In this case, you can use a `terms` facet on the `_index` automatic attribute: see issue karmi/tire#539 which has all the code just for that.

**Comment by matteomelani** [comment]
This really help! Thank you so much!

-Matteo

**Comment by karmi** [comment]
Which of the options was yours, by the way? :)
