### ISSUE TITLE
How to search multiple fields?

### ISSUE THREAD

**Issue by mrcasals** [karmi/retire#548]
Hi, 

I'm currently querying my elasticsearch database using Tire like this:

``` ruby
Tire::Search::Search(my_index, {load: true, analyze_wildcard: true, q: *my_term*)
```

But this searches for `*my_term*` on all the fields of my document. How can I filter this so that it only searches in the fields I want?

Thanks.

**Comment by karmi** [comment]
Many ways -- one of the better options: https://github.com/karmi/tire/blob/master/test/integration/match_query_test.rb#L45

**Comment by mrcasals** [comment]
Hi @karmi, thanks for the quick reply! I'll try it and tell you if something goes wrong :)

**Comment by karmi** [comment]
Please close the issue once it's resolved.

**Comment by mrcasals** [comment]
I close this, working as expected :)
