### ISSUE TITLE
Tire::Index.logging requires multi_json >= 1.3

### ISSUE THREAD

**Issue by ghost** [karmi/retire#549]
As of Tire 0.5.0 Tire::Index.logging uses MultiJson#load. This method was introduced in multi_json 1.3 and the gemspec file should be updated accordingly. It now requires multi_json 1.0 or higher but things will break if you try to use Tire 0.5.x in combination with multi_json < 1.3. (In my case my Rails app tried to invoke 'load' from the ActiveSupport::Dependencies::Loadable module which throws a LoadError.)

**Comment by karmi** [comment]
Argh, true -- thanks for the catch! It was probably introduced in karmi/tire@0f8d4fa already. I tried to stay away from the new dump/load semantics, but seems like we should make the leap.

**Comment by karmi** [comment]
Updated, thanks for the report!
