### ISSUE TITLE
somthing is converting string ids into integers when using  Tire::Model::Search

### ISSUE THREAD

**Issue by gaffo** [karmi/retire#55]
I have ids that are uuids like 17a66b59-c8bc..... and when I call ._id on the object that has been returned from the search, I'm getting id is 17.

**Comment by karmi** [comment]
It's more complicated then that. I've pushed karmi/tire@648c77 with sanity check for ActiveModels. Tire is definitely not converting IDs to Integers.

Could you be more specific as to your use-case? Do you use ActiveModel or ActiveRecord? How is your `id` column defined in the database? I am not able to replicate your bug.

(P.S. Why are you calling `result._id` and not `result.id`.)

**Comment by gaffo** [comment]
It looks like it is active record. I was trying to pull snapshots of our ES data into mysql for analysis over time. Looks like I just need a second object that does the ES mapping. The ID from the target (mysql) model isn't the same as the uuid that I'm putting into ES. I was making an _id column in mysql to be the target.

**Comment by karmi** [comment]
OK, so if it's ActiveRecord, you should check with your migrations or in dbconsole, how the column in question is defined, eg. with `describe <YOURTABLE> id;`.

>  The ID from the target (mysql) model isn't the same as the uuid that I'm putting into ES. I was making an _id column in mysql to be the target.

Sorry, I don't understand what you mean.

**Comment by gaffo** [comment]
it's definitely an int. Not sure what I really want as my usecase isn't
typical. Raw access to the data might be a nice compromise.

**Comment by karmi** [comment]
I would gladly help but I don't understand what is your problem.

**Comment by karmi** [comment]
Closing the issue as invalid, the discussion can continue.

**Comment by gaffo** [comment]
Sounds good on the closing. Looking through the code, I believe you are
hiding the stuff that is pulled from ES as protected or private and just
letting active record return it. I think it would fix my issue to be
able to just have access to it. Say tire_raw_attributes[:_id] or
tire_raw_attributes['_id'].

**Comment by karmi** [comment]
I do apologize, but I _still_ don't understand what's the real issue :) And I cannot replicate that. If you would be able to post a gist with teh situation, I may be able to help...

Tire is not hiding the raw response in any way. With ActiveRecord, it tries to instantiate AR records from the JSON. There are issues with it, see karmi/tire#11 and karmi/tire#12. There is definitely a solution or workaround for your case.
