### ISSUE TITLE
How to disable auto index creation

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#550]
The call to **include Tire::Model::Search** is triggering the auto index creation for the model where I included this module. Is there any way to disable the creation of auto index via tire? Where does the call to create the auto index happen in tire?

```
module SearchIndex

  def self.included(base)

    base.class_eval do
      include Tire::Model::Search

    end
  end

end
```

**Comment by karmi** [comment]
The index auto-creation is triggered when you [define the mapping](https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L61).

The index is only created when it does not exist, so it should not present any errors unless you have a specific use-case?

**Comment by vamsi-krishna-E0029** [comment]
Thanks for the reply...

I agree, the index gets created only when it doesn't exist. I just want to know if there is anyway to stop the auto index creation itself. I want to create it, as and when I need it.

**Comment by karmi** [comment]
The proper solution is to create the index beforehand, by your own code. The creation will then be skipped.

**Comment by vamsi-krishna-E0029** [comment]
Thanks a lot.

**Comment by mikebaldry** [comment]
In my case, I'm using an alias called "products_current" as my index_name. This works fine except when the alias doesn't exist, say I go to create an index with rake tire:import CLASS="Product" INDEX="products-201305220900" -- this will create an index "products_current" which will be empty and the expected "products-201305220900".. I'm currently using a script to delete the index if it exists and create/update alias..
