### ISSUE TITLE
Is it possible to limit the resultset to a certain number

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#552]
I am only interested in the top 5 resultset items. I couldn't find documentation here but elasticsearch has a limit filter (http://www.elasticsearch.org/guide/reference/query-dsl/limit-filter.html).  Does this exist in Tire?
Thanks!

**Comment by karmi** [comment]
If you want to return only a limited number of items, use the `size` method in DSL -- seee README.

The limit filter serves a different purpose -- it limits the number of documents a query is executed against. Filters in the Tire DSL follow closely the Elasticsearch DSL semantics, so should be supported transparently -- see integration tests for examples.

**Comment by cameronkendall** [comment]
Thanks!
