### ISSUE TITLE
Mapping a model from subdirectory

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#553]
How do I map a model which is present in a subdirectory of models directory?

```
  include Tire::Model::Search

  Tire.index('account_1') do
    create(
      :mappings => {
        :user => {
          :properties => {
            :name => { :type => :string, :boost => 10 },
            :company_name => { :type => :string, :boost => 5 }
          }
        },
        :comments => {
          :properties => {
            :description => { :type => :string, :boost => 5 }
          }
        }
      }
    )
  end
```

In the above example my user and comments model are available in a subdirectory inside models directory.

app->models->admin->user model
app->models->admin->comments model

I tried the below formats but none of them seem to work.

Format 1:

```
  Tire.index('account_1') do
    create(
      :mappings => {
        :admin_user => {
          :properties => {
            :name => { :type => :string, :boost => 10 },
            :company_name => { :type => :string, :boost => 5 }
          }
        },
        :admin_comments => {
          :properties => {
            :description => { :type => :string, :boost => 5 }
          }
        }
      }
    )
  end
```

Format 2:

```
  Tire.index('account_1') do
    create(
      :mappings => {
        :admin => {
          :user => {
            :properties => {
              :name => { :type => :string, :boost => 10 },
              :company_name => { :type => :string, :boost => 5 }
            }
          }
        },
        :admin => {
          :comments => {
            :properties => {
              :description => { :type => :string, :boost => 5 }
            }
          }
        }
      }
    )
  end
```

**Comment by karmi** [comment]
> How do I map a model which is present in a subdirectory of models directory

Sorry, I don't understand what you mean by that.

**Comment by vamsi-krishna-E0029** [comment]
My user model is not directly available in models directory of rails app folder. It is located in Admin folder inside.

app->models->admin->user.rb

so the class name is defined using namespace as Admin::User. In this case how do I provide the mapping definition.

I'm sorry if the question I asked previously was total wrong.

**Comment by karmi** [comment]
If you use the `mapping` method in the model, the proper type is inferred correctly. In this case, the type would be `admin/user`.

``` ruby
p Admin::User.document_type
p Admin::User.mapping_to_hash
```

**Comment by vamsi-krishna-E0029** [comment]
Thanks a lot.
