### ISSUE TITLE
mongoid has_many children not saving through nested_attributes

### ISSUE THREAD

**Issue by gregory** [karmi/retire#554]
Hey guys,

So here is the issue:

context:
- mongoid (2.2.6)
- tire (0.5.1)

classes:

```
class Account
  include Mongoid::Document
  has_many :comments, auto_save: true
  accepts_nested_attributes_for :comments
end
class Comment
  include Mongoid::Document
  include Tire::Callbacks
  include Tire::Search
  belongs_to :account
end
```

operations: 

```
account = Account.first
account.comments_attributes = [{content: 'super'}]
account.comments => [#<Comment content: 'super'>]
```

issue:

```
Comment.count => 0
Comment.search().count => 1
account.comments.build {content: 'super'}
account.save => true
Comment.count => 1
```

it seems that there is conflict with the autosave with nested_attributes change on mongoid and the callbacks of tire ...

**Comment by karmi** [comment]
Crosspost from http://stackoverflow.com/questions/13979145/mongoid-has-many-children-not-saving-through-nested-attributes-when-tirecallba, closing here, please post the relevant portions of your mapping definition, and output or link to output of your model's JSON serialization (Account#to_indexed_json).
