### ISSUE TITLE
Adding Support passing a partial document (since ES  0.20)

### ISSUE THREAD

**Issue by palanglung** [karmi/retire#557]
The update API also support passing a partial document (since 0.20), which will be merged into the existing document (simple recursive merge, inner merging of objects, replacing core “keys/values” and arrays). For example:

curl -XPOST 'localhost:9200/test/type1/1/_update' -d '{
    "doc" : {
        "name" : "new_name"
    }
}'

**Comment by palanglung** [comment]
palanglung/tire ref: palanglung/tire@c2ce0f97a2c5d7f2ccd9c595b702f32e079205f9

**Comment by karmi** [comment]
True -- I'll look into adding some integrations tests for the behavior and unbreak the `Index#update` method.

**Comment by karmi** [comment]
Closed by karmi/tire@ede225d.
