### ISSUE TITLE
muti valued key fields in term_facets

### ISSUE THREAD

**Issue by visasquare** [karmi/retire#559]
Hi Karmi, 

Can you please let us know if TireGem supports muti valued key fields in term_facets,

We have a use case to get min,max and average for a value given two key fields. 

for e.g: We want to min, max and average salary information(    :value_field =>  SALARY) for job title and Year(    :key_field => 'JOB_TITLE.exact', 'Year.exact')

s = Tire.search('index1') do 
   query do
         string 'NAME:ABC'
     end
  facet 'city_stats' do  
   terms_stats do
    :key_field => 'JOB_TITLE.exact', 'Year.exact'
    :value_field =>  SALARY
   end
  end
end

**Comment by karmi** [comment]
`terms_stats` is fully supported (see integration test: https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L202-L218), but Elasticsearch AFAIK does not support "grouping" results like this in the `terms_stats` facet. It should be doable with a script facet.

**Comment by visasquare** [comment]
Thanks Karmi, but in the elastic search document it mentions that following, maybe we can check with Shay what it means? 

Note, the terms stats can work with multi valued key fields, or multi valued value fields, but not when both are multi valued (as ordering is not maintained).

We will look into implementing a script facet. Thank you so much for all your help!

**Comment by karmi** [comment]
OK, got you. "Multi-valued" in context of Elasticsearch means "has more then one value" (AFAIK). So, it's possible to use `terms_stats` eg. for properties with more values (such as `tags`), or properties which are analyzed into multiple tokens.

What you seem to be after is some kind of "aggregation" -- `GROUP BY` in SQL terms --, and that is not supported directly in Elasticsearch.

Note though, that thanks to the flexibility brought by the scripting support, you could write this aggregation in Mvel/JavaScript and have it executed by Elasticsearch in a "map/reduce" fashion -- just combine the year with the job title.

**Comment by karmi** [comment]
@visasquare Hello, any news?

**Comment by karmi** [comment]
Closing, please reopen if you have any more questions.

**Comment by visasquare** [comment]
Our apologies for the delayed response. Sure, we are trying some other workaround including one suggested by you. We will keep the group posted.
