### ISSUE TITLE
How to define mappings for nested Data?

### ISSUE THREAD

**Issue by ysf** [karmi/retire#56]
Currently I have Yellowpages, each containing an address. When searching for an Yellowpage I want the search to search in those nested addresses too. So I embedded address in the to_index_json method.

``` ruby
class Yellowpage < ActiveRecord::Base
  has_one :address

  mapping do
    indexes :id,      :type => 'integer', :analyzed => false
    indexes :title,   :type => 'string',  :boost => 2
    indexes :body,    :type => 'string',  :analyzer => 'snowball'
  end

  def to_indexed_json
    {
      id:     id,
      title:  title,
      body:   body,
      address: {
        id:     address.id,
        name:   address.name,
        street: address.street,
        ...
      }      
    }.to_json
  end
end
```

Is there a way to define the nested mapping (yellowpage.address) in an ActiveRecord with Tire? And is this a good way to solve my problem or is there an other best-practice/usage pattern I should look into=

**Comment by karmi** [comment]
Hi, presently you can define the mapping like this:

``` ruby
indexes :address,
          :type => 'object',
          :properties => {
            :id   => { :type => 'string', :analyzed => false },
            :name => { :type => 'string', :boost => 10 },
            # ... etc
          }

```

Does it work for you?

I'm playing with a bit more DSL-ish way how to expose the API, we'll see how it goes.

**Comment by karmi** [comment]
Hi, I've added a more DSL-ish way how to define nested mapping like this in karmi/tire@1f3e644

```
    class Article
      include Tire::Model::Search
      include Tire::Model::Callbacks

      mapping do
        indexes :title, :type => 'string'
        indexes :author do
          indexes :first_name, :type => 'string'
          indexes :last_name,  :type => 'string', :boost => 100
        end
      end
    end
```

**Comment by ysf** [comment]
Uh, thanks a lot for your nice work and superb support! :)

**Comment by karmi** [comment]
You're welcome, glad if it's working!

**Comment by khoan** [comment]
Can we do two level deep mapping/index? Should I create a ticket for this?

**Comment by karmi** [comment]
> Can we do two level deep mapping/index?

I don't know :) Could you try it?

> Should I create a ticket for this?

Definitiely, if the implementation does not support deeper hierarchies of mapping.

**Comment by khoan** [comment]
this is what I tried:

``` ruby
class NestedModel
  ...

  mapping do
    indexes :base_field, index: :not_analyzed
    indexes :first_level do
      indexes :first_level_field, index: :not_analyzed

      indexes :second_level do
        indexes :second_level_field, index: :not_analyzed
      end
    end
  end

  ...
end
```

querying http://localhost:9200/nested_models/_mapping would give something along the line of:

``` ruby
{
  nested_models: {
    nested_model: {
      properties: {
        base_field: {type: :string, index: :not_analyzed},

        first_level:  {
          properties: {
            first_level_field: {type: :string, index: :not_analyzed},

            second_level: {
              dynamic: true,
              ...
            }
          }
        },

        second_level: {
          properties: {
            second_level_field: {type: :string, index: :not_analyzed}
          }
        }
      }
    }
  }
}
```

Have I done something silly in the mapping definition?

**Comment by karmi** [comment]
Hi, no, you haven't. The code in https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L30 is silly, since it does not take into account deeper hierarchies. You have to create the index with a mapping like this manually (by passing a Hash to `Index#create`) at the moment. I'll have a look into making the code proper and more flexible...

**Comment by khoan** [comment]
Cool, glad a greater mind has confirmed it. created #75 for this issue.

**Comment by chromeragnarok** [comment]
It's weird that this only creates the mapping, but will not send the values of the nested attributes on update if you do it with ActiveRecord. To get the nested value attribute updated then you have to use :as , thus it will become like this : 

``` ruby
class Article < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :title, :type => 'string'
    indexes :author_first_name, :type => 'string', :as => Proc.new { author.first_name }
    indexes :author_last_name,  :type => 'string', :boost => 100, :as => Proc.new { author.last_name }
  end
end
```

Which makes me wonder, what would be the point of having the nested indexes, if it only creates the mapping but doesn't update the value at all.
