### ISSUE TITLE
Parent/Child how to specify the parent type

### ISSUE THREAD

**Issue by driki** [karmi/retire#560]
Hi,

Thanks for all the great work on this gem. I've spent the past few hours trying to track down how to use parent/child with ElasticSearch Tire::Model::Persistence. I see how to add the value for the parent id via: https://github.com/karmi/tire/commit/12a0fede119d2718f14447f1b72b0db7e63a4a45 but I don't see how to specify the parent type.

Any pointers? Example: https://gist.github.com/4390503

Thanks,
Matt

**Comment by karmi** [comment]
Hi, parent/child is really a grey area with _Tire_ right now.

First, AFAIK you need to setup mapping properly, in the `Document` class ([full code](http://pastie.org/5588689)):

``` ruby
class Document
  ...
  mapping :_parent => { :type => 'municipality' } do; end

  property :id, :type => 'string'
  property :type, :type => 'string'
end
```

Then you have to pass queries as Hashes:

``` ruby
require 'tire'

s = Tire.search 'documents',
                query: {
                  has_parent: {
                    query: { match: { name: { query: 'New', type: 'phrase_prefix' } } },
                    parent_type: 'document'
                  }
                }

puts 'Query:',   s.to_curl

puts 'Results:', s.results.to_a.inspect
```

Unfortunately, my experience with parent/child is limited -- if you'd have a complete use case, I can certainly help you on the _Tire_ side of things.

**Comment by driki** [comment]
Hi,

Thanks for the pointers. I made a minor change and am able to query for parent/child as I was hoping to do (finding documents for a given municipality). Any tips you have on how to build more complex queries (OR,filters,sorting,facets) this way would be welcome.

``` ruby
require 'tire'

s = Tire.search 'municipalities/document',
                query: {
                  has_parent: {
                    type: 'municipality',
                    query: { match: { name: { query: 'New', type: 'phrase_prefix' } } }
                  }
                }

puts 'Query:',   s.to_curl

puts 'Results:', s.results.to_a.inspect
```

**Comment by karmi** [comment]
Until there's proper API/DSL support for parent/child, I'm afraid you're stuck with the less expressive and convoluted way of doing things, namely working with Hashes.

Do note though, that you can define your searches (queries, facets) in the DSL, and then pass their Hash serialization to the payload (see code below), until the support is there...

``` ruby
require 'tire'

my_query = Tire::Search::Search.new do
  query do
    string "name:new*"
  end
end

my_facets = Tire::Search::Search.new do
  facet 'tags' do
    terms :tags
  end
end

# p my_query.to_hash
# p my_facets.to_hash

payload = { query: {
              has_parent: {
                type: 'municipality'
              }
            }
          }

payload[:query][:has_parent].update(my_query.to_hash)
payload.update(my_facets.to_hash)

s = Tire.search 'municipalities/document', payload


puts 'Query:',   s.to_curl
puts 'Results:', s.results.to_a.inspect
```

**Comment by driki** [comment]
Wonderful! Thanks for the help.

**Comment by demirhanaydin** [comment]
I have spent few hours on your example but I can't run it successfully, so I created a new one. That's my working example of parent/child gist https://gist.github.com/demirhanaydin/6548883
