### ISSUE TITLE
Is highlight with :load => true possible?

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#564]
Can I highlight the results when the search is done with the option :load => true? If yes please let me know how?

```
def self.search(params)
    tire.search(:load => true) do
      query { string params[:query] }
      highlight :title
    end
end
```

The above code doesn't seem to highlight my results.

**Comment by karmi** [comment]
Hi, on the current master/0.5.3, you can use the `@results.each_with_hit` method, to acess the `_score` or `highlight` properties, see https://github.com/karmi/tire/compare/bcf2914e909b9475d58776cb554125834b8c573c...6244bd7ca9529204799873cb0e128b2bf763aadb

**Comment by vamsi-krishna-E0029** [comment]
Thanks for the reply. Will look into it. Closing the ticket as of now.

**Comment by karmi** [comment]
Cool, please ping back if it wouldn't work...

**Comment by vamsi-krishna-E0029** [comment]
Added the each_with_hit method in the collection.rb (As the version I'm using is 0.4.3). But, the highlight is always being returned as nil value.

```
@search_results.each_with_hit do |result,hit|
      puts "$$$$$$ #{hit['_highlight']}"
end
```

OUTPUT: $$$$$$

**Comment by karmi** [comment]
`hit['highlight']` should be much better .)

**Comment by vamsi-krishna-E0029** [comment]
Even that didn't work. I checked the hit output.
    puts "$$$$$$$ #{hit.inspect}"

OUTPUT: The output doesn't contain the highlight itself

**Comment by karmi** [comment]
That's weird -- check the added integration test in https://github.com/karmi/tire/commit/7e4f3dcd2f386296a75d3f8980ebc18d009448ce

**Comment by vamsi-krishna-E0029** [comment]
Has gone through that. Anything can be done if the highlight is available in the results. But, I see only score, type, index, id and source.
The version I'm using is 0.4.3. Does that have anything to do with? I integrated the changes from link provided. I don't think any vital change is required apart from adding the each_with_hit in the collection.rb. Am I correct here?

Do I have to specify anything while mapping for the relevant field which needs to be highlighted?

**Comment by karmi** [comment]
Please try with the latest version or master...

**Comment by vamsi-krishna-E0029** [comment]
Tried with the latest master. Issue seems to be the same. Unable to get highlight in results.

**Comment by karmi** [comment]
@ovamsikrishna Please try to run the test added on master. If passes, and displays highlights, try to change your code accordingly. If it doesn't pass, we need to work on why it doesn't pass...

**Comment by mahemoff** [comment]
Although `each_with_hit` can work, I'm trying to reuse a list partial which was originally designed for regular active records (and this is really the main reason I use `load => true` in the first place).

I think it would be useful if `load => true` automatically set a (regular, non-persisted) `highlight` attribute on the active record, if it exists. Same for other properties like score. Maybe for efficiency purposes it would need to be a different value for the load argument, e.g. `load => :all`. Then for example in a list of results, I could just render `highlight || description` which would work whether or not the code had been loaded by Tire.
