### ISSUE TITLE
How do you update a specific index item?

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#566]
i couldn't find this anywhere but is there a way to update a specific index item?  Say I have a User object with an id of '50e75dda5d39f386f9000004' and I would like to update it in my 'user_index'.  How do I do this?  Is there a Tire.index('user_index').update(User.find('50e75dda5d39f386f9000004')) command?  Thanks!

**Comment by cameronkendall** [comment]
Found the answer - Just run a  User.find('50e75dda5d39f386f9000004').update_index.

**Comment by karmi** [comment]
@cameronkendall Yeah, for ActiveModel integration -- when you use `Tire::Model::Persistence`, just call `User.find('abc').save`.
