### ISSUE TITLE
Problems with sorted search

### ISSUE THREAD

**Issue by danielgatis** [karmi/retire#570]
I'm trying to do a sorted search but i always get this error:

[No mapping found for [occupation] in order to sort on]]

what's wrong with my code?

``` ruby
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Tire::Model::Search
  include Tire::Model::Callbacks

  belongs_to :occupation

  field :name, :type => String, :default => ""
  field :email, :type => String, :default => ""
  field :kind, :type => String, :default => ""

  def to_indexed_json
    { id: id,
      name: name,
      email: email,
      kind: kind,
      occupation: occupation.try(:name),
      created_at: created_at,
      updated_at: updated_at
    }.to_json
  end

  mapping do
    indexes :id, :type => 'integer'
    indexes :name, :type => 'String'
    indexes :email, :type => 'String'
    indexes :kind, :type => 'String'
    indexes :occupation, :type => 'String'
    indexes :created_at, :type => 'Date'
    indexes :updated_at, :type => 'Date'
  end

  def self.search q, params={}
    tire.search page: (params[:page] || 1)  do |search|
      search.query do |query|
        query.string q
      end
      search.sort do |sort|
        sort_column = params[:sort] || 'occupation'
        sort_direction = params[:direction] || 'asc'
        sort.by(sort_column.to_sym, sort_direction)
      end
    end
  end
end

```

**Comment by jwoertink** [comment]
I just ran into this today myself. Haven't solved it, but there's this

https://github.com/elasticsearch/elasticsearch/issues/1558

From what I understand, if there's no results, then elasticsearch fails to sort on an empty result set, so they added that option. Just need to figure out how to do it via tire.

_EDIT_
This works for me...

``` ruby
search.sort do
  by :occupation, {order: :asc, ignore_unmapped: true}
end
```

**Comment by karmi** [comment]
@jwoertink Thanks for the answer, it's correct!

@danielgatis Either use the suggestion above, or just make sure the field exists in your data with some meaningful `NULL` value. You can do that in Ruby, or with the `null_value` option in Elasticsearch mapping. Please reopen if the problem persists.

**Comment by danielgatis** [comment]
thanks

**Comment by joselo** [comment]
@jwoertink thanks!!

**Comment by ethier** [comment]
@jwoertink I'll join the chorus, thanks!
