### ISSUE TITLE
bulk import doesn't work with MongoID

### ISSUE THREAD

**Issue by reiz** [karmi/retire#576]
Hi, 

I tried to do a bulk import. As database I am using MongoID. I tried this here: 

```
Tire.index( Settings.elasticsearch_product_index ).import Product.all

But that didn't work. That returned this error message here: 

[ERROR] 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}, retrying (1)...
[ERROR] 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}, retrying (2)...
[ERROR] 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}, retrying (3)...
[ERROR] 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}, retrying (4)...
[ERROR] 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}, retrying (5)...
[ERROR] Too many exceptions occured, giving up. The HTTP response was: 400 > {"error":"Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@0"}
#2013-01-09 20:53:14:161 [_bulk] ("/product_test")
#
curl -X POST "localhost:9200//product_test/_bulk" --data-binary '{... data omitted ...}'

#2013-01-09 20:53:14:161 [400]

 => nil 
1.9.3p327 :005 > 
```

Any idea what I am doing wrong?

**Comment by chrisyuska** [comment]
I had this error in an application I'm working on now just a little bit ago.  I had an indexer running in the background that bulk indexes stuff as needed.  I tracked it down to instances where Tire.index.import was being called on an empty array.  e.g.

``` ruby
Tire.index( Settings.elasticsearch_product_index ).import []
```

I'd check to see if you're ever calling the import method when Product.all returns empty for some reason.  It's hard to tell much else without seeing more code first.

**Comment by reiz** [comment]
I will double check it on the weekend. Thanks for the hint.

**Comment by karmi** [comment]
Hi guys, I've pushed a commit which short-circuits the import action when passed an empty collection, _Tire_ should behave better now :) Please reopen if you have more problems.

**Comment by karmi** [comment]
Just a note, it seems like Mongoid collection's `empty?` method does not work correctly -- you have to call `to_a` on it. The new importing code will take this into account.
