### ISSUE TITLE
Missing filter to check the existence of field and null_value.

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#577]
As per this article http://www.elasticsearch.org/guide/reference/query-dsl/missing-filter.html,
I need search results to display if the field has a particular value (the field can exist or the field can't exist or the field can be null)

```
  filter :or, { :not => { :exists => { :field => :field_name } } },
                { :term => { :field_name => value } }
```

I tried this. But, this gives results with null value as well.
I need the check for null value to be included as well.

Tried missing filter too. But, I'm confused how this can be achieved with missing filter. Please help...

**Comment by karmi** [comment]
I'm afraid I don't understand your query. You want to return results if they:
1. Contain certain term,
2. _or_ the field is missing,
3. _or_ the field is `null`?

(The `missing` filter is supported in Tire, as are all other filters.)

**Comment by vamsi-krishna-E0029** [comment]
My Mapping example:

```
include Tire::Model::Search

  Tire.index('account_1') do
    create(
      :mappings => {
        :user => {
          :properties => {
            :name => { :type => :string, :boost => 10 },
            :company_name => { :type => :string, :boost => 5 }
          }
        },
        :comments => {
          :properties => {
            :description => { :type => :string, :boost => 5 }
          }
        }
      }
    )
  end
```

In the above mapping I would like to filter search results with a particular company_name. The company_name can be Null also (This is just an example). As you can see the comments type doesn't have company_name field. So, I have to use exists filter also.

```
search_key = 'test'
Tire.search [account_1] do
          query do
            filtered do
                query { string search_key }
                filter :or, { :not => { :exists => { :field => :company_name } } },
                              { :term => { :company_name => 'test' } }
            end
          end
        end
```

The above filter checks just the existence of company_name field or filters exact company_name if exists. I want to add null_value check along with this if company_name field exists.
I want to avoid the results where company_name is nil for the user type along with the above filter.

**Comment by karmi** [comment]
Sorry, I don't understand.  You want to return results if they:
1. Contain certain term,
2. _or_ the field is missing,
3. _or_ the field is `null`?

**Comment by vamsi-krishna-E0029** [comment]
I have to get results from comments type when field is not available. And then I have to avoid the results from user type if the company_name is null or if it is **not** a particular term. The results from comments type should always be available.
Sorry if that was confusing.

The main problem was, missing filter and exists with a combi of not, are getting combined results of non-existant and null_value.

**Comment by karmi** [comment]
For the spec **"Find results which contain certain term, or the field is missing, or the field is null"**, see the following code:

``` ruby
require 'tire'

Tire.index('test-missing-properties') do
  delete
  store id: 1, title: 'Test 1', assigned_to: 'john'
  store id: 2, title: 'Test 2', assigned_to: nil
  store id: 3, title: 'Test 3'
  store id: 4, title: 'Test 4', assigned_to: 'mary'
  store id: 5, title: 'Test 5', assigned_to: 'alice'
  refresh
end

s = Tire.search('test-missing-properties') do
  query do
    filtered do
      query { all }
      filter :or, { term: { assigned_to: 'john' } },
                  { missing: { field: 'assigned_to' } }
    end
  end
end

puts "QUERY: ",  s.to_curl, "",
     "RESULTS:", s.results.map(&:id).to_s

# => ["1", "2", "3"]
```

**Comment by vamsi-krishna-E0029** [comment]
This is exactly what I get as of now. But, actually what I need is I need to avoid the result which has assigned_to as nil. I mean I need the result set to be ["1", "3"]

I have tried different combinations of almost all the filters. But couldn't achieve. I feel this is pretty small but equally confusing. This is driving me crazy since yesterday...

**Comment by vamsi-krishna-E0029** [comment]
Is that possible with any combo of filters...?Please help.

**Comment by karmi** [comment]
No, this is not possible: a field with a `null` value simply isn't even stored.

You have to replace the `null` value in your document, either on the client side, or with mapping via the `default_value` option, and then use a `not` filter for that.

**Comment by vamsi-krishna-E0029** [comment]
Thanks for the reply Karmi...Will look into it.
