### ISSUE TITLE
index prefix option?

### ISSUE THREAD

**Issue by timoschilling** [karmi/retire#578]
Is there an way to prefix all index names?

My problem is that i use the same code in 2 projects on one elasticsearch instance.

**Comment by karmi** [comment]
There's [`index_prefix`](https://github.com/karmi/tire/blob/master/lib/tire/model/naming.rb#L10-L35) for model integration, but not a way how to set a "namespace" eg. a la the _redis-namespace_ gem, if that's what you're after.

**Comment by timoschilling** [comment]
I don't use the model stuff, namespace is what i need.

Is a namespace configuration of interest for tire? If yes, I will make a pull request

**Comment by karmi** [comment]
Absolutely interesting, as a part of [`tire-contrib`](https://github.com/karmi/tire-contrib) (or even as a separate gem), with a nice extension DSL method for `Tire.configure` or an `include SomeModel` approach, or a la https://github.com/defunkt/redis-namespace...

**Comment by timoschilling** [comment]
ok, i have done it by karmi/tire-contrib#12
