### ISSUE TITLE
Chicken & Egg problem with <Model>.index_name

### ISSUE THREAD

**Issue by leehambley** [karmi/retire#58]
I have an initializer, which looks like this:

``` ruby
Tire.index(Show.index_name) do
  create(
    :settings => {
      "analysis" => {
        "analyzer" => {
          "show_name_analyzer" => {
            "type" => "custom",
            "tokenizer" => "lowercase",
            "filter" => ["name_ngram"]
          }
        },
        "filter" => {
          "name_ngram" => {
            "type" => 'edgeNGram',
            "min_gram" => 2,
            "max_gram" => 7,
            "side" => "front"
          }
        }
      }
    }
  )
end
```

However the problem is that when autoloading `Show`, in order to call `index_name`, the index is created first, with the mapping as defined in the model, I see this in the (verbose) tire log:

``` text
#2011-07-13 17:40:30:412 [CREATE] ("test-wit-shows")
#
curl -X POST "http://localhost:9200/test-wit-shows" -d '{"mappings":{"show":{"properties":{"id":{"type":"string","analyzer":"not_analysed"},"name":{"type":"string","analyzer":"show_name_analyzer","boost":500},"overview":{"type":"string"},"started":{"type":"integer"}}}}}'

#2011-07-13 17:40:30:412 [400 Bad Request]

#2011-07-13 17:40:30:537 [CREATE] ("test-wit-shows")
#
curl -X POST "http://localhost:9200/test-wit-shows" -d '{"settings":{"analysis":{"analyzer":{"show_name_analyzer":{"type":"custom","tokenizer":"lowercase","filter":["name_ngram"]}},"filter":{"name_ngram":{"type":"edgeNGram","min_gram":2,"max_gram":7,"side":"front"}}}}}'

#2011-07-13 17:40:30:538 [200]
```

Suggestion would be to allow to set a `settings` along side the mapping inside the model, an issue about which I have spoken with you on IRC; thus ensuring when the model is auto-loaded from anywhere, 

The workaround, of course is to define the index name explicitly, in my case `#{Rails.env}-wit-shows`.

Perhaps I am mis-using `index_name` on models, for me the naming scheme is clear, it's always `Rails.env` plus whatever the name of the project and model are.

**Comment by karmi** [comment]
As discussed on IRC #elasticsearch, the solution is to have this index creation logic in a class method of your model, and call this from Rake task when bootstrapping the app, or from test setup in integration tests...

I'd definitely keep the `settings` support (alongside `mapping`) in mind.
