### ISSUE TITLE
How to search within document ids?

### ISSUE THREAD

**Issue by moudy** [karmi/retire#580]
What's the best way to search within a set of documents? The following code doesn't seem to work. Should this work and maybe there's something wrong with my index, or is the code wrong?

``` ruby
user_ids = User.limit(100).map(&:id)

s = Tire.search('users') do
  query do  
    filtered do    
      query { string "name:ni*" }      
      filter :terms, id: user_ids
    end  
  end  
end

# Expecting a subset of the first 100 users 
# with name that starts with "na"
s.results
```

Alos, thanks for all the work on this great gem!

**Comment by karmi** [comment]
Hi, yes, this should definitely work -- this is some example code I have prepared for a Stackoverflow answer: http://pastie.org/private/z0mqugcwptvwckfkc4lbg, can you have a look at it and try to isolate your issue?

**Comment by moudy** [comment]
Ah yeah this works. The problem was that i had `terms :tags, [tags], minimum_match: 1` after the filtered block which that canceled out the id filter. 

I moved it into the filtered block and made it a filter. The output from the log looks right but the results I'm getting include documents that are tagged 'javascript' but are not within the ids.

This `and` below makes it seem like the documents need to fill all the requirements (tagged with 'javascript' and have and id of 1, 2, or 3).

```
 "filter": {
        "and": [
```

Tire DSL code

```
Tire.search 'users' do
  query do
    filtered do
      query { string "name:ni*" }
      filter :term, deleted: false
      filter :term, approval_status: 'approved'
      filter :terms, id: [1,2,3]
      filter :terms, tags: ['javascript'], minimum_match: 1
    end
  end
end
```

Full output from the logs form about search

```
curl -X GET 'http://localhost:9200/users/_search?from=0&size=10&pretty' -d '{
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "name:*"
        }
      },
      "filter": {
        "and": [
          {
            "term": {
              "approval_status": "approved"
            }
          },
          {
            "term": {
              "deleted": false
            }
          },
          {
            "terms": {
              "id": [
               "1",
               "2",
               "3" 
              ]
            }
          },
          {
            "terms": {
              "tags": [
                "javascript"
              ],
              "minimum_match": 1
            }
          }
        ]
      }
    }
  }
}'
```

I tried re-indexing to make sure the mappings where right. Let me know if this is more of an elastic search question.

**Comment by karmi** [comment]
Tire sugar coats the filters a bit here, and multiple filter invocations create an `and` filter automatically.

> This and below makes it seem like the documents need to fill all the requirements (tagged with 'javascript' and have and id of 1, 2, or 3).

Yes, that's the case, they must fulfill all the requirements. Can you create a full recreation with data à la the code below?

---

> The problem was that i had terms :tags, [tags], minimum_match: 1 after the filtered block which that canceled out the id filter.

That really shouldn't happen, see this code:

``` ruby
require 'tire'

Tire.index('test-filtered-and-filters') do
  delete
  create

  store id: 1, title: 'Title 1', user_id: 1, tags: ['python', 'ruby', 'javascript']
  store id: 2, title: 'Title 2', user_id: 2, tags: ['javascript']

  refresh
end

Tire.configure { logger STDERR }

Tire.search('test-filtered-and-filters') do
  query do
    filtered do
      query { string 'title' }
      filter :terms, :user_id => [1]
    end
  end
  filter :terms, :tags => ['javascript']
end.

results.each do |d|
  puts "* TITLE: #{d.title}, USERID: #{d.user_id}, TAGS: #{d.tags}"
end
```

**Comment by moudy** [comment]
That works. Thanks for walking me through this. The issue was that I had the filter definition inside the query block. Moving it one level up into the main search block fixed the issue.

To clarify the the part about tags canceling out the id filter:

```
Tire.search 'users' do
  query do
    filtered do
      query { string query_string }

      filter :term, approval_status: 'approved'
      filter :term, deleted: false

      filter :terms, id: user_ids
    end

    # this cancels out above id filter
    terms :tags, tags, minimum_match: 1
  end
end
```

Not sure if this is intentional.

Thanks again!

**Comment by karmi** [comment]
@moudy I'm interested in the issue where one filter "cancels out" other one -- that sounds like a bug. The problem is I can't replicate it -- would you be able to send a full recreation based on the script I've sent above?

Also, do note that `terms :tags, tags, minimum_match: 1` is not a valid option for the `terms` filter -- is it in your actual code?

**Comment by moudy** [comment]
Yeah removed `minimum_match` thanks

This should recreated the issue. 

```
Tire.index('test-filtered-and-filters') do
  delete
  create

  store id: 1, title: 'Title 1', user_id: 1, tags: ['python', 'ruby', 'javascript']
  store id: 2, title: 'Title 2', user_id: 2, tags: ['javascript']

  refresh
end

Tire.configure { logger STDERR }

s = Tire.search('test-filtered-and-filters') do
  query do
    filtered do
      query { string 'title' }
      filter :terms, :user_id => [1]
    end

    terms :tags, ['javascript']
  end
end

s.results.each do |d|
  puts "* TITLE: #{d.title}, USERID: #{d.user_id}, TAGS: #{d.tags}"
end
```

log output:

```
curl -X GET 'http://localhost:9200/test-filtered-and-filters/_search?pretty' -d '{
  "query": {
    "terms": {
      "tags": [
        "javascript"
      ]
    }
  }
}'

* TITLE: Title 2, USERID: 2, TAGS: ["javascript"]
* TITLE: Title 1, USERID: 1, TAGS: ["python", "ruby", "javascript"]
```

when I remove `terms :tags, ['javascript']`

```
curl -X GET 'http://localhost:9200/test-filtered-and-filters/_search?pretty' -d '{
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "title"
        }
      },
      "filter": {
        "and": [
          {
            "terms": {
              "user_id": [
                1
              ]
            }
          }
        ]
      }
    }
  }
}'

* TITLE: Title 1, USERID: 1, TAGS: ["python", "ruby", "javascript"]
```
