### ISSUE TITLE
How to search an array of hashes field?

### ISSUE THREAD

**Issue by cheneveld** [karmi/retire#592]
I have an Array field in an ActiveModel setup.  This field would look like 

```
field :account_tags, type: Array # [{:account_id => 1, :tags => ["tag1", "tag2"], :acccount_id => 2, :tags => ["tag3", "tag4"] }]
```

I am having a hard time understanding how I can map and search on these nested tag strings?

Any help would be much appreciated!

**Comment by karmi** [comment]
Sorry for the delay... You need to use the `nested` type and queries here, see:
- Documentation: http://karmi.github.com/tire/#section-Nested_Documents_and_Queries
- Tests: https://github.com/karmi/tire/blob/master/test/integration/nested_query_test.rb
