### ISSUE TITLE
Highlight with associations and :load => true

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#595]
The highlight seems to be working when there is no association.

But when the mapping has an association, how do I get the highlight results.

```
include Tire::Model::Search

  Tire.index('account_1') do
    create(
      :mappings => {
        :user => {
          :properties => {
            :name => { :type => :string, :boost => 10, :store => 'yes'  },
            :company => { :type => "object", :name => { :type => :string, :boost => 5, :store => 'yes' }  }
          }
        },
        :comments => {
          :properties => {
            :description => { :type => :string, :boost => 5, :store => 'yes'  }
          }
        },
        :company => {
           :name => { :type => :string, :boost => 5, :store => 'yes'  }
        }
      }
    )
  end
```

In the above specified mapping the highlight doesn't seem to work in case of user.company.name. That works fine when company.name is used.

I want the company name to be highlighted in case of user type too. How can I do this? Should I change the mapping to something else to make this work? Please help.

**Comment by karmi** [comment]
I suggest you create a `curl` version and send your question to the mailing list...
