### ISSUE TITLE
Sorting by multiple fields

### ISSUE THREAD

**Issue by amnesia7** [karmi/retire#596]
Can someone give me a clue how to sort by multiple fields, eg `name, age`.

I found this on the web but I can't get the equivalent code to work for me: https://coderwall.com/p/te8bbq

Is the code in the link correct?

Thanks

**Comment by ike-bloomfire** [comment]
post your code

**Comment by karmi** [comment]
Added integration test, see closing commit.

**Comment by amnesia7** [comment]
Cool. Works a treat. 

Thanks.
