### ISSUE TITLE
Multi Tenant api

### ISSUE THREAD

**Issue by kidpollo** [karmi/retire#597]
Hey!

I wanted to share some of my ideas for a Tire friendly multi tenant api. The reasoning behind might be very opinionated but I have been giving this api a lot of thought and would like to make it open for suggestions.
# Background

The use case is specific for us at [Get Satisfaction](http://getsatisfaction.com) but might apply to others. We are are going to build a new Multi Tenant search infrastructure where each account will have a unique index. Appart from the scaling issues of maintaining thousands of indexes we believe that its worth it for multiple reasons. 
- Keep index configurations separate
  - Different mappings
  - Account specific stop words, locales, analyzers, etc.
- Index A should not affect performance of index B
- Better manage the underlying provisioning and monitoring of different indexes.
# Api

Currently there are ways to get around the vanilla use case that Tire supports and use parts of the DSL separately but I think that with a few extra additions to the current api a lot can be provided.

``` ruby
class Account < ActiveRecord::Base
  has_many :topics

  include Tire::Model::Search
  tire do
    leases_to :topic

    # Account specific index (optional)
    mapping do
      indexes :id,       type: 'string',  index: :not_analyzed
      indexes :name,  type: 'string'
      ...
    end
  end

  # dynamic tenant mapping definition
  def tenant_mapping
    ...
  end
end

class Topic < ActiveRecord::Base
  belongs_to :account

  tire do
    tenant :account

    #defaults to "tenant.class_#{id}"
    index_name proc {|tenant| tenant.name + '_index'}

    # default mapping if Tenant does not respond to tenant_mapping
    mapping do
      indexes :id,               type: 'string',  index: :not_analyzed
      indexes :account_id,  type: 'string',  index: :not_analyzed
      indexes :subject,       type: 'string'
      ...
    end
end

# searches on the specific tenant documents
Account.first.topics.search('*')

# searches on the specified indexes via cross index search
Topic.search('*', 'index_a', 'index_b')

# raises exception
Topic.search('*')
```

Hope this is specific enough to understand the mechanics behind this simple api. Of course other changes would require changing like `index import`, `update_index` and `rake import` but in our case I don think we'll be indexing via the callbacks on production but its a super nice to have for development environments.

I will start to build something like this asap but I really would like input from the community to make it useful for all.

Cheers

**Comment by karmi** [comment]
Hi, thanks for the writeup, Francisco. I'm terribly busy with some other stuff at the moment, but would like to just add couple of points:
- the API you describe makes perfect sense, we had many, many discussions in the early times of Tire development, and usually it was centered about ideas like these,
- if I remember correctly, the problem always was getting the `index_name` lambda/proc right (model instance as argument, but how do you integrate it with the model class `search` method then, etc)
- please make sure you read the outline for a [different strategy](https://github.com/karmi/tire/pull/92#issuecomment-6929988) I have prepared in one of those discussions, it may give you more ideas,

In general, I understand why having a separate _“physical”_ index for each account/user/tenant/etc is attractive. But... I wouldn't say it's a wrong path, but I'd say it has many hidden dangers and it comes with a cost. Scaling indices upto tens of thousands is something not easy to do with Elasticsearch. I think it may be still beneficial for your team to brainstorm other possible data layouts, such as using a set of shared indices for small users, using aliases with filters/routings for clean integration with application, migrating big users to separate indices, etc.

As frequently mentioned, Shay has been talking about these scenarios in this Berlin Buzzwords talk: [“ElasticSearch: Big Data, Search, and Analytics”](http://vimeo.com/album/1968418/video/44716955) ([slides](https://speakerdeck.com/u/kimchy/p/elasticsearch-big-data-search-analytics)) -- it's essential material.

**Comment by kidpollo** [comment]
Thanks for the response!

I did look at your strategy. I actually went ahead and implemented a very similar version of it for now. We are going to test out different strategies in the following weeks I will let you know our discoveries. Our ops team really likes these challenges.

In the mean time I will try to dig in the code to see how possible is this with the current tire api. My main concern is the ability to provide different mappings for different tenants. I does not seem to be possible without separate indexes.

Thanks for the slides I will check them out for sure.!

**Comment by kidpollo** [comment]
Say we change `index_name 'blah'` to `tindexed_at :some_method_name` where some_method_name is a method on the 'leaser' routes to an index or sets the routing or the filtering required for the tenant. 

Or something similar where you could actually define the aproach you want to take.

**Comment by plentz** [comment]
@kidpollo I'm facing the same challenge here. We were using a single index using a tenant_id to split data, but since  we changed our multi tenancy approach to use [multiple postgresql schemas](http://railscasts.com/episodes/389-multitenancy-with-postgresql) instead of using a tenant column, we faced this problem as well. If I can help with something(your team is working in some branch?), let me know.

**Comment by karmi** [comment]
> My main concern is the ability to provide different mappings for different tenants.
> I does not seem to be possible without separate indexes.

Yes, for that separate indices would be the only solution. You should be able to use strategy outlined in #92, where you set the index before search (`Document.index_name "documents-#{current_user.id}"`). Of course, it could be wrapped into some `with_index` etc. for better readability. I really thing this is hard to support generally and is better handled by the application code...

Closing this for now, if it's OK, feel free to reopen or open new issue for further discussion!
