### ISSUE TITLE
to_curl duplicates query "size" and "from" attrs in query string and query JSON

### ISSUE THREAD

**Issue by bgadoury** [karmi/retire#599]
This is a tiny issue, but it is annoying when trying to debug a query by copying the output of to_curl in a shell and working with it there. Can we get rid of size and from in the query string?

If the answer is yes, I'd be happy to submit a PR for changing it in lib/tire/search.rb and lib/tire/multi_search.rb

**Comment by karmi** [comment]
Yeah, I think there's much more mess like that. If you could review it, that would be cool!

Closing this in favor of specific issue/pull request.
