### ISSUE TITLE
Client implementation

### ISSUE THREAD

**Issue by pfeiffer** [karmi/retire#6]
Not that much of an issue, rather a question:

Is there a reason why tire isn't using eg. rubberband (https://github.com/grantr/rubberband/) for communication with ElasticSearch, but rather rolling it's own client?

**Comment by karmi** [comment]
Well, that's an interesting (and tough) question, thanks. I'll try at least some answer.

First, I never really understood where the focus of Rubberband is. It feels like a generic "wrapper" for ElasticSearch API. It feels like a bit of an overkill with all the Thrift stuff? I can talk to ES via jQuery.getJSON() or RestClient just fine. I mean no offense to Rubberband or @grantr here! But big part of ES charm is the HTTP/JSON interface, which means you can wrap it very easily/quickly and focus on the upper levels of the API.

Second, I have been badly burned by depending on gems providing this sort of "interface", CouchDB gems being the main culprit. CouchDB gems are a horrible, horible hell, `couchrest` being the biggest sinner. Of course, subjective, but still my experience.

Third, I don't think about _Tire_ as a “client”. The low-level client implementation is deliberately simply — and also too weak right now. I'd like the HTTP client to be truly pluggable, so you can use RestClient, Typhoeus, Patron, Curb, ..., whatever you feels is the best library. RestClient is just the start. There's sure performance to be gained by plugging-in a better HTTP client.

I think about _Tire_ as being a very strong **API** for using ES in Ruby and Rails. Hence the amount the energy poured into the ActiveModel integration, in searching, importing, etc... That's the real focus of _Tire_, not hauling JSONified `Hashes` back and forth between ES and thin Ruby methods.

**Comment by grantr** [comment]
@karmi none taken! I agree that in many cases the maintenance cost of using a library within a library is often higher than duplicating that functionality, especially when the low-level interface is so simple.

I do find that automatic failover and discovery increase reliability and flexibility significantly in production deployments. As for Thrift, I don't use alternative transports in production and I'm not aware of anyone who does.

**Comment by karmi** [comment]
@grantr thanks for the reply! We're quite happy with using HTTP transport in production, since that's what we are quite used to; we know how to scale, proxy, authorize, etc it. I think the fact that ES exposes the API via sane HTTP to be its major benefit, maybe the most important one...

**Comment by karmi** [comment]
@pfeiffer Is this reply satisfactory at the very least?

**Comment by pfeiffer** [comment]
Absolutely :-)

**Comment by grantr** [comment]
A clarification for future readers: Failover and discovery in rubberband is implemented for all transports. When I mention alternative transports, I mean any transport besides HTTP. We use HTTP in production as well and have no reason to switch.
