### ISSUE TITLE
Array type not being set in mapping

### ISSUE THREAD

**Issue by JamesHarrison** [karmi/retire#600]
So we've got a model that looks like this:

``` ruby
class Image
  include Mongoid::Document
  include Tire::Model::Search
  has_and_belongs_to_many :tags  
  tire.mapping do
    indexes :tags, analyzer: 'keyword', type: 'array'
  end
  def to_indexed_json
    d = self.as_json
    d[:tags] = self.tags.only(:name).map{|t|t.name}
    d.to_json
  end
end
```

If we check the details here:

``` ruby
1.9.3p194 :020 > Image.tire.mapping[:tags][:type]
 => "array"
# make sure the index is totally clear - verified with elasticsearch-head
1.9.3p194 :024 > Tire.index('images'){delete}
 => #<Tire::Index:0x00000008c7d2f8 @name="images", @response=404 : {"error":"IndexMissingException[[images] missing]","status":404}>
# rebuild it
1.9.3p194 :026 > Image.each{|i|i.tire.update_index}
# succeeds, and we can see data in elasticsearch-head
```

So far so good!

``` ruby
1.9.3p194 :030 > Tire.index('images').mapping['image']['properties']['tags']
 => {"type"=>"string"}
```

And there's the problem. We end up with a string. I've tried everything I can think of. Any ideas as to where the heck this is going wrong, or a workaround?

**Comment by karmi** [comment]
@JamesHarrison Sorry for embarrasing delay. Well, the problem with your workflow is that the index is deleted, and then the mapping is created _dynamically_, based on the first `Image` instance which is indexed.

Try calling `Image.create_elasticsearch_index` after you call delete, and then do the indexing. But generally, string/array is all the same, see http://www.elasticsearch.org/guide/reference/mapping/array-type.html

**Comment by karmi** [comment]
Closing, feel free to reopen with more info if needed...
