### ISSUE TITLE
Elastic Search equivalent of "Scoping (Scalar Fields)" in sunspot 

### ISSUE THREAD

**Issue by letronje** [karmi/retire#606]
I'm exploring various options for a search engine for our rails-app/data. I was able to make sunspot/solr work and am currently exploring ElasticSearch as an alternative and couldn't get the same thing(scoping/filtering) to work.

I would like to filter/scope objects as described in the "Scoping (Scalar Fields)" section in 'https://github.com/sunspot/sunspot'. Not sure if 'filters' in Elastic Search mean the same thing. 

I have an active record class 'Product'.

```class Product < ActiveRecord::Base

  ......
  ......

  include Tire::Model::Search
  include Tire::Model::Callbacks

  tire.mapping do
    indexes :name, :type => :string
    indexes :categories do
      indexes :id, :type => :integer
    end
  end
end```

Once I imported products into ES,

the following query works and gives results

`Product.tire.search { query { string '*', default_operator: "AND", default_field: "name" } }.results`

How do I get products of a particular category given a category id ?

`Product.tire.search { query { string '*', default_operator: "AND", default_field: "name" }; filter(:term, 'categories.id' => 38) }.results`

I'm basically looking for the tire equivalent for the following sunspot call:

`Product.search do
  with(:category_ids, 38)
end`

with the following in the Product class

```searchable :auto_index => true, :auto_remove => true do
    text :name

```
integer :category_ids, :multiple => true do
     self.categories.map &:id
end
```

end```

**Comment by nz** [comment]
I'm no Tire expert, but I am a Sunspot expert, and I can say that its `with` scope is a filter query under the hood. So you seem to be going in the right direction. Did you figure this out since opening the ticket?

**Comment by letronje** [comment]
Yup. I'm not relying on tire to index associations, doing it via overriding to_indexed_json.

**Comment by karmi** [comment]
@letronje Could you post the solution and close the ticket?
