### ISSUE TITLE
Issues rewriting query to use match instead of text

### ISSUE THREAD

**Issue by matthewford** [karmi/retire#607]
I'm trying to rewrite the following query to not use text (as it's deprecated) however I get query parsing errors, or alternatively with a multi match query (which I also get parsing errors on) Anyone know how best to do this with the following:

```
q.boolean do |it|
  it.should do |q|
    q.text 'title', @keywords, { type: 'phrase_prefix',
                                 operator: 'and',
                                 analyzer: 'query_default',
                                 boost: 10,
                                 fuzziness: 0.5 }
  end
  it.should { |q| q.string @keywords, default_operator: 'and', analyzer: 'query_default' }
end
```

**Comment by karmi** [comment]
Hi, can you try using the `match` query, which replaced the `text` query, integration tests here: https://github.com/karmi/tire/blob/master/test/integration/match_query_test.rb

**Comment by matthewford** [comment]
Changing the text to use match throws the following error: 

500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], total failure; shardFailures {[5dElDQ3dRuil76eZpwNhSw][government][0]: SearchParseException[[government][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should\":[{\"match\":{\"title\":{\"query\":\"schools\",\"type\":\"phrase_prefix\",\"operator\":\"and\",\"analyzer\":\"query_default\",\"boost\":10,\"fuzziness\":0.5}}},{\"query_string\":{\"query\":\"schools\",\"default_operator\":\"and\",\"analyzer\":\"query_default\"}}]}},\"filter\":{\"and\":[{\"or\":[{\"term\":{\"format\":\"publication\"}},{\"term\":{\"format\":\"statistical_data_set\"}},{\"term\":{\"format\":\"consultation\"}}]},{\"range\":{\"public_timestamp\":{\"to\":\"2013-01-31\"}}}]},\"size\":20,\"from\":0}]]]; nested: QueryParsingException[[government] No query registered for [match]]; }]","status":500}

The logged query

```
    {
      "query": {
        "bool": {
          "should": [
            {
              "match": {
                "title": {
                  "query": "schools",
                  "type": "phrase_prefix",
                  "operator": "and",
                  "analyzer": "query_default",
                  "boost": 10,
                  "fuzziness": 0.5
                }
              }
            },
            {
              "query_string": {
                "query": "schools",
                "default_operator": "and",
                "analyzer": "query_default"
              }
            }
          ]
        }
      },
      "filter": {
        "and": [
          {
            "or": [
              {
                "term": {
                  "format": "publication"
                }
              },
              {
                "term": {
                  "format": "statistical_data_set"
                }
              },
              {
                "term": {
                  "format": "consultation"
                }
              }
            ]
          },
          {
            "range": {
              "public_timestamp": {
                "to": "2013-01-31"
              }
            }
          }
        ]
      },
      "size": 20,
      "from": 0
    }
```

**Comment by karmi** [comment]
My bet is you're on old Elasticsearch version? Try upgrading and report back, please.

**Comment by joshweinstein** [comment]
Thanks Karel! Was having the same issue, but upgrading ElasticSearch to 0.20.5 did the trick.

**Comment by karmi** [comment]
Cool, closing then!
