### ISSUE TITLE
Records aren't being indexed

### ISSUE THREAD

**Issue by Rockyyost** [karmi/retire#608]
I've got a project working on Mongoid, Tire, and ElasticSearch. After batch indexing, I'm able to search and update indexed records successfully. However, when I save a new recorde to MongoDB through Mongoid, the record doesn't get indexed into ElasticSearch. I can't figure out why. I'm not getting an error that I can see in my logs. Is it because I'm doing an upsert when saving the records into MongoDB? I do have include Tire::Model::Callbacks in my model.

**Comment by karmi** [comment]
@Rockyyost Sorry for such a delay. Could you post some code so I can try it? If the `upsert` in Mongoid doesn't trigger `after_save`, then it won't be picked up by the callback hooks.

**Comment by karmi** [comment]
Closing, feel free to reopen with more info if needed...
