### ISSUE TITLE
Can not get type => 'geo_point' and 'geo_polygon' to work

### ISSUE THREAD

**Issue by cis-pjain** [karmi/retire#609]
I am trying to set up my settings and mappings block to be able to create a geo_point.

I have the following set up in my model:

```
class Property < ActiveRecord::Base
    include Tire::Model::Search
    include Tire::Model::Callbacks
    def lat_lon
        [self.lat, self.lng].join(',')
    end
    def to_indexed_json
        to_json(methods: ['lat_lon'])
    end
    tire do
        mapping do
            indexes :lat_lon,  :type => 'geo_point'
        end
    end
   def self.search(params)
       tire.search(load: true, :per_page => 1000) do
           filter :geo_polygon, :lat_lon => {:points => p[[45.570072697443905, -73.663330078125], [45.56141984730463, -73.59260559082031]] }  
       end
   end
end
```

I didn't get any result with this code, Could you try it and report on results?

**Comment by cis-pjain** [comment]
Main problem is with the lat_lon method, I have remove join from [self.lat, self.lng].join(',') and now it works fine.... :) :)

**Comment by karmi** [comment]
The `"lat,lon"` is also [valid](http://www.elasticsearch.org/guide/reference/mapping/geo-point-type.html), but you're passing the values as arrays. Good it's resolved, closing then?

**Comment by cis-pjain** [comment]
Thanks Karmi, Yes its resolve.
