### ISSUE TITLE
Pass variable into search block supported?

### ISSUE THREAD

**Issue by rubytastic** [karmi/retire#610]
Try to exclude the current logged in user ( current_user.id ).

Searched for long since you cannot access current_user value in the model how would one exclude this, is this supported by Tire?

must_not { string 'user_id: <current_user.id here>' }

**Comment by vamsi-krishna-E0029** [comment]
Tire doesn't know about current_user instance. But, that will be available in your application code. So, you have to pass that in the options as a hash to the search query.

Once that is passed, you can use the filter.

```
options = {:current_user => current_user}
Tire.search ['index_name'], options do
<do whatever u want using options[:current_user]>
end
```

Answered as per my understanding of the question. Hope, this helps.

**Comment by karmi** [comment]
@rubytastic You have access to any variables defined outside your search with the "blocks with arguments" syntax:

``` ruby
(params ||= {})[:query] = 'foo'
current_user = 'bar'

MyModel.search do |search|
  search.query do |query|
    query.filtered do |q|
     q.match  :title, params[:query]
     q.filter :term, user_id: current_user
    end
  end
end
```

Notice, that you have access to `current_user` _only_ in the controller instance scope, you can't access it in your model class.
