### ISSUE TITLE
Display distance value in view

### ISSUE THREAD

**Issue by amnesia7** [karmi/retire#611]
I'm filtering by `geo_distance` and `_geo_distance` is also part of my results sorting.

Is there anyway to reference the distance value for each result by name? 

At the moment I am referencing it by its position in my sort array.

Thanks

**Comment by karmi** [comment]
@amnesia7 It's really hard to answer your question when you don't include full recreation: the question would also be more appropriate on the Elasticsearch mailing list or IRC channel, since it's not about the Ruby integration it seems...

**Comment by amnesia7** [comment]
Yeah, no problem.
