### ISSUE TITLE
Applying filter and get corresponding facets?

### ISSUE THREAD

**Issue by liangjh** [karmi/retire#612]
Hi,

Great job w/ this gem.  I know that we can get the applicable facets after a query (ie only the facets that apply to the results of that query), but is it possible to do the same after querying a number of filters?  

I want to build a search experience where a user can filter down results by a set of tags.  After each tag selection, all of which are cumulative, I want to display the remaining tags that the user can choose from.  I've noticed, however, that the current-tags facets apply only to queries and not filters.  Is there any way to make this happen?

Thanks

**Comment by liangjh** [comment]
Basically - what I'm asking is whether tire supports facet filters - thanks

**Comment by liangjh** [comment]
Looks like it was addressed here?  https://github.com/karmi/tire/pull/467

**Comment by liangjh** [comment]
do facet filters allow for bool operators (i.e. "and") if there are multiple things that I want to filter by?   thanks.

**Comment by karmi** [comment]
Yes, `facet_filter` is supported, either as an [option](https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L52) to the `facet` method or as a DSL [method](https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L66).

For your use case, the right path is:
- Use the `filtered` query,
- remember queries limit all facets, top level filters limit only results,
- `facet_filter` limits the results of the facet being passed to,
- so you need to create a combination of mutually exclusive filters.

**Comment by liangjh** [comment]
thanks -
