### ISSUE TITLE
Does Tire remove items from the index when the ActiveRecord Model is deleted?

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#615]
I don't have Tire::Model::Callbacks specified anywhere in my ActiveRecord model, but on delete the items get deleted from the index ... is this expected behavior?

**Comment by karmi** [comment]
No, if you don't include callbacks, no indexing operations should be happening on model changes. Please reopen with more info if needed.

**Comment by ike-bloomfire** [comment]
Thanks Karel!
