### ISSUE TITLE
update_index causing error when ThinkingSphinx is running in parallel

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#616]
Getting the following error:

```
wrong number of arguments (3 for 0)

/Users/vamsi/.bundler/ruby/1.8/tire-f4374f7b956b/lib/tire/model/search.rb:292:in `update_index'
/Users/vamsi/.bundler/ruby/1.8/tire-f4374f7b956b/lib/tire/model/search.rb:292:in `__send__'
/Users/vamsi/.bundler/ruby/1.8/tire-f4374f7b956b/lib/tire/model/search.rb:292:in `update_index'
/Library/Ruby/Gems/1.8/gems/thinking-sphinx-1.4.3/lib/thinking_sphinx/active_record/attribute_updates.rb:23:in `update_attribute_values'
/Library/Ruby/Gems/1.8/gems/thinking-sphinx-1.4.3/lib/thinking_sphinx/active_record/attribute_updates.rb:16:in `each'
/Library/Ruby/Gems/1.8/gems/thinking-sphinx-1.4.3/lib/thinking_sphinx/active_record/attribute_updates.rb:16:in `update_attribute_values'
```

Reason:
ThinkingSphinx running in parallel. When ThinkingSphinx is stopped everything works fine.

Tried including tire after ThinkingSphinx index definition. That didn't help.

I'm making a specific call to the tire's update_index. 

```
@item.tire.update_index
```

Why is this hitting ThinkingSphinx's update_index?

**Comment by karmi** [comment]
That's probably because ThinkingSphinx is calling the `update_index` method [directly](https://github.com/pat/thinking-sphinx/blob/v1.4.7/lib/thinking_sphinx/active_record/attribute_updates.rb#L23), based on callbacks in your model -- that's what the backtrace suggests.

**Comment by vamsi-krishna-E0029** [comment]
As per this 

```
You may have just stopped wondering: what if I have my own settings class method defined? Or what if some other gem defines settings, or some other Tire method, such as update_index? Things will break, right? No, they won't.

In fact, all this time you've been using only proxies to the real Tire methods, which live in the tire class and instance methods of your model. Only when not trampling on someone's foot — which is the majority of cases —, will Tire bring its methods to the namespace of your class.

So, instead of writing Article.search, you could write Article.tire.search, and instead of @article.update_index you could write @article.tire.update_index, to be on the safe side. Let's have a look on an example with the mapping method:
```

I'm not calling that directly. Am I doing something wrong here? I'm using **@item.tire.update_index**

**Comment by karmi** [comment]
I don't know about other operations, and about your setup. This works for me nicely:

``` ruby
require 'thinking-sphinx'
require 'tire'
require 'logger'

ActiveRecord::Base.logger = Logger.new(STDERR)
ActiveRecord::Base.establish_connection( adapter: 'sqlite3', database: ":memory:" )

Tire.configure { logger STDERR }

ActiveRecord::Schema.define(version: 1) do
  create_table :articles do |t|
    t.string   :title
    t.timestamps
  end
end

class Article < ActiveRecord::Base
  include Tire::Model::Search
end

a = Article.new title: 'Test'
a.save

a.tire.update_index
a.tire.index.refresh

table_count = Article.count
index_count = Article.search('*').results.size

puts '-'*80,
     'Article table count:', table_count,
     'Article index count:', index_count
```

---

As a side note: the version of Thinking Sphinx you're using is rather old.

**Comment by vamsi-krishna-E0029** [comment]
Thanks a lot... Will look into it. Closing this issue for now. Will add a comment for sure if this works.

**Comment by vamsi-krishna-E0029** [comment]
When ThinkingSphinx is trying to call update_index the tire's update_index is getting called. I'm not aware why actually this is happening. 

For now, in order to resolve the conflict, I have changed the update_index method name to update_tire_index in the tire/model/search.rb and callbacks.rb. 

Would that impact any other part of code? I mean change of the method name from update_index to update_tire_index.
