### ISSUE TITLE
Non blocking I/O for autocomplete real-time searches

### ISSUE THREAD

**Issue by dfuentes77** [karmi/retire#618]
Can tire use something like em-http-request or something like it when connecting to an elasticsearch cluster in order to avoid the extreme amount of blocking requests to an elasticsearch cluster (using Rails and Unicorn) that result with real-time autocomplete searches using Tire. I don't want to do it from browser since that exposes the ES cluster to the public. 

Thanks.

**Comment by karmi** [comment]
@dfuentes It's possible to write a custom HTTP client class and pass it to _Tire_ in the `configure` block. Not sure how it will behave with em-http-request, you can try it.

>  I don't want to do it from browser since that exposes the ES cluster to the public.

Not neccessarily, BTW: you can put eg. Nginx in front of it, and expose only certain endpoints, sanitize/verify payloads, etc for auto-completion requests.

**Comment by dfuentes77** [comment]
Thanks Karel. I actually do that now.  I front it with Varnish and Nginx for load balancing and filtering/auth of requests and then front that with a CDN.  I just don't like the endpoint out on its own.  It adds a level of complexity that at this point, I have found unnecessary.   If I can just use a cloud service like Bonsai or Found through Tire without having to worry about blocking I/O, then it just becomes another Heroku service to us... which is where all this PAAS stuff is going anyway.  Thanks again.

**Comment by karmi** [comment]
I understand. There's a [_Faraday_](https://github.com/karmi/tire/blob/master/lib/tire/http/clients/faraday.rb) based client, so it should be very simple to check out em-http-request. What about this issue? Closing now, reopening if you bump into something?

**Comment by dfuentes77** [comment]
Sounds good. Thanks.
