### ISSUE TITLE
Working with locations wiki document is incorrect

### ISSUE THREAD

**Issue by kristopher** [karmi/retire#620]
In the working with locations wiki document it shows passing an array to the index like so [lat, lon]. When indexing an array as a geo point elastic search whats the order to be [lon, lat]. 

Here's whats the elastic search documentation has to say about it.  

```
Lat Lon as Array

Format in [lon, lat], note, the order of lon/lat here in order to conform with GeoJSON.
```

http://www.elasticsearch.org/guide/reference/mapping/geo-point-type.html

[lat, lon] will index fine and the search queries appear to work but upon closer inspection you will can see that the distances are way off.

**Comment by karmi** [comment]
@kristopher, yes, latlon as Array are "reversed" in the standard, confusingly enough. Can you edit the Wiki?

**Comment by kristopher** [comment]
Confusing for sure, even if the wiki article didn't exist I still would have done the same thing, because who orders coordinates that way :)

I'll edit it as soon as I get some time.

PS - Great library, with it it was simple and quick to get search up and running.

**Comment by karmi** [comment]
Thanks! :) Yes, the order is confusing, but is a standard... You mean this page? https://github.com/karmi/tire/wiki/How-to-work-with-locations-(geo)-in-Tire

**Comment by kristopher** [comment]
Ya that page.

**Comment by kristopher** [comment]
Updated the wiki page.  I just changed lat_lon to return a string and added a note about the ordering differences and a link to the documentation.

**Comment by karmi** [comment]
Thanks, @kristopher!
