### ISSUE TITLE
document.id.as_json throws exception if document.id is nil

### ISSUE THREAD

**Issue by tatemae** [karmi/retire#621]
This commit changed get_id_from_document to encode document.id as json:
https://github.com/karmi/tire/commit/98e6dc7a97b029d73a32adfde91cbc121ec7bc66

However, we have an attribute on our model called id. This value is nil for new entries and so will always throw an exception. What about adding a check for document.id before calling .as_json?

**Comment by luislavena** [comment]
I'm suffering similar issues with custom `id` field. Our ID field is a combination of several fields of the document.

We even expose `to_indexed_json` and use `MultiJson.dump` in it.

I'm using Tire in a plain Ruby application so ActiveSupport is not added (even that is dependency of Tire)

After I require `active_support/json` at the top of `Tire::Index`, things start working.

**Comment by karmi** [comment]
Yeah, but that commit was really needed so Mongoid integration works at all... Where is the exception thrown? In JSON library, in Tire, in Elasticsearch? Notice:

```
>> Oj.dump(nil)
=> "null"
```

**Comment by luislavena** [comment]
> Yeah, but that commit was really needed so Mongoid integration works at all...

Can you simply `require "active_support/json"` at the top as I commented above?

In my case I'm using Tire outside Rails, so `ActiveSupport::JSON` is not automatically loaded.

`Tire::Index` should deal with its requires/dependencies, or when requiring `tire` it should load the needed part of ActiveSupport.

**Comment by luislavena** [comment]
> Where is the exception thrown? In JSON library, in Tire, in Elasticsearch?

`Oj.dump(nil)` works on my end, but since `Tire::Index` is doing `id.to_json` and `to_json` isn't defined, is failing:

```
irb(main):003:0> nil.to_json
NoMethodError: undefined method `to_json' for nil:NilClass
    from (irb):3
    from /Users/luis/.rbenv/versions/1.9.3-p385/bin/irb:12:in `<main>'
irb(main):004:0> require "active_support/json"
=> true
irb(main):005:0> nil.to_json
=> "null"
```

**Comment by karmi** [comment]
@luislavena OK, understood, sorry. The thing is, I don't think we need all of `activesupport/json`: the ActiveSupport dependency is brought in by ActiveModel, and only selected parts are included [explicitely](https://github.com/karmi/tire/blob/master/lib/tire.rb#L7-L9).

But I agree that the `as_json` call in [`Index#get_id_from_document`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L477) makes it now very fragile. Let's try adding it and see how much it eventually breaks for people.
