### ISSUE TITLE
#save on child model doesn't work

### ISSUE THREAD

**Issue by barakcoh** [karmi/retire#622]
Hi

I have a Child model with Tire::Model::Persistence. When I `#save` it, I get back a `RoutingMissingException[routing is required for [...` error. This is consistent with the documentation on elasticsearch.org which states either "parent" or "routing" are required for updating a child document. 

It looks like `#save`  calls `update_index` which in turns calls `index.store` but does not pass on the `_parent` in the options hash.

**Comment by karmi** [comment]
> It looks like #save calls update_index which in turns calls index.store but does not pass on the _parent in the options hash.

Indeed. I think your best option here is to provide the indexing logic yourself. It is imaginable the library would be able to introspect your models and perform this automatically, but I think it's better to leave complicated scenarios to application code. I'm open to any ideas or suggestions, on the other hand!

**Comment by karmi** [comment]
Closing.
