### ISSUE TITLE
Import silently ignoring failed index creation

### ISSUE THREAD

**Issue by nz** [karmi/retire#623]
Specifying an index with an invalid mapping can lead to a 400 response from Elasticsearch when attempting to create the index. The import rake task will silently ignore this error, and proceed to start indexing documents.

The default development configuration will subsequently auto-create an index as the documents are being imported, using a dynamic mapping. This is incorrect behavior, because Elasticsearch is not using the (invalid) user-supplied mapping.

If index auto-creation is disabled with `action.auto_create_index: 0` then attempting to add the documents will fail. This currently results in a slightly misleading error message about the index not existing, but otherwise no real information about why.
### Setup

An example invalid mapping.

``` ruby
class ServiceProvider < ActiveRecord::Base

  attr_accessible :name

  include Tire::Model::Search
  include Tire::Model::Callbacks

  tire.mapping do
    indexes :name, type: 'string', index: 'keyword'
  end
end
```

Note the invalid setting of `index: 'keyword'` rather than the intended `analysis: 'keyword'`.
### Attempting to import

```
# index does not yet exist
$ curl http://localhost:9200/service_providers/_search  
{"error":"IndexMissingException[[service_providers] missing]","status":404}

# importing - should create index
$ bundle exec rake environment tire:import CLASS=ServiceProvider
[IMPORT] Creating index 'service_providers' with mapping:
{"service_provider":{"properties":{"name":{"type":"string","index":"keyword"}}}}
[IMPORT] Starting import for the 'ServiceProvider' class
--------------------------------------------------------------------------------
1/1 | 100% [ERROR] 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}, retrying (1)...
[ERROR] 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}, retrying (2)...
[ERROR] 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}, retrying (3)...
[ERROR] 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}, retrying (4)...
[ERROR] 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}, retrying (5)...
[ERROR] Too many exceptions occured, giving up. The HTTP response was: 404 > {"error":"IndexMissingException[[service_providers] missing]","status":404}

================================================================================
Import finished in 0.01029 seconds
```

The import task should fail if it doesn't receive a successful response from Elasticsearch for the index creation request. It looks like there's even a conditional in the import task for exactly that, so the issue may be higher up from the import task itself.

Here's the response that Elasticsearch is sending back (via net-http-spy):

```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 159

{"error":"MapperParsingException[mapping [service_provider]]; nested: MapperParsingException[Wrong value for index [keyword] for field [name]]; ","status":400}
```

Is `Response#success?` not returning `false` when it should be for this response?

I don't quite have the time today to dig into the specs and figure out a real fix, hence the Issue instead of a PR, but I'll try to get to that later this week. Unless @karmi or someone else can beat me to it?

CC @ph who graciously helped me track down what we first thought might be an error with [Bonsai](http://www.bonsai.io/). Also cc @fizx for our general interest on a vaguely Bonsai-related support issue.

**Comment by karmi** [comment]
I can't replicate the issue:

```
$ rake environment tire:import CLASS=Article FORCE=true
[IMPORT] Deleting index 'articles'
[IMPORT] Creating index 'articles' with mapping:
{
  "article":{
    "properties":{
      "title":{
        "type":"string",
        "index":"keyword"
      }
    }
  }}
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":"MapperParsingException[mapping [article]]; nested: MapperParsingException[Wrong value for index [keyword] for field [title]]; ","status":400}
```

**Comment by nz** [comment]
Awesome. False alarm! Version mismatch on my end. Which is good, because I was about to be even more confused ;)
