### ISSUE TITLE
Error loading custom synonym file in Elasticsearch

### ISSUE THREAD

**Issue by brupm** [karmi/retire#624]
I am using Rails, Tire and Elasticsearch on EC2 single server setup, no sharding or replication (this is the Jenkins CI Server). With a custom initializer as such:

```
analysis:
  filter:        
    name_synonyms:
      type: synonym
      synonyms_path: <%= Rails.root.join("config", "synonyms", "name_synonyms.txt") %>
```

This file runs thru Erubis and the synonyms path is converted to something like this: 

```
/root/workspace/project-project-0f317744a1870b4baf61bbaeb390ebe1/config/synonyms/term_synonyms.txt
```

When I list the files in the sever I see the following: 

```
root@ip-XX-XXX-XX-XXX:~/workspace/project-project-0f317744a1870b4baf61bbaeb390ebe1/config/synonyms# ls -la
total 20
drwxr-xr-x 2 root root 4096 Feb 11 18:25 .
drwxr-xr-x 7 root root 4096 Feb 11 18:25 ..
-rw-r--r-- 1 root root 3117 Feb 11 18:25 location_synonyms.txt
-rw-r--r-- 1 root root 3999 Feb 11 18:25 name_synonyms.txt
-rw-r--r-- 1 root root 2144 Feb 11 18:25 term_synonyms.txt
```

Which is exactly I am expecting, however I see the following error when running `rake spec`

```
500 : {"error":"IndexCreationException[[test_facilities] failed to create index]; nested: FailedToResolveConfigException[Failed to resolve config path [/root/workspace/project-project-0f317744a1870b4baf61bbaeb390ebe1/config/synonyms/term_synonyms.txt], tried file path [/root/workspace/project-project-0f317744a1870b4baf61bbaeb390ebe1/config/synonyms/term_synonyms.txt], path file [/etc/elasticsearch/root/workspace/project-project-0f317744a1870b4baf61bbaeb390ebe1/config/synonyms/term_synonyms.txt], and classpath]; ","status":500}
```

It seems to me Elasticsearch is not capable of loading the files although the path is correct, could be a load order issue, I am really not too sure.

**Comment by brupm** [comment]
cc @nz any ideas?

**Comment by nz** [comment]
@brupm color me stumped. do you get this locally in development? doesn't really seem like a Tire thing tbh.

**Comment by karmi** [comment]
> It seems to me Elasticsearch is not capable of loading the files although the path is correct, could be a load order issue, I am really not too sure.

Yes, agreed. First thing, is Elasticsearch properly configured to look in this folder for config files? Second, those files are owned by root, under which user is Elasticsearch running?

**Comment by brupm** [comment]
I do agree this isn't _100%_ on the Tire side, but it could affect people using Tire (I also posted the question to Stackoverflow and the Elasticsearch mailing list) 

I have made a few changes and now the file is owned by elasticsearch, it has the same exact permissions as /var/log/elasticsearch/elasticsearch.log which the ES binary is writing to. _Still the same issue continue to happen yet the file is absolutely there_

@karmi you asked if ES is properly configured to look in this folder. It seems to know where to look at it provides me the full path of the file.

If I place the files under a static location such as `/etc/elasticsearch/synonyms` even with root perms it works flawlessly.

**Comment by karmi** [comment]
Closing this, this is an Elasticsearch issue. BTW, I'd consider adding synonyms to my application and creating the correct analyzer via API.

**Comment by bpang** [comment]
I know this is an old thread, but I ran across the same issue.  It's due to the elasticsearch user not being able to traverse the directories that contain the term_synonyms.txt file.  chmod o+x /parentfolders should suffice.

**Comment by kranthitech** [comment]
@bpang Thanks for sharing the solution. I was facing the same problem.
To get it running, I had to run chmod o+x on all parent folders i.e. if the file was in 
/root/a/b/synonyms.txt

chmod o+x /root
chmod o+x /root/a
chmod o+x /root/a/b

Please let me know if this was the right approach, or is there a better way? Thanks.

**Comment by jogaco** [comment]
In case anyone ends here with the same problem: This is the correct way of doing it: http://stackoverflow.com/a/35402714/345996
By adding the corresponding entry in the Java security policy file!
