### ISSUE TITLE
Highlight not working for long type fields

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#625]
Elasticsearch: 0.20.2v
Tire: 0.4.3v

The mapping I'm using is of the format:

```
:user => {
            :properties => {
              :mob => { :type => :long, :store => 'yes' },
              :name => { :type => :string, :store => 'yes' }
            }
          }
```

My highlight option is set as following in the query:

```
highlight :mob, :name
```

I'm getting blank results in the highlight array when the values in mob are searched. But, the highlight is working when values from name field are searched.

The results are getting displayed in case of mob, but only the highlight is not working. Is there any limitation like only certain type of fields can be highlighted?

```
query_results.each_with_hit do |result,hit|
        puts hit['highlight'].inspect
end
```

PS: I tried the same with elasticsearch as well (via curl), that doesn't seem to work there too. I'm not getting any highlight fields for mob field...

**Comment by karmi** [comment]
I think this is a restriction on the Elasticsearch level then, please submit an issue or ask on the mailing list..
