### ISSUE TITLE
Is there any way to create multi_match query?

### ISSUE THREAD

**Issue by vsizov** [karmi/retire#626]
That's example of match i did. I need the same but with multi_match

``` ruby
def by_user_input(text_location, load = true)
  tire.search(load: true) do |search|
    search.size 25
    search.query do
      filtered do
        query do
             match(:cityname, text_location, :type => :phrase_prefix)
        end
      end
    end
  end.results
end
```

**Comment by karmi** [comment]
Have you looked into integration tests for the match/multi_match?

**Comment by vsizov** [comment]
hm. I tried that. But i have another context i think. When i try to pass array to match in my code i got error.

**Comment by karmi** [comment]
Could you explain it better and post code examples of stuff which si failing for you?

**Comment by vsizov** [comment]
sorry. Works fine. Thanks for your time.
