### ISSUE TITLE
Tire.search not accepting pagination options

### ISSUE THREAD

**Issue by Will-Sommers** [karmi/retire#627]
Below will not accept pagination options

``` ruby
Tire.search "users", :per_page => 2, :page => 4 do
  query do
    string '*'
  end  
end  
```

Whereas does accept pagination options.

``` ruby
User.search :per_page => 2, :page => 4 do
  query do
    string '*'
  end  
end  
```

I'm asking this pretty trivial question because I'm trying to use msearch to search across multiple models and failing at passing in pagination options successfully. Any thoughts?

**Comment by karmi** [comment]
The `query :per_page => 2` is invalid. Could you please look into integrations tests? https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L282-L295

**Comment by Will-Sommers** [comment]
Karmi, you beat me to it. I've edited the question. Looking into it now.

**Comment by Will-Sommers** [comment]
@karmi is there a reason why there's no pagination in the multi_search integration test? I've taken a look at the integration test but it just confirms that the second example works but doesn't cast any light on the first. I've read through almost all of the gem's source code and integration tests but haven't found much help.

https://github.com/karmi/tire/blob/master/test/integration/multi_search_test.rb

**Comment by Will-Sommers** [comment]
Sorry for the multiple posts at once... just delving into this... 

 will_paginate is accepting the options in the first case and building the pagination scheme accordingly however the results are still being shown without :page or :per_page being considered.

**Comment by karmi** [comment]
> I've taken a look at the integration test but it just confirms that the second example works but doesn't cast any light on the first

Ah, sure. The convenience per_page/page don't work with the `Tire.search`, will need to have a look into that.

>  is there a reason why there's no pagination in the multi_search integration test

I think those convenience params are exposed only for models... Will try to have a look shortly into it.

**Comment by Will-Sommers** [comment]
Could you give me a starting place to think on if I wanted to add pagination or retrieve records past 10?

 Thanks so much for replying so fast.

**Comment by karmi** [comment]
You can work with the default `articles` index, and just a very small `per_page`, eg. 1. The DSL tests are [here](https://github.com/karmi/tire/blob/master/test/integration/dsl_search_test.rb), maybe just add a context there... But still on the fence with the feature -- with the DSL searches, I think it's better to use the `size`/`from` methods...

**Comment by karmi** [comment]
Any new info about this? I would really expose these params _only_ for models.

**Comment by karmi** [comment]
Closing, feel free to reopen with more info if needed...

**Comment by Will-Sommers** [comment]
Sorry man. Thanks for the help. We ended up going with your solution.
