### ISSUE TITLE
Index not updating on Mongoid inc()

### ISSUE THREAD

**Issue by relevante** [karmi/retire#628]
I'm not sure if this is a Tire or a Mongoid issue, but in my application, when I use inc to increment an indexed counter field, the Tire index is not updated.  Manually saving the field updates the index.

**Comment by karmi** [comment]
@relevante Please post some code :)

**Comment by relevante** [comment]
After incrementing a field called :view_count like this:

``` ruby
  # in a model
  def count_view!
    self.inc(:view_count, 1)
  end
```

calls to search including

``` ruby
      s.sort { by :view_count, 'desc'}
```

ignore the updated value.  The model has the updated value coming back from Mongoid, but the search is ordered according to the value prior to the update.

If I call save on the model after incrementing the field, like this:

``` ruby
  # in a model
  def count_view!
    self.inc(:view_count, 1)
    self.save
  end
```

the Tire index updates, and everything is fine.

**Comment by karmi** [comment]
1/ Depends on how the `inc` is reflected in `to_indexed_json`, that should be easy for you to check out in Irb/Rails console

2/ Remember, there's a 1sec delay between Elasticsearch's indices being refreshed, ie. before the results are available for search.

**Comment by relevante** [comment]
It's not a timing-related issue, as the incorrect sort persists though many refreshes of the sorted result page.

to_indexed_json is correct after the inc and before the save.  The issue appears to be that whatever hook causes Tire to update its indexes isn't called when inc is called.

**Comment by relevante** [comment]
OK, upon digging a little deeper, Mongoid doesn't fire any callbacks after atomic updates (https://github.com/mongoid/mongoid/issues/2751), so doesn't look like there's much that can be done on this end.  Thanks!

**Comment by karmi** [comment]
> The issue appears to be that whatever hook causes Tire to update its indexes isn't called when inc is called.

It uses the `after_save` callback, and I encourage everyone to use a custom strategy here, when they need something other then the naïve default.

Also, remember that you have to call `refresh` so your changes are immediately available in searches, eg. in tests.
