### ISSUE TITLE
Having problems searching within two different indexes

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#631]
I couldn't find this in the documentation but from looking at the issues in the past I was able to get the following syntax:

``` ruby
    search_result = Tire.search ['cars-shops-index', 'car-drivers-index'] do
      query { string query }
      filter 'geo_distance', distance: '5miles', coordinates: user_coordinates
      min_score 5
      size 100
    end
```

But I am not getting a result set. How do you search in two (or more indexes) even if one depends on a geo_distance filter and the other one doesn't?

Thank you!

**Comment by cameronkendall** [comment]
This is in fact working.  I needed to use search_result.results.

**Comment by karmi** [comment]
Ah, sure, you need to use the `results` method of the object.
