### ISSUE TITLE
One Global Settings for Multiple Models with one Index url

### ISSUE THREAD

**Issue by miry** [karmi/retire#632]
What is the best practice to  manage next.
1. I have one index for each models, because there are no ability to search with multiple indexes in Heroku Bonsai. Lets call it "test"
2. I want to setup custom analyzers and filters for these models.
3. Do you have some configuration to put block `settings` to example like:

``` ruby
Tire.configure do
  url "index-#{Rails.env}"
  settings :analysis           => {
               "filter"   => {
                   "filter_synonym" => {
                       "type"          => "synonym",
                       "expand"        => "true",
                       "synonyms_path" => Rails.root.join("config/analysis/synonym.txt")
                   }
               },

               "analyzer" => {
                   "analyzer_synonym" => {
                       "type"      => "custom",
                       "tokenizer" => "standard",
                       "filter"    => ["standard", "word_delimiter", "lowercase", "filter_synonym", "stop", "kstem"]
                   }
               }
end
```

So to be sure that anyone model would not replace this settings. If I put this to

**Comment by brupm** [comment]
You can use templates: http://www.elasticsearch.org/guide/reference/api/admin-indices-templates.html

**Comment by nz** [comment]
@miry, fwiw, the Bonsai addon supports multi-index search now. So you shouldn't strictly _need_ to use a combined index for your cross-model searching. Trying to work with a single consolidated index per environment with Tire is probably swimming upstream at this point unless you're willing to really dig in under the hood.

**Comment by miry** [comment]
@nz It is very good news about multi index search. I will try to use it again.

 Also I have solved the problem to use one settings, I have combined all mappings and settings and do creation of index own self without Model's helper method `create_elasticsearch_index` https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L106. Because it does not work good for my situation. It use incorrect mappings and settings for some type(models).

It is looks like https://gist.github.com/miry/4993652

Also I duplicate this mapping in models too, to be ensure that do store in elasticsearch only required fields.

**Comment by karmi** [comment]
@miry Should we close the issue then? You can store your analysis/mapping definitions in whatever Ruby structure which makes most sense to you, and either manually indices, or pass these configurations to Tire's `settings`, `mappings` methods.

**Comment by miry** [comment]
you may close
