### ISSUE TITLE
add support for _version_type during bulk import

### ISSUE THREAD

**Issue by bavaro** [karmi/retire#633]
According to:
http://www.elasticsearch.org/guide/reference/api/bulk.html

"Each bulk item can include the version value using the _version/version field. It automatically follows the behavior of the index / delete operation based on the _version mapping. It also support the version_type/_version_type when using external versioning."

As of now, Tire supports the _version field only, _version_type is ignored.

**Comment by marclennox** [comment]
I'm trying to use external version numbers and I see from this issue (and from the code) that the _version parameter is supported for bulk updates, but I'm not seeing support for it when calling the individual record "store" method on index.

Please confirm that _version is not supported on individual index store calls.

**Comment by karmi** [comment]
True, neither `version` nor `version_type` are supported in `Index#store`, though trivial to add.

**Comment by marclennox** [comment]
+1 to add it.  For now I've changed my method to use bulk store with an
array of 1 document.

That being said, I can't figure out to how to properly set the version_type
string in the index settings.  I'm getting a VersionMismatch exception
every time despite the fact that I'm sending a larger index number in the
buik store.

Where (and how) do I set the version_type to "external" through the Tire
gem?

**Comment by marclennox** [comment]
I sent pull request https://github.com/karmi/tire/pull/698 for this.  Version is properly sent over the wire with this change, however I still can't figure out how to configure the index to accept my external version.  Getting this every time.

``` ruby
VersionConflictEngineException[[openera_development:cloud_file:main:v1][0] [cloud_file][18549]: version conflict, current [-1], provided [1365518739]]
```

**Comment by karmi** [comment]
`version_type` is a regular URL parameter, set it to `external`...

**Comment by marclennox** [comment]
So in that case the index store method will need to also send version_type=external if a version is provided?  I don't see a way in the current method call to add the version_type parameter.

**Comment by karmi** [comment]
Yes, exactly. It's not supported yet, you can add it as part of your pull request?

**Comment by marclennox** [comment]
Will do

**Comment by karmi** [comment]
Example of the requests with `version_type`:

``` bash
curl -X DELETE localhost:9200/test-version-type
curl -X POST localhost:9200/test-version-type

echo
curl -X PUT 'localhost:9200/test-version-type/d/1?version_type=external&version=100' -d '{"title":"A"}'
echo
curl -X PUT 'localhost:9200/test-version-type/d/1?version_type=external&version=101' -d '{"title":"B"}'
echo
```

**Comment by marclennox** [comment]
Thanks.

I'm a bit confused though.  It seems that version was implemented in bulk
store, however the version_type=external is not in there, so it actually
doesn't work through the bulk API.  Also in elasticsearch documentation it
doesn't mention the version_type=external URL parameter, it mentions that
it's a "setting".

http://www.elasticsearch.org/guide/reference/api/index_/

**Comment by karmi** [comment]
Hmm, true -- `version_type` is not supported in `Index#bulk_store`...

**Comment by marclennox** [comment]
OK, I'll add that to my PR.  I've tested it locally and it works.  Thanks.

**Comment by bavaro** [comment]
Ok, reopening because were kinda of confused as to what happened here...

We opened Issue #633 because we saw that the '_version' parameter is supported by Tire during bulk indexing, but the '_version_type' parameter is not (we only use bulk indexing so we did not bother to look at single document indexing).

We opened a pull request, Issue #634, adding support for the '_version_type' parameter, along with tests for it.  We closed this issue (Issue #633) because we figured having the pull request open would suffice (we originally thought pull requests were supposed to reference issues, but they are actually issues themselves, so sorry about that).

Then 2 months later, marclennox commented that '_version_type' is not supported, and opened pull request Issue #698, with his own changes.  marclennox changes (from what we understood) seems to assume that if the '_version' parameter is specified, then Tire should assume that '_version_type' should be set to external.  That is not correct!

See: http://www.elasticsearch.org/guide/reference/api/index_/

Basically,  you can specify '_version' without '_version_type'.  It is used for optimistic locking.  You can pull a document out of the ES index, keep note of the version, and post the same document back with modifications AND the version of the document you pulled.  If the version you're posting does not match the version the ES index has, the write is not accepted, and you must try again; someone updated that document between the time you pulled and reposted it.

When using '_version' in conjunction with '_version_type' (set to 'external'), ES trusts that you will handle the versioning, and checks that the version you are posting is greater than the version in the ES index.

The two use cases differ, so however this is added, please don't assume '_version_type' should be external when '_version' is supplied.

So it seems we need support for '_version_type' in both Tire bulk and store operations.  Issue #634 adds it for bulk, but not for store.

**Comment by marclennox** [comment]
OK, if you look at the comment history I had asked for direction on this before making the assumption...  but perhaps I wasn't clear.

So with that being said, can I get some direction on where I should take this pull request.  Should I rollback my bulk import changes and just get the single update with version working?

**Comment by bavaro** [comment]
Hey marclennox,  sorry for not responding to your request for comments.  We don't check this account as often as we should.

The rules kinda go:
'_version' can be specified alone
'_version' and '_version_type' can be specified together
'_version_type' cannot be specified without '_version'

And I would just depend on the user of Tire to set the '_version_type' to whatever they want it to be, and let them handle the ES error Tire will return if they put something invalid.  This way, in the future, if ES supports other '_version_type' values, the code doesn't have to change.  Our code looks like:

@meta_data.merge(_version: version.to_s, _version_type: "external")

Does this help?

**Comment by marclennox** [comment]
Thanks for this.  I'll update the PR hopefully tonight.

**Comment by bavaro** [comment]
No problem.  Also see #634 if you need tests for the bulk import supporting '_version_type'

**Comment by karmi** [comment]
Hi, sorry for the ridiculous reaction time! I've merged and refactored the commit a bit, it's now on master.

**Comment by marclennox** [comment]
Thank you.
