### ISSUE TITLE
original id of document gets replaced with elasticsearch id

### ISSUE THREAD

**Issue by moudy** [karmi/retire#636]
when inspecting the results of a query the `id` is the id in the elasticsearch, not the indexed value.

```
# expecting the mongo id to be here, not ES _id
<Item id: "762phS8zTuug89oqXaqhSg", ...>
```

the id is mapped as such `indexes :id, as: 'id'` and is correctly indexed.

is this intended, am i missing something about how to correctly index and retrieve the id field?

**Comment by karmi** [comment]
Please provide more context, full data & query, etc...

**Comment by moudy** [comment]
as you can see from the data below the document's original mongo id is replaced by the elasticsearch id. i can see the use case for this but am confused about how to preserve the mongo id.

query

```
s = Tire.search('users1') do
  query do
    match ['name.autocomplete', 'username.autocomplete'], 'moudy'
  end
end
```

result of `s.results.first` (note the missing mongo id)

```
<Item id: "762phS8zTuug89oqXaqhSg", email: "moudy@gmail.com", name: "Moudy", username: "moudy", _score: 7.311601, _type: "user", _index: "users_2_19_13", _version: nil, sort: nil, highlight: nil, _explanation: nil>
```

data when looking at document through elasticsearch-head

```
{
  _index: users_2_19_13
  _type: user
  _id: 762phS8zTuug89oqXaqhSg
  _score: 7.870416
  _source: {
    id: 5002c42eb1f4ed000201d6e6
    email: moudy@gmail.com
    name: Moudy
    username: moudy
  }
}
```

**Comment by moudy** [comment]
ok sorry this is related to doing a bulk import. found the answer to my issue here https://github.com/elasticsearch/elasticsearch/issues/2638

**Comment by karmi** [comment]
Good! I must admit I was a bit confused by the issue -- no MongoDB user ever reported something like this, and there's plenty of ES <> Mongo deployments via Tire out there... The IDs between search results and your mongo data should really be 1:1 consistent.
