### ISSUE TITLE
Export all index data to file

### ISSUE THREAD

**Issue by amejiarosario** [karmi/retire#637]
Is there a way to export model data to CSV files?

**Comment by karmi** [comment]
Not, but I was toying with an idea to write implementation for https://github.com/meskyanichi/backup.

If all you need to do is export index to CSV, use the `Index#scan` method, it's less then 10 lines of Ruby:

``` ruby
require 'tire'
require 'csv'

csv = CSV.open("people.csv", "wb")

Tire.scan('test-people').each do |results|
  results.each { |r| csv << r.to_hash.values }
end
```

**Comment by amejiarosario** [comment]
I have millions of records and it's eating up the memory... Any ideas to make it scale?

**Comment by karmi** [comment]
@amejiarosario Use the new gem, use the `scan` method, that will give you batches of data to store.
