### ISSUE TITLE
Too general method name - matches - on tire models

### ISSUE THREAD

**Issue by erez-rabih** [karmi/retire#638]
Hi,

I tried to integrate the gem into my system, and had some trouble since I have a matches table in my system and also a matches association to the model I wanted to index.

The method name "matches" defined at https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L192 is too general and might collide with local model method names.

I think a more specific method name should be considered.
I forked the gem and mass replaced all occurrences of the string 'matches' with 'tire_matches' and tests pass well.

I'd be more than happy to open a pull request with an agreed method name to replace the old matches.

Thanks for the great gem.

**Comment by karmi** [comment]
Hi, Tire goes to some lenghts to _not_ collide with any already defined methods, with the `tire` proxy (see README).

In the `matches` case, there has been a bug, see issue #501, but it has since been fixed by 69234af. What version this is on?

**Comment by erez-rabih** [comment]
I'm on version 0.5.4

**Comment by karmi** [comment]
The commit is included in that version. Again, Tire does _not_ override any already defined method names, including `matches`, please see tests. You need to provide more info about your model etc.

**Comment by karmi** [comment]
Closing, feel free to reopen with more info if needed...
