### ISSUE TITLE
too much data for sort() with no index.  add an index or specify a smaller limit

### ISSUE THREAD

**Issue by jpsilvashy** [karmi/retire#64]
When running import for my model, if I have a lot of records I get the following:

```
[IMPORT] Starting import for the 'Recipe.all' class
--------------------------------------------------------------------------------
rake aborted!
too much data for sort() with no index.  add an index or specify a smaller limit
```

Now, I think this is more of a Mongo problem, but I'm not sure what index to create to satisfy Tire, or maybe it's a tire problem, I can't really tell.

**Comment by karmi** [comment]
Hi, this is definitely a Mongoid problem. You're loading the data with `CLASS='Recipe.all'` trick, which loads all documents into memory. There's full info about importing and Mongoid at issue #48: https://github.com/karmi/tire/issues/48#issuecomment-1499519...

**Comment by karmi** [comment]
This: karmi/tire@8d592e7 is the culprit. I'll recheck what was the funky stuff with `documents.empty?` in will_paginate...

(`will_paginate` needs a check for `#empty?`, _Kaminari_ needs a check for `#size > 0`)
