### ISSUE TITLE
Sorting on script_fields

### ISSUE THREAD

**Issue by brupm** [karmi/retire#642]
I am trying to sort by rand, and I added the following script_field to my query: 

``` ruby
tire.search
  query { all }
  script_field :random_sort, script: "Math.random()"
  sort { by :random_sort, "asc" }
end
```

Although I am able to retrieve the random_sort field from the Tire::Results::Item, I don't seam to be able to use it for sorting. 

```
Parse Failure [No mapping found for [random_sort] in order to sort on]]; }]","status":500}
```

@karmi is this possible? 

I am trying to get the equivalent to this query with Tire https://gist.github.com/brupm/5035241

**Comment by brupm** [comment]
Seems it needs the mapping defined: http://pastie.org/6342437#11

**Comment by karmi** [comment]
So, any resolution to this? Should we close it? It won't work like this anyway...

For context, see the Stackoverflow answer: http://stackoverflow.com/questions/9796470/random-order-pagination-elasticsearch

**Comment by karmi** [comment]
Closing, feel free to reopen with more info if needed...
