### ISSUE TITLE
Setting index_prefix doesn't work when also supplying index name

### ISSUE THREAD

**Issue by marclennox** [karmi/retire#644]
Looking at the code it seems that setting an index_prefix is only relevant if you don't specify an index_name and rely on the default index_name from class conversion.

Is this correct?

**Comment by karmi** [comment]
Yes, correct -- if you set index name via `MyModel.index_name`, the prefix is ignored. Do you think it makes sense to support it for custom index names?

**Comment by marclennox** [comment]
Thanks Karel.  My assumption was that the prefix would apply in both cases.
 I suppose there's an argument to be made for both cases.  For my own
usecase I would want the delimiter to be configurable also (I use : instead
of _).  For now I'm just prepending my own prefix to the index name.

**Comment by karmi** [comment]
@marclennox I think that's a good approach, and since `index_name` can be defined as a block, makes it very readable and more transparent, I'd say... Closing this, if that's OK.

**Comment by marclennox** [comment]
Sounds good.

**Comment by karmi** [comment]
Cool.
