### ISSUE TITLE
Using tire/elasticsearch with a multi-tenant app

### ISSUE THREAD

**Issue by fbernier** [karmi/retire#646]
Hey, I'd like to integrate tire with ActiveModel integration in a multi-tenant app. So we've got models which are used on multiple databases. I'd need to do the same with tire.

When a request comes in, I switch the current database to the one needed. I'd need to do the same with elasticsearch so if I take the example of the Readme, I can have an Article table in multiple databases. I'd need to isolate the elasticsearch indexes to fit with my current database.

Do you know a way/workaround to do such things with tire? If not do you see what could be added to make it work?

Thanks for everything!

**Comment by fbernier** [comment]
I finally fell on this conversation which looks to be what I want. Sorry for the noise.

https://github.com/karmi/tire/pull/92#issuecomment-6929988

**Comment by karmi** [comment]
@fbernier Yes, sorry I didn't get here sooner, indeed the [discussion in #92](https://github.com/karmi/tire/pull/92#issuecomment-6929988) is what I would point you to. Feel free to update the thread or open new issue for questions.
