### ISSUE TITLE
Tire and the Rails Console

### ISSUE THREAD

**Issue by Will-Sommers** [karmi/retire#647]
Karmi,

I'm noticing differences when I complete actions via my rails console and via my web interface. Most importantly, the index is not updating when items are changed via the rails console. 

I've confirmed via curl -XGET that the index is not updating via the console. It is the updating when changes are made via the web interface.

Thanks!

**Comment by karmi** [comment]
Hi, that would be very strange -- it doesn't matter if you execute the code in controller or in console. Please post relevant info from your console session / model setup.

**Comment by Will-Sommers** [comment]
Karmi, you're right. I hadn't restarted the console but had changed ES URL.

**Comment by karmi** [comment]
@Will-Sommers Cool, then close the issue? :)
