### ISSUE TITLE
Extra queries fired on ActiveRecord Indexing

### ISSUE THREAD

**Issue by mikecx** [karmi/retire#649]
With an empty tire.mapping hash i'm seeing 8 queries per record happen when trying to create the initial index using Class.import. The queries are hitting tables that are associated with the current model but not being used for any indexing. This would not be a problem at small scale but would take us months to index our real dataset.

The question is, why is an empty mapping causing those other tables to be hit and queried on index?

**Comment by mikecx** [comment]
After seeing some ideas around to_indexed_json tried that out too. Setting that to {}.to_json continues to show the problem. Also tried with just indexes :id and seeing the same thing. A quick estimation shows that even with the bulk importer we are looking at 10+ weeks because of this. This is a huge issue for anyone with any sizable data.

**Comment by mikecx** [comment]
More information, seems to only be happening on the batch importing. Using Class.update_index only seems to make external database calls where needed.

**Comment by karmi** [comment]
I'm not sure I understand 100% your question/problem, but if you're importing records across tables, and you want to fight `n+1` queries, you can pass relevant snippets as params to the paginate method:

``` ruby
bundle exec rake environment tire:import PARAMS='{:include => ["comments"]}'  CLASS=Article FORCE=true
```

See this StackOverflow question for context: http://stackoverflow.com/questions/13600086/index-the-results-of-a-method-in-elasticsearch-tire-activerecord/13847929#13847929\

If you're loading substantial amount of data, not that paginating with `LIMIT/OFFSET` is not exactly effiecient, and `find_in_batches` does a better job -- see [code](https://github.com/karmi/tire/issues/530#issuecomment-10996259) in issue #530

**Comment by mikecx** [comment]
karmi, certainly appreciate the updates to the docs. We've switched to using find_each and to_indexed_json which has it running much faster and will work. The importing problem using Class.import is that it appears to make n+1 queries even when the mappings only contains the model id and the to_indexed_json is returning only { :id => id }.to_json.

**Comment by karmi** [comment]
Hmm, I'm wondering how this would happen -- the `to_indexed_json` with `{ :id => id }.to_json` should just fetch the ID and that's it. Would it be possible if you add more info to the issue, Class definition (relevant parts), and the output of the importing -- ideally with Tire.logger and ActiveRecord.logger set to STDERR? Gist/pastie/etc usually works better if the outuput is huge...

**Comment by karmi** [comment]
@mikecx Hi, any news on this?

**Comment by mikecx** [comment]
Sorry, been super busy over the last few days. Will try and get a test setup today and report back.

**Comment by karmi** [comment]
Closing, please reopen with new info, OK? Thanks!
