### ISSUE TITLE
Relations in Tire::Model::Persistence?

### ISSUE THREAD

**Issue by naquad** [karmi/retire#65]
I want to throw away MongoDB and I need relations. So the question is: are all those belongs_to, has_many, has_and_belongs_to_many, has_one, has_many :xxx, :as => :polymorphic are they planned for Tire::Model::persistence?

Thank you.

**Comment by naquad** [comment]
`ActiveRecord::Associations` can't help here :( Those methods will have to be implemented ground up.

**Comment by karmi** [comment]
Hi,

first, I'd _definitely_ like some sort of support for associations in `Tire::Persistence`.

But I don't think the ActiveRecord semantics are good fit for a schema-free store such as ES. I don't think the association support in CouchRest or SimplyStored makes much sense, for example. In a store such as ES, splitting the data into different objects (say `Article` and `Tag`) is usually an antipattern. There are valid cases, such as `Article` and `Comment`. For such cases, a [nested documents](http://www.elasticsearch.org/guide/reference/mapping/nested-type.html) would make a great fit.

As for the Ruby API, that's still far away. The preliminary feature for anything like this would be to allow casting values, in the similar sense as CouchRestModel does it...

**Comment by naquad** [comment]
I won't argue on pattern / antipattern, because using search engine instead of database is hardly a common practice, so for doing that some patterns must be broken.

I'm doing my own extension for Tire implementing associations atm. There is not much to show yet, but if I'll get it to production I'll post a patch or pull request here.

To be honest I still don't know will it get to production or not, because ES is missing couple of features I need and I'm starting to look at Solr with its dynamic attributes.

**Comment by karmi** [comment]
> I won't argue on pattern / antipattern, because using search engine instead of database is hardly a common practice (...)

Yeah, but one way to look at ElasticSearch would be to see it as a database with pretty powerful search and aggregation capabilities. Nothing wrong with using it as a storage (for instance when compared with CouchDB or MongoDB).

> I'm doing my own extension for Tire implementing associations atm. There is not much to show yet, but if I'll get it to production I'll post a patch or pull request here.

Great. (There's a `tire-contrib` repo prepared for extensions like that. Feel free to submit a patch against `tire`, I'll do the extraction myself.)

> To be honest I still don't know will it get to production or not, because ES is missing couple of features I need and I'm starting to look at Solr with its dynamic attributes.

Are you referring to http://wiki.apache.org/solr/SchemaXml#Dynamic_fields? ElasticSearch does not need anything like that, because with dynamic mapping, it infers the field type from the JSON document (integer vs string vs date, etc). Could you describe your case in more detail if this is not satisfactory?

**Comment by naquad** [comment]
> Are you referring to http://wiki.apache.org/solr/SchemaXml#Dynamic_fields? ElasticSearch does not need anything like that, because with dynamic mapping, it infers the field type from the JSON document (integer vs string vs date, etc). Could you describe your case in more detail if this is not satisfactory?

I know ES is schema-less. I mean if I'll move to Solr I'll have to use those.
Problem is I need spell checking and recommendations, which are already implemented in Solr, but not in ES.

**Comment by karmi** [comment]
If you'll move from ES to Solr, you'll have a whole different set of problems, _dynamic fields_ being the smaller one, I'd bet :)

**Comment by hgujral** [comment]
For some reason I'm not able to get an index mapping property of 'integer' for my persistence model.

```
class Product
  include Tire::Model::Persistence
  include Tire::Model::Search
  include Tire::Model::Callbacks

  property :name, boost: 10
  property :description, analyzer: 'snowball'
  property :price, type: 'integer'
  ...
  ...
```

When I look at the index metadata, this is what I get:

```
...
...
name: {
   type: string
},
price: {
   type: string
},
description: {
   type: string
},
...
...
```

What's wrong here!?

**Comment by karmi** [comment]
@hgujral Could you try with current master? It has lots of improvements in persistence.

@naquad There's been some improvements to persistence since you filed the issue, eg. 91e39fb. Closing this, please open a new one if your problems are not solved...
