### ISSUE TITLE
Tire::Results::Collection returns nil for each Tire::Results::Item

### ISSUE THREAD

**Issue by mdi** [karmi/retire#651]
Using Ruby v2.0.0p0, ES v0.20.5, Tire v0.5.4. Doesn't happen with Ruby v1.9.3-p374.

I'm doing a multi-model search like this:

```
if term = params[:term].presence
  s = Tire.search TIRE_INDEX_NAME, load: true do
    query { string term }
  end
end
```

`s.results` contains four items, as it should:

```
#<Tire::Results::Collection:0x007fe0b42514e8 @response={"took"=>4, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>4, "max_score"=>7.13994, "hits"=>[{"_index"=>"lj-development", "_type"=>"venue", "_id"=>"5091369a4c80861ebe000001", "_score"=>7.13994, "_source"=>{"name"=>"foo", "sort"=>"foo"}}, {"_index"=>"lj-development", "_type"=>"venue", "_id"=>"507cbe374c8086feb9000001", "_score"=>6.7372184, "_source"=>{"name"=>"foo", "sort"=>"foo"}}, {"_index"=>"lj-development", "_type"=>"venue", "_id"=>"507cc1214c808680bb000001", "_score"=>5.6764817, "_source"=>{"name"=>"foo", "sort"=>"foo-1"}}, {"_index"=>"lj-development", "_type"=>"act", "_id"=>"50e98fa84c8086eee1000001", "_score"=>5.389775, "_source"=>{"name"=>"Foo Bar", "sort"=>"foo-bar"}}]}}, @options={:load=>true}, @time=4, @total=4, @facets=nil, @max_score=7.13994, @wrapper=Tire::Results::Item, @results=[nil, nil, nil, nil]>
```

But notice they are all `nil`. Everything looks right when I run the same search with `curl`.

**Comment by karmi** [comment]
Hi, this is strange. Just tested some script on `2.0.0-p0` and I can see the results just fine. More importantly, the whole Tire integration test suite runs on 2.0.

Notice you're using `load: true` -- is it possible something is off with the dabatase? What kind of database it is? Can you turn on logging for Tire and ActiveRecord/Mongoid/etc?

**Comment by mdi** [comment]
Turned on logging and tried with and without `load: true`. Same results either way. Here is a [log file](https://gist.github.com/mdi/5075488). Results are stored in mongo v2.2.3 and I'm using mongoid v3.1.2.

**Comment by mdi** [comment]
Ah, I think I know what it is. I need to load the records by passing their `slug` attribute to `.find` instead of `id`. How can I do that with tire?

**Comment by mdi** [comment]
The real problem is that `mongoid-slug` is broken with 2.0.0p0. It will only find records by `slug` instead of `id` and/or `slug`. Bug report [here](https://github.com/digitalplaywright/mongoid-slug/issues/114). So I need to work around this until that bug is fixed.

**Comment by karmi** [comment]
Ah, hopefully it'll get fixed soon. You can overload the [`Collection#__find_records_by_ids`](https://github.com/karmi/tire/blob/master/lib/tire/results/collection.rb#L150-L152) -- not the nicest solution, but will get you there. (It'd be worth it here to allow pass a different, custom "collection" class.)

**Comment by mdi** [comment]
Thanks!
