### ISSUE TITLE
Pass routing parameter in a direct search

### ISSUE THREAD

**Issue by hemantsingal** [karmi/retire#661]
I am changing my ES client to tire and I have all those queries in hash format.
I want to use those same queries with Tire and also pass options like routing.

Is it possible? Can someone please provide an example?

**Comment by karmi** [comment]
You should be able to [pass search definitions as a Hash](https://github.com/karmi/tire/blob/master/test/integration/dsl_search_test.rb#L10-L16) in Tire as well.

**Comment by hemantsingal** [comment]
I can do that. That is correct. 
I want to know how to pass a routing parameter in this scenario.

**Comment by karmi** [comment]
Ah, sorry, sure! Fixed now on master, see 904798f

**Comment by hemantsingal** [comment]
Great!
