### ISSUE TITLE
Elasticsearch mapping does not include attributes from Rails key-value store

### ISSUE THREAD

**Issue by niuage** [karmi/retire#662]
The problem is more likely to be between the chair and the keyboard than with Tire, but still...

Model:

```
class Item
    store :socket_store, accessors: [:sockets, :socket_count, :socket_link_count]
end
```

Mapping:

```
mapping do
  indexes :id,                    key: "value", index: :not_analyzed
  indexes :sockets,               type: "object"
  indexes :socket_count,          type: "integer"
  indexes :socket_link_count,     type: "integer"
end
```

But here's what my actual index looks like:

![](http://i.imgur.com/zVkEBvN.png)

`socket_cout` and the othe 2 attributes are not at the root of the mapping, as if they were completely ignored.
edit: Actually, there are at the root of the mapping when I type `Tire.index('items').mapping`, I can see the 3 attributes. But when I look at the data in elasticsearch-head, I dont see them...

I know I could create methods with a different name and add them to the to_indexed_json, but I would have guessed it should work as is.

You could answer here if you like reputation points! (who doesn't?)

http://stackoverflow.com/questions/15224710/elasticsearch-mapping-does-not-include-attributes-from-rails-key-value-store

Thanks

**Comment by karmi** [comment]
@niuage My immediate ideas/questions would be:
- Isn't this on a stale index? What happens when you delete and re-populate the index?
- The `Item` class could be problematic, Tire does use a class like this, hopefully there's no clash.
- I see the `socket_count` being part of the `socket_store` object -- can you please pastie/embed a) mapping definition (as JSON or Hash), b) the JSON from `http://localhost:9200/yourindex/yourtype/someid`?

**Comment by niuage** [comment]
Hey,

No, I completely reset everything, database, and index, and still the same problem (btw I renamed socket_link_count to linked_socket_count)

I don't think the `Item` class is a problem because my search is working nicely, except for this.
Also, I actually have an index per type of items, and no `items` mapping, it was just to make the question easier.

I didn't exlude sockets_store from the indexed json, so yeah, `socket_count` and the other attributes appear in it. But ideally this field wouldn't be there. I'll clean up the indexed data later.

Here is the complete json of a Bow: https://gist.github.com/niuage/5093359

Btw, thanks for the help, nice to know we can always count on you :)

**Comment by niuage** [comment]
I'm going to try to add the key-value store accessors to the list of methods in to_indexed_json.

**Comment by niuage** [comment]
Ok, it worked when I do that: 

```
def to_indexed_json
    to_json(include: [:stats], methods: [:socket_count, :linked_socket_count, :sockets])
end
```

Looks like the fact that they are not actual item attributes forces me to add them to this method list. It kinda makes sense... so I don't think there's anything to fix.

Thanks a lot :)
