### ISSUE TITLE
import method interferes with activerecord-import gem

### ISSUE THREAD

**Issue by christoph-buente** [karmi/retire#664]
I use activerecord-import gem for bulk inserting SQL statements. Now when i try to run Model.import method the tire method is called instead. I know i can call Tire.index.import 

Is there a change of unregistering Model.import from tire?

Thx, Chris

**Comment by karmi** [comment]
Tire [tries hard](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L297) not stomp on previously defined methods, and puts everything into `tire` proxy by default. However, it depends on the load/include/etc order.

I can successfully do this:

```
    $ bundle exec rails console

    >> Article.import
    ArgumentError: Invalid arguments!
      from /Users/karmi/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activerecord-import-0.3.1/lib/activerecord-import/import.rb:199:in `import'
      ...

    >> Article.tire.import
      Article Load (15.4ms)  SELECT "articles".* FROM "articles" LIMIT 1000 OFFSET 0
      ...
```

So, it depends on the order in Gemfile, `require`, `include`, etc. Can you provide more info?

**Comment by karmi** [comment]
For completeness sake, if that would be your own custom methods, you'd need to do something like this:

``` ruby
class Article < ActiveRecord::Base

  def self.import(*)
    p "MY IMPORT"
  end

  include Tire::Model::Search
  include Tire::Model::Callbacks

  ...
```

**Comment by christoph-buente** [comment]
Well, this could be the reason. I do not need the mass import gem for the rails app to work. I have a minutely rake task running, which is doing the hard work. Parts of my gemfile look like this:

```
# Gemfile
gem 'activerecord-import', '<0.3.0', :require => false
gem 'tire'

# import.rake
require "activerecord-import/base"
ActiveRecord::Import.require_adapter('mysql2')
```

Requiring the activerecord-import gem in the Gemfile did the trick. Thanks a lot.

**Comment by karmi** [comment]
Cool!
