### ISSUE TITLE
Usin Mocha expectations with Tire?

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#667]
I'm trying to detect a 

```
  post.tire.update_index 
```

method call in one of my tests but 

```
 post.expects(:tire)
```

doesn't seem to work. Should I be looking for a different method call signature?
PS: post is a factory girl instance

**Comment by karmi** [comment]
Hi, not knowing the context, but I think the correct way would be to trap the call to `update_index`, like this:

``` ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'active_record'
require 'tire'

require 'test/unit'
require 'shoulda'
require 'mocha'

ActiveRecord::Base.establish_connection( adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Schema.define(version: 1) do
  create_table :books do |t|
    t.string   :title
    t.timestamps
  end
end

class Book < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end

class MyModelTest < Test::Unit::TestCase

  context "Book" do
    setup do
      @book = Book.new title: "How to impress your Rails friends with elasticsearch"
    end

    should "call `update_index` on save" do
      @book.tire.expects(:update_index)
      assert @book.save
    end

  end

end
```

**Comment by ike-bloomfire** [comment]
Thank you, that helped a lot, knowing where to put the expects.
 ... update_index is just not firing when it should during the test (have it in a callback than i'm doing manually vs using Tire::Model::callbacks), just have to figure out why.

**Comment by karmi** [comment]
Feel free to post the full test case, can have a look. Tests can be pain like this sometimes...

**Comment by karmi** [comment]
Closing, feel free to ping back if there's a problem.
