### ISSUE TITLE
Can tire callbacks be put into a resque job?

### ISSUE THREAD

**Issue by jasonfb** [karmi/retire#669]
We are using include Tire::Model::Callbacks on normal ActiveRecord models. 

We had some downtime for our website this weekend when Bonsai went down, is there a way to move the update/create callbacks into a resque job so that if the Elastic Search is down it does not kill our website?

has anyone tried this before?
Thanks in advance.
Jason

**Comment by karmi** [comment]
Yes, I bet many people background the indexing task like that... Just don't include the `Callbacks` module, and intercept the `after_commit/rollback/etc` events in your code, and `Resque.enqueue` them.

The downside here is that Resque brings an overhead, and within write-heavy application, your queues could be backed up. I think Sidekicq is worth exploring here, might have smaller footprint.

When you'd do this, I'd definitely put up some monitoring here, so you know when your data aren't indexed -- this could lead to surprising results. For example, you can store the IDs of records which weren't indexed, and periodically re-index them via sheduled Resque job, etc.

**Comment by karmi** [comment]
@jasonfb Closing, reopen or ping if you need more help, please.

**Comment by mahemoff** [comment]
https://github.com/EvilFaeton/tire_async_index

Apparently yes.
