### ISSUE TITLE
Document Escaping Procedure and/or Provide a mechanism for it

### ISSUE THREAD

**Issue by jordan-thoms** [karmi/retire#670]
One thing that has bit us when integrating tire is the lack of automatic escaping - I guess we've been conditioned to expect it from activerecord & friends.

I understand there are good reasons for not doing the escaping automatically, but this should still be clearly documented and information/methods for doing the escaping provided, since any time user input is being put into tire it should be escaped. (Are there injection risks since there is no escaping? In that case the provided examples are insecure, since they don't do any).

**Comment by karmi** [comment]
Hi, what kind of escaping do you mean, can you provide examples, links?

**Comment by Hengjie** [comment]
Characters '[' or ']' will cause Elastic Search to crash. It's in section 2 of this article: http://blog.tutorwith.me/2012/02/implementing-your-own-site-search-in-a-rails-app/

**Comment by karmi** [comment]
@jordan-thoms Please provide examples or close the issue.

@Hengjie That is expected -- the article uses the `string` query with a Lucene query string syntax. This query is generally not good for exposing the search feature to users, a `match` query is better here and the article is factually incorrect. Thanks for pointing the article, will try to post comment there.

**Comment by jordan-thoms** [comment]
@karmi  - Create any elastic search model, run  Model.search "[a}" - and it'll fail, since the argument is not escaped.

```
irb(main):001:0> Document.search "[a}"
[REQUEST FAILED] curl -X GET "http://elastic:password@elasticsearch:8080/documents/document/_search?pretty=true" -d '{"query":{"query_string":{"query":"[a}"}}}'
Tire::Search::SearchRequestFailed: 500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[XlBSTzQISwCs1zmdcm42-A][documents][0]: SearchParseException[[documents][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"[a}\"}}}]]]; nested: QueryParsingException[[documents] Failed to parse query [[a}]]; nested: ParseException[Cannot parse '[a}': Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; }{[XlBSTzQISwCs1zmdcm42-A][documents][1]: SearchParseException[[documents][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"[a}\"}}}]]]; nested: QueryParsingException[[documents] Failed to parse query [[a}]]; nested: ParseException[Cannot parse '[a}': Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; }{[XlBSTzQISwCs1zmdcm42-A][documents][2]: SearchParseException[[documents][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"[a}\"}}}]]]; nested: QueryParsingException[[documents] Failed to parse query [[a}]]; nested: ParseException[Cannot parse '[a}': Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; }{[XlBSTzQISwCs1zmdcm42-A][documents][3]: SearchParseException[[documents][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"[a}\"}}}]]]; nested: QueryParsingException[[documents] Failed to parse query [[a}]]; nested: ParseException[Cannot parse '[a}': Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; }{[XlBSTzQISwCs1zmdcm42-A][documents][4]: SearchParseException[[documents][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"[a}\"}}}]]]; nested: QueryParsingException[[documents] Failed to parse query [[a}]]; nested: ParseException[Cannot parse '[a}': Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 3.\nWas expecting one of:\n    \"TO\" ...\n    <RANGEIN_QUOTED> ...\n    <RANGEIN_GOOP> ...\n    ]; }]","status":500}
```

Clearly these methods are not designed for passing user input in since they don't do escaping, but in that case the example should be updated to follow the best practice when passing user input ( see https://github.com/karmi/tire/blob/master/examples/rails-application-template.rb#L204 ) - I don't know what that best practice is though, hence why I created this issue.

This is a gotcha with the search methods, and I do think it merits being included in the documentation.

Thanks for your work on tire BTW - we've found it very useful.

**Comment by karmi** [comment]
@jordan-thoms That is expected -- the `query_string` query exposes the full Lucene syntax, so it's very good for "playing" with search, but not for a generic "here's a search box" functionality. Thank for the hint regarding docs/example Rails template -- I'll update it.

**Comment by Hengjie** [comment]
I've tried using `match` and even then that fails when I use [ or any other special characters.

**Comment by karmi** [comment]
@Hengjie The problem must be elsewhere:

``` ruby
require 'tire'

s = Tire.search do
  query do
    match :_all, '[foo] bar'
  end
end

p s.results
```

@jordan-thoms Closing the issue, OK?
