### ISSUE TITLE
Intermittent issues when Elasticsearch response not valid or not found.

### ISSUE THREAD

**Issue by nickcoyne** [karmi/retire#671]
We are using Tire on Heroku with the Bonsai Elasticsearch service. Periodically there are issues with connectivity, which Tire does not seem to rescue/retry from adequately. 

Eg.

Curl::Err::GotNothingError: Curl::Err::GotNothingError

> vendor/bundle/ruby/1.9.1/gems/curb-0.8.3/lib/curl/easy.rb:60 • perform
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/http/clients/curb.rb:33 • http_post
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/http/clients/curb.rb:33 • post
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/index.rb:87 • store

**Comment by nickcoyne** [comment]
Another example

Curl::Err::ConnectionFailedError: Curl::Err::ConnectionFailedError

> vendor/bundle/ruby/1.9.1/gems/curb-0.8.3/lib/curl/easy.rb:60 • perform
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/http/clients/curb.rb:33 • http_post
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/http/clients/curb.rb:33 • post
> vendor/bundle/ruby/1.9.1/gems/tire-0.5.4/lib/tire/index.rb:87 • store

**Comment by karmi** [comment]
Hi, I'm wondering what would be the best approach here on the Tire side... I think leaving errors like these bubble up and crash the application code is the only sensible option; you can always rescue them there.

I suspect this is about automatic indexing in a model via including `Callback`, right? As noted across the issues, that's only a "good enough" convenience mechanism to get started or for simple cases -- anything complex, write-heavy, etc. will probably need you to handle the indexing workflow yourself... What do you think?

//cc @nz

**Comment by nickcoyne** [comment]
Yep, this is happening in the background when a new record is created. I'm tempted to try something like this approach:

``` ruby
def self.post(url, data)
  tries = 2
  begin
    @client.url = url
    @client.post_body = data
    @client.http_post
    Response.new @client.body_str, @client.response_code
  rescue Curl::Err::GotNothingError => e
    tries -= 1
    sleep 0.1
    retry if tries > 0
  end
end
```

I'm not sure if the connectivity is lost for just a microsecond (which this might solve), or if its a few seconds, in which case things will still fail. Perhaps I should just try this and see if alleviates the issue.

There is no way I can rescue in my model code if I'm using the included Callbacks, is there?

**Comment by nickcoyne** [comment]
Ignore my last question, I see it is quite straightforward to not include Callbacks.

**Comment by karmi** [comment]
That would be a good approach, trying it couple of times. Yes, the solution would be to _not_ `include` the Callbacks module, and intercept save/commit/destroy/etc ActiveRecord hooks. It would make sense to use the “retry couple of times” logic in there.

**Comment by nickcoyne** [comment]
Thanks, I think I will take that approach.

**Comment by karmi** [comment]
Cool, closing the issue then?

**Comment by nickcoyne** [comment]
Sorry, yes.
