### ISSUE TITLE
Requests timing out

### ISSUE THREAD

**Issue by abitdodgy** [karmi/retire#675]
I'm not exactly sure what happened and I have no idea how to debug this, but after running deleting an index, Tire has stopped working. I keep getting "request timed out" after running `rake db:populate` or issuing any requests to the app. The app was working fine until I deleted the `Discussions` and tried to reset my seed data by running `rake db:populate`.  I also ran bundle update.

To get around this, I reverted to 0.5.1, and even reinstalled elasticsearch, but nothing has worked.

Any ideas? (I'm on OSX Mountain Lion, Using Tire 0.5.5, and Rails 3.2.6, the latest elasticsearch from home bew). I updated Java a few days ago, but nothing was out of the ordinary until today.

This is a sample request output through the browser (notice line 32):

``````
RestClient::RequestTimeout at /discussions
==========================================
> Request Timeout
app/controllers/discussions_controller.rb, line 32
``` ruby
   27     end
   28   
   29     def create
   30       @discussion = current_user.discussions.build(params[:discussion])
   31       respond_to do |format|
>  32         if @discussion.save
``````

Here's the back trace:

````- (gem) activerecord-3.2.6/lib/active_record/query_cache.rb:64:in`call'
- (gem) activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
- (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `_run__1334503416742692961__call__4179017657952087275__callbacks'
- (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
- (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
- (gem) activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/reloader.rb:65:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
- (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:84:in `protected_app_call'
- (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:79:in `better_errors_call'
- (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:56:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
- (gem) railties-3.2.6/lib/rails/rack/logger.rb:26:in `call_app'
- (gem) railties-3.2.6/lib/rails/rack/logger.rb:16:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/request_id.rb:22:in `call'
- (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
- (gem) rack-1.4.5/lib/rack/runtime.rb:17:in `call'
- (gem) activesupport-3.2.6/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
- (gem) rack-1.4.5/lib/rack/lock.rb:15:in `call'
- (gem) actionpack-3.2.6/lib/action_dispatch/middleware/static.rb:62:in `call'
- (gem) railties-3.2.6/lib/rails/engine.rb:479:in `call'
- (gem) railties-3.2.6/lib/rails/application.rb:220:in `call'
- (gem) railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:147:in `handle'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:99:in `rescue in block (2 levels) in start'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:96:in `block (2 levels) in start'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:86:in `each'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:86:in `block in start'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:66:in `loop'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:66:in `start'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:13:in `run'
- /Users/Mohamad/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/bin/nack_worker:4:in `<main>'

```

As for running the rake tasks, here's the back trace for that:

```

*\* Invoke db:structure:load_if_sql (first_time)
*\* Invoke db:create 
*\* Execute db:structure:load_if_sql
*\* Invoke db:seed (first_time)
*\* Execute db:seed
*\* Invoke db:abort_if_pending_migrations (first_time)
*\* Invoke environment 
*\* Execute db:abort_if_pending_migrations
*\* Execute db:setup
rake aborted!
Request Timeout
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rest-client-1.6.7/lib/restclient/request.rb:184:in `rescue in transmit'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rest-client-1.6.7/lib/restclient/request.rb:140:in`transmit'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in`execute'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.5/lib/tire/http/client.rb:19:in`post'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.5/lib/tire/index.rb:143:in `store'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.5/lib/tire/model/search.rb:148:in`block in update_index'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:403:in `_run__42179389288198320__update_elasticsearch_index__2812542342298808294__callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in`__run_callback'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_update_elasticsearch_index_callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in`run_callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.5/lib/tire/model/search.rb:144:in `update_index'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.5/lib/tire/model/callbacks.rb:21:in`block in included'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:438:in `_run__42179389288198320__save__2812542342298808294__callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in`__run_callback'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in`run_callbacks'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/callbacks.rb:264:in `create_or_update'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/persistence.rb:104:in`save!'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/validations.rb:56:in `save!'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/attribute_methods/dirty.rb:33:in`save!'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in `block in save!'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/transactions.rb:295:in`block in with_transaction_returning_status'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/transactions.rb:208:in`transaction'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.6/lib/active_record/transactions.rb:246:in`save!'
/Users/Mohamad/Documents/Code/reverbee/lib/tasks/sample_data.rake:33:in `block (3 levels) in <top (required)>'
/Users/Mohamad/Documents/Code/reverbee/lib/tasks/sample_data.rake:28:in`times'
/Users/Mohamad/Documents/Code/reverbee/lib/tasks/sample_data.rake:28:in `block (2 levels) in <top (required)>'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:228:in`call'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:223:in`each'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/Users/Mohamad/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:159:in`invoke_with_call_chain'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:143:in`invoke_task'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in`each'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:110:in`run_with_threads'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:73:in`block in run'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:70:in`run'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/bin/rake:23:in`load'
/Users/Mohamad/.rvm/gems/ruby-1.9.3-p327/bin/rake:23:in `<main>'
Tasks: TOP => db:populate

```
```

**Comment by karmi** [comment]
Hi, sorry for not getting to you sooner. There's some problem when connecting to Elasticsearch, notice:

```
/gems/tire-0.5.5/lib/tire/index.rb:143:in `store'
/gems/tire-0.5.5/lib/tire/model/search.rb:148:in `block in update_index'
/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:403:in `_run__42179389288198320__update_elasticsearch_index__2812542342298808294__callbacks'
```

When you include the `Tire::Model::Callbacks` module, Tire tries to update the Elasticsearch index whenever you save the record. In this case, the request fails/timeouts.

So the question is:
- Have you solved the problem in the meantime?
- How is Tire configured, leaving the default `localhost:9200` on?
- If so, what happens when you `curl localhost:9200`?
- If this is some kind of hosted ES, what kind and how you configure it?

**Comment by abitdodgy** [comment]
Hey there, thanks for getting back to me.

I actually just solved this today. To be honest, I'm not 100% sure what solved it, but I essentially deleted everything and started my setup again. After manually creating an index in the terminal, everything worked fine. I had deleted an index manually during that day, which started a cascade of issues. In the end I think it was a combination of missteps and  lack of know-how on my part.

**Comment by karmi** [comment]
Glad it's resolved! I think the problem was either in Elasticsearch not running or not restarting application code, or something like that.

**Comment by 9mm** [comment]
I'm not certain yet but I may be having the same issue.

```
A RestClient::RequestTimeout occurred in resources#create:

 Request Timeout
 rest-client (1.6.7) lib/restclient/request.rb:184:in `rescue in transmit'
```

I forced a re-index to see maybe if that helps.

```
rest-client (1.6.7) lib/restclient/request.rb:184:in `rescue in transmit'
 rest-client (1.6.7) lib/restclient/request.rb:140:in `transmit'
 rest-client (1.6.7) lib/restclient/request.rb:64:in `execute'
 rest-client (1.6.7) lib/restclient/request.rb:33:in `execute'
 rest-client (1.6.7) lib/restclient.rb:72:in `post'
 tire (0.6.1) lib/tire/http/client.rb:19:in `post'
 tire (0.6.1) lib/tire/index.rb:146:in `store'
 tire (0.6.1) lib/tire/model/search.rb:148:in `block in update_index'
 activesupport (3.2.15) lib/active_support/callbacks.rb:403:in `_run__1215428825891427617__update_elasticsearch_index__1803585120871585077__callbacks'
 activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `__run_callback'
 activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_update_elasticsearch_index_callbacks'
 activesupport (3.2.15) lib/active_support/callbacks.rb:81:in `run_callbacks'
 tire (0.6.1) lib/tire/model/search.rb:144:in `update_index'
 tire (0.6.1) lib/tire/model/callbacks.rb:21:in `block in included'
```

If that doesn't work I'll reboot server maybe. It's been running for like 2 years now flawlessly with elasticsearch, so who knows.

**Comment by emerak** [comment]
@9mm did you find a solution?
