### ISSUE TITLE
Tire.search dsl not handling :type option correctly

### ISSUE THREAD

**Issue by marcrohloff** [karmi/retire#676]
Tire.search('articles', :type=>'article').to_curl 
is not extracting :type as an option, compare to
Tire.search('articles', :type=>'article'){}.to_curl

(type is missing from the search_params word list)

**Comment by karmi** [comment]
Hi, I understand the issue, after considering it for a while, I don't think we can do much about it without either breaking compatibility or complicating the codebase too much.

In your example, just add the document type as a part of the index argument:

``` ruby
Tire.search('articles/article').to_curl 

Tire.search('articles/article', {query: {match_all: {}}}).to_curl 
```

**Comment by ghost** [comment]
@karmi I’ve been looking for quite a while on how to do this today, I didn’t know that we could pass something like 'articles/article' to .search(). I think such an example should probably be added to the documentation. I don’t think it’s documented already.
