### ISSUE TITLE
Stub Requests

### ISSUE THREAD

**Issue by weblee** [karmi/retire#677]
OK just added tire to my gem file and included the callbacks in my model now all my tests are broken. I am getting error.

``` ruby
You can stub this request with the following snippet:

stub_request(:head, "http://localhost:9200/listings").
  with(:headers => {'Accept'=>'*/*; q=0.5, application/xml', 'Accept-Encoding'=>'gzip, deflate', 'User-Agent'=>'Ruby'}).
  to_return(:status => 200, :body => "", :headers => {})
```

I have not even written any tests yet for it. Any advice to whats going on?.

I do have "vcr & webmock" gems installed.

**Comment by karmi** [comment]
Yeah, that's expected -- Tire checks for the existence of an index corresponding to model on startup. You have to stub the call or allow this specific call in Webmock.

**Comment by weblee** [comment]
Ok sorry for being thick where would i stub this?

**Comment by karmi** [comment]
The best place would be in your test_helper.rb, where you setup/require Webmock. Or, alternatively, you can [allow localhost](https://github.com/bblimke/webmock#external-requests-can-be-disabled-while-allowing-localhost) and just stub/mock when you need to do it. Note though, that for integration tests, best is to leave everything bubble up and down and work with real responses.

**Comment by weblee** [comment]
Thanks for your help Karmi but im just not getting it. I have tried adding the stub to my spec_helper in various ways and its just not picking up the stub. Do I need to add the stub directly into the spec_helper.rb ?? Im new to testing if you have not noticed!! I hope you can advise a little bit more!

**Comment by karmi** [comment]
You have to stub the request or allow localhost _before_ you load Tire. I can't give you any more specific advice, sadly. Upload the relevant portion of the code somewhere and I can have a look.
