### ISSUE TITLE
Questions about ActiveRecord branch

### ISSUE THREAD

**Issue by aaronchi** [karmi/retire#68]
I noticed that the activerecord branch has the :load option for loading results from the database but master does not. Is this something that is going to be merged or will it stay in a separate branch?

I'm trying to figure out if I can use this functionality or if I should change my index to include all of the fields I want to display in my app.

**Comment by karmi** [comment]
Yes, that's something which will be merged into upcoming 0.2 release. The activerecord integration tests have all the details. See issues tire#11 and tire#12 for background.

**Comment by aaronchi** [comment]
cool... one thing to note. Using the branch I was getting an error calling results if the search doesn't return any items

**Comment by karmi** [comment]
Care to paste a backtrace, please?
