### ISSUE TITLE
Bounding Box not returning results

### ISSUE THREAD

**Issue by weblee** [karmi/retire#680]
Hi,

I cant get elasticsearch to return results for a geo_bounding_box and hope someone can spot the obvious!

Here is a gist with the model, curl and listings json data: https://gist.github.com/weblee/5192868

I know the box cords are good and that all three of the listings should be found within it.

Can you spot anything obvious?

**Comment by weblee** [comment]
I found the issue.

My filter was close but should have been as string not an array ie,

``` ruby
filter :geo_bounding_box, :location => {
          :top_left => "#{params[:geo_bounding_box][:top_left_lat]}, #{params[:geo_bounding_box][:top_left_lon]}",
          :bottom_right => "#{params[:geo_bounding_box][:bottom_right_lat]}, #{params[:geo_bounding_box][:bottom_right_lon]}"
        }

```

**Comment by monfresh** [comment]
Why does it have to be a string? Shouldn't it support an array, like this?

``` ruby
filter :geo_bounding_box, :coordinates => { :top_left => [37.3084,-122.521], :bottom_right => [37.1066,-122.08] }
```

According to @karmi's [comment](https://github.com/karmi/retire/issues/140#issuecomment-2568675), it should, but it doesn't. I had to use strings for it to return results, like this:

``` ruby
filter :geo_bounding_box, :coordinates => { :top_left => "37.7084,-122.521", :bottom_right => "37.1066,-122.08" }
```

If it only supports strings, it would be nice if this were documented. I couldn't find a spec for this either.
