### ISSUE TITLE
Importing very large set of data

### ISSUE THREAD

**Issue by nazarhussain** [karmi/retire#691]
Hi,

I made a transition from `thinking sphinx` to `tire`, in development it was workign really fine. But now as I migrated my origional data into new application which is abour 1.2 million records, its indexiging just drops me out of the game. 

Initially the `rake tire:import` takes about `22 hours` and later when I checked it with `head` plugin, the total number of indexes does not match to total records in database. This creates  inconsistenat and un-expected behavior from application. 

Is there any way to track down those lenghty hours of re-indexing and how should we troubleshoot why indexes count does not match to records count?

**Comment by karmi** [comment]
> why indexes count does not match to records count

Do you mean document count in the index vs. record count in the database? Don't use Head for that, use `curl  localhost:9200/myindex/_refresh && curl localhost:9200/myindex/_count`.

> Initially the rake tire:import takes about 22 hours (...)

It depends on how your model(s) are set up. Recently, we introduced a change which uses `find_in_batches` for ActiveRecord, and is very fast, but doesn't prevent n+1 queries. Turn on ActiveRecord logging and observe the queries being issued to your database. 1.2mio of documents is a small corpus in Elasticsearch's terms.

**Comment by nazarhussain** [comment]
For first one, I tried the curl option and it is showing the same count as head plugin, which is almost 20K less than the records count in database. 

I will try the `find_in_batches` and will let you know.

**Comment by karmi** [comment]
@nazarhussain The important part is "turn on ActiveRecord logging and observe the queries being issued to your database while importing".

**Comment by nazarhussain** [comment]
Really thanks for your input. New feature `find_in_batches` has some performance improvment when every things is active record relation which is going to be used in `to_indexed_json`, 

In my case, I am building that json of some complex business logic. I had enabled the logging and watched the logs deeply, major time is taking by ActiveRecord queries, and that's the reason it is slow. 

Is there any plugin or tool available that I made that index on some super fast computer and then export/import it to my live server? I googled and found `knapsack`, but for me it is not working, can you take a look into it https://github.com/jprante/elasticsearch-knapsack/issues/3 That will be great help for me.

**Comment by karmi** [comment]
Sorry for keeping it hanging here. Basically, you should be able to import your data into Elasticsearch, and then just `scp` the data into a (stopped) production cluster -- provided versions match, etc etc.

But really, I wonder what's the bottleneck here, even with n+1 queries, 1.2mio documents should be imported in a reasonable amount of time. If n+1 queries (or other database bottleneck like this) would be the problem, the solution would be to write the indexing code yourself -- it's really only a matter of querying the database and feeding the data into ES via `Tire::Index#bulk`.

**Comment by nazarhussain** [comment]
@karmi Yes you are right. That's what I finally think to focus on. I am closing this issue, thanks for your great input. And thanks for that great tip of `scp` the indexed data. That will help us a lot.
