### ISSUE TITLE
Is it possible to "save partial filters / script_fields as Ruby blocks"

### ISSUE THREAD

**Issue by mattiassvedhem** [karmi/retire#692]
As search methods gets long (or just for reuse between facet_filters etc) it would be nice to extract filters, script_fields etc, as one can do with sort, boolean, etc where you actually call something on the passed scope.

i.e passing the `search` scope to the lambda.
Something like this:

``` Ruby
Tire.search do |s|
  s &some_filter
end

def some_filter
  ->(s) do
    s.filter :or, {
      term: { some: 'thing' }
    },
    {
      term: { some: 'thing' }
    }
  end
end
```

**Comment by karmi** [comment]
It's an interesting idea, but I wonder how to support that interface in the code...

I mean, you can do this:

``` ruby
require 'tire'

Tire.index('articles') do
  store id: 1, title: 'One', tags: ['ruby','python']
  store id: 2, title: 'Two', tags: ['javascript']
  refresh
end

f = lambda do |s|
  s.filter :terms, tags: ['ruby']
end

search = Tire.search 'articles' do |s|
  s.query { all }
  f.call(s)
end

puts search.to_curl
```

To support the API you outline, we would need to add a different method, or teach the `filter` method to take blocks...

On the other hand, what I have been frequently doing when extracting the filter definitions is something like this:

``` ruby
require 'tire'

Tire.index('articles') do
  store id: 1, title: 'One', tags: ['ruby','python']
  store id: 2, title: 'Two', tags: ['javascript']
  refresh
end

f = [ :terms, tags: ['ruby'] ]

search = Tire.search 'articles' do |s|
  s.query { all }
  s.filter *f
end

puts search.to_curl
```

Do you think this would be enough?

**Comment by mattiassvedhem** [comment]
Thanks for outlining the different options Karmi!

I think they are all viable in different situations. In most cases, I ended up creating a separate class, which takes the `Search` object, and is then responsible for calling the appropriate methods on it.

Something like this:

``` Ruby
require 'tire'

class Sort
  def initialize(search, params)
    @search = search
    @point  = params[:point]
  end

  def by_distance
    @search.sort.by :_geo_distance, {
     :point => @point,
      unit: 'km',
      order: 'asc'
    } 
  end
end

Tire.index('articles') do
  store id: 1, title: 'One', tags: ['ruby','python'], point: [3.53535, 5.535353]
  store id: 2, title: 'Two', tags: ['javascript'], point: [3.53535, 5.535353]
  refresh
end

params = { point: [3.53535, 5.535353] }

search = Tire.search 'articles' do |s|
  Sort.new(s, params).by_distance
end

puts search.to_curl
```

So, yeah. Probably better not to change it.

**Comment by karmi** [comment]
@mattiassvedhem I'm leaning towards closing this ticket for now, and keeping it in mind for future, what do you think?

**Comment by mattiassvedhem** [comment]
Yep, close it :)
