### ISSUE TITLE
Any plans  to support persistent connections in Tire?

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#696]
Elasticsearch literature recommends using persistent connections and as far as i know, Tire doesn't support this, I was wondering if it was on your radar.

**Comment by karmi** [comment]
The [_Curb_](https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb) client does support keep-alive connections.

**Comment by ike-bloomfire** [comment]
My apologies if I sound like a newb but I was unclear how to use this to do persistent connections? 
would I have to manually fire head requests at the server in the background or something?

Also am I correct that Tire does _not_ use persistent connections?

**Comment by karmi** [comment]
I'm not sure what you're referring to as "persistent", in the [HTTP context](http://en.wikipedia.org/wiki/HTTP_persistent_connection), Curb just does it:

``` ruby
Tire.configure do
  client Tire::HTTP::Client::Curb
end
```

**Comment by ike-bloomfire** [comment]
Ahh right ... just wanted to know if Tire essentially re-used connections as opposed to opening up a new connection on each Elasticsearch request. Looks like keepalives are another name for that, I didn't know that is why I was confused initially.

 Looks like it does,https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb#L11, sorry for bothering you about it.
