### ISSUE TITLE
Return default results when no params are supplied to tire?

### ISSUE THREAD

**Issue by rubytastic** [karmi/retire#704]
Is there a way / What would be the correct way to return a default recordset ( not all ) when no params are available?
Should you handle this in controller or is there  a way for setting this in Model?

```
    @profiles = Profile.search(params)
```

Returns profiles for params or _ALL_ I want to NOT return _ALL_ but something like Profile.where(:age => 20 ) for example. Could not find anything in the documentation regarding default values, anyone could share some insight on this please? thanks in advanche!

**Comment by mattiassvedhem** [comment]
You can do something like this:

``` Ruby
class Profile
  def self.search(params)
    defaults = { some: 'default_param' }
    options = defaults.merge(params)

    tire.search do
      # use the options
    end
  end
end
```

**Comment by rubytastic** [comment]
Thanks that totally works, just merging in the params - smart - i was looking for tire to handle a default set of options but this works perfect!
