### ISSUE TITLE
finding deleted records

### ISSUE THREAD

**Issue by lasssim** [karmi/retire#705]
Hi,

we need to be able to find records, that are deleted in the database. deleted records are marked as deleted by setting the deleted_at attribute to Time.now. which is handled by the paranoid gem.

update_index of tire detects the model instance as deleted (through the deleted? predicate) and removes the record from the index. 
my first idea to fix this was adding an around callback for update_elasticsearch_index but the around callback is not in den list of callbacks.
permanently overriding the deleted? method is not an option, because other parts of my app rely on it.

so, my questions are:
- are there any issues with around callbacks, or why are they omitted?
- is there a nicer way i could achieve holding deleted records in the db?

this is untested code, but i think you get the idea how i could implement the behavior i need.

``` ruby
define_model_callbacks(:update_elasticsearch_index)
around_update_elasticsearch_index do
  tmp = @destroyed
  @destroyed = false
  yield
  @destroyed = tmp
end
```

br, simon

ps.: this gem is awesome! thx!

**Comment by barkerja** [comment]
http://www.elasticsearch.org/guide/reference/query-dsl/missing-filter/

Perhaps you may want to use a missing filter on your `deleted_at` column, instead of actually removing that record from the index. Using this would only return records with an empty `deleted_at` value when needed.

**Comment by lasssim** [comment]
hi,

that is actually my point. i don't want to delete the records from the index. i want that they stay in the index. 

the update_index method from tire removes destroyed records though.

``` ruby
       def update_index
          instance.run_callbacks :update_elasticsearch_index do
            if instance.destroyed?
              index.remove instance
            else
              response = index.store( instance, {:percolate => percolator} )
              instance.tire.matches = response['matches'] if instance.tire.respond_to?(:matches=)
              self
            end
          end
        end
```

br, simon

**Comment by brupm** [comment]
Don't include the callbacks module and handle it with after_save and after_destroy callbacks.

**Comment by karmi** [comment]
> we need to be able to find records, that are deleted in the database. deleted records are marked as deleted by
> setting the deleted_at attribute to Time.now. which is handled by the paranoid gem.

Hi @lister, yes, as suggested, the best approach is to don't include the callbacks module, and handle it manually -- unfortunately you can't use the `update_index` method, you need to work with the `MyModel.index.store @myinstance` directly... I'm not familiar with the current behaviour of "paranoid-like" gems (https://github.com/radar/paranoia?) -- do they set the `#destroyed?` property to true?

**Comment by lasssim** [comment]
hi,

thanks for your replies.
my current solution is to implement the update_index method in my model like this:

``` ruby
      def update_index
        instance = self
        instance.run_callbacks :update_elasticsearch_index do
          response = index.store( instance, {:percolate => percolator} )
          instance.tire.matches = response['matches'] if instance.tire.respond_to?(:matches=)
          self
        end
      end
```

which is working fine, but this is actually nothing want to do. i would miss changes on an update of the gem if the update_index method was changed.

the paranoid gem implements destroyed? like this:

``` ruby
  def destroyed?
    !self.deleted_at.nil?
  end
  alias :deleted? :destroyed?
```

it also implements a method called paranoid? which could be used to find out if the model is paranoid. but i'm not sure if other paranoid-like gems implement this mehtod...

br, simon

**Comment by karmi** [comment]
Hi, you have two options here:
1. Add the `deleted:true|false` property into the document JSON, and just filter everything deleted in Elasticsearch (if it would make sense to do it like this)
2. Manually index the models -- I've added some info into the README about this.

Does it sound OK?
