### ISSUE TITLE
Using 'tire.settings' to define custom settings for an index fails

### ISSUE THREAD

**Issue by xxx** [karmi/retire#706]
Hello,

Just ran into an issue where using `tire.settings` to define custom settings for a model doesn't actually save the custom settings, though any `mapping` defined in a block passed is still mapped as expected. If you just use `settings` instead, the custom settings are used as they should be.

**Comment by xxx** [comment]
eh, this isn't quite the issue.

I guess if you change the settings for an index, you have to delete the current index, quit the console/irb session you're in, and restart it, or it will always use the default settings. I still think there's a bug here somewhere, but the issue described above isn't it.

**Comment by karmi** [comment]
I think the issue here is that Tire tries to create the index for the model with all the specified settings/mappings when you load the model (in your app, console, etc), but skips it when the index already exists.

You have to `MyModel.tire.index.delete && MyModel.tire.create_elasticsearch_index`.
