### ISSUE TITLE
Rails environment not loaded properly on rake tasks

### ISSUE THREAD

**Issue by mikebaldry** [karmi/retire#708]
I saw the new version is meant to auto load the environment, ala:

```
 Rails detected, loading environment...

But this did not load the initializers, and my tire.rb was not run, so I was working against the local index all the time, when I was trying to change production... 

Adding environment task back in before tire:index/import fixed the issue.
```

**Comment by karmi** [comment]
Argh, that's bad. Thanks for this report, will remove auto-invoking the `environment` task, never liked it anyway...

**Comment by jwaldrip** [comment]
@karmi  I may have a better way

**Comment by karmi** [comment]
@jwaldrip I really think we're doing "too much" here. It's entirely in users hands how she wants to load the Rails environment? Running `rake environment tire:import:model CLASS='MyModel'` is _perfectly fine_, and will prevent any errors like this.

**Comment by mikebaldry** [comment]
How bout a tire-rails gem?

**Comment by karmi** [comment]
@brightbits That is definitely in the works for the future... .) But we have to keep the current gem clean & working as well.

**Comment by jwaldrip** [comment]
I agree with that. Save auto environment for tire rails. Have you started on that @karmi? If not i can start laying the ground work.

**Comment by karmi** [comment]
@jwaldrip It doesn't have much sense to extract the Rails related stuff from the Tire codebase -- it is quite coupled to ActiveModel (in `Item`) etc.
