### ISSUE TITLE
Specify wrapper for specific model?

### ISSUE THREAD

**Issue by mattiassvedhem** [karmi/retire#714]
While it's great to be able to switch out the wrapper completely, I've run into a situation where I need to augment `Item` for a specific ElasticSearch index (i.e a specific model) at a low level, so [Decorating with draper](https://github.com/karmi/tire/wiki/Using-Tire-with-Draper) isn't a good solution.

Could we add something like this?

```
class Article < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  wrapper ArticleItem
end
```

```
class ArticleItem < Tire::Results::Item
  def my_method

  end
end
```

Since `Tire::Results::Collection` knows the `_type` we could infer the correct class and access the state there, right? Or maybe put the wrapper setting somewhere else?

**Comment by mattiassvedhem** [comment]
Turns out `Tire::Search::Search` already takes wrapper as an option! 
Would be nice to be able to pass the options directly to `Tire.search` though? Or is this the preferred way?

```
search = Tire.search do
  # stuff
end

Tire::Search::Search.new(
  'menus/menu',
  payload: search,
  wrapper: ArticleItem
).results
```

**Comment by karmi** [comment]
@mattiassvedhem The `wrapper` option should be passable to `Tire.search` just fine:

``` ruby
require 'tire'
require 'virtus'

class Article
  include Virtus

  attribute :title,   String
  attribute :content, String
end

s = Tire.search 'articles', wrapper: Article do
  query { all }
end

puts "Title: %s" % [ s.results.first.title ]
```

**Comment by mattiassvedhem** [comment]
Thanks Karmi, you're right, wasn't clear in my example, when passing a block it does work. 
However it does not work when just passing the `indices` and the `payload` parameters.

I suspect the problem is [here](https://github.com/karmi/tire/blob/master/lib/tire/dsl.rb#L26), the naming here seems a little bit convoluted, since if as block is given, the argument `payload` is really a hash with options, not exclusively the `payload`, right? But if no block is passed the code expects it to only be the `payload`, and no further options.

**Comment by mattiassvedhem** [comment]
i.e this, `Tire.search('articles', payload: search.to_hash, wrapper: Article)` would result in this hash being passed to `Tire::Search::Search`

```
{ payload: { payload: # the actual payload, wrapper: Article } }
```

**Comment by karmi** [comment]
Closing, migrating the issue to karmi/tire#716.
