### ISSUE TITLE
Support for Admin indices stats

### ISSUE THREAD

**Issue by devilankur18** [karmi/retire#717]
Please add support to get stats from the index http://www.elasticsearch.org/guide/reference/api/admin-indices-stats/

**Comment by karmi** [comment]
Hi, index `_stats` and `_status` would be nice to add, but there's an ongoing effort focused on building a more robust Ruby library, which makes it less reasonable to add features to the current library.

For the moment, please use something (eyehurting) like this:

``` ruby
stats = MultiJson.load( Configuration.client.get("#{Configuration.url}/i/_stats").body )
```
