### ISSUE TITLE
Possible pagination issue when importing with mongoid >=2.1.2

### ISSUE THREAD

**Issue by wulffeld** [karmi/retire#72]
Take a look at https://github.com/mongoid/mongoid/issues/1131.

Doing the importing like described here: https://github.com/karmi/tire/issues/48#issuecomment-1499519 started to result in these errors:

```
[ERROR] 400 Bad Request:{"error":"Failed to derive xcontent from []"}, retrying (1)...
[ERROR] 400 Bad Request:{"error":"Failed to derive xcontent from []"}, retrying (2)...
[ERROR] 400 Bad Request:{"error":"Failed to derive xcontent from []"}, retrying (3)...
[ERROR] 400 Bad Request:{"error":"Failed to derive xcontent from []"}, retrying (4)...
[ERROR] 400 Bad Request:{"error":"Failed to derive xcontent from []"}, retrying (5)...
```

I worked around it by adding ".all.to_a" to my paginate call as seen here: https://github.com/mongoid/mongoid/issues/1131#issuecomment-1808706

Bug?

**Comment by karmi** [comment]
Could be a bug -- what kind of object does `Article.page(options[:page]).per(options[:per_page]).all` return? (_Tire_ should be content with anything iterable with `map`, see http://rubydoc.info/github/karmi/tire/master/Tire/Index:bulk_store)

**Comment by wulffeld** [comment]
```
>> Article.page(1).per(10).class
Mongoid::Criteria < Object
>> Article.page(1).per(10).all.class
Mongoid::Criteria < Object
>> Article.page(1).per(10).all
#<Mongoid::Criteria
  selector: {},
  options:  {:limit=>10, :skip=>0},
  class:    Article,
  embedded: false>
```

Note, however, that is the same pre-mongoid 2.1.2.

Also using #map works fine in the console and only returns 10 results.

Here tire is calling #size however: https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L122 - that's what no longer works as before. I.e. it will return the same as Article.count instead of the number of documents found and hence the loop blows up because it's always >0 even though the documents is empty when trying to to do #map here: https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L82.

**Comment by karmi** [comment]
Ah, indeed, that is probably a bug. What happens when you change that to `and ! documents.empty?`? Or is there any way to check if the next iteration returns empty result (as is the case with `will_paginate`)?

**Comment by wulffeld** [comment]
It's the same deal. Only #to_a makes it behave.

**Comment by karmi** [comment]
OK, at least you have found some workaround. I'll try to have a look into that, eventually. It's a shame ActiveModel does not offer some chunked find such as `ActiveRecord#find_in_batches`...

**Comment by karmi** [comment]
Hi, this came back to bite Mongoid users. Should be fixed in karmi/tire@5b79c7 and karmi/tire@f491d4. In the end, the `to_a` conversion was neccessary. Could you verify that master works with new Mongoid and you app?

**Comment by karmi** [comment]
Hi @wulffeld, any news on this, please? Could you verify master so we can close this?

**Comment by wulffeld** [comment]
Sorry, been _completely_ swamped the past couple of weeks. 3.2 seems to work just fine.

**Comment by karmi** [comment]
Great news!, many thanks for trying it out!
