### ISSUE TITLE
Sporadic failures on tests

### ISSUE THREAD

**Issue by pzac** [karmi/retire#721]
I get intermittent failures on BoostingQueriesIntegrationTest and ConstantScoreQueriesIntegrationTest (current master branch, elasticsearch 0.20.6). If I run the tests individually they're all green. Any clue?

**Comment by radixhound** [comment]
Some more detail would probably improve your chances of a response. Why not include the actual errors and stack traces?

**Comment by karmi** [comment]
@paozac I've been too busy for the last couple of days, sorry!, will get back to you. These tests indeed fail from time to time, will investigate it a bit deeper.

**Comment by pzac** [comment]
The stack trace unfortunately isn't very helpful, it looks like ES is not returning the expected results. I wonder if it could be due to timing issues. Adding a `refresh` request after the record insertion could help maybe?

```
Tire::ConstantScoreQueriesIntegrationTest
     FAIL (2:00:15.906) test: Constant score queries in the featured results scenario should return featured results first.
          <"Kitchen tool tool tool"> expected but was
          <"Garage tool">.
        @ test/integration/constant_score_queries_test.rb:60:in `block (3 levels) in <class:ConstantScoreQueriesIntegrationTest>'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/shoulda-context-1.1.1/lib/shoulda/context/context.rb:400:in `call'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/shoulda-context-1.1.1/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/mocha-0.13.3/lib/mocha/integration/mini_test/version_2112_to_320.rb:40:in `run'
```

A new failure here:

```
     FAIL (5:00:00.146) test: Percolator when percolating a document should return an empty array when no query matches.
          <[]> expected but was
          <nil>.
        @ test/integration/percolator_test.rb:61:in `block (3 levels) in <class:PercolatorIntegrationTest>'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/shoulda-context-1.1.1/lib/shoulda/context/context.rb:400:in `call'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/shoulda-context-1.1.1/lib/shoulda/context/context.rb:400:in `block in create_test_from_should_hash'
          /Users/paozac/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/mocha-0.13.3/lib/mocha/integration/mini_test/version_2112_to_320.rb:40:in `run'
```

I've ran the tests twice in a row and got the errors only the first time.

**Comment by karmi** [comment]
@paozac The percolator tests indeed fail intermittently for a long time, and I haven't yet found a solution apart from wiping the whole `_percolator` index. That might be an option on Travis, but not on the development machine.

I'll look into why the "kitchen" results are not demoted consistently...

**Comment by karmi** [comment]
Found the culprit -- the default setting of 5 shards per index confuses the scorer. The solution would be to have an index with one shard, or -- preferably -- to use the [`dfs_query_then_fetch`](http://www.elasticsearch.org/guide/reference/api/search/search-type/) search type.

Tested the changes with following script:

``` bash
rm -f results.txt
time for i in {1..15}
  do
    echo "-------------------------------------------------------------------------------"
    echo "TEST $i"
    echo "-------------------------------------------------------------------------------"
    ruby -I lib:test test/integration/constant_score_queries_test.rb
  if [ $? == 0 ]; then echo "$i: OK" >> results.txt; else echo "$i: FAIL">> results.txt; fi
done

echo; echo; echo "==============================================================================="
cat results.txt
rm -f results.txt
```

The tests consistently succeed.

**Comment by pzac** [comment]
Great! Cheers
