### ISSUE TITLE
Multi-Field Value Mapping

### ISSUE THREAD

**Issue by barkerja** [karmi/retire#727]
I'm not sure if I'm wording or describing this properly, so forgive me if I am (I'm fairly new to Elasticsearch .. migrating over from Sphinx).

So what I have is an index that has multi_field for one particular attribute. I have three types for this mapping:

```
indexes :value, type: 'multi_field', fields: {
    value:    { type: 'string', index: :analyzed },
    integer:  { type: 'integer' },
    exact:    { type: 'string', index: :not_analyzed }
}
```

My reasoning is: one for exact matching, another for 'fuzzy' and another (integer) that lets me do number comparisons (greater than, etc.)

All is fine until I hit the integer type, since this attribute isn't all integers, I need to be able to convert the value for this mapping to an integer. Still following?

Perhaps I am thinking about this all wrong, but I was quite positive I could handle this all using a multi_field.

In my `to_indexed_json` hash that I build, can I somehow map my `value` attribute multiple values to its correct mappings? If that makes sense ..

**Comment by karmi** [comment]
Hi, the intuition to use `multi_field` is correct, but there are other ways around this. (The right approach obviously depends on what exactly is the data/property in question.)

In the first approach, you can use `multi_field` like you do, with the `ignore_malformed` flag. Elasticsearch will then extract the numeric value of the field; see example: https://gist.github.com/clintongormley/5575590.

In the second approach, you can "split" and define the property in your Ruby code, using the `:as` option, using extra methods, etc. Example:

``` ruby
mapping do
  indexes :as_string, type: 'string',  as: 'title.to_s'
  indexes :as_number, type: 'numeric', as: proc { title.to_i }
end
```

The second approach could be attractive when you'd need a more sophisticated control how the property is converted to each type; note, that Elasticsearch is much smarter in converting the string then a simple `to_i`.

(Also note, that you can run range queries on string fields as well, but of course "numerical strings" would be sorted lexicographically, not as numbers.)

**Comment by barkerja** [comment]
Thanks @karmi. It looks like `ignore_malformed` is exactly what I was looking for. Cheers.
