### ISSUE TITLE
Multiple projects on the same elastic (namespace)

### ISSUE THREAD

**Issue by fabien7337** [karmi/retire#728]
Hi,

I have 3 projects and each one use ElasticSearch with Tire. Right now I run 3 instances on 3 separates servers but I would like share ressources between projects and so create indexes like "{PROJECT_NAME}_{ENVIRONMENT}_{INDEX}" on the top of activerecord...

Is that possible? Or is that a request for a new features?

Thanks

**Comment by karmi** [comment]
@zywx Separating indices for models like this is possible, just set the `index_name` from Ruby, see https://github.com/karmi/tire/blob/master/test/models/active_model_article_with_custom_index_name.rb#L6?

**Comment by fabien7337** [comment]
Seems good thanks !
