### ISSUE TITLE
Exception handling with faraday is broken

### ISSUE THREAD

**Issue by threez** [karmi/retire#729]
Currently the faraday wrapper dosn't rewrap the faraday exceptions into rubies exceptions. 

See here: https://github.com/karmi/tire/blob/master/lib/tire/http/clients/faraday.rb#L62

The problem is, that index creation just resques the `Errno::ECONNREFUSED` exception. But Faradayraises a `Faraday::Error::ConnectionFailed`exception.

See here: https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L115

So the driver must rescue such exceptions, in the request method like this:

``` ruby
def request(method, url, data = nil)
   # ...
rescue Faraday::Error::TimeoutError => ex
  raise Errno::ETIMEDOUT, ex.message
rescue Faraday::Error::ConnectionFailed => ex
  raise Errno::ECONNREFUSED, ex.message
# ... more exception handling
end
```

**Comment by karmi** [comment]
Hi, I've added a `__host_unreachable_exceptions` method to all HTTP clients, and the `MyModel#create_elasticsearch_index` method now rescues these. Could you verify it for your stack with Faraday?

**Comment by threez** [comment]
sure i when will be the next release this things are in?

**Comment by karmi** [comment]
Soon, but it should be trivial to check against Git master with the `:git => ...` support in Bundler...

**Comment by threez** [comment]
I can tell you in the next 24h if it is working. Thx for taking care of the issue...

**Comment by karmi** [comment]
Great, thanks!

**Comment by threez** [comment]
Nice, `Faraday::Error::TimeoutError` and `Faraday::Error::ConnectionFailed` are handled correctly.
