### ISSUE TITLE
Automatic index creation on Indexing#mapping undesired

### ISSUE THREAD

**Issue by threez** [karmi/retire#730]
Currently the index creation happens while the `#mapping` method (https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L61) is called. This means if the class is loaded the mapping will cause to create an index. The problem is, that some frameworks preload there classes (like rails 4). If you preload your classes the mapping will try to create the index at boot time. However, if you get an timeout/connection error while tire tries to create the index, the raised exception will interrupt the boot and the application will fail to start. This should be fixed, so that the index is only lazyly created (maybe as a config option) or nor automatically created at all.

**Comment by karmi** [comment]
Yes, but the error should be properly rescued, see https://github.com/karmi/tire/blob/master/lib/tire/model/indexing.rb#L115

Can you share the specific error you get? I think we need to broaden the list of errors here.

**Comment by threez** [comment]
The problem is, that the server is not reachable. So if you start your app and your elastic search cluster is not up and running yet you will face the problem. I think it max be the default to create the indexes on startup but should be  possible to disable it.

**Comment by threez** [comment]
With the current HEAD i got:

```
Skipping index creation, cannot connect to Elasticsearch
(The original exception was: #<Faraday::Error::ConnectionFailed>)
```

**Comment by karmi** [comment]
Thanks, so the error is properly rescued by the changes in 3dc8cb70ec84547538cdb7a8ea8a7f68b47f3609 ?

**Comment by karmi** [comment]
Closing this in favor of #748, if that's OK.
