### ISSUE TITLE
Page load takes more time when tire gem is included (development mode)

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#735]
Please note: **Issue related to development mode**

Implemented elasticsearch in my app using tire (v0.4.3). Included tire in multiple models. Since then, the app page load takes more time.

I have tried:

Removed all the code related to tire in the app. Removed the gem inclusion in gemfile. The app was faster.

Removed all the code related to tire in the app. The tire gem inclusion in the gem file was not removed. The app was slower :( .

Just the inclusion of gem in the gem file made the app to load slower (I meant page loads)

The app already has rails-dev-boost installed.

Not sure why this is happening. Let me know if you need any other details.

**Comment by karmi** [comment]
The heaviest Tire dependency is ActiveSupport, which is already loaded by Rails. You may want to use the [`require-prof`](https://github.com/gdb/require-prof) gem to identify the gems which slow down the app and post more info.
