### ISSUE TITLE
update an index in sliding window index

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#736]
I'm trying to implement the sliding window based index for my multi tenant app.
Say an index for every 10 accounts. In case if I want to re index a particular account data in this combined index, how can I do that?

eg:

Index data for accounts 1-10 in an index "tire_index". Now if I want to re index the entire data for account 2 in this index, how can I do that?

**Comment by vamsi-krishna-E0029** [comment]
My bad...Can import the account data specifying the index name as "tire_index".

**Comment by karmi** [comment]
You can reindex a portion of the index with the `Tire#index#reindex` method, see https://github.com/karmi/tire/blob/master/test/integration/reindex_test.rb#L35-L50

**Comment by vamsi-krishna-E0029** [comment]
I have a field with account number indexed in each document.
Using delete by query delete all the documents with account number (term filter). Then import documents from the account to the same index ("tire_index").

Would that work?

Will the `Tire#index#reindex` method work for the same index? (i.e., reindexing into same index)

**Comment by karmi** [comment]
No, Tire#index#reindex will simply extract a portion of the index by scanning, and putting the data into another index.

**Comment by vamsi-krishna-E0029** [comment]
Then the data will be available only in the new index. The old index doesn't contain the data which is transferred to new one.

Correct me if I'm wrong.

**Comment by vamsi-krishna-E0029** [comment]
Using delete by query delete all the documents with account number (term filter). Then import documents from the account to the same index ("tire_index").

Would the above solution work for my issue?
