### ISSUE TITLE
Problems with indexing

### ISSUE THREAD

**Issue by rizwanreza** [karmi/retire#737]
I am having a weird problem. It seems like indexing using the following task is not indexing all records from the table.

```
rake environment tire:import CLASS=Announcement FORCE=true
```

Every time I index, it gives me a different count, and from my tests, it's also indexing a different set of records each time:

![screen shot 2013-05-23 at 6 13 38 pm](https://f.cloud.github.com/assets/16111/557842/70028d54-c3fe-11e2-86a1-02023c29d5f0.png)

Which is much less than this one:

```
[1] monaqasat »  Announcement.unscoped.count
Creating scope :default_scope. Overwriting existing method Announcement.default_scope.
(29.4ms)  SELECT COUNT(*) FROM "announcements"
=> 32105
[2] monaqasat »  Announcement.count
(35.3ms)  SELECT COUNT(*) FROM "announcements" WHERE "announcements"."active" = 't'
=> 32105
```

Any ideas? 

Thanks!

**Comment by karmi** [comment]
@rizwanreza Hmm, previously importing from ActiveRecord relied on pagination, and depending on the scopes in your application, it could mix up order or something. Can you try it with a recent version? It definitely should import all documents -- can you share your model code, or relevant parts of it?

**Comment by karmi** [comment]
@rizwanreza Hi, any new info here?

**Comment by tmlee** [comment]
@rizwanreza  Have you tried doing `Announcement.index.delete` to purge the index and `Announcement.import` to reindex ?

**Comment by karmi** [comment]
Closing as stale, please reopen or ping back when you need help.
