### ISSUE TITLE
each_document: undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by rb2k** [karmi/retire#738]
Not quite sure how this happened, but thought I'd report it:

```
block in <main>': undefined method `join' for nil:NilClass (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.8/lib/tire/search/scan.rb:75:in `block in each_document'
    from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.8/lib/tire/results/collection.rb:35:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.8/lib/tire/results/collection.rb:35:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p327/gems/tire-0.5.8/lib/tire/search/scan.rb:75:in `each_document'
```

Nothing fancy really, happened at around document 122100:

```
s = Tire.scan 'my_index'
s.each_document do |result|
...
end
```

**Comment by karmi** [comment]
@rb2k Hmm, this seems to be coming from the code which yields to a passed in block. Do you call the join in your block? Can you share it?

**Comment by rb2k** [comment]
Oh, I think it was a bit too late/early when I posted that :)

The stacktrace was a bit misleading and I think, within my code, I did actually call .join("|") on an array that probably ended up being nil in some freak accident.

Sorry :)
