### ISSUE TITLE
bulk response is sometimes nil

### ISSUE THREAD

**Issue by cjbottaro** [karmi/retire#740]
This is in `Index#bulk`

``` ruby
@response = Configuration.client.post("#{url}/_bulk#{params_encoded}", payload.join("\n"))
raise RuntimeError, "#{@response.code} > #{@response.body}" if @response && @response.failure?
@response
```

Why is `@response` sometimes nil?  This happens quiet frequently in my use of Tire.  The curious part is that the request actually succeeded; I can see the documents in the index.  The other curious part is that issuing the request again will (err, might) return a non-nil response.

I'm using `tire-0.5.7` and `curb-0.8.4` as the client.

Thank you.

**Comment by karmi** [comment]
@cjbottaro Can you describe the issue in more detail? Maybe there's some kind of proxy in front of ES, or it can't serve the load, or the request time outs?

**Comment by cjbottaro** [comment]
Sorry, everything works as expected.  Retry failures are logged to stderr instead of the logger, which was throwing me off.  Sorry for the noise.

**Comment by karmi** [comment]
@cjbottaro No worries and glad it's working!
