### ISSUE TITLE
undefined method `geo_shape' for #<Tire::Search::Query:....

### ISSUE THREAD

**Issue by chrishale** [karmi/retire#742]
Forgive me if I am going the wrong way about this, but I'm wanting to use the geo_shape query as a part of elastic search (http://www.elasticsearch.org/guide/reference/query-dsl/geo-shape-query/)

But when I try:

``` ruby
Model.search do 
    query do
        boolean do
            must { geo_shape :location, { :shape => { :type => 'envelope', :coordinates => [[13, 53],[14, 52]] } } }
            ...
        end
     end
end
```

I get:

```
undefined method `geo_shape' for #\<Tire::Search::Query:0x007ff07673e4e8 @value={}>
```

any ideas?

**Comment by karmi** [comment]
There is no DSL "sugar" for geo in Tire yet -- you have to simply configure the filter as any other:

``` ruby
Tire.search 'venues' do
  query do
    filtered do
      filter :geo_distance, distance: '100km', lat_lon: "41,-71"
    end
  end
end
```

**Comment by chrishale** [comment]
Ok, really needed to do a query rather than a filter. I've forked it and managed to get it working. I've sent you a pull request! :)

Cheers,
Chris
