### ISSUE TITLE
Receiving the error message: "undefined method `tire' for Drug:Class"

### ISSUE THREAD

**Issue by ghost** [karmi/retire#745]
I was able to create the index on the local server normally using the following command:-
"rake environment tire:import CLASS=Drug FORCE=true"
however when attempting to executing the same command "bundle exec rake environment tire:import CLASS=Drug FORCE=true RAILS_ENV=production" on the production server, i got the following error message

undefined method `tire' for Drug:Class
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/tire-0.4.3/lib/tire/tasks.rb:47:in`block (2 levels) in <top (required)>'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:244:in `call'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:244:in`block in execute'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in`execute'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in`invoke_with_call_chain'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in`invoke_task'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in`each'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in`run_with_threads'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in`block in run'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/deployer/public_html/nabda-net/shared/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in`run'
Tasks: TOP => tire:import
(See full trace by running task with --trace

Could you please let me know what i could do to fix this issue?

**Comment by karmi** [comment]
You're using fairly old Tire version -- try to upgrade both locally and on the production server, and run it again?

**Comment by ghost** [comment]
Thank you very much :+1: upgrading the gem resolved my problem
