### ISSUE TITLE
How to achieve model include in ElasticSearch model to get hierarchical json? 

### ISSUE THREAD

**Issue by animeshdash** [karmi/retire#750]
I am having Job,User,JobType & Company_Logo models which are indexed. 
Earlier i was using :include of ActiveRecord model to  get Job model included with User,JobType. And Company_Logo is included under User.

Using below code in controller : 
format.json { render json: [@jobs.to_json(include: [:state,:city,:jobtype,:user=>{include: [:company_logos]}])

User,JobType are having has_many relation with Job. Similarly Company_Logo is having has_many relation with User.

Now i want to use only Elasticsearch model in place of ActiveRecord so that the database will not be accessed (by using load: false).

I am using backbone.js,coffescript with Rails 3.2.9. 

How can i achieve it ?

**Comment by karmi** [comment]
You have to properly define the `mapping` and/or `to_indexed_json` to serialize all the information you need for displaying to the user / rendering as JSON. Please have a look in the test directory, where you'll find many examples, and see the Stackoverflow answer: http://stackoverflow.com/questions/11692560/elasticsearch-tire-and-nested-queries-associations-with-activerecord/11711477#11711477

You might need to research Elasticsearch `nested` type and the parent/child support.

**Comment by karmi** [comment]
Closing, feel free to ping back if you have more info.
