### ISSUE TITLE
Type in 'ids' query should not be required.

### ISSUE THREAD

**Issue by tpitale** [karmi/retire#751]
https://github.com/karmi/tire/blob/master/lib/tire/search/query.rb#L95

Requires that a type be set when doing an ids query. However, type is optional http://www.elasticsearch.org/guide/reference/query-dsl/ids-query/

If nil is passed, the query is broken.

**Comment by tpitale** [comment]
We had another issue, my apologies. This was a red herring.

**Comment by karmi** [comment]
@tpitale You're way too kind :) Type is indeed optional, so I make it so in Ruby as well, and improved the handling of arguments a bit in the attached commit (00eafc0).

**Comment by tpitale** [comment]
Thank you!
