### ISSUE TITLE
Mapping is not created according to model

### ISSUE THREAD

**Issue by atombender** [karmi/retire#752]
I have a model like this:

```
class Comment < ActiveRecord::Base
  include Tire::Model::Search
  mapping do
    indexes :thread_title,
      include_in_all: false,
      analyzer: 'norwegian',
      boost: 3.0,
      as: ->(c) { c.parent.title }
  end
end
```

This results in the following mapping:

```
"comment" : {
  "properties" : {
    "thread_title" : {
      "type" : "string"
    }
  }
}
```

Obviously, `include_in_all`, `analyzer` and `boost` are all missing.

This can be reproduced with no existing index. Tire's initial index creation does not provide the correct mapping.

If I manually create the mapping like so, it works:

```
Comment.index.mapping('comment', properties: Comment.mapping)
```

**Comment by karmi** [comment]
> Tire's initial index creation does not provide the correct mapping.

That would be suprising. What happens when you delete the index and call `Comment.create_elasticsearch_index`?

**Comment by karmi** [comment]
@atombender Can you confirm that when you call `Comment.index.delete; Comment.create_elasticsearch_index`, the index is created with correct settings/mappings?

**Comment by atombender** [comment]
That works.

Interestingly, if I stop ES, delete the entire ES folder, start ES and then do `Comment.create_elasticsearch_index`, nothing at all happens.

If I stop ES, delete the entire ES folder, start ES and then do `Comment.update_index`, I get the index without any of the mappings I specified.

**Comment by karmi** [comment]
For the first case, you need to load the model -- so when you eg. run `rails console`, you must "touch" the model, just calling `Article` is enough.

For the second case, that call is incorrect, you must call something like `Comment.first.update_index`.

I've added more info in d97f7fc5e555750945c2c2fcd22bcbfeeb5bde17 to the README.

**Comment by atombender** [comment]
Please don't just close issues like that before you have determine the cause or even solved the problem.

I obviously meant `Comment.first.update_index`. That also results in a partial index. Touching the model does nothing, by the way. I have now played around with the models a bit, and it is evident that _some_ models work, but others don't. The problem occurs even if I gut everything except a single mapping.

I believe I have found the cause. At the top of `comment.rb`, I have:

```
require 'event'
```

This is because the model stores entire objects (`Event` in this case) using `Rails.cache`, and this is required when Rails is in development mode, otherwise model classes will not be reloaded.

I have not determined why this screws up Tire. The strange thing is that Tire does not complain; it just stores an incomplete mapping. `Comment.mapping` returns valid stuff, by the way, so that's pretty weird.

I will investigate further. Any ideas?

**Comment by atombender** [comment]
All right, what's happening is that ES creates the mapping automatically when indexing the object. That's why it's missing stuff. Tire never creates the full mapping.

The reason is that Tire only creates a mapping when there is no existing index. But all my models use a single index (I use `index_name` in each model class). So what is happening is that `require "event"` requires `event.rb`, which declares `Event`, which has a `mapping do ...` block. `mapping` calls `create_elasticsearch_index`, which creates the index, but only for the mappings in `Event`. When it comes to the `mappings do ...` block in `Comment`, the index already exists, and no mappings are stored.

So this is a real bug. You seems to conflate the notions of "index" and "mappings", even though they are separate. An index stores data; mappings tell ES how to handle that data. There is no reason for Tire to assume that mappings exist even though the index itself exists.

Something like this would work:

```
def create_elasticsearch_index
  unless index.exists?
    new_index = index
    unless result = new_index.create(:mappings => mapping_to_hash, :settings => settings)
      STDERR.puts "[ERROR] There has been an error when creating the index -- elasticsearch returned:",
                  new_index.response
      result
    end
  else
    index.put_mapping(document_type, properties: mapping_to_hash)
  end
  ...
```

**Comment by karmi** [comment]
If the default behaviour where Tire creates the index for your model is not desired, please create the index with proper settings/mappings manually, as the README states:

> It may well be reasonable to wrap the index creation logic declared with Tire.index('urls').create in a class method of your model, in a module method, etc, to have better control on index creation when bootstrapping the application with Rake tasks or when setting up the test suite. Tire will not hold that against you.

**Comment by atombender** [comment]
It's still a bug. Tire makes an invalid assumption.

**Comment by karmi** [comment]
I understand your frustration, but not your argument, I'm afraid. Tire tries to create the index with the correct settings/mappings only when it doesn't exist -- that is documented and "safe" behaviour.

If all your models share a single index, you're precisely in the spot where you can't rely on Tire defaults. It should be easy to define the mapping externally, or merge all mappings from the model definitions, and create the index imperatively/manually.

The solution you propose, to update the mapping on each class load has two big drawbacks:
- It issues a "put mapping" call on each class load, which is not something you might want, which might create problems with class reloading in development, etc
- There's a problem of handling incompatible changes, conflicts. The library would make even more "false promises" here, in my opinion.

**Comment by atombender** [comment]
It is only necessary to update the mapping _if it does not already exist_. This will not introduce any conflicts, compatibility issues, etc. After all, you do the same thing with indexes.

The current approach (creating only the first mapping that is encountered) is inconsistent and the violates the principle of least surprise. After all, if I declare a mapping, I _should expect it to be created_, and not silently ignored.
