### ISSUE TITLE
Appears to be no way to make sorting case insensitive via the Tire api? 

### ISSUE THREAD

**Issue by jmdfm** [karmi/retire#753]
Performing an alphabetical sort on an indexed field results in some case sensitivity being applied.

Is there a way to specify that the sort should be case-insensitive via the Tire api?

**Comment by karmi** [comment]
Hi, I don't know if I understand correctly -- it doesn't make much sense generally to sort on analyzed fields, though Elasticsearch 0.91 and higher supports it. Could you post more info?

**Comment by jmdfm** [comment]
Apologies. Here's more info:

Given:

```
indexes :name,                :index    => :not_analyzed
```

I'd like to be able to have the query results on :name be sorted alphabetically, but when I say

```
s.sort { by :name, 'asc'  }
```

The results are sorted with capital case first, then lower case, like:

   Albatross 
   Bamboo
   Zebra
   albany
   church

**Comment by jmdfm** [comment]
I've just discovered this link: http://elasticsearch-users.115913.n3.nabble.com/Case-Insensitive-Sort-td4021310.html

But I'm not sure how that would translate into the Tire API, if at all?

**Comment by jmdfm** [comment]
Seem to have solved this with a custom analyzer:

```
settings :analysis => {
           :analyzer => {
             :name_analyzer => {
                "tokenizer"    => "keyword",
                "filter"       => "lowercase",
                "type"         => "custom" }
           }
          }

indexes :name,                :analyzer=>'name_analyzer'
```

**Comment by karmi** [comment]
@johnmcdowall Ahh, OK, yes, if you want the name "not_analyzed", you have to lowercase it yourself as you do. The field seems like a good candidate for [`multi_field`](http://www.elasticsearch.org/guide/reference/mapping/multi-field-type/), where you have both the analyted (stemmed, etc) version and the not analyzed version?
