### ISSUE TITLE
Ruby 2 support?

### ISSUE THREAD

**Issue by djcp** [karmi/retire#755]
@karmi et al.,

Thanks for your great work on this gem. Basic question - does this explicitly support ruby 2? Running the specs locally it MOSTLY passes, only 3 or 4 failures.

Thanks!

**Comment by karmi** [comment]
@djcp It should be 100% compatible with Ruby 2.0, some integration tests fail for a long time (percolator issues). See eg. https://travis-ci.org/karmi/tire/jobs/7905760, the unit tests pass.

**Comment by djcp** [comment]
Awesome. Yeah, we're actually seeing MORE tests pass under ruby 2 than 1.9 on the same system. We'll give it a go!

**Comment by karmi** [comment]
@djcp Do unit tests fail, or only integration test?
