### ISSUE TITLE
.search conflicts with other gems

### ISSUE THREAD

**Issue by sporto** [karmi/retire#756]
I have another search gem in my app 'ransack', it works in quite a different way so we want to keep them both. Both Tire and ransack try to add .search to active record. 

Having an alias for .search will be great, so they can both be used. See this related issue https://github.com/ernie/ransack/issues/214

**Comment by karmi** [comment]
Tire does not overwrite existing methods, and depends on the order of `include` statements. See the README for the `tire` proxy method: you can use `Mymodel.tire.search`.

**Comment by sporto** [comment]
great, the proxy method is what I was looking for.
