### ISSUE TITLE
Add support for rails url helpers to work with friendly_id slugs with tire result items

### ISSUE THREAD

**Issue by gudata** [karmi/retire#763]
I want to be able to use result items with slugs auto magically with rails url helpers.

AR with friendly_id

```
Photo.first.slug 
> "nice_sluggg"
Photo.first.friendly_id
> "nice_sluggg"
```

Tire Result::Item

```
result = Search::Collection.new(category_id: 28).paginate(1,0).results.first
result.slug (field)
> "nice_sluggg"
result.friendly_id
> nil
```

The Photo class

```
class Photo < ActiveRecord::Base
  # The order is important
  include ActiveModel::ForbiddenAttributesProtection
  include Publication::SeoUrl
  include Publication::Base
  include Publication::Blockable
  include Search::Photo
```

The  Publication::SeoUrl

```
module Publication
  module SeoUrl
    extend ActiveSupport::Concern

    included do
      extend ::FriendlyId
      friendly_id :slug_base, use: [:slugged, :history, :scoped], scope: :category

      def slug_base
          self.slug = self.name ? self.name[0..254].to_ascii : "#{I18n::t('Without a title')} - #{rand(999999)}"
        end
      end
    end

  end
end
```

The Search::Photo module

```
module Search::Photo
  extend ActiveSupport::Concern
  include Search::Base
  include ActionView::Helpers::SanitizeHelper
  include Publication::SeoUrl
```

**Comment by karmi** [comment]
Could just index the `friendly_id` in your model `mapping` definition?

**Comment by gudata** [comment]
I have putting a field friendly_id but it doesn't work.
It works only if I specify the id like this

```
 photo_path(publication.slug) 
```

and it should be 

```
 photo_path(publication)
```

_photo_path_ is calling internally _.to_param_
which returns the id as a number, and I expect friendly id to override this method and construct the slug dynamically (or just return the slug stored field)

Maybe I am doing something wrong with the includes and friendly id doesn't have the chance to override the to_param method I don't know. 

Do you have an app which is working with result items and friendly id ?

**Comment by karmi** [comment]
Then use a custom wrapper (https://github.com/karmi/tire/blob/master/test/unit/index_test.rb#L430-L438), where you implement `to_param` correctly, or overload the Item [`to_key`](https://github.com/karmi/tire/blob/master/lib/tire/results/item.rb#L60) to use slug instead of id.

**Comment by gudata** [comment]
The solution with the wrapper object will force creating a new proxy object for each result item because I have multiple types. Because of this the good way for me will be to overload to_key but I have to find a way to do it.

Thanks!

**Comment by karmi** [comment]
> The solution with the wrapper object will force creating a new proxy object for each result item because I have multiple types.

Not necessarily -- the wrapper could be "smart" about which model it represents.

**Comment by gudata** [comment]
When use the wrappers everything is in place.
Thanks!

**Comment by jeremylynch** [comment]
Hi Gudata, did you solve this issue in the end? How did you construct your wrapper?

**Comment by gudata** [comment]
It was long time ago. check if this will help https://gist.github.com/gudata/7691749
