### ISSUE TITLE
:load => true doesn't load all records

### ISSUE THREAD

**Issue by danielhum** [karmi/retire#764]
for some reason, sometimes `:load => true` doesn't properly eagerly load all records.

for example,

``` ruby
results = Article.search("hello",load:true)
puts results.count
puts results.to_a.inspect
```

`results.count` may show the correct number, eg. 4, but `results.to_a` gives `[nil, <Article >, nil, nil]`

anyone encounter this too?

**Comment by karmi** [comment]
It might be because your docs are missing from the db? See #602 and #702, implement your own `__find_records_by_ids` if you need it.

**Comment by danielhum** [comment]
no, I've verified that the docs are in the db. I'll continue debugging for now.

**Comment by phoet** [comment]
@hsadan did you find anything? like @karmi said, it's usually missing records (or scopes in rails) that just don't find the records in the db. have a look in the application logs and try to execute the query yourself to find out why the records are missing.

**Comment by danielhum** [comment]
Thanks for the suggestions. Interestingly I can't seem to replicate this again, closing for now.
