### ISSUE TITLE
chars interval

### ISSUE THREAD

**Issue by alotela** [karmi/retire#765]
Hi,

how can I use Tire to select all documents where title start between A and E for example ?
I need to select documents by chars intervals (non alpha, 0..9, a-e / A-E, f-j/F-J etc etc...., including accented chars).

I don't see how to do it easily...

Does anyone know?

thanks

**Comment by karmi** [comment]
You simplest option is to use a `query_string` query, another option is a bool query with `prefix`, or, for maximum performance, adding a field such as `initial_letter` to the document and using `range` filter then:

``` ruby
require 'tire'

Tire.index 'alphabet' do
  delete
  create
  store title: 'Aesop', initial_letter: 'a'
  store title: 'Aleph', initial_letter: 'a'
  store title: 'Burgundy', initial_letter: 'b'
  store title: 'Eternal', initial_letter: 'e'
  store title: 'Hell', initial_letter: 'h'
  store title: 'Kierkegaard', initial_letter: 'k'
  store title: 'Yin', initial_letter: 'y'
  refresh
end

s = Tire.search 'alphabet' do
  query { string 'title:[A* TO F*]' }
end

puts "", "String query", '-'*80, s.results.map { |r| r.title }

s = Tire.search 'alphabet' do
  query do
    boolean do
      should { prefix :title, 'a' }
      should { prefix :title, 'b' }
      should { prefix :title, 'c' }
      should { prefix :title, 'd' }
      should { prefix :title, 'e' }
    end
  end
end

puts "", "Boolean query", '-'*80, s.results.map { |r| r.title }

s = Tire.search 'alphabet' do
  query do
    filtered do
      filter :range, title: { from: 'a', to: 'f' }
    end
  end
end

puts "", "Range filter", '-'*80, s.results.map { |r| r.title }
```

**Comment by alotela** [comment]
very interesting. Thank you.
I think I need to study lucene query syntax deeper.
I thought range filter was only for integer values. I will try all your solutions.

and do you know how to select all non alphanumeric chars ?

**Comment by karmi** [comment]
You can either fine tune how you index (see the hint with `initial_letter`), or, when the performance would be acceptable, use eg. the `regex` query.

**Comment by alotela** [comment]
Ok,

I will try and see what is the best for me.

Thank you.

**Comment by alotela** [comment]
how can I search for non alpha first letter ?

in my document, I have this field for example : "creator_first_letter":"-"

indexes :creator_first_letter, type: 'string'

but my facet doesn't list it : facet('first_letter') { terms ["creator_first_letter"], size: 10000, order: "term" }
(by the way, if you have a better solution than "size: 10000" to return all terms > 0, I'm happy to learn it.)

**Comment by karmi** [comment]
probably since the analyzer throws it out, set it to `analyzer: 'keyword'`. see the doc for returning all terms in facet.

**Comment by alotela** [comment]
ok i remived the analyzer for now. works perfect.

thank you for quick answers!
