### ISSUE TITLE
Moped::BSON::ObjectId still a PITA

### ISSUE THREAD

**Issue by brknstrngz** [karmi/retire#769]
Hi Karel,
Would it make sense to force a String cast for Mongoid document IDs? Documents are currently indexed/update properly, using the string representation of {"$oid" => "value"}, but that makes queries such as the one below quite harder:

``` ruby
current_user_id = "_id:#{current_user.id}"
skip_self_qry = lambda do |boolean|
  boolean.must_not { string current_user_id  }
end
```

For the time being I have overridden the "id" method in my model to return a string:

``` ruby
def id
  self._id.to_s
end
```

... but I assume there would be a better way of doing this. Maybe an aditional check in get_id_from_document - if the class of the result returned by the 'id' method is Moped::BSON::ObjectId, then to_s it.

P.S. I am using Mongoid 4.0.

Thanks for looking
Vlad

**Comment by phoet** [comment]
@vgalu when using the `:load` option, you would have to change it back to the `{"$oid" => "value"}` format, for mongo to find it, right?

**Comment by brknstrngz** [comment]
I am not sure, I have not tried that yet. I have changed the JSON representation of my models to include everything I needed so that I don't have to call into Mongo to fetch that information.

**Comment by karmi** [comment]
@vgalu This is due to incorrect serialization of ID in Mongoid, see #775, you don't _have_ to change the model (possibly breaking other stuff in your app), just change the JSON serialization.

**Comment by brknstrngz** [comment]
@karmi I had tried that as well, but get_id_from_document still returned the {"$oid" => "value"} hash as an ID.
Looking at Mongoid's #2497 entry in the 4.0 ChangeLog, I think they used to do what I did, so Tire must have been working with the string representation of the Mongo ID before. I cannot test whether :load => true breaks anything, but I can do that later.

What I am sure of, though, is that in my Rails controller there are at least a couple of methods that receive a model ID (as tweaked in my original post) as an argument that do call Mongoid and work.

**Comment by karmi** [comment]
@vgalu Pushed 3291bee a while ago, could you verify it solves your issue?

**Comment by brknstrngz** [comment]
@karmi Seems to work, thanks!

**Comment by karmi** [comment]
@vgalu Great!
