### ISSUE TITLE
How to get total score as sum of boost points?

### ISSUE THREAD

**Issue by regedarek** [karmi/retire#773]
I am sending query like this:(using `query { all }`)

``` json
{"query":{"custom_filters_score":{"query":{"match_all":{}},"filters":[{"filter":{"range":{"last_contact_at":{"gte":"2013-06-21T12:02:25Z"}}},"boost":1},{"filter":{"range":{"available_at":{"gte":"2013-06-28"}}},"boost":2},{"filter":{"term":{"company_type":"intern"}},"boost":10},{"filter":{"range":{"friends_count":{"from":1}}},"boost":3},{"filter":{"term":{"blacklisted":true}},"boost":-100},{"filter":{"term":{"focuses":"ruby php"}},"boost":5},{"filter":{"term":{"tags":"ruby php"}},"boost":4}],"score_mode":"total"}}}
```

and I get following response with max_score: `16` which is sum of my boost points.

**Response**

``` json
{
   "took": 3,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 10,
      "max_score": 16,
...
```

And when I am sending the same `custom_filters_score` but with `query { string term }`

``` json
{"query":{"custom_filters_score":{"query":{"query_string":{"query":"ruby php"}},"filters":[{"filter":{"range":{"last_contact_at":{"gte":"2013-06-21T12:03:46Z"}}},"boost":1},{"filter":{"range":{"available_at":{"gte":"2013-06-28"}}},"boost":2},{"filter":{"term":{"company_type":"intern"}},"boost":10},{"filter":{"range":{"friends_count":{"from":1}}},"boost":3},{"filter":{"term":{"blacklisted":true}},"boost":-100},{"filter":{"term":{"focuses":"ruby php"}},"boost":5},{"filter":{"term":{"tags":"ruby php"}},"boost":4}],"score_mode":"total"}}}
```

and I get following response with max_score: `8.990471`

**Response**

``` json
{
   "took": 4,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 6,
      "max_score": 8.990471,
...
```

How to achieve `max_score` as sum of my boost points and also show only results which contains `term` ?

**SearchService**: https://gist.github.com/8f13ce2be820d9ef1959

**Comment by phoet** [comment]
@regedarek boosting in elasticsearch is not trivial. it depends on the number of keywords in a document and i always forget how to tweak those things, because it's so akward. if you want to read more, here is a nice article about scoring in elasticsearch http://jontai.me/blog/2013/01/advanced-scoring-in-elasticsearch/

i don't think that this is a tire issue though, as it is just an api for ES.

**Comment by karmi** [comment]
@regedarek Is this related to #774? Can you please consolidate the question into single issue? Also, it would help if you had a _full_ example, which would allow to recreate your situation entirely.
