### ISSUE TITLE
Select fields on eager loading

### ISSUE THREAD

**Issue by lfv89** [karmi/retire#778]
I'm already able to select the fields that will be returned from the ElasticSearch query, but now I would like to be able to select the fields that will be loaded from the database when I pass the `load: true` option, maybe something like:

`tire.search(load: { fields: [:title] })`

Can I achieve this behaviour directly trough tire ? Thank you.

**Comment by phoet** [comment]
@vasconcelloslf when you look at the collection class (https://github.com/karmi/tire/blob/master/lib/tire/results/collection.rb#L156) you can see that everything that you pass to `:load` will get propagated `klass.find(ids, @options[:load])`

so when you use the ActiveRecord option `:select` for find, it should work.

**Comment by phoet** [comment]
also connected to #762

**Comment by lfv89** [comment]
@phoet thank's for your attention.

Yep I saw that method, but I don't think that works with MongoID, I just tried `Article.find(id, only: :email)` and nothing... So I forked tire to make that work with MongoID... Would that be an interesting PR to make ?

**Comment by phoet** [comment]
@vasconcelloslf can you link the changes in there, so that @karmi can review that?

**Comment by karmi** [comment]
@vasconcelloslf Sorry for the silence. This is also related to #767 and effectively all discussions we're having about having  a set of strategies which would allow customizable finders for major ORMs. If you have time, sure link the changes or submit a PR so we can talk around code.
