### ISSUE TITLE
Tire result construction taking lot of time

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#779]
When I do a search using Tire.search with just the filters alone I get the response within 250-300ms. But, when I use the results the time goes upto 5-6 seconds. Why is this happening?

say,

```
@items = Tire.search do
filtered do
filter ...
end
end
<when I don't have the below line of code, the response time is 250milliseconds>
<when I have the below line of code, the response time is 3-5seconds>
results = @items.results
```

**Comment by karmi** [comment]
Results are lazy loaded, see: https://github.com/karmi/tire/blob/master/lib/tire/search.rb#L34, so until you touch results, no request is executed.

Also, it's quite impossible for the block to take 250msec to execute, without executing the response. Compare:

``` ruby
require 'tire'
require 'benchmark'

duration = Benchmark.realtime do

  s = Tire.search do
    query do
      filtered do
        query { match :title, 'foo' }
        filter :terms, tags: ['one']
      end
    end
  end

  puts s.to_json
end

puts "", "Duration: #{duration*1000} ms"

```

**Comment by vamsi-krishna-E0029** [comment]
I have used Benchmark.bmbm

and these are the results I get with and without the line. The only difference in code is, just the assignment of result set to a variable.

(results = @items.results)

```
user       system      total          real
0.000000   0.000000   0.000000   (  0.000191) - search without results
0.360000   0.010000   0.370000   (  6.331976) - search with results
```

**Comment by karmi** [comment]
@ovamsikrishna Sure, until you touch `results`, no request is executed to Elasticsearch, please see my note and link above...

**Comment by vamsi-krishna-E0029** [comment]
I got it, You mean that the response from elasticsearch itself is taking so long. Thanks for the info.
Any idea why this could take so long at elasticsearch?

**Comment by vamsi-krishna-E0029** [comment]
Closing the issue. Please let me know if you have any idea regarding the slow response time at elasticsearch.

**Comment by karmi** [comment]
That really depends on the query itself, the amount of data, available resources, etc.

**Comment by vamsi-krishna-E0029** [comment]
With the same setup direct curl request (search query) was taking very less response time. But, when I use tire it was taking 3.5seconds. Does tire use anything else in between? I verified it with the took field in search result. Am I doing wrong here? As far as I know the took field represents the time taken by entire search API.

**Comment by karmi** [comment]
@ovamsikrishna Without concrete numbers and details about how you measure, it's impossible to come up with a reasonable assesment.
