### ISSUE TITLE
Is it possible to index hstore attributes?

### ISSUE THREAD

**Issue by abitdodgy** [karmi/retire#780]
I have an `Item` model that belongs to a `Product` model. I want to use Tire to search for `Item` based on attributes found in `Product`. One such attribute, `platform`, is in an `hstore` col called `properties`. At the moment `platform` appears to display as an empty string.
1. How can I get Tire to display/index the  `product.platform` attribute?
2. Is it possible to use `product.platform` in a filter?

``` ruby
  # product.rb
  store_accessor :properties, :platform
  has_many :items

  # item.rb
  belongs_to :product

  def self.search(params)
    tire.search(page: params[:page], per_page: 12) do
      query do
        string params[:query], default_operator: "AND"
      end if params[:query].present?

      filter :term, 'product.platform' => 'a_platform' # Does not appear to be working.
    end
  end

  def to_indexed_json
    to_json(include: :product)
  end
```

**Comment by karmi** [comment]
Tire just indexes model attributes/methods, so it shouldn't make a difference if it's a column or Hstore property or something like that. Evaluate (and possibly post here) `@yourmodel.to_indexed_json` to see how it looks like and how it gets indexed into ES.

**Comment by abitdodgy** [comment]
OK. I solved one problem. I can now search `Item` by `product.properties.platform`. I used `delegate`. But I can't filter `Item` by `product.properties.platform`. To avoid bashing my head on the wall, is that possible?

This does not work:

``` ruby
filter :term, product_platform: params[:platform] if params[:platform]
```

Here's how I solved the other issue using `delegate`:

``` ruby
class Item < ActiveRecord::Base
  belongs_to :product
  delegate :platform, to: :product, prefix: true
end
```

Here's my `item.to_indexed_json`; notice `product_platform` is in the methods list:

``` ruby
  def to_indexed_json
    to_json(include: :product, methods: :product_platform)
  end
```

**Comment by karmi** [comment]
Post the JSON serialization of the model, please.

**Comment by abitdodgy** [comment]
I'm not sure if I understand you correctly:

`curl -X GET 'http://localhost:9200/items/item/_search?size=12&pretty' -d '{"sort":[{"created_at":"ASC"}],"filter":{"and":[{"term":{"availability":"in_stock"}},{"tem":{"product_platform":"Nintendo Wii"}}]},"size":12}'`

This is what that returns:

```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by karmi** [comment]
Nono, I mean, if you can post the output of `@yourmodel.to_indexed_json`, so we can see what is being sent to Elasticsearch.

**Comment by abitdodgy** [comment]
Here's a search got a hit:

`curl -X GET 'http://localhost:9200/items/item/_search?size=12&pretty' -d '{"query":{"query_string":{"query":"Way","default_operator":"AND"}},"sort":[{"created_at":"ASC"}],"filter":{"term":{"availability":"in_stock"}},"size":12}'`

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : null,
    "hits" : [ {
      "_index" : "items",
      "_type" : "item",
      "_id" : "2",
      "_score" : null, "_source" : {"id":2,"product_id":394,"user_id":1,"condition":"New","availability":"in_stock","price":"68","created_at":"2013-07-02T02:17:51.826Z","updated_at":"2013-07-02T02:17:51.826Z","product_name":"Way of the Samurai 3","product_platform":"Xbox 360","product":{"id":394,"name":"Way of the Samurai 3","slug":"way-of-the-samurai-3","category_id":1,"image_url":"2330","properties":{"genre":"Action \u0026 Adventure","rating":"4.1","platform":"Xbox 360","subgenre":"Historic Action Adventure","multiplayer":"","online_play":"Y","release_date":"2009-10-20","classification":"16 Anos","online_players":""}}},
      "sort" : [ 1372731471826 ]
    } ]
  }
}
```

**Comment by abitdodgy** [comment]
OK, here's a sample. The data is being indexed (twice, once from the delegate methods, and once from the include call), but it's not working in the filter:

```
'{"id":1,"product_id":234,"user_id":1,"condition":"Good","availability":"in_stock","price":"119","created_at":"2013-07-02T02:17:51.818Z","updated_at":"2013-07-02T02:17:51.818Z","product_name":"The
  Godfather","product_platform":"Playstation 3","product":{"id":234,"name":"The
  Godfather","category_id":1,"image_url":"1280","properties":{"genre":"Action
  Adventure","rating":"3.9","platform":"Playstation 3","subgenre":"Historic
  Action Adventure","developer":"Electornic Arts","multiplay":"N","publisher":"Electronic
  Arts","multiplayer":"","online_play":"Y","release_date":"2007-03-20","online_players":""}}}'
```

**Comment by karmi** [comment]
> > `{"tem":{"product_platform":"Nintendo Wii"}`
> 
> `"_source" : ... "product_platform":"Xbox 360"...}`

Seems like your `product_platform` is indexed correctly, but since you're using a term filter, it expects the field to be non-analyzed, ie not broken into terms. Post the output of your `MyModel.mapping.to_json`, and also try to set up mapping correctly with eg. "keyword" analyzer -- have a look in integration tests and also search Google/StackOverflow.

**Comment by abitdodgy** [comment]
I haven't defined any mappings. This is what the search looks like:

``` ruby
  def self.search(params)
    tire.search(page: params[:page], per_page: 12) do
      query do
        string params[:query], default_operator: "AND"
      end if params[:query].present?

      filter :term, product_platform: params[:platform] if params[:platform]
    end
  end

  def to_indexed_json
    to_json(include: :product, methods: [:product_platform, :product_name])
  end
```

Is it necessary to use mappings?

**Comment by karmi** [comment]
> I haven't defined any mappings.

You _have_ to define proper mapping for the term filter to work correctly. Please have a look in integration tests and on StackOverflow.

Karel

**Comment by abitdodgy** [comment]
I'm sorry, could you just explain something to me: Why does not filter correctly by `product_platform` ?

**Comment by abitdodgy** [comment]
I tried using an analyzer, and setup this mapping. It still produces 0 hits, with and without an analyzer. Could you point me some where to see examples of how to get this to run?

I posted this on SO: http://stackoverflow.com/questions/17430899/tire-failing-to-filter-results

``` ruby
  mapping date_detection: false do
    indexes :id, type: 'integer'
    indexes :user_id, type: 'integer'
    indexes :product_id, type: 'integer'
    indexes :product_platform, analyzer: 'keyword'
  end
```

**Comment by abitdodgy** [comment]
OK. I figured out the the filter will not work if we pass to it two words: `Playstation 3`, for example. It will work when I use a single word, and in lowercase, like `playstation`.

How do I modify this behaviour?

**Comment by karmi** [comment]
@abitdodgy I'm afraid I can't walk you through the whole problem. Have you researched how analyzers work? When you use the `keyword` analyzer, the field is indexed "as is", ie. without lowercasing, splitting, etc. I suggest starting eg. here, http://www.elasticsearch.org/videos/bbuzz2013-getting-down-and-dirty-with-elasticsearch/.

**Comment by abitdodgy** [comment]
Thank you. Yes, the difference was the `keyword` analyzer. Before I close this, I have a quick question:

My `Item` model changes constantly. When an `item` is `bought` the `in_stock` column is changed, and the item must be removed/filtered from the index. Bought `items` are unique and must be removed. This can happen hundreds if not thousands of times per day. Is my use case something that ElasticSearch is meant to handle? Having to update the indecies so often?

**Comment by karmi** [comment]
Glad to hear that.

> This can happen hundreds if not thousands of times per day. Is my use case something that ElasticSearch is meant to handle?

That's not a problem. Have a look at the Update API in Elasticsearch (Tire integration test: https://github.com/karmi/tire/blob/master/test/integration/index_update_document_test.rb), which allows you to update a document without sending all the JSON across the wire. (Of course, your infrastructure must be able to withstand continuous updating & searching.)

**Comment by abitdodgy** [comment]
Great, thank you.
