### ISSUE TITLE
where are the docs being generated?

### ISSUE THREAD

**Issue by bhaibel** [karmi/retire#782]
It's pretty clear that the documentation up on karmi.github.io/tire is being generated with docco, but I can't find the files docco is pointing at anywhere in the repo.

I'd like to update them to reflect some currently-undocumented methods (count, scan, maybe some other things) but I'd like to edit the actual source for them, rather than the HTML docco is generating.

not 100% sure that the issue tracker is the right place for a "how do I contribute" question but it seemed as good as any. :)

**Comment by karmi** [comment]
It's the [`examples/tire-dsl.rb`](https://github.com/karmi/tire/blob/master/examples/tire-dsl.rb) file. Using issues is a perfect place to ask for help, ask questions, suggest improvements, etc.

**Comment by karmi** [comment]
Closing, feel free to open issues for questions or continue discussions in old ones, we can always re-open them.
