### ISSUE TITLE
undefined method `highlight' with tire/elasticsearch and mongoid

### ISSUE THREAD

**Issue by hyperrjas** [karmi/retire#783]
My search engine with `elasticsearch` is working fine but now I want highlight the snippets matching our query in the displayed results.

Model

```
class Car
  def self.search(params)
    tire.search(load: true, page: params[:page], per_page: 9) do
      query do
        boolean do
          must { string params[:query], default_operator: "AND" } if params[:query].present?
          must { range :published_at, lte: Time.zone.now }
        end
      end
      highlight :title, :description, :options => { :tag => '<strong class="highlight">' }
    end
  end

  mapping do
    indexes :_id, index: :not_analyzed
    indexes :published_at, type: 'date'
    indexes :title, analyzer: 'snowball', boost: 100
    indexes :description, analyzer: 'snowball', boost: 90
  end

  def to_indexed_json
    {
      _id: _id,
      title: title,
      description: description,
      published_at: published_at,
    }.to_json
  end
end
```

action controller:

```
def search
  @cars = Car.search(params)
end
```

The view:

```
<%= @cars.results.each do |document| %>
  <%= p document.highlight %>
<% end %>
```

I get the next error:

`undefined method 'highlight' for #<Car:0xee980f0>`

**Elasticsearch version: 0.20.2**
**Tire version: 0.5.5**

What am I missing?

Thanks!

**Comment by karmi** [comment]
Are you using `load:true`? Tire complains about your model not having the method, not Results::Item...

**Comment by hyperrjas** [comment]
I have fixed the error with `each_with_hit`:
    `<% @cars.each_with_hit do |result, hit| %>`
          `<%= raw hit['highlight']['title'].map(&:inspect).join(',').gsub('"', '') if hit['highlight']['title'] %>`
        `<%= raw hit['highlight']['description'].map(&:inspect).join(',').gsub('"', '') if hit['highlight']['description'] %>`
    `<% end %>`

I don't know if this is the best approach...

Thanks!

**Comment by karmi** [comment]
It's not an error, then .) You were loading your model instances, which don't have the method -- `each_with_hit` is designed specifically for this situation.

**Comment by hyperrjas** [comment]
Thank you very much for this explanation!

**Comment by fillman** [comment]
A BIG note here guys, when there's no match then you'll get no HIGHLIGHT field at all. This is sometimes tricky when you highlight one field but do search on several fields. So document is returned but no highlights. Be careful :)
