### ISSUE TITLE
ActiveRecord::RecordNotFound - Couldn't find all <records> after destroy

### ISSUE THREAD

**Issue by edrush** [karmi/retire#791]
Hi,

I spent some hours on this, allthough it seems such an obvious issue I can not find solutions so I guess the error is on my side: I have different records stored in SQLite and ElasticSearch/Tire. So far it works great, but when I delete a record which leads to the index view I get an "ActiveRecord::RecordNotFound" and "Couldn't find all ..." error, I guess since the record is deleted in the database but not yet in ES (works after reloading the page). Same thing for creating new records: they don't appear in the first place after saving, but the second time reloading the page they're there. I found and I tried some update_index and tire.update_index in the classes' callbacks and also Emp.tire.index.remove @emp (Emp is one of my model), but none of them worked out. 

Thanks for your help!
Wolfram

**Comment by karmi** [comment]
Please search the issues, many mention this thing, you can manually overload the finder method... Alternatively call index.refresh after delete.

I'll post you some links tomorrow if you'll be still lost,

Karel

**Comment by edrush** [comment]
Hi Karel,

I did some searching here, without success (e.g. search for "ActiveRecord::RecordNotFound" or "refresh on destroy") and I tried index.refresh after destroy, but nothing changed, I'm still lost. What do you mean with overloading the finder method? I'm sure that many run into this, that's why I'm surprised that it's so hard to find answers. Maybe I'm searching for the wrong key words? It would be nice if you sent me some links - thanks a lot!

Wolfram

**Comment by edrush** [comment]
Ok, I figured it out, in the model class one needs to:

after_save do
    tire.index.refresh
end

after_destroy do
    tire.index.refresh
end

Thanks! I close this issue.
