### ISSUE TITLE
Creating a custom single index for multiple models

### ISSUE THREAD

**Issue by abrahamD** [karmi/retire#793]
Hi,

I don't know if this was asked already, but I couldn't find any similar question. I am basically trying to index all my ActiveModel objects with a single customized index. It looks something like this:

**Config file:**

``` ruby
INDEX_NAME = "some_index"

# Analysis block repeated in all models
SEARCH_ANALYSIS = {
    :analysis => {
        :filter => {
            "custom_ngram"  => {
                "side"     => "front",
                "max_gram" => 50,
                "min_gram" => 2,
                "type"     => "edgeNGram"
            }
        },
        :analyzer => {
            :name_analyzer => {
                "tokenizer" => "standard",
                "filter" => %w{lowercase asciifolding custom_ngram},
                "type" => 'custom'
            }
        }
    }
}
```

**All model classes:**

``` ruby
class MyModel < ActiveRecord::Base
  default_scope order('name')

  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name INDEX_NAME

  validates :name, presence: true, uniqueness: true

  settings SEARCH_ANALYSIS  do
    mapping do
      indexes :id, :index => :not_analyzed
      indexes :name, :analyzer => 'name_analyzer'
    end
  end
end
```

The result is when I create the index and import my models it doesn't respect the custom settings. This only seems to work when I manually do `Model.tire.index.delete` then `Model.create_elasticsearch_index` and `Model.import`. Then it works for this model only.

I'm sure something  is missing about mixing a single index with custom analyzers but I can't figure it out. Please help.

**Comment by phoet** [comment]
@abrahamD looks good, are you sure everything is configured properly? did you have a look at the tire logs to see what happens exactly.

**Comment by abrahamD** [comment]
Hi @phoet,
My setup was working fine before I customized the search so I guess I can rule out configuration issues. The logs show a normal query. I do get a PhaseExecutionException of some sort that leads me to think the indexing fails and not the actual search. 
Again it works for **one** model if I do the setup manually for that model; but as soon as I try indexing more it just fails to search anything.

Here's the rake task I use for resetting indexes if that's any help

``` ruby
  namespace :single_index do
    desc 'Resets all ActiveRecord model indices'
    task :reset => :environment do

      Rails.application.eager_load!

      Product.tire.index.delete
      Product.create_elasticsearch_index

      ActiveRecord::Base.descendants.each do |model_class|
        next unless model_class.respond_to? :tire

        puts "Resetting #{model_class}"
        model_class.import
      end
      puts 'All indices reset'
    end
  end
```

**Comment by karmi** [comment]
@abrahamD The setup you have must be a bit different I think. Tire, by default, just takes the mapping defined in your class, and when that class is loaded, it tries to create the index.

In your setup, you have to create the index in advance, passing it all settings/mappings you have. Nothing holds you, of course, from gathering the mapping definitions from your models (eg. via the `ActiveRecord::Base.descendants` you use), merging them, and creating the index. Just be careful since Tire tries to create the index when the class is loaded, see #798 for discussion.

The Rake task you have is very similar to the bundled `rake tire:import:all` task.

**Comment by abrahamD** [comment]
So, can I just create the index in the rake task and set my custom analyzer inside it and use it in each individual mapping block in my models? (Like so:)

``` ruby


namespace :single_index do
  desc 'Resets all ActiveRecord model indices'
  task :reset => :environment do

    Rails.application.eager_load!

    Tire.index INDEX_NAME do
      delete
      create :settings => {
        :analysis => {
          :filter => {
            "custom_ngram"  => {
              "side"     => "front",
              "max_gram" => 50,
              "min_gram" => 2,
              "type"     => "edgeNGram"
            }
          },
          :analyzer => {
            :name_analyzer => {
              "tokenizer" => "standard",
              "filter" => %w{lowercase asciifolding custom_ngram},
              "type" => 'custom'
            }
          }
        }
      }
    end

    ActiveRecord::Base.descendants.each do |model_class|
      next unless model_class.respond_to? :tire

      puts "Resetting #{model_class}"
      model_class.import
    end

    puts 'All indices reset'
  end
end
```

**Comment by karmi** [comment]
Yes, but you have to care about the fact that mappings set in individual models via the `mapping` method are ignored.

You can "gather" all the mappings from the models and pass it to index#create method as the `mappings:` argument easily (for some definition of "easily"):

``` ruby
Tire.index('myindex').create mappings: ActiveRecord::Base.descendants.select do |m|
  m.respond_to? :tire
end.reduce({}) do |s,m|
  s[m.tire.document_type] = { properties: m.tire.mapping.to_hash}; s
end
```

**Comment by karmi** [comment]
@abrahamD Please ping me back if something like this would be a sufficient workaround.

**Comment by abrahamD** [comment]
Hi @karmi ,

Thanks for the code snippet! I'll give it a try as soon as possible. Right now, the index is on hold but I'll update when we give it a try.

Thanks again,

Abe

**Comment by abrahamD** [comment]
Hi @karmi,

I gave it a try and it worked fine. Here is my final rake task:

``` ruby
namespace :single_index do
    desc 'Resets all ActiveRecord model indices'
    task :reset => :environment do

      Rails.application.eager_load!

      Tire.index INDEX_NAME do
        delete
        create( :settings => {
            :analysis => {
                :filter => {
                    "custom_ngram"  => {
                        "side"     => "front",
                        "max_gram" => 50,
                        "min_gram" => 2,
                        "type"     => "edgeNGram"
                    }
                },
                :analyzer => {
                    :name_analyzer => {
                        "tokenizer" => "standard",
                        "filter" => %w{lowercase asciifolding custom_ngram},
                        "type" => 'custom'
                    }
                }
            }
        }, :mappings => ActiveRecord::Base.descendants.select do |m|
          m.respond_to? :tire
        end.reduce({}) do |s,m|
          s[m.tire.document_type] = { properties: m.tire.mapping.to_hash}; s
        end)
      end

      ActiveRecord::Base.descendants.each do |model_class|
        next unless model_class.respond_to? :tire

        puts "Resetting #{model_class}"
        model_class.import
      end

      puts 'All indices reset'
    end
  end
```

Thanks for the help.

**Comment by zengjing** [comment]
i got the same problem, i used the way in last comment, but i get the error:
Invalid arguments!
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/activerecord-import-0.3.1/lib/activerecord-import/import.rb:199:in `import'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bundler/gems/tire-1341e9ee3616/lib/tire/tasks.rb:201:in`block (3 levels) in <top (required)>'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bundler/gems/tire-1341e9ee3616/lib/tire/tasks.rb:197:in `each'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bundler/gems/tire-1341e9ee3616/lib/tire/tasks.rb:197:in`block (2 levels) in <top (required)>'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:236:in`block in execute'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:231:in`execute'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/home/zengjing/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/task.rb:161:in`invoke'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:106:in`block in top_level'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:100:in`top_level'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bin/rake:23:in `load'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bin/rake:23:in`<main>'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bin/ruby_noexec_wrapper:14:in `eval'
/home/zengjing/.rvm/gems/ruby-1.9.3-p392@tangor/bin/ruby_noexec_wrapper:14:in`<main>'

plz help!

**Comment by zengjing** [comment]
issue solved.
closed.
