### ISSUE TITLE
Multi-word facets with Persistence

### ISSUE THREAD

**Issue by anthias** [karmi/retire#795]
I'm having trouble similar to http://stackoverflow.com/questions/11917835/multi-word-facets-elasticsearchtire, where the facet terms are being tokenized into single words. I've tried using `analyzer: 'keywords'` or `index: 'not_analyzed'`, as recommended, without any luck. I've also been sure to delete the index after each change. 

``` ruby
  class Issue
    include Tire::Model::Persistence

    property :geographies, analyzer: 'keywords', :default => []

    def self.facet_search(params)
      tire.search(page: 1, per_page: 0) do
        query { string params[:q] } if params[:q].present?
        facet "geographies" do
          terms 'geographies'
        end
      end
    end
  end
```

My results look like:

```
{"term"=>"ward", "count"=>2}, {"term"=>"pd", "count"=>2}, {"term"=>"new", "count"=>2}
```

which are clearly one word terms. Any ideas? Thank you.

**Comment by phoet** [comment]
what exactly do you want to achieve? please give some input and output examples.

i am just guessing, but i think that this might be what you are looking for:

when defining `geographies` as `:type => 'string', :index => :not_analyzed`

and i persist documents like

``` ruby
store :type => 'bar', :geographies => "ward"
store :type => 'bar', :geographies => "ward bord"
```

then i get `ward bord` and `ward` as facets

``` ruby
 @facets=
  {"geographies"=>
    {"_type"=>"terms",
     "missing"=>0,
     "total"=>2,
     "other"=>0,
     "terms"=>
      [{"term"=>"ward bord", "count"=>1}, {"term"=>"ward", "count"=>1}]}},
```

**Comment by karmi** [comment]
@anthias  There is one problem with your setup and one problem in Tire:
1. First, `keywords` is incorrect, it must be: `analyzer: 'keyword'` (singular). This is mostly preferable to `index: 'not_analyzed'`.
2. Tire does not create the index with correct mapping, as it does when you use ActiveModel integration. You have to create your index manually with `Issue.create_elasticsearch_index`.

All should work well then. Note that you can use multifield to have the `geographies` property both analyzed for searches and not analyzed for facets.

**Comment by karmi** [comment]
Actually, a slightly dumb way how to make it work is to force the index being created by wrapping the properties definition in the `mapping` method:

``` ruby
class Issue
  include Tire::Model::Persistence

  mapping do
    property :geographies, analyzer: 'keyword', :default => []
  end

  def self.facet_search(params)
    tire.search(page: 1, per_page: 0) do
      query { string params[:q] } if params[:q].present?
      facet "geographies" do
        terms 'geographies'
      end
    end
  end
end
```

I'll try to have a look about supporting this better or just using this notation in the documentation...

**Comment by anthias** [comment]
This worked perfectly for me after I moved the class from a namespace. I'm not sure if the fix was to remove the namespace (I see your integration tests consider this a special case) or to rename the class. If I run `Issue.index.delete` does that accomplish the same task as renaming the class?

Thank you for the fast response and great gem!

**Comment by anthias** [comment]
One more update... After working with this a bit more, I see what I think my problem was. If I create a new class and just start creating records, the above configuration works. If I then delete that index using `Issue.index.delete` and start creating records, for some reason the terms are not combined properly. If I delete the index using `Issue.index.delete` and then create the index using `Issue.create_elasticsearch_index` as suggested by @karmi , then start loading data everything is fine.

Thanks again.

**Comment by karmi** [comment]
Yes, this is unfortunate and many users bump into this -- when you delete the index, and then start indexing data, the default, "dynamic" mapping is created, ignoring your mapping. For serious use cases, it usually makes sense to wrap the index creation method in a module/class/etc method, so you can create it in tests, via Rake tasks, etc.
