### ISSUE TITLE
Latest Release Breaks STI

### ISSUE THREAD

**Issue by aaronchi** [karmi/retire#80]
I had some trouble tracking this down, but for some reason, in 0.2.0, if add tire to an ActiveRecord model that is inherited via STI, it breaks Rail's ability to correctly set the type column. Search still works, but for some reason, Rails can no longer correctly set the type column for the model when new records are created.

**Comment by karmi** [comment]
Hmm, that is weird -- could you check if STI uses a `_type` method of the model? Previously, both `type` and `_type` methods were defined for the model instance in question.

**Comment by karmi** [comment]
Any news on this?

**Comment by aaronchi** [comment]
I don't believe STI uses _type but something happens when you include Tire::Model::Search that breaks the type handling. I'll take a deeper look sometime next week and see if I can figure out what's going on.

**Comment by aaronchi** [comment]
Ah yes. I believe rails does use _type internally. there may be other stuff going on as well.

In my model:

```
class Image < Asset

end
```

without tire:

```
> Image.first._type
 ←[1m←[35mImage Load (1.0ms)←[0m  SELECT `assets`.* FROM `assets` WHERE `assets`.`type` IN ('Image') LIMIT 1
=> "Image"
```

 with tire:

```
> Image.first._type
←[1m←[35mImage Load (1.0ms)←[0m  SELECT `assets`.* FROM `assets` WHERE `assets`.`type` IN ('Image') LIMIT 1
 NoMethodError: You have a nil object when you didn't expect it!
 You might have expected an instance of Array.
 The error occurred while evaluating nil.[]
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tire-0.3.1/lib/tire/model/search.rb:199:in `block (2 levels) in <class:InstanceMethodsProxy>'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tire-0.3.1/lib/tire/model/search.rb:259:in `_type'
    from (irb):66
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/commands/console.rb:45:in `start'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/commands/console.rb:8:in `start'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:35:in `require'
    from script/rails:35:in `<main>'
```

also:

```
> Image.first
  ←[1m←[36mImage Load (0.0ms)←[0m  ←[1mSELECT `assets`.* FROM `assets` WHERE `assets`.`type` IN ('Image') LIMIT 1←[0m
(Object doesn't support #inspect)
=>
```

**Comment by karmi** [comment]
Hmm, [`_type`](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L195) should not be added when the model has that method already defined. Could you create a Rails template which generates some STI scaffolds etc, so I have less work with recreating that?

**Comment by karmi** [comment]
Any news? Neither `#type` nor `#_type` really should be added to your model on 0.3.

**Comment by aaronchi** [comment]
I added a basic rails app that shows the problem here:
https://github.com/aaronchi/tire-sti

Tire is defined on the Image model which is a child of the Asset model. If you go into console and try to create an image

```
Image.create(:title => 'Something')
```

You get the error I was describing above:

```
 NoMethodError: You have a nil object when you didn't expect it!
 You might have expected an instance of Array.
 The error occurred while evaluating nil.[]
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tire-0.3.2/lib/tire/model/search.rb:199:in `block (2 levels) in <class:InstanceMethodsProxy>'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tire-0.3.2/lib/tire/model/search.rb:259:in `_type'
```

If you move the tire index to the Asset model, creation works fine because it doesn't conflict with the STI type variable.

**Comment by karmi** [comment]
OK, thanks for being stubborn on this. I have found the offending code and moved the the unneccessary methods into `Model::Persistence`. The sample app works now.
