### ISSUE TITLE
Custom mappings not set when models use the same index.

### ISSUE THREAD

**Issue by msonnabaum** [karmi/retire#800]
The following test should fail only the second assertion:

``` ruby
require 'minitest/autorun'
require 'tire'

class WithMapping
  include Tire::Model::Persistence

  index_name 'mapping_test'

  mapping do
    property :title
    property :someint, :type => 'integer'
  end
end

class SecondWithMapping
  include Tire::Model::Persistence

  index_name 'mapping_test'

  mapping do
    property :title
    property :someint, :type => 'integer'
  end
end

describe WithMapping do
  it "should have the correct mapping" do
    WithMapping.create :someint => 10

    type = WithMapping.index.mapping['with_mapping']['properties']['someint']['type']
    assert_equal "integer", type

  end
end

describe SecondWithMapping do
  it "should have the correct mapping" do
    SecondWithMapping.create :someint => 10

    type = SecondWithMapping.index.mapping['second_with_mapping']['properties']['someint']['type']
    assert_equal "integer", type
  end
end

MiniTest::Unit.after_tests do
  WithMapping.index.delete
  SecondWithMapping.index.delete
end
```

This looks like it's because create_elasticsearch_index only gets called when the index doesn't previously exist, so there's nothing to create the mapping for the new document type.

Not sure what the best way to handle that would be.

**Comment by msonnabaum** [comment]
Hmm, I see this is actually covered in the README. Still, this is pretty unexpected behavior.

**Comment by karmi** [comment]
Yes, this is suprising and a bit dumb, no questions about that. For any setup where you want models to share an index, you have to define its settings/mappings and create it in advance anyway. There's simply no way around it. The default behaviour is there simply for convenience.

The dumb part is that `MyModel.index.create` does not create the index with correct mappings, as `MyModel.create_elasticsearch_index` does, simply because the former is just a pointer to a "blank" index instance. The current codebase does not support an obvious solution such as:

``` ruby
i = Tire::Index.new 'heyho', mappings: { properties: { foo: { type: 'string', analyzer: 'snowball' } } }
```

**Comment by karmi** [comment]
@msonnabaum This is also related to #793; I'm wondering what would be best to do here, apart from better documentation. I mean, we could potentially go through the acrobatics of gathering of all the mappings defined in models, merging them, creating the index... but that could get out of hand easily. I think that for a scenario like this, people need to create the index in advance, and we can give them pointers as suggested in the linked issue. What do you think?

**Comment by msonnabaum** [comment]
For this issue, I think it might be reasonable to say that if the index exists and there is a custom mapping defined, we check if a custom mapping exists, and if not, add it.

As a workaround, I just added all my mappings to a single "mapping" method on another object and run this when the application starts:

``` ruby
  # Make sure all the custom mappings exist, and if not, add them.
  def check_mappings
    index_mappings = Tire.index(index_name).mapping
    mappings.each do |type, mapping|
      if index_mappings[type.to_s].nil?
        Tire::Configuration.client.put Tire.index(index_name).url + "/#{type}/_mapping", {
          type => mappings[type]
        }.to_json
      end
    end
  end
```

It doesn't seem like much work though to do this on a per-model basis.

**Comment by karmi** [comment]
> It doesn't seem like much work though to do this on a per-model basis.

It doesn't, but first, that's the kind of acrobatics I'd be wary to get into, and second, there will be a problem with mapping updates -- you would need to wipe out the index and recreate it when a single model changes the mapping in an incompatible way.

On the other hand, maybe we can find a good equilibrium here between "standard stuff works out of the box" and "you have to configure non-standard stuff" with a bit of code...

**Comment by msonnabaum** [comment]
Well, my thinking was, updating mapping is simply not supported, since that's not supported in elasticsearch, whereas adding new mappings to an index is.

Seems sensible for tire to enforce the same limitations.

**Comment by karmi** [comment]
You can, in fact, update mappings (for example adding a new field), but you really need to know what you're doing and frequently that's not the case for some people :) I agree that we _can_ support the behaviour you describe -- it would require some larger refactoring I think, though...

**Comment by msonnabaum** [comment]
Right, you can add a new field but you can't change an existing mapped field. So maybe it'd be ideal to support that case as well.

If you agree that that's a worthwhile approach I can try to put together a PR.

**Comment by karmi** [comment]
@msonnabaum Sorry for the silence -- if you think we can come up with something which is maintainable and doesn't shoot people in the foot, definitely go for a pull request. Though, since Tire has been retired recently, I wonder if we should limit the gem updates to bug fixes and really important improvements...

**Comment by msonnabaum** [comment]
No worries, we can revisit this with whatever get's built on the new lib.
