### ISSUE TITLE
Not being able to iterate over all the result set. 

### ISSUE THREAD

**Issue by mhussain** [karmi/retire#802]
Hello. 

I have a paginated query which returns me a Tire::Results::Collection. I can get the total results counted by doing 

``` ruby
@results = Model.search(:page => n, :per_page => x) do ... end
@results.total_count # or @results.total
```

But if I wanted to iterate over the "entire" result set, and not just the current page e.g. 

``` ruby
@results.each_with_hit {|x,h| h['_score'] > BOOST} 
```

I cannot do that. 

Am I missing something or is that not available at the moment ?

Cheers

**Comment by vonbirdie** [comment]
I think you need to use the scan API that Karmi linked to in #788 if I understand you correctly?

**Comment by karmi** [comment]
@mhussain As suggested, for iterating over large number of results, you should use scan. If you want to just continue paging, you have to increase `page` parameter, getting new `@results` and iterating over them. Can you clarify what kind of problem are you having exactly?

**Comment by mhussain** [comment]
@karmi Thanks for your reply (@luuse as well) 

The result set that my query is returning is basically split in two tiers. One with score of say x and one with score of say y. This is because I am doing custom filter scores on them. I basically need to be able to get a count of both sets. 

I can do a total count on the result set that I get. But in order to find out the count of elements in that set which have a score x , I need to be able to iterate over the entire set, which I cannot do because the query is paginated. 

W.r.t the scan results suggestion, would that not mean that then I am basically querying the index twice ? Once to get the entire set and once to get paginated results ?

**Comment by karmi** [comment]
@mhussain I'm afraid I understand less, not more, now :)

You can't iterate over more result items than the `search` method returns; in other words, you can iterate only over `@results` in your example. Of course, you can set the `page_size` parameter to a higher number, but be aware of performance implications.

If you would like to iterate over _all_ results for a particular query for real, the `scan` API is dedicated to that — but then again, it's not something you should do normally or on each and every user request, etc.
