### ISSUE TITLE
What is the default timeout of a request made using Tire?

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#804]
I couldn't figure this out by searching in the code :\

**Comment by karmi** [comment]
There is no default timeout, it depends on the client used and its configuration.

**Comment by ike-bloomfire** [comment]
Thanks karmi, 
I'm just using the default configuration, can you point me to where I need to be looking?
I just want to know the proper way to configure the default client that is bundled with Tire

**Comment by karmi** [comment]
See https://github.com/karmi/tire/tree/master/lib/tire/http -- also, is the question about the client's timeout or the timeout parameter for ES?

**Comment by ike-bloomfire** [comment]
Looked in there and didn't see an obvious setting ... is curb the default http client?
And yes I'm just trying to set the clients timeout

**Comment by ike-bloomfire** [comment]
So I found out that tire is using the rest-client library as its default (I couldn't get it to use Curb) but you don't pass in a timeout setting for any of the requests you make in tire

https://github.com/karmi/tire/blob/master/lib/tire/http/client.rb

even though it looks like RestClient supports this. Is there a way to hack around this, or should I submit a pull request of some sort?
