### ISSUE TITLE
Document supported versions of elasticsearch

### ISSUE THREAD

**Issue by vonbirdie** [karmi/retire#807]
We're running version 0.20.6 now but does Tire support version 0.90?

**Comment by karmi** [comment]
Yes. Elasticsearch rarely breaks backward compatibility, by the way.

P.S.
You should upgrade to 0.90.x as soon as possible, many optimizations and improvements there, 0.90.3 should be released soon.

**Comment by vonbirdie** [comment]
Ok, thanks!
