### ISSUE TITLE
match_phrase_prefix with Tire

### ISSUE THREAD

**Issue by amejiarosario** [karmi/retire#808]
How can I use match_phrase_prefix (http://www.elasticsearch.org/guide/reference/query-dsl/match-query) with Tire?

**Comment by karmi** [comment]
See integration test, https://github.com/karmi/tire/blob/master/test/integration/match_query_test.rb#L52-L60.

**Comment by amejiarosario** [comment]
Great! This phrase_prefix has the default behavior I need for a search box... I see that I can also combine it with filters. However, I also need to use negative filter or something like this `NOT serial_number:18402909040007`. But, It seems to not be supported. e.g:

``` ruby
Tire.search('access_points') do
    query do
        match :_all, "00:19:92:00:7", type: 'phrase_prefix'
        string "NOT serial_number:2909040007"
    end
    filter :term, domain: 'domain_2'
end
```

Tire produce the following curl (omitting the match clause altogether)

``` bash
# with `string "NOT serial_number:2909040007"'
curl -X GET 'http://localhost:9200/access_points/_search?pretty' -d '{"query":{"query_string":{"query":"NOT serial_number:2909040007"}},"filter":{"term":{"domain":"domain_2"}}}'

#withOUT `string "NOT serial_number:2909040007"'
curl -X GET 'http://localhost:9200/access_point/_search?pretty' -d '{"query":{"match":{"_all":{"query":"00:19:92:00:7","type":"phrase_prefix"}}},"filter":{"term":{"domain":"domain_2"}}}'
```

Do you know if there is a way to make it work? Or if I can use negative filters? Or If can make a `query{string(...)}` behaves like a match_phrase_prefix?

**Comment by karmi** [comment]
Preferably, use a filter for a field like that, and a `filtered` query, not top level filter (unless you do facets). Please see the integration tests.

**Comment by amejiarosario** [comment]
boolean's `must_not` are the negatives filters :)

Solution:

``` ruby
Tire.search('access_points') do
  query do
      boolean do
          must { match :_all, "00:19:92:00:7", type: 'phrase_prefix' }
          must_not { term :serial_number, '2909040007' }
      end
  end
  filter :term, domain: 'domain_2'
end
```

thus,

``` bash
curl -X GET 'http://localhost:9200/access_points/_search' -d '{"query":{"bool":{"must":[{"match":{"_all":{"query":"00:19:92:00:7","type":"phrase_prefix"}}}],"must_not":[{"term":{"serial_number":{"term":"2909040007"}}}]}},"filter":{"term":{"domain":"domain_2"}}}'
```

**Comment by karmi** [comment]
> boolean's must_not are the negatives filters :)

Sure, but filters are more performant, notably on a field like `serial_number`.

**Comment by amejiarosario** [comment]
For performance sake... I tried in the code above to use `filter`, but it doesn't work inside `must_not` block, so I ended up using `term` as you saw. Could you please provide an example how will `must_not { term :serial_number, '2909040007' }` be with filters?

**Comment by karmi** [comment]
Have you had a look at the filtered query integration tests?

**Comment by amejiarosario** [comment]
Ok. I used filter :not with filtered and it worked too. For future reference, how do I know which ones has better performance?

``` ruby
# Using Filtered
Tire.search('access_points') do
  query do
    filtered do
      query { match :_all, "00:19:92:3", type: 'phrase_prefix' }
      filter :not, { term: { serial_number: "4212050043" } }
    end
  end
  filter :term, domain: 'domain_2'
end.results

# Using Boolean
Tire.search('access_points') do
  query do
    boolean do
      must { match :_all, "00:19:92:3", type: 'phrase_prefix' }
      must_not { term :serial_number, '4212050043' }
    end
  end
  filter :term, domain: 'domain_2'
end.results
```
