### ISSUE TITLE
Search using multiple es clusters

### ISSUE THREAD

**Issue by vamsi-krishna-E0029** [karmi/retire#811]
I would like to use multiple es clusters. If I create another cluster, of course with unique cluster names in each machine. How do I search, update or actually connect with multiple clusters using Tire?

**Comment by karmi** [comment]
Hi, currently Tire does not support connection to multiple ES clusters in one Ruby process. There is an undergoing effort to improve the Ruby client significantly.

**Comment by vamsi-krishna-E0029** [comment]
It is a multitenant app with an account per tenant. We created 6 indices one for each searchable model. Once an account is created, we create 6 aliases(one for each model) with routing and filter on account id. All the search, update, delete operations are done on these aliases.

We actually have a setup which consists of data nodes and non data nodes. The non data nodes are used for http requests. We use HaProxy before the non data nodes. Now we want to add another cluster and add all new accounts from now to the new cluster.

Is there any ugly way to do the same? How does the tire connect to the elasticsearch cluster?
Tire version: 0.4.3 with some custom tweaks and additional changes to support rails 2.3.x. So, it is difficult to upgrade at this stage.
Elasticsearch version: 0.90.1

**Comment by karmi** [comment]
This is really not possible with Tire, sadly. The new Ruby client does support that, of course.
