### ISSUE TITLE
Adding support for index-queries?

### ISSUE THREAD

**Issue by johvet** [karmi/retire#813]
I ran accross a problem where I need to execute a search based on two indices. That works fine using Tire.search ['index_1', 'index_2']. But then I got stuck as I had to apply different queries on each index. ES supports an index-query to allow exactly that, but I couldn't figure out how to accomplish this using Tire. Is there any sort of roadmap to get there?

(http://www.elasticsearch.org/guide/reference/query-dsl/indices-query/)

Keep up the good work!

**Comment by karmi** [comment]
Hi, no support for the `indices` query in Tire, though I imagine it would be a simply (monkey)patch on your side.

Maybe you could use the [`multi_search`](https://github.com/karmi/tire/blob/master/test/integration/multi_search_test.rb) support?
