### ISSUE TITLE
Need example of advanced search

### ISSUE THREAD

**Issue by kjeremy** [karmi/retire#815]
I think a working example of an 'advanced search' would be really useful.  I'm struggling with the concept.  For instance: a series of checkboxes for selecting tags in a blog post or something of that nature.  I've yet to come across an example of this for tire.  Something similar to linkedin's advanced search would be really useful.

**Comment by brupm** [comment]
I can understand the frustration when you first start using a new library. However this is not a valid issue. There are plenty of example in the readme under Usage: https://github.com/karmi/tire/blob/master/README.markdown#usage

Moreover I have a repos that contains a few experiments you may find useful depending on what you are trying to do. Each ruby file runs independently and is useful when trying to troubleshoot/understand particular aspects of Tire/Elasticsearch https://github.com/brupm/elasticsearch_ruby
