### ISSUE TITLE
after_index callback for activemodel

### ISSUE THREAD

**Issue by joshcutler** [karmi/retire#819]
I have looked through the code and docs and do not see anything that looks like an event that fires after indexing on a model is complete.  Am I missing something?

If not, I think that this feature would be a useful addition.

Thanks.

**Comment by joshcutler** [comment]
Doh.  This is literally implemented exactly as requested.  I need more coffee.

**Comment by karmi** [comment]
@joshcutler No, the code in question: https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L144 is quite messy and ugly -- it's the code fault, not yours :)
