### ISSUE TITLE
aliasing types?

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#823]
is it possible to alias types in elastics search so that 

```
curl localhost:9200/content/blog_post/2939
```

and

```
curl localhost:9200/content/post/2939
```

become equivalent?

**Comment by karmi** [comment]
No, only indices can be aliased. This would be quite easy with a proxy in front of ES, though.

**Comment by ike-bloomfire** [comment]
Hmmm, I had no idea that could work
Are you saying that would make it so that 

```
Tire.index('content').remove("blog_post", object.id)
```

would be the same as

```
Tire.index('content').remove("post", object.id)
```

 ... any pointers/links you can give will be useful in figuring this out.

**Comment by karmi** [comment]
Yes, you could rewrite the URL in this fashion. See eg. http://wiki.nginx.org/HttpRewriteModule, https://blog.engineyard.com/2011/useful-rewrites-for-nginx, etc.

**Comment by ike-bloomfire** [comment]
Thank you Karel!
