### ISSUE TITLE
Exclamation point breaks field queries

### ISSUE THREAD

**Issue by kjeremy** [karmi/retire#828]
I'm hitting an issue similar to http://elasticsearch-users.115913.n3.nabble.com/Exclamation-point-breaks-field-queries-td3678504.html when I include exclamation marks and other special characters:

[REQUEST FAILED] curl -X GET 'http://localhost:9200/people/person/_search?load=true&size=20&pretty' -d '{"query":{"bool":{"must":[{"query_string":{"query":"software!"}}]}},"sort":[{"first":"asc"}],"facets":{"division":{"terms":{"field":"division_id","size":10,"all_terms":false}}},"size":20}'
  Search (8.2ms)  {"query":{"bool":{"must":[{"query_string":{"query":"software!"}}]}},"sort":[{"first":"asc"}],"facets":{"division":{"terms":{"field":"division_id","size":10,"all_terms":false}}},"size":20}
Completed 500  in 12ms

Tire::Search::SearchRequestFailed - 500 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[G1F6mXc0QjyJ9blwut1uyw][people][2]: SearchParseException

That post suggests that there is a handy perl method for resolving this: https://metacpan.org/module/ElasticSearch::QueryParser

I've looked but can't find a similar function in tire.

**Comment by karmi** [comment]
You have to escape the `!` character -- `Tire.search('') { query { string 'software\!' } }.results`, see http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping%20Special%20Characters
