### ISSUE TITLE
problem trying to use Curb as http client

### ISSUE THREAD

**Issue by ike-bloomfire** [karmi/retire#829]
I have curb in my gem file and I've specified that I want it as my http client by doing the following

```
Tire.configure do
  client Tire::HTTP::Client::Curb
end    
```

but I keep getting this error when I try to start my app

```
uninitialized constant Tire::HTTP::Client::Curb (NameError)
```

**Comment by karmi** [comment]
See the file, you have to require the file as well.

**Comment by ike-bloomfire** [comment]
require it where?

I put it at the top of tire.rb ... same error

**Comment by ike-bloomfire** [comment]
finally figured it out for anyone that might need help with this

```
require 'curb'
require 'tire/http/clients/curb'
Tire.configure do
  client Tire::HTTP::Client::Curb
end
```

**Comment by HenleyChiu** [comment]
Thanks ike-bloomfire for the very explicit solution.
