### ISSUE TITLE
Cannot index virtual attributes

### ISSUE THREAD

**Issue by jfalk** [karmi/retire#83]
In my User model I have the following mapping specified:

mapping do
    indexes :id, :type => 'integer', :index => :not_analyzed
    indexes :lat_lon, :type => 'geo_point'
  end

lat_lon is just a virtual attribute that takes the actual latitude and longitude attributes and puts them in the correct geo_point format.  However, it doesn't seem to try and index this (I know I can get around this by overriding to_indexed_json).  Is there anyway that this can be done without overriding to_indexed_json though?  Or is there an easier way to index geo_points?

**Comment by karmi** [comment]
Hey Jason,

no, you have to define the serialization in `to_indexed_json`; I've taken the hint and updated the documentation so it gives more examples.

_Tire_ has different approach then the Sphinx and Solr gems, and divides the mapping and serialization declarations. With `mapping`, you define how your model JSON serialization should be understood by ES, with `to_indexed_json`, you define what _is_ this serialization.

Is that OK for your use case?

**Comment by signpost** [comment]
Yea, this is what I wound up doing anyways.  I made the assumption (incorrectly) that it used your mapping to dictate some of the serialization unless you used to_indexed_json.  Your explanation though makes a lot of sense and cleared things up for me.  Keep up the good work!
