### ISSUE TITLE
Using Tire for M to N Relation

### ISSUE THREAD

**Issue by yashshah** [karmi/retire#835]
I have M to N association. To make my problem simple to understand, i am explaining using Users and Articles model. User will have many Articles and Article can also have many Users.  I need to search Article Title of all the Articles which belong to current User.

``` ruby
class User < ActiveRecord::Base
  ....
  has_many :articles
end
```

``` ruby
class Article < ActiveRecord::Base
  ....
  has_many :users
end
```

I cannot find any reference/wiki for the similar problem. I will be highly obliged if you can help me in implementing search in my use case.

**Comment by karmi** [comment]
Please see http://stackoverflow.com/questions/11692560/elasticsearch-tire-and-nested-queries-associations-with-activerecord/11711477#11711477
