### ISSUE TITLE
Updates and inserts are silently failing.

### ISSUE THREAD

**Issue by sandeepbeit** [karmi/retire#849]
After adding new field in elastic search index updates and inserts started failing.
Status of cluster is green and there is no information in log.
We tried restarting elastic search.
Index status seems fine
Also tried to close and re-open the index but nothing helped.
We are using tire gem to interact with elastic search.
We created new index and same code works fine with new index.
I didn't find any help on internet regarding this issue.
Can some please help us to troubleshoot this issue.

**Comment by karmi** [comment]
Try `Tire.configure { logger STDERR, level: "debug" }` and see what is being sent and returned from Elasticsearch.

**Comment by sandeepbeit** [comment]
Using the logger in i can get the error message.
{"index":{"_index":"bw-listings","_type":"listing","_id":"ap-310186","error":"MapperParsingException[Failed to parse [standout]]; nested: JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors\n at [Source: [B@2c9278b0; line: 1, column: 3690]]; "}}

This is corresponding to one of the new boolean attribute we added to our index.

this help me to debug this issue.

**Comment by sandeepbeit** [comment]
I have the resque block why  it is not getting captured into it?

**Comment by karmi** [comment]
You have to re-create your index (drop, create with mapping, load all data) when you change the mapping in an incompatible way. Tire comes with Rake tasks and API for those.

> I have the resque block why it is not getting captured into it?

I don't understand.

**Comment by sandeepbeit** [comment]
Also on more thing. when I'm using Tire.configure { logger STDERR, level: "debug" }, get requests are getting logged into my logs but response coming back from ES is not getting logged in log and it raises below mentioned exception any idea?

  LoadError: no such file to load -- {"took":7,"items":[{"index":{"_index":"***_","_type":"**__","_id":"_***","error":"MapperParsingException[Failed to parse [standout]]; nested: JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors\n at [Source: [B@6e64b4f8; line: 1, column: 405]]; "}}]}

Regarding the "MapperParsingException" i think it is problem in ES core code.Instead of return success message and within body the error message.It should throws exception.

One question if ES returned error code/Exception we should raise an Exception in Tire gem so that we know something went wrong rather than silently failing.

**Comment by karmi** [comment]
> One question if ES returned error code/Exception we should raise an Exception in Tire gem so that we know something went wrong rather than silently failing.

Yes, that's one of the pain points in Tire, which should definitely be handled better in [the new Ruby client](https://github.com/elasticsearch/elasticsearch-ruby).

The error you see seems to be related to sending `false` to a property which accepts numeric values.
