### ISSUE TITLE
`settings` in a model raises error

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#85]
I created a `settings` block, and I got this error:

```
NoMethodError: undefined method 'settings' for #<Class:0x106b28930>
```

Looking at the source of the 0.2.0 gem, I couldn't find any `def settings` method. However, your master branch has it. You may need to publish a new release :)

**Comment by karmi** [comment]
Yeah, that's just in master, still. [0.2.0 release](https://github.com/karmi/tire/blob/v0.2.0/README.markdown) has no such thing :) Will release 0.2.1 soon.
