### ISSUE TITLE
Rake task exiting with no errors before completion

### ISSUE THREAD

**Issue by simonmorley** [karmi/retire#851]
I'm attempting to index a couple of million rows via the rake task:

```
rake environment tire:import CLASS='Accnt' RAILS_ENV=production FORCE=true PARAMS={per_page:1000}
```

Elasticsearch is installed remotely. In the ES logs, I can see the following:

```
[2013-08-24 16:56:43,705][INFO ][cluster.metadata         ] [i-6bd33e24] [accnt] deleting index
[2013-08-24 16:56:43,877][INFO ][cluster.metadata         ] [i-6bd33e24] [accnt] creating index, cause [api], shards [5]/[1], mappings [accnt]
```

I get the following output on the Rails server I'm running the task:

```
[IMPORT] Deleting index 'accnt'
[IMPORT] Creating index 'accnt' with mapping:
{
  "accnt":{
    "properties":{
      "id":{
      "type":"integer"
 ...
```

Followed by:

```
Acct:         1% |                                                          | ETA:  00:25:28
```

And then it exits with no errors. CPU is around 58%, it's only a small EC2 instance. Load is less than 80% average over 15 mins.

The ES server is 0.90.3 and Tire version 0.6.0

Is this likely to be a memory issue or is there something else I can try here?

**Comment by karmi** [comment]
Hmm, this could indeed be memory related. Despite much effort to make the import task robust, it might overload a small system. If you're on EC2, can you maybe try it temporarily on a bigger machine such as `m2.xlarge` or `m2.2xlarge` to see whether it proceeds further?

**Comment by mrkaspa** [comment]
I got the same error here you can test http://107.22.43.154:9200/ the import doesn't work but it doesn't throw errors @karmi
