### ISSUE TITLE
How to monkey patch to avoid 'Couldn't find all users with IDs', found 9 results was looking for 10

### ISSUE THREAD

**Issue by inspire22** [karmi/retire#852]
Sometimes my servers lose a connection, or there's a database issue, and a rogue row gets left in ES, that is not in my database.  It's not terribly important for me.

Ideally I'd rescue it to delete the missing row and return the result.

Initially it sounds simpler to just monkey-patch around raising this error, to silently  return whatever results could be found.  

Any tips where in the source to start looking?  Load: true is difficult to search for...

Thanks for a great project :)

**Comment by inspire22** [comment]
In case anyone else has this problem, this seems to work as an obvious workaround:

```
 ids = request.results.to_a.collect {|a| a['id']}
 myclass.where(:id => ids)
```

**Comment by Awea** [comment]
To force deletion on ES with Tire you can use something like this :

``` ruby
MyModel.index.remove('my_model', object_id)
MyModel.index.refresh #without I can't get it work
```

This help you ?

**Comment by inspire22** [comment]
That unfortunately requires the more-complicated step of finding which row was missing.

I'm still lobbying for this "Couldn't find al" "feature" to be removed.

**Comment by karmi** [comment]
Hi, the hook point for the monkeypatch is the [`Tire::Results::Collection#__find_records_by_ids`](https://github.com/karmi/retire/blob/master/lib/tire/results/collection.rb#L155-L157). Just override it by using `where(ids:...)` instead of `find(ids)` for ActiveRecord. Please ping me if you'd have trouble with it.

**Comment by karmi** [comment]
Related: #810
