### ISSUE TITLE
null field included in to_json does not show up in results

### ISSUE THREAD

**Issue by monfresh** [karmi/retire#856]
Hi,

For some reason, when I have this:

``` ruby
def to_indexed_json
  self.to_json(:include => {
    :address => { :except => [:_id] }
  })
end
```

when the `address` field is `null`, it doesn't show up in the search results, even though other null fields do show up.

If I have this:

``` ruby
{
 :id => id,
 :name => name,
 :address => address
}.to_json
```

then `address` shows up when it is null.

What could be causing this discrepancy?

I'm using Rails 3.2.13 with Mongoid 3.1.4 and `address` is `embedded_in :location`.

**Comment by monfresh** [comment]
On the flip side, is there an easy way to globally prevent any fields whose value is nil from being output in the JSON?

**Comment by monfresh** [comment]
There's most likely a more elegant way to do this, but this is how I removed fields with nil values from the JSON output:

``` ruby
def to_indexed_json
  hash = self.as_json(
    :except => [:organization_id], :methods => ['url'],
    :include => {
      :services => { :except => [:_id, :location_id, :created_at] },
      :contacts => { :except => [:_id] }
    }
  )
  remove_nil_fields(hash,["contacts","services"])
  hash.to_json
end

# Removes nil fields from hash
#
# The main hash passed to the method is a JSON representation
# of a Model including associated models (see to_indexed_json).
# The fields passed are the associated models that contain
# nil fields that we want to get rid of.
# Each field is an Array of Hashes because it's a 1-N relationship:
# Location embeds_many :contacts and has_many :services.
# Once each associated model is cleaned up, we removed nil fields
# from the main hash too.
#
# @param obj [Hash]
# @param fields [Array] Array of strings
# @return [Hash] The obj Hash with all nil fields stripped out
def remove_nil_fields(obj,fields=[])
  fields.each do |field|
    obj[field].each { |h| h.reject! { |_,v| v.blank? } }
  end
  obj.reject! { |_,v| v.blank? }
end
```

**Comment by karmi** [comment]
I don't understand this issue well, can you clarify what you mean by "doesn't show up in the search results"? I think this is related to how AcitveSupport's `to_json` handles `nil` values?

**Comment by monfresh** [comment]
What I mean by "doesn't show up" is that the field is not present in the JSON output. Here's a sample Tire search results output for an entry that has at least one `contact`:

``` JSON
[
{
_id: "521d33331974fcdb2b001f45",
address: {
  city: "Palo Alto",
  state: "CA",
  street: "425 Hamilton Avenue",
  zip: "94301"
},
contacts: [
{
  _id: "521d33331974fcdb2b001f46",
  name: "Philip Dah",
  title: "Director"
}
],
name: "Downtown Palo Alto Food Closet",
url: "http://ohanapi.herokuapp.com/api/locations/521d33331974fcdb2b001f45",
id: "521d33331974fcdb2b001f45",
_score: null,
_type: "location",
_index: "production-ohana_api",
_version: null,
sort: [
1377645363000
],
highlight: null,
_explanation: null
}
]
```

If an entry does not have any `contacts`, I want to be able to specify whether or not the `contacts` field is present in the output. If I don't want it to "show up", I want the output to be like this:

``` JSON
[
{
_id: "521d33331974fcdb2b001f45",
address: {
  city: "Palo Alto",
  state: "CA",
  street: "425 Hamilton Avenue",
  zip: "94301"
},
name: "Downtown Palo Alto Food Closet",
url: "http://ohanapi.herokuapp.com/api/locations/521d33331974fcdb2b001f45",
id: "521d33331974fcdb2b001f45",
_score: null,
_type: "location",
_index: "production-ohana_api",
_version: null,
sort: [
1377645363000
],
highlight: null,
_explanation: null
}
]
```

I don't want it to appear in the output with an empty array, like this:

``` JSON
[
{
_id: "521d33331974fcdb2b001f45",
address: {
  city: "Palo Alto",
  state: "CA",
  street: "425 Hamilton Avenue",
  zip: "94301"
},
contacts: [],
name: "Downtown Palo Alto Food Closet",
url: "http://ohanapi.herokuapp.com/api/locations/521d33331974fcdb2b001f45",
id: "521d33331974fcdb2b001f45",
_score: null,
_type: "location",
_index: "production-ohana_api",
_version: null,
sort: [
1377645363000
],
highlight: null,
_explanation: null
}
]
```

**Comment by karmi** [comment]
Sorry, I still struggle to understand what exactly is the problem. I think you either want to remove the `contacts` property from your document when you're indexing it, or removing it from the returned documents when the property is empty. How can I help you here?

**Comment by monfresh** [comment]
That is correct. My question is, is there a better way to remove the property from the returned documents than the one I have [here](https://github.com/karmi/retire/issues/856#issuecomment-23639650)?

**Comment by dzhlobo** [comment]
Empty array isn't really nil. @monfresh I think you can simply don't store blank fields. You just need to override `#to_indexed_json` in model. Look at current realization (https://github.com/karmi/retire/blob/master/lib/tire/model/search.rb#L167-190) and add filtering blank fields.

**Comment by karmi** [comment]
@monfresh This somehow went by. I think you might have solved the problem in the meantime... Indeed, the only way would be to have some custom logic within `to_indexed_json`.
