### ISSUE TITLE
ability to chain sorts

### ISSUE THREAD

**Issue by iwarshak** [karmi/retire#858]
is it possible to chain sorts like so:

```
sort { by(:created_at, order: 'desc')  }
sort { by(:_geo_distance, location: "#{lat}, #{lng}", order: 'asc')  }
```

It seems that the last sort wins

**Comment by brupm** [comment]
Sure:

``` ruby
sort do
  by :name, "desc"
  by :created_at, "desc"
end
```

**Comment by iwarshak** [comment]
Ok, so I guess you can't just chain the commands?

**Comment by karmi** [comment]
@iwarshak The solution by @brupm is indeed correct! That should work exactly as you want.
