### ISSUE TITLE
Toward an inheritable index_prefix, for great justice

### ISSUE THREAD

**Issue by ches** [karmi/retire#859]
To wit, http://git.io/OvTLwA

Hi @karmi,

This is something that's been marked as a TODO in Tire source for awhile, I've been devising gross hacks to work around it for awhile, and it's finally given me enough of an itch to try to spark a discussion.

Our scenario is that we have a decoupled subsystem using Tire, able to run and be tested in isolation, that is also loaded into a larger system that independently uses Tire as well (at this time a Rails app, FWIW).

We fight tedious load ordering issues because we want the subsystem, loaded as a gem by Bundler, to share the same prefix configuration as the parent app when they're run together. But, because `Tire::Model::Search.index_prefix` is statically set as module state, it's the default of nil when Bundler loads a gem, before the parent app's initializers run to set configuration. Using `index_prefix` as a declarative classmethod on models in the subsystem isn't practical, since it also functions standalone -- the prefix needs to be configurable for either usage. So right back to the problem of how to set up configuration state before classes load.

We manage to hack around this using `autoload` to lazy-load things after we've had a chance to set `Tire::Model::Search.index_prefix`, but it's very brittle to refactoring and it just shouldn't be this hard.

We also have an index and type name setup that follows a module/class hierarchy, for which we could remove some hacks if `index_name` had `class_attribute` semantics, but that's less painful to work around at this point than the prefix matter.

Hope that all makes some sense, I can extract some code examples if it helps.
### Possible Improvements

I'd like to help with this. You're pretty opinionated about changes to Tire, and the integration test suite is a bear to run, so I'd prefer to seek your input before hacking away and sending a pull request. Two possibilities in mind:
1. This.
   
   > TODO: Maybe this would be more sane with ActiveSupport extensions such as `class_attribute`?
   
   Plus :100: The behavior of `class_attribute` is pretty much exactly what I want, personally. It doesn't seem like it'd be a lot of work...
   
   I know there's been some discussion in the past about reliance on ActiveSupport, but if you want to reduce it you can do selective requires or copy an implementation into Tire.
2. Possibly less invasive but still a big help to me I think: allow `index_prefix`, when used as a declarative classmethod, to be given a callable or a symbol that references a method.

Thoughts or suggestions?

**Comment by karmi** [comment]
Hi @ches, sorry for the long delay. Thanks for the great explanation!

As you might guess, at the moment Tire should receive only mild treatment, and this fix does look like one. Since we cannot easily not depend on ActiveSupport right now (the whole ActiveModel -> ActiveSupport thing), just using `class_attribute` is really fine with me.

Can you have a shot at the implementation in a separate pull request? Closing this issue in favor of that.
