### ISSUE TITLE
Ability to index to multiple indexes

### ISSUE THREAD

**Issue by brupm** [karmi/retire#861]
This may be a long shot but I wanted to start a discussion around it. 

When performing a reindex which requires mapping modifications one needs to truncate and reindex. In order to avoid an empty or partial index while it's being generated I create a new index as such `users_20130905092742` and begin adding the documents to the index. Once the reindex is done I then swap the alias `users` from my old index into this new one. The application does not have to know anything about this as it always looks for an index called `users` and it finds based on the alias. 

The problem with this approach is if DB records change while the new index is being created, the application will index to the old index. When the alias is swapped and the app starts querying the new index, the DB changes will not be present.

I know it is possible to search multiple indexes at once. I would like to be able to index to multiple indexes as well (on a per doc basis).

Each time update_index is called, if enabled, it should index to the current index it knows about `users` as well as the new one being created `users_20130905092742` I considered modifying the update_index method in tire/model/search.rb to account for this but wanted your opinions first.

This would allow for 100% zero downtime, zero data loss, index swap.

**Comment by brupm** [comment]
Perhaps this is something to consider for the new elasticsearch ruby client? https://github.com/elasticsearch/elasticsearch-ruby

**Comment by karmi** [comment]
The new Ruby client will have a Rails/ActiveRecord integration for sure!

As for this particular issue, you'd want to "split" the indexing into two separate indices? On the one hand, I don't see a nice "generic" solution for this, on the other hand, the new integration should provide you with much more powerful tools to achieve something like this.

**Comment by karmi** [comment]
I think the only way how to handle this would be to leave it to the user (pseudo-code):

``` ruby
class Article < ActiveRecord::Base
  include Future

  after_save do
    self.index.save self
    Index.new(self.index.name+'v2').save self
  end

  after_destroy
    # ...
  end
end
```
