### ISSUE TITLE
Sorting on nested fields

### ISSUE THREAD

**Issue by niuage** [karmi/retire#863]
http://www.elasticsearch.org/guide/reference/api/search/sort/ (search for `sorting within nested objects`)

How can I do that using Tire, especially the `nested_filter` part? Is it supported?

Thanks.

**Comment by niuage** [comment]
Looked at the code, and it seems like it's not possible yet, so I just hacked a solution for now.

**Comment by karmi** [comment]
This is indeed true, I guess it's something which will be sorted (no pun intended :) in the [new Ruby client](https://github.com/elasticsearch/elasticsearch-ruby).
