### ISSUE TITLE
How to index associated data and apply filters?

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#87]
I have an album and I want users to be able to find albums when they type in the artist's name. I know I can do something like this:

```
def to_indexed_json
  :name => name,
  :artist_name => artist.name
end
```

However, **how do I apply filters/analyzers to those?**

If there's a way to determine what association's methods to index via the `indexes` methods in the `mapping` block, then I could use that. However, I can't seem to find a way to do that.

**Comment by karmi** [comment]
`mapping` serves only for setting up your mapping for ElasticSearch (things like analyzers), `to_indexed_json` serves for serialization of your data for ElasticSearch. (As opposed to other search libraries, eg. for Sphinx or Solr, which combine these).
