### ISSUE TITLE
newrelic_rpm gem breaks curb client

### ISSUE THREAD

**Issue by vhyza** [karmi/retire#872]
Newrelic [added instrumentation](https://github.com/newrelic/rpm/blob/master/CHANGELOG#L43) for Curb which unfortunately breaks `http_put` method https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/curb.rb#L49

**Comment by felixbuenemann** [comment]
According to the newrelic_rpm changelog, this was fixed in v3.6.9 of the gem.
