### ISSUE TITLE
Syntax: facet_filter, value_script and terms_stats?

### ISSUE THREAD

**Issue by fabien7337** [karmi/retire#873]
Hi,

I have something like that, working:

```
facet 'advanced_stats', facet_filter: { terms: { :brand_ids => params[:brand_ids] } } do
  terms_stats :brand_ids, [:views_count], size: 4, order: 'total'
end
```

But it's a value_field and I want to use value_script, I don't succeed to do that :(

```
facet 'advanced_stats', facet_filter: { terms: { :brand_ids => params[:brand_ids] } } do
  terms_stats 'advanced_stats', { key_field: :brand_ids, value_script: Video.advanced_stats_value_script(params[:advanced_stats]), size: 4, order: 'total' }
end
```

doesn't work ! Please HELP :'(

Thanks,

Fabien

**Comment by fabien7337** [comment]
Okay for the record, you need to specified nil for value_field and the add the value script :+1: 

```
facet 'advanced_stats', facet_filter: { terms: { :brand_ids => params[:brand_ids] } } do
  terms_stats :brand_ids, nil, THE_VALUE_SCRIPT, size: 4, order: 'total'
end
```

@karmi no better solution right?

**Comment by karmi** [comment]
@zywx No, unfortunately, that's the effect of the method signature. BTW, that's why the new client uses "single Hash arguments" as pseudo-named-arguments approach.

**Comment by fabien7337** [comment]
Okay thanks
