### ISSUE TITLE
DSL for new function_score

### ISSUE THREAD

**Issue by brupm** [karmi/retire#874]
Elasticsearch 0.90.5 includes the new [function_score](https://github.com/elasticsearch/elasticsearch/issues/1170#issuecomment-22819670 functionality) see [more details](https://www.google.com/search?q=function_score+elasticsearch&oq=function_score+elasticsearch&aqs=chrome..69i57j69i60l3j69i61j69i60.3063j0&sourceid=chrome&ie=UTF-8). 

This would be a very valuable addition to Tire. I have two questions. 
1. Should it go in tire or tire-contrib ([custom_filters_score](https://github.com/karmi/tire/blob/master/test/integration/custom_filters_score_queries_test.rb) is in tire and this is very similar).
2. Should it be based on the custom_filters_score given how similar they are? 

@karmi what are your thoughts?

**Comment by emptyflask** [comment]
I'm implementing this on a project now, and IMHO it should go into Tire.

Meanwhile, this kind of thing works:

``` ruby
def randomized(seed)
  Tire.search("#{Tire::Model::Search.index_prefix}_ideas", query: {
    function_score: {
      query: { match_all: {} },
      random_score: { seed: seed }
    }
  }).results
end
```

**Comment by karmi** [comment]
Hi, I think this crosses the line for "new features" on Tire -- the [new Ruby client](https://github.com/elasticsearch/elasticsearch-ruby) does support all features, though not via a proper Ruby DSL yet. It is certainly something which should go to the future `elasticsearch-dsl`. 

@emptyflask If you have any examples etc, please drop them here for record!
