### ISSUE TITLE
if value does not miss, check valid condition.

### ISSUE THREAD

**Issue by RobDoan** [karmi/retire#876]
I have deleted_at column. And I want to search records which have deleted_at is null or deleted_at in greater than now. I try to do like this:

`filter :or, [missing: { field: 'deleted_at',  null_value: true }, range: { deleted_at: { gte: Time.zone.now } } ]`

but it does not work, If I remove range condition, it will work.

**Comment by karmi** [comment]
Can you configure logging to see how this search is sent to ES? Normally, the syntax is a bit different: https://github.com/karmi/retire/blob/master/test/integration/filters_test.rb#L39-L40
