### ISSUE TITLE
facets with mongoid and tire/elasticsearch

### ISSUE THREAD

**Issue by hyperrjas** [karmi/retire#879]
Model user:

```
class User
  include Mongoid::Document
  field :city, :type => String
  has_one: car
end
```

Model car:

```
class Car
  include Mongoid::Document

  belongs_to: user
  field: :name, :type => String

  def self.search(param)
    tire.search :load => true do
    query do
      boolean do
        must { term :user_city, params[:user_city] } if params[:user_city].present?
      end
    end
    filter :term, user_city: params[:user_city] if params[:user_city].present?
    facet "cities" do
      terms :user_city
    end
  end

  def user_city
   user.city
  end

end
```

This is my filter with facet `user_city`

```
 <% @cars.facets['cities']['terms'].each do |facet| %>
  <li>
    <%= link_to_unless_current User.where(city: facet['term']).first, params.merge(user_city: facet['term']) %>
    <% if params[:user_city] == facet['term'].to_s %>
     (<%= link_to "Remove", params.merge(user_city: nil) %>)
    <% else %>
      (<%= facet['count'] %>)
    <% end %>
  </li>
<% end %>
```

If I inspect `<%= @cars.facets['cities']['terms'].inspect %>`, I get a empty result `[]`

Once I'd made a search, I'd like to filter by the city of the vehicle owner. 

**How I can do it?**

**Remember I am using MongoId instead of Activerecord**

**Comment by karmi** [comment]
The syntax and setup are correct, this should work. I've added an integration test just to cover this case. Are you sure you're not running this against empty index, not refreshed index (eg. in tests), etc?

**Comment by hyperrjas** [comment]
Thanks. I'm using this gem for autocomplete https://github.com/leschenko/elasticsearch_autocomplete. All facets with car fields does works fine except this.

The unique requirement of this gem is add fields like this:

```
class Car
  include Mongoid::Document
  ac_field :name, :user_city, :skip_settings => true
  def self.ac_search(param)
   .
   .
   .
  end
  def user_city
    user.city
  end
end
```

I have reindex the Car model with:

```
bundle exec rake environment tire:import CLASS=Car FORCE=true
```

What am I missing or what I'm doing wrong?

Thanks!

**Comment by karmi** [comment]
Can you submit an issue at the `elasticsearch_autocomplete` repo as well, please?

Also, are you sure your model is properly serialized into JSON? Ie. `user_city` is working etc?

**Comment by hyperrjas** [comment]
Thanks, I fixed the problem with:

```
def to_indexed_json
  to_json(methods: [:user_city])
end
```

Thanks!
