### ISSUE TITLE
Add ability to specify the routing of a document

### ISSUE THREAD

**Issue by changa** [karmi/retire#88]
It would be great if we could specify the [routing](http://www.elasticsearch.org/guide/reference/api/search/index.html) when indexing a Tire::Model.

**Comment by karmi** [comment]
Yeah. How should the interface look like? Options for the `search` method or part of the DSL?

(BTW, I think it would be much nicer to have the [`search_type`](http://www.elasticsearch.org/guide/reference/api/search/request-body.html) exposed.)

**Comment by changa** [comment]
Hi (and sorry for the lag) !
I guess it would be fine as options to `search`.
Concerning `search_type`, you're right, it certainly could prove useful.

(And BTW, thanks a lot for this gem, it rocks :-)

**Comment by benzheren** [comment]
+1 for this feature, it will definitely helps the performance of the search itself.
