### ISSUE TITLE
Impossible to get all_terms when using facet

### ISSUE THREAD

**Issue by janoskaz** [karmi/retire#880]
Hi,
I have encounter following problem: I want to get table with frequencies of some keywords, which I can achieve like this:

``` ruby
s = Tire.search 'github' do
  query { term :_type, 'user' }    
  facet('codes'){ terms :country_code}  
end
```

but I get only 10 most frequent

when I pass option "all_terms => true", still, I got only 10 most frequent, because option "size => 10" remains in the query

``` ruby
s = Tire.search 'github' do
  query { term :_type, 'user' }    
  facet('codes'){ terms :country_code, :all_terms => true}  
end
```

```
s.facets
=> {"codes"=>{:terms=>{:field=>:country_code, :size=>10, :all_terms=>true}}}
```

Even setting "size => nil" does not do the trick

Of course, setting ":size => sufficiently high number" would solve the problem, but I would like to avoid it

Is this a bug, or am I missing something?

Zbynek

**Comment by karmi** [comment]
It's probably a bug, but I think the "sufficient high number" is a good workaround for now. If you'd like to submit a patch, please send it in a pull request!

**Comment by janoskaz** [comment]
Update: after some reading I have found out, that: 
"This has been fixed in the 0.90 branch. Note: all_terms doesn't mean that it will return all terms in the index. It means that it will return all terms even if their count is zero, up to the specified size."
(https://github.com/elasticsearch/elasticsearch/issues/1530)
Therefore current functionality is correct and it is not a bug

**Comment by nicolasgarnil** [comment]
Does the "sufficient high number" workaround has any drawbacks? Isn't really any way to ensure all the terms are returned?

**Comment by karmi** [comment]
@negarnil You just have to specify the size, that's the only option.
