### ISSUE TITLE
why is the github repo called retire instead of tire?

### ISSUE THREAD

**Issue by gfrivolt** [karmi/retire#882]
Is it going to retire? I hope not..

**Comment by benpickles** [comment]
It's being retired in favour of an official gem (which doesn't match Tire's functionality):

http://www.elasticsearch.org/blog/unleash-the-clients-ruby-python-php-perl/#ruby

**Comment by karmi** [comment]
Hi, I've added a banner to the README and also a Wiki page: https://github.com/karmi/retire/wiki/Tire-Retire
