### ISSUE TITLE
Elasticsearch returns result, but using Tire does not

### ISSUE THREAD

**Issue by nickcoyne** [karmi/retire#887]
I have an index defined on a Lesson model as follows:

```
  tire.settings :analysis => {
      :analyzer => {
        :kstem_no_stopwords => {
          "tokenizer"    => "lowercase",
          "filter"       => "kstem",
          "type"         => "custom"
        }
      }
    } do
    tire.mapping do
      indexes :name,                  :analyzer => 'kstem_no_stopwords', :boost => 2000
    end
  end
```

If I try Lesson.search('haystack') I get 

```
#<Tire::Results::Collection:0x007fbe24d71948 @response={"took"=>103, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}, @options={:size=>10}, @time=103, @total=0, @facets=nil, @max_score=0.0, @wrapper=Tire::Results::Item>
```

whereas if I query ElasticSearch directly I get a result

```
curl -XGET 'localhost:9200/lessons/_search?q=name:haystack'
```

gives

```
{"took":165,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":2,"max_score":2795.0693,"hits":[{"_index":"lessons","_type":"lesson","_id":"418934","_score":2795.0693, "_source" : {"id":418934,"...
```

Is this a bug or am I doing something wrong?

**Comment by dzhlobo** [comment]
Hi @nickcoyne.

Look at your requests. In the first case you search by 'haystack' but in the second case your search string is 'name:haystack'. `Lesson.search('name:haystack')` will do the same as your curl request. Also you can give a list of fields you want to search by:

``` ruby
Tire.search 'lessons' do
  query do
    match ['name', 'whatever'], 'haystack'
  end
end
```

**Comment by nickcoyne** [comment]
Thanks, that helps. 

Then a question that I guess is more related to ElasticSearch than Tire... why does it only return a result when I specify the field in the query? Using the above example, `Lesson.search('haystacks')` does return a result (the lesson name includes the word "haystacks"), but `Lesson.search('haystack')` returns no result.

**Comment by dzhlobo** [comment]
> why does it only return a result when I specify the field in the query?

When you don't specify field (in that particular case), Elasticsearch (actually Lucene) don't know which analyzer to apply for your request. And when you do, it uses the analyzer which you specified for the field in mapping.

You can specify analyzer by hand:

``` ruby
Tire.search 'lessons' do
  query do
    string 'haystack', analyzer: 'kstem_no_stopwords'
  end
end
```

`#search` method in model generates "Query String" query without specifying any parameter except of `query`. Read more about this type of queries in Elasticsearch's guides: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html.

Hope it is clear :).

**Comment by nickcoyne** [comment]
Thanks for that. Problem solved.
