### ISSUE TITLE
Tire returning no "hits" with Bonsai Elasticsearch

### ISSUE THREAD

**Issue by colewinans** [karmi/retire#893]
Locally, tire and elasticsearch work. However, tire doesn't seem to be working well with Bonsai on Heroku.

The index builds properly, however, Tire is not hitting the index with the search method. When I inspect the search method called on my model, I get the following:

```
#<Tire::Results::Collection:0x0000000659ab90 @response={"took"=>2, "timed_out"=>false, "_shards"=>{"total"=>1, "successful"=>1, "failed"=>0}, "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}, @options={:load=>true, :size=>100}, @time=2, @total=0, @facets=nil, @max_score=0.0, @wrapper=Tire::Results::Item>
```

I've followed this gist to a T: https://gist.github.com/nz/2041121

It may be worth cross-referencing a StackOverflow post I have with the same issue (where I share the code for my controller, model, initializer, etc.): http://stackoverflow.com/questions/19471707/tire-returning-no-hits-with-bonsai-elastic-search-on-heroku

**Comment by karmi** [comment]
Hey, cross-posting between Github issues and Stackoverflow is actually something which makes it very hard for me and others to help you. Since the SO post contains more detail, I'm closing this one.

CC @nz since it's a Bonsai issue.

**Comment by nz** [comment]
Thanks for the cc. This doesn't sound familiar to me, but @colewinans should drop us an email at support@bonsai.io with relevant URLs so I can investigate more directly.

**Comment by colewinans** [comment]
Thanks guys
