### ISSUE TITLE
Suggester in mappings

### ISSUE THREAD

**Issue by bramu** [karmi/retire#894]
Hi,

I am wondering how we can add the suggest in the mapping using retire, Could you please let us know. Here is the url for the suggestor doc from es.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html#completion-suggester-mapping

Thanks!

**Comment by karmi** [comment]
See #857

**Comment by bramu** [comment]
Hi Karmi,

Thanks for pointing me to the correct issue, but when I try to add from that fork, it is throwing me the below error. I think I am missing something here. 

irb(main):007:0> Artist.create_elasticsearch_index
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":"MapperParsingException[mapping [artist]]; nested: MapperParsingException[No handler for type [completion] declared on field [suggest]]; ","status":400}

Can you please give me the correct Gemfile entry for this commit?

Thanks!
