### ISSUE TITLE
rails 4 and jruby

### ISSUE THREAD

**Issue by anggainwgs** [karmi/retire#896]
Hi guys,
I'm using rails 4 with jruby 1.7.4
it not work well like when I used rails 3.2 with jruby 1.7.2
I always get nothing from my search!
and would you tell me if there is any extra config?

Thanks before!

**Comment by redrick** [comment]
have you run through for example this code here

```
https://gist.github.com/karmi/3200212
```

it gives you whole demo of retire elasticsearch :)
you will maybe find those missing configs in there :)

**Comment by karmi** [comment]
@anggainwgs Tire should work with both Rails 4 and jRuby just fine. It's not really too helpful to tell us “I always get nothing from my search!”, since we can't really know anything about your data, about the query you do, etc. Please update the issue with more information.
