### ISSUE TITLE
Include Tire methods in model top-level namespace, if not clashing with existing methods

### ISSUE THREAD

**Issue by karmi** [karmi/retire#9]
If we're not stepping on other libraries' toes, bring Tire methods like `index`, `search`, `mapping` also to the class/instance top-level namespace.

**Comment by pacoguzman** [comment]
Maybe we could do some like this:

alias_method :index, :tire_index unless method_defined? :index

Tire should define tire_method_name methods an execute this code when the module is included

**Comment by karmi** [comment]
Yeah, that's exactly what I'd like to do in the end -- but only after the "proxy" object (karmi/tire#8) is available...

**Comment by karmi** [comment]
DONE! https://github.com/karmi/tire/blob/1255bfc9964dff2b053776ff7993d792022aff29/lib/tire/model/search.rb#L177-191
