### ISSUE TITLE
Add delete_by_query

### ISSUE THREAD

**Issue by olivere** [karmi/retire#90]
I didn't find a simple way to use the `delete_by_query` feature from Elasticsearch (see [here](http://www.elasticsearch.org/guide/reference/api/delete-by-query.html)). Of course, one could use `Tire::Configuration.client`, but I think it could be directly supported.

I'd be willing to work on this (same for the timeout issue), if you like.

**Comment by karmi** [comment]
I'm not sure how much `delete_by_query` is generally useful, but yeah, it would be great to have it. What about the interface? Pass a query block to `Tire::Index.remove`?

**Comment by olivere** [comment]
It'd be worthwhile when you need `dependent: :delete_all` semantics, e.g. you have a product catalog entity in DB and its products in ES-only. When you remove the product catalog, the products need to be purged from ES. Does that make up a use case?

Regarding the interface, `remove` looks good. Does `delete_by_query` in ES accept the same parameters as a standard query? Have to check that. We could reuse the Tire query interface then, couldn't we?

**Comment by karmi** [comment]
I'm pretty sure there are use cases -- I'd only be wary of performance on large datasets and predictability for some queries. Destructive actions should be predictable.

Yes, AFAIK `delete_by_query` has the same interface, it's just a `DELETE`, not `GET` request. Didn't investigated that, though...

**Comment by olivere** [comment]
Right, I really have to check performance impact of destructive actions. I could live with low-priority removal in a background task--as long as the root object is gone (the product catalog in the above sample), it's no big deal.

**Comment by olivere** [comment]
Maybe it'd be better to do some "index alias juggling" instead of using `delete_by_query`. You already mention that in your README.

Which brings up the next issue which is how to handle index aliasing with Tire. Do you have any plans and/or thoughts about this?

Before going off-topic: Do you think this is the right place to discuss this, or would it be time to start a mailing list?

**Comment by karmi** [comment]
For almost any use case, a ["sliding window"](http://www.slideshare.net/karmi/your-data-your-search-elasticsearch-euruko-2011/52) approach would be better, I think.

That said, I can see how the `delete_by_query` could be nicely supported by an API outlined above.

And, regarding the discussion place: I, myself, don't mind discussing everything related to _Tire_ here, in Github issues. Maybe folks who follow the project do mind the constant chatter in their Github feed, I don't know. I just don't wanna to take care and maintain another communication channel, given how much Google Groups sucks, and how Librelist is half-baked... Anybody has any opinion on this?

**Comment by karmi** [comment]
Hey, been meditating on this with @vhyza. The problem is neither _RestClient_ nor _Curb_ support sending bodies in `DELETE` requests. Don't know what RFC says here.

For simple queries, you can do it like this:

``` ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'tire'
extend Tire::DSL

index 'articles' do
  delete
  create

  store type: 'article', title: 'One',   tags: ['ruby']
  store type: 'article', title: 'Two',   tags: ['ruby', 'python']
  store type: 'article', title: 'Three', tags: ['java']
  store type: 'article', title: 'Four',  tags: ['php']

  refresh
end

puts "", "Matching results:"
search = Tire.search('articles') { query { string 'tags:ruby' } }
p search.results.map(&:title)

puts "", "Deleting results..."
p Tire::Configuration.client.delete "#{Tire::Configuration.url}/articles/article/_query?q=tags:ruby"

puts "", "The index now contains:"
index('articles').refresh
p Tire.search('articles') { query { all } }.results.map(&:title)
```

Good luck! :P
