### ISSUE TITLE
Using Validate API Through Tire

### ISSUE THREAD

**Issue by benubois** [karmi/retire#905]
Is there a way to access the [validate API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-validate.html) through tire?

**Comment by karmi** [comment]
No support in Tire, can you use the new Ruby client here? https://github.com/elasticsearch/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/indices/validate_query.rb

**Comment by benubois** [comment]
Ok thanks. It wouldn't be a problem to use elasticsearch-ruby and tire would it?

**Comment by karmi** [comment]
No, they shouldn't clash in any way.
