### ISSUE TITLE
Sidekiq/Resque for after_destroy

### ISSUE THREAD

**Issue by mengqing** [karmi/retire#911]
``` ruby
class Article < ActiveRecord::Base
    include Tire::Model::Search

    after_save    { Indexer::Index.perform_async(document) }
    after_destroy { Indexer::Remove.perform_async(document) }
end
```

Looking at this code example from the Readme
1. I'm getting undefiend method `document` error
2. How would I get the background process to delete the index with the after_destroy callback. I've changed to the following

``` ruby
after_destroy { Indexer::Remove.perform_async(self.id, self.class) }
```

But how do I get the object and aync delete the index when it has already been destroyed?

Thanks

**Comment by karmi** [comment]
The code is only illustrative -- you have to implement the worker logic yourself. Also, have a look at https://github.com/EvilFaeton/tire_async_index
