### ISSUE TITLE
update index of single attribute

### ISSUE THREAD

**Issue by jeremylynch** [karmi/retire#917]
How can I update the index of just one attribute for a document?

**Comment by karmi** [comment]
Could you add a concrete example? I don't understand.

**Comment by jeremylynch** [comment]
I have a document with the attribute 'name' when the name attribute is updated, I would like to update the index for this document. Is it possible to update just the 'name' attribute or does the entire index have to be updated?

**Comment by karmi** [comment]
Understood -- in Tire, the whole document is re-indexed with the default callbacks. 

a) You can of course use the `Index#update` method, to partially update the document yourself, by reading the `changes` attribute and storing it, etc

b) In the new Ruby model integration, all this will be automatic for models which implement the [`ActiveModel::Dirty`](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html) interface.
