### ISSUE TITLE
How can I re-index, but still be able to modify the data in the meantime

### ISSUE THREAD

**Issue by demo3600** [karmi/retire#918]
Hi
we have an index that will need to be rebuild. But when we do that it take near an hour to achieved the job. So we will create a new index on the side and set an alias after that on this new index, to avoid downtime. But during this process, data can change in the databases. How could we get data change to be applied on both index?

**Comment by karmi** [comment]
Tire doesn't give you anything out of the box here.

The best option would probably be to intercept the changes, store them in some kind of queue, and "replay" them after the re-indexing is finished. Of course, you might want to use the versioning support, to not overwrite data which have been updated in the meantime, as you're replaying.
