### ISSUE TITLE
Upgrading elasticsearch to 0.90.0 from 0.20.4

### ISSUE THREAD

**Issue by jeremylynch** [karmi/retire#919]
<b> Firstly, does tire fully support elasticsearch version 0.90.0? </b>

I have upgraded to elasticsearch 0.90.7 in my local environment with homebrew ('brew upgrade'), reloaded elasticserach (run 'brew info elasticsearch' to get this info): 

```
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
```

flushed elasticsearch: 

```
curl -XPOST 'http://localhost:9200/_flush'
```

And reindexed my date 

```
rake environment tire:import CLASS='Document' FORCE=true
```

Everything appears to be working fine in my local development environment. 

How can I do the same in my production environment?

**Comment by karmi** [comment]
Yes, Tire is compatible with the 0.90.x series.

To upgrade your production, the decision factor is whether you can sustain downtime, a maintenance window.

Assuming you can, then just shutdown the server, [install](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup.html#setup-installation) 0.90.7 (via curl+extract, deb/rpm, etc), and start it up again. Of course, depends on how you have it installed in production, you have to keep the elasticsearch.yml and data folders around, etc.

No need to reindex data from Ruby, by the way, Elasticsearch 0.90 will hapilly work with data from 0.20.
