### ISSUE TITLE
Sorting by integer issue

### ISSUE THREAD

**Issue by jeremylynch** [karmi/retire#920]
I am having an issue with sorting of my documents by an integer (number of views). Previously, I wasn't having any issues, but an unknown commit changed this, the sorting seems in some ways ordered, but many documents are out of place and I don't understand what is wrong. 

I have reindexed my data in vain with the following: 

```
rake environment tire:import CLASS='Document' FORCE=true
```

Interestingly, in my development environment after deleting all my documents and adding new ones, everything worked fine. Perhaps all that is required is to flush elasticsearch or to flush the cache?

**Comment by karmi** [comment]
More likely is that your mapping got setup incorrectly -- import with `FORCE` creates the index with mapping specified in the model.

There is no need to flush anything in Elasticsearch.
