### ISSUE TITLE
parser error only appears via tire

### ISSUE THREAD

**Issue by morphil** [karmi/retire#924]
this simple query

``` ruby
 s=Tire.search 'users' do
      query do
        boolean do
          should { string gender: 'male' }
          should { range :birth, { gte: 8, lte: 8} }
          should { range :dis1, { gte: 1, lte: 1} }

        end
        #score_mode 'total'
      end
    end
```

errors with:

```
QueryParsingException[[users] [query_string] query does not support [gender]]
```

However GETing the same url in a browser works fine....
http://localhost:9200/users/_search?size=100&pretty'%20-d%20'{%22query%22:{%22bool%22:{%22should%22:[{%22query_string%22:{%22query%22:{%22gender%22:%22male%22}}},{%22range%22:{%22birth%22:{%22gte%22:8,%22lte%22:8}}},{%22range%22:{%22dis1%22:{%22gte%22:1,%22lte%22:1}}}]}},%22size%22:100}

**Comment by karmi** [comment]
That's because you have an error in your `string` query syntax, correct is:

``` ruby
should { string "gender:male" }
```

**Comment by morphil** [comment]
that certainly did it. must have misread to docs.

thanks

Mor Philosoph
c: (011) 972 52 6172257
H: (011) 972  3 6995102
