### ISSUE TITLE
keyword terms of query

### ISSUE THREAD

**Issue by suresh4154** [karmi/retire#926]
HI,

```
     First of all thanks to the Tire team. I have a requirement to know the keyword terms of a query.
```

For example if I pass a query like "austin happy hours", then I would like to know on which keyword basis it is making search (like austin,happy,hours,austin happy,austin dance... etc.,)

Is there any method in the tire to find out the keywords of query. If there is anything please let me know.

When we try to make search with a keyword "business",it is giving some different results 
(http://www.halfpastnow.com/search?key=business)

Thanks

**Comment by karmi** [comment]
Hi, sorry for the delay.

You can do two things here I guess:

1/ The easier one would be to use the `highlight` feature (search integration tests and the Elasticsearch documentation), which would give you back an Array of matching tokens. You can use this Array for implementing some custom logic.

2/ You can use the ["named queries"](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html#_named_queries) feature of Elasticsearch -- you would have to split your incoming query such as `austin happy hours` into individual tokens and pairs (word bigrams, trigrams, ...), and use the `bool` query to define a separate query for each.
