### ISSUE TITLE
high and low frequency operator

### ISSUE THREAD

**Issue by suresh4154** [karmi/retire#928]
HI,
Is there any way to use high frequency operator and low frequency operator for search query instead of default operator using tire gem. If it is possible, can you please build basic query for search which consists high or low frequency operator.

Elastic search reference link
http://www.elasticsearch.org/blog/stop-stopping-stop-words-a-look-at-common-terms-query/

**Comment by karmi** [comment]
The `common` query is not supported -- you're encouraged to use the new https://github.com/elasticsearch/elasticsearch-rails model integrations with the https://github.com/elasticsearch/elasticsearch-ruby gem.

**Comment by suresh4154** [comment]
Thanks, I go through the documentation and try to use the high frequency operator and low frequency operator, but It is raising some errors like unknown high_freq_operator.

If possible can you please build a search query using elasticsearch-rails by using the high or low frequency operator

**Comment by karmi** [comment]
Unfortunately, I don't have the bandwidth to prepare the query for you; the `elasticsearch-ruby` gem works with plain Ruby Hashes, so it should be dead easy to translate the query from the Elasticsearch's documentation to a Ruby query.

**Comment by rockaBe** [comment]
Could this issue be closed then?
