### ISSUE TITLE
Tire callbacks remove non-persistent attributes from Elasticsearch

### ISSUE THREAD

**Issue by jeroenr** [karmi/retire#934]
I have a simple ActiveRecord model, User, which has a few persistent attributes (i.e. stored in a SQL DB) and a few properties which only need to be indexed in Elasticsearch. It looks like this:

```
class User < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessor :status
  attr_accessible :uuid, :name, :status

  tire do
    mapping do
     indexes  :uuid,            :index  => :not_analyzed
     indexes  :name,            :type   => 'string'
     indexes  :status,          :type   => 'string'
    end
  end

  def self.partial_update(id, partial_doc)
   index = Tire.index 'users' do
     update('user',id, :doc => partial_doc)
     refresh
   end
   index.response.success?
  end
end
```

So, basically I can create a User (i.e. User.create(hash)) and do updates (@user.update_attributes(hash)). Tire's callbacks make sure the Elasticsearch index is in sync with the SQL DB. 

I can also do User.partial_update(id, hash) which only updates Elasticsearch. This works fine and in practice I use this to update the 'status' attribute frequently.

However, when I persist my User to the database (e.g. @user.update_attributes, @user.save!, etc) the 'status' field gets removed from Elasticsearch, even wel I explicitly set the status attribute on the user object (i.e. u.status = "foo"). This is undesired behaviour.

**Comment by karmi** [comment]
Hmm, I'm wondering why this might be... Do you define the `to_indexed_json` method? Is the status part of it? What is the output of `@user.to_indexed_json`? Finally, you can enable detailed logging with `Tire.configure { logger STDERR, level: "debug" }` to see all communication with ES.

Also, there's a new ActiveModel integration available here: https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model, with similar semantics as Tire has. I advice to evaluate and potentially migrate to that..

**Comment by jeroenr** [comment]
Thanks for your quick reply. I didn't define the to_indexed_json method. I rely on the default implementation which is based on to_hash. But, now I see indeed that the status attribute is not part of the to_hash output. So, I guess that explains the behaviour. Am I missing something basic?

Anyway, It might be a good idea to define the to_indexed_json and make sure I include the non-persistent attributes. Or I can override the 'attributes' method and merge my attr_accessor attributes in, so to_hash should pick it up.

**Comment by karmi** [comment]
It definitely [_should_](https://github.com/karmi/retire/blob/master/lib/tire/model/search.rb#L167-L190) serialize all regular attributes of your model. The `to_hash` method defined in Tire delegates to [`serializable_hash`](https://github.com/karmi/retire/blob/master/lib/tire/model/search.rb#L290) -- can you inspect your model and see any discrepancies there? Maybe some other gem redefined the `to_hash`?

Again, make sure you evaluate the new [`elasticsearch-model`](https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model) gem...

**Comment by jeroenr** [comment]
I found a related issue on stackoverflow http://stackoverflow.com/questions/11986792/non-persistent-activerecord-model-attributes 

So when I do override the attributes method like is suggested, the 'status' field is present in the JSON generated by the default implementation of to_indexed_json. I believe this is acceptable for me. Anyway, it doesn't seem to be a Tire issue, but more like a general Rails issue.

I definitely will checkout the new elasticsearch-model gem, thanks for the tip!

**Comment by rockaBe** [comment]
Could this issue be closed then?
