### ISSUE TITLE
Can't access model instance methods

### ISSUE THREAD

**Issue by lennartkoopmann** [karmi/retire#94]
I am sure that I did or understood something wrong - I hope somebody can help me.

In my Rails 3 application I have a "Message" model that looks something like this:

```
class Message
  include Mongoid::Document
  include Tire::Model::Search
  index_name "test"

  def to_indexed_json
    self.to_json
  end

  def created_at_time
    Time.zone.at(self.created_at)
  end
end
```

Now when I do this:

```
Message.search("*", :per_page => 100).each do |f|
  f.created_at_time
end
```

created_at_time gives back nil and f.methods does not show any of my "Message" model instance methods. Why not? I would suspect f to be an instance of Message.

All the attributes/fields of the messges are there and work fine.

Thanks!

**Comment by karmi** [comment]
Hi,

you have to include the `created_at_time` custom method in `to_json` call (as suggested by the readme):

``` ruby
      def to_indexed_json
        to_json :methods => ['created_at_time']
      end
```

The returned results are _not_ instances of you `Message` model, but instances of `Item`, which you can generally use interchangeably. You can eagerly load the instances from your database -- see the information in the Readme.

**Comment by lennartkoopmann** [comment]
How am I suspected to access the created_at_time method then? The README is not very helpful with this.

**Comment by karmi** [comment]
The Readme says:

> This way, we can index whatever JSON we like in ElasticSearch, and retrieve it, simply, via the dot notation:
> ...
> puts article.title
> ...

Can I make it more clear, somehow?

**Comment by lennartkoopmann** [comment]
Well I tried that, but `msg.created_at_time` is still nil and not called.

```
def to_indexed_json
  to_json :methods => [ 'created_at_time' ]
end
```

As an improvement for the README I think it could be more structured. It is good that it's a real text to make people completely read it before starting but it makes looking up things hard.

**Comment by karmi** [comment]
Could you have a look in your index, http://localhost:9200/test/message/_search?q=*, how is your documents stored there? If you added a `to_indexed_json` method like the one above, restarted the app/console, and added some documents, or reimported, you shoud definitely be able to access it as `Message.search("*").first. created_at_time`.

**Comment by lennartkoopmann** [comment]
ahhh, of course, I forgot that this will only work with messages imported via tire - Thanks.

The Problem is, that the messages get indexed by a whole other system and there are instance methods of the model that do dynamic stuff that can't be calculated when stored. Seems like I have to think about some stuff again - Thanks!

**Comment by karmi** [comment]
Hi,

> the problem is, that the messages get indexed by a whole other system and there are instance methods of the model that do dynamic stuff that can't be calculated when stored (...)

yeah, you can load the models from the underlying storage with the `:load` option or `load` method.
