### ISSUE TITLE
ActiveRecord 4.1 Support

### ISSUE THREAD

**Issue by benubois** [karmi/retire#941]
It looks like tire no longer works when using ActiveRecord integration with the `:load` option on Rails 4.1.0.rc1. 

This is the code that causes an error in [collection.rb](https://github.com/karmi/retire/blob/3805ff0a50eb31954ec5eada62884b884789cb0d/lib/tire/results/collection.rb#L156-L158)

``` ruby
def __find_records_by_ids(klass, ids)
  @options[:load] === true ? klass.find(ids) : klass.find(ids, @options[:load])
end
```

The `klass.find(ids, @options[:load])` part is the problem. ActiveRecord 4.1 no longer accepts an options hash argument here.

If `:include` is the only key that is ever used then one option that would work with ActiveRecord 4.0 or later is:

``` ruby
klass.includes(@options[:load][:include]).find(ids)
```

Alternatively it might work if you make [Active Record Deprecated Finders](https://github.com/rails/activerecord-deprecated_finders) a dependency.

Happy to submit a pull request but would appreciate your thoughts.

Thanks!

**Comment by karmi** [comment]
Hi, thanks for looking into it in detail!

I'm not principially oposed to making it work on AR 4.1+, but I think it would be a wasted time for anybody involved. The gem is effectively retired, no major features will be added, and people are actively adviced against using it.

The new `elasticsearch-model` and `elasticsearch-rails` gems [https://github.com/elasticsearch/elasticsearch-rails] are the future of Elasticsearch & Rails integration -- have you checked them out?

**Comment by benubois** [comment]
Hi @karmi,

Yes that makes sense, however I wasn't clear if `elasticsearch-model` and `elasticsearch-rails` should be used either since they say they are pre-release.

I already use `tire` in production and if it is difficult to migrate to the replacement gems then it might be easier to continue using tire. Is there a migration guide available? Also is support for the percolate API implemented? I couldn't find it in the docs.

Thanks!

**Comment by karmi** [comment]
Hey,

first, the migration should be easy. There's no Ruby DSL in the new gems, but given how much tricky the Tire DSL can be at times, that's for the better for everyone involved I guess.

There is, and won't be, a "migration guide" -- the semantics are very similar, and the new gem is extensively documented, with examples and integration tests.

I stongly advice you _against_ using Tire in production, unless you have some really compelling reason.

>  I wasn't clear if elasticsearch-model and elasticsearch-rails should be used either since they say they are pre-release.

So, if I remove the `pre` from `version.rb`, do you think it will magically work better? :) I wouldn't judge software by the number, but by the code, the docs, the tests.

**Comment by karmi** [comment]
>  (...) is support for the percolate API implemented (...)

Percolation has changed in Elasticsearch 1.0, so it's no longer possible to percolate during indexing, something Tire made really simple.

There's no explicit support for percolation in the elasticsearch-rails gems, I haven't been thinking about it deeply, but I think it's more of an end-user's thing -- if you wanna trigger some event when you index a specific document, just put those docs as Hashes on a queue (Resque, Sidekiq, RabbitMQ, ...), consume them, do something based on response...

See the [`percolate`](http://rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#percolate-instance_method) documentation.

**Comment by benubois** [comment]
Thanks for all the info. I'll look into switching to `elasticsearch*`.
