### ISSUE TITLE
Cannot connect to Elasticsearch when starting Rails console

### ISSUE THREAD

**Issue by Linuus** [karmi/retire#942]
When I start the rails console on my servers I get this error:

```
Skipping index creation, cannot connect to Elasticsearch
(The original exception was: #<SocketError: getaddrinfo: Name or service not known>)
```

The URL for Elasticsearch is set in my environment configs like this:

```
ENV['ELASTICSEARCH_URL'] = "http://myserver.com:9200"
```

This is set in each environment file, staging.rb, production.rb and so on.

Why do I get this error when I start the console?

Also, I use index aliases, so my indices are named:

```
mymodel_staging_201401011244
```

With an alias called `mymodel_staging`. Then I have a rake task which creates new indices and aliases them correctly.

I guess the reason is that the `ENV['ELASTICSEARCH_URL'] = ....` in my environment configs has not been run yet before my models load and Tire tries to check if my indices exists?

How can I avoid this error?

**Comment by Linuus** [comment]
I added this to my hosts file and the errors went away:

```
127.0.0.1          localhost
```

It's a bit weird because it also solved the issues in my production environment where elasticsearch is running on another server, i.e. _not_ localhost

**Comment by karmi** [comment]
Where do you put the `ENV['ELASTICSEARCH_URL'] = "http://myserver.com:9200"` config? And why do you do it like that? If you want to configure Tire for a specific server, just use some initializer with the `Tire.configure` block.

The environment variable is preferable, but you have to run it like this then:

``` bash
ELASTICSEARCH_URL=http://myserver.com:9200 bundle exec rails console
```

**Comment by Linuus** [comment]
I have the `ENV['ELASTICSEARCH_URL'] = "http://myserver.com:9200"` in my environment configs,
staging.rb, production.rb etc. since I want different urls for different servers.

If I use an initializer `tire.rb` I have to do something like:

```
if Rails.env.staging?
    Tire.config...
elsif Rails.env.production?
    Tire.config...
....
```

I mean, the environment config files is supposed to be used for specifying configs for different environments, right?

**Comment by karmi** [comment]
Yeah, then configure the Tire client directly in each environment file, that should work.

**Comment by Linuus** [comment]
OK, and not use the ENV variable?

**Comment by karmi** [comment]
Not when you _directly_ set the URL in a `Tire.configure` block :)

**Comment by Linuus** [comment]
No, of course :) I meant that I should use

```
Tire.configure do
    url....
end
```

and not the ENV style.

May I just ask why this would work but not the ENV variant? I mean, Tire uses the ENV if it is set, right? Otherwise it uses the config url or falls back to localhost.

**Comment by karmi** [comment]
OK, so let me explain it again :)
1. The _simplest_ way how to configure the URL is to use the ENV variable. You have to set it in the environment, though, either with `export` or when running the command. This is what Heroku does by default, and is recommended by the [12factor](http://12factor.net/config) design. In other words, _do not set it in you Ruby code, but "on the command line"._
2. If you want to configure Tire differently for each environment, use the initializers with `Tire.configure` Ruby blocks. It has all the downsides associated with it -- the config is baked into the codebase, into the Git repo, etc.

**Comment by Linuus** [comment]
Ok, thank you for the explanation!
