### ISSUE TITLE
Tire::Model::Persistence fails to save documents with ES 1.0

### ISSUE THREAD

**Issue by sigmarstern** [karmi/retire#943]
The return value of the `save` method in `Tire::Model::Persistence::Storage::ClassMethods`relies on ES's response having `"ok": true`, which has been removed with https://github.com/elasticsearch/elasticsearch/issues/4310. Thus `save` always returns `false`, no matter if `index_update` was successful or not.

A solution might be setting this response value by default in `Tire::HTTP::Response`:

``` ruby
body['ok'] ||= self.success?
```

**Comment by karmi** [comment]
True. However, I'd keep Tire on 0.90 series -- people should really migrate to https://github.com/elasticsearch/elasticsearch-rails/

**Comment by ghost** [comment]
@karmi you should probably update the README with a notice now that 1.0 is out. I know it’s pretty clear that Tire is deprecated, but the more info the better.

**Comment by karmi** [comment]
@hydrozen Fair point. Tire works with 1.0 for many workflows, but obviously, this would also be a nice incentive to upgrade to the new gems.

@sigmarstern Waiting for your reply -- should I close the ticket? I'm really against any substantial effort to make Tire 1.0 compatible.

**Comment by ghost** [comment]
@karmi I would have opened a pull request but wasn’t sure how you wanted to word it. Thanks for adding it :+1: 

Keep up the good work.

**Comment by sigmarstern** [comment]
@karmi please go on, close the ticket. We decided to keep our current project on ES 0.90.\* until we managed to migrate to elasticsearch-rails. (I was just asking since I noticed other ES 1.0 related issues being solved here.)

**Comment by karmi** [comment]
@sigmarstern Yes, cool. Please _do_ consider upgrading to both ES 1.0 and the new gems as a priority, the benefits are really huge across the performance, flexibility, extendability, stability, predictability aspects... Ping me on the new repos issues or IRC if you need assistance or ping-pong something.
