### ISSUE TITLE
Add aggregations support

### ISSUE THREAD

**Issue by arion** [karmi/retire#948]
Hi

Could you add `aggregations` support (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations.html) to your`retire` gem?

Here is my usage example (https://gist.github.com/arion/9525840). I would like to do this by use standart DSL.

**Comment by karmi** [comment]
Hi, I'm sorry, but adding new features to the gem is not something I'd like to do -- it is effectively freezed.

**Comment by karmi** [comment]
Please check the https://github.com/elasticsearch/elasticsearch-rails and https://github.com/elasticsearch/elasticsearch-ruby projects.

**Comment by dfens** [comment]
+1
