### ISSUE TITLE
Facet sizing crash

### ISSUE THREAD

**Issue by craigsheen** [karmi/retire#949]
I am returning a number of facets from my search but I want/need it to return more than the default 10.

If I change this to be;

``` ruby
s.facet('brands') { terms :brand_id, size: 100 }
```

This fixes the issue.  However when I then use the facets to filter the search down, if the search does not return any results that have that facet (i.e. brand) and I have the size specified I get an error;

``` ruby
!! Invalid request
```

Any ideas how to solve this?

**Comment by craigsheen** [comment]
Ah sorry this is not actually an issue with tire.

I was passing the facets in the url as I needed to show them again but filter down on them, When I had large sizes the uri request was becoming too large and causing it to crash.

**Comment by karmi** [comment]
Ah, great. Was wondering what was causing it :)
