### ISSUE TITLE
Undefined method `encode_json`

### ISSUE THREAD

**Issue by leehambley** [karmi/retire#95]
Using `tire-0.3.2`:

``` log
(rdb:1) AffiliateProduct.search('schuhe').to_json
"[,,,,,,,,,]"
(rdb:1) AffiliateProduct.search('schuhe', :load => true).to_json
NoMethodError Exception: undefined method `encode_json' for #<AffiliateProduct:0x112a3fa58>
(rdb:1) AffiliateProduct.first.to_json
"{\"remote_id\":717880341,\"price\":\"17.1................on-handy-zubehoer-usb-sync-und-ladestation-fujitsu-loox-n500\",\"last_sync_date\":\"2011-05-26\"}"
```

I'm not sure whats really going wrong here, looks like the `:load => true` is causing something not to be loaded? Perhaps resetting attributes and failing to re-include/extend some modules from ActiveSupport? ( /cc @markohiel )

**Comment by karmi** [comment]
What are you trying to do? What do you think is an error here? What do you suggest?

Both of these calls work:

``` ruby
Article.search('lorem').to_a.to_json
Article.search('lorem', :load => true).to_a.to_json
```

Should `Results::Collection` implement `to_json`?

**Comment by leehambley** [comment]
I think so, as `Array`, and `ActiveRecord::Relation` both do? (it could easily defer to `#to_a`) At least I believe `AR::Relation` defers to `#to_a` already.

In the case that you agree, I'll gladly submit a patch, to the best of my ability.

(also my apologies, I wrote this ticket in haste whilst trying to assist a colleague getting some code running, I should have written it much more clearly)

**Comment by karmi** [comment]
I'm kinda wary about that... It starts with `to_json` and continues with `to_xml` and what else...

I think everybody is better off with just calling `#to_a` on the collection and can use whatever core extensions any gem brought into her app?

**Comment by leehambley** [comment]
(Thanks, I agree in hindsight)
