### ISSUE TITLE
Temporarily Disable Callbacks

### ISSUE THREAD

**Issue by rdetert** [karmi/retire#950]
I'm performing an operation which require me to iterate though every item in the table to generate slugs on save by running Model.find_each(&:save)

It is pretty quick except for the the Elasticsearch callbacks. Is there any way to disable these callbacks on the fly?

**Comment by karmi** [comment]
Hmm, I guess just "nuking" the callbacks by redefining them with `define_method` or `class_eval` or something like that...

**Comment by rdetert** [comment]
Fair enough. I think I may just run a cron job every hour to batch import new records.
