### ISSUE TITLE
Override _id

### ISSUE THREAD

**Issue by niuage** [karmi/retire#951]
It's pretty simple: I want to override the _id field. I want it to be the value of another field, not the id of my ActiveRecord model.

If I define an `_id` method on my model, and indexes it, I get the error:

`failed to parse [_id]` cause by `Provided id [5] does not match the content one [Xdevore]`

I think that might be because of the Tire method `get_id_from_document` that actually just get the model id to create the POST url.

Is there an easy way to override it?

Thanks!

**Comment by karmi** [comment]
Yeah, your right about the method -- the immediate solution would be to monkeypatch the `get_id_from_document` method, so it ignores your special `_id` method.

**Comment by niuage** [comment]
Ok thanks! (you mean "so that it doesn't ignore your special _id method", right?)

**Comment by niuage** [comment]
Ok, since I have you, let me ask you this: (don't worry about it if you don't have time, but you probably have a lot more experience than me on this so it might be obvious)

I have a parent/child relationship between items and players:

```
# item mapping
tire do
    mapping(
        _parent: { type: 'player' },
        _routing: { required: true, path: :account }
    ) do
        indexes :account, type: "string", index: :not_analyzed
 end

# player mapping
tire do
    mapping(
        _routing: { required: true, path: "account" }
    ) do
        indexes :_id, type: "string", index: :not_analyzed
        indexes :account, type: "string", index: :not_analyzed
end
```

To index my items, I overrode the `update_index` method, because items are indexed in different indexes depending on their league_id, and also so that I can provide the parent and routing:

```
def update_index
    run_callbacks :update_elasticsearch_index do
        if destroyed?
            index.remove self
        else
            options = { percolate: percolator}
            options.merge!({ parent: account, routing: account }) # if I do "parent: player.id" here, it works
            response = index.store(self, options)
            tire.matches = response['matches'] if tire.respond_to?(:matches=)
            self
        end
    end
end
```

My issue is that now that I've changed the `_id` of players to be their `account` name (and I've checked they're indexed correctly, with the account as their `_id`), my `has_parent` query doesn't work, as if the items are not linked properly with their player.

Thanks.

**Comment by karmi** [comment]
So, since you have `path: :account`, shouldn't you simply use an "account" property of your document for routing?

**Comment by niuage** [comment]
How do you do that? I'm passing the routing option set to `account` when indexing my items. Is there another way?
edit: the second mapping is the Player mapping.

**Comment by niuage** [comment]
After setting the `_id` to the `account` property, it actually worked. There was an issue on how I was updating the parents, that's why my query was not returning anything...
Thanks.
