### ISSUE TITLE
Using search with blocks results in a null query string.

### ISSUE THREAD

**Issue by therealjasonkenney** [karmi/retire#952]
The following based on the example in the readme:
puts Article.tire.search :load => true do
   query { string 'hello' }
end.results
Returns:
Failed to parse source [{\"query\":{\"query_string\":{\"query\":{\"load\":true}}},\"size\":10}

It seems no matter what, the block is completely ignored and it just passes the first argument as the query string. Even when I pass a string and then add a filter in the block, the filter is ignored. If tire was updated to disable using blocks, please update the README, I've never used tire before, and its rather confusing to not be able to even run basic examples.

Thanks.

**Comment by karmi** [comment]
Should be `puts Article.tire.search "something", :load => true do ...`.
