### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by 64kramsystem** [karmi/retire#956]
In the documentation at http://karmi.github.io/retire/ the example for configuring Tire is:

```
Tire.configure do
  url "http://search.example.com"
  # otherstuff
end
```

this is misleading, and won't work in standard configurations, because the port needs to be specified

In many gems, the port automatically defaults to the standard one when not specified, but (re)tire doesn't do it, so the example above won't generally work, because it will try to connect to port 80, which is very unlikely to be used in the ES server.

**Comment by karmi** [comment]
That's not that much misleading, since the intention of this example is _indeed_ to connect to port 80, presumably, to an Nginx/etc proxy in front of Elasticsearch. You generally don't and shouldn't have port 9200 open to the outside world.
