### ISSUE TITLE
Using auto fuzziness

### ISSUE THREAD

**Issue by Linuus** [karmi/retire#957]
Hi

I have a query that looks something like this:

```
[...]
query.boolean({:minimum_number_should_match => 1}) do |bool|
  bool.should { |m| m.match :_all, search_query.strip, fuzziness:  2 }
  bool.should { |m| m.string "title.autocomplete:#{search_query}", default_operator: 'AND' }
end
[...]
```

Instead of a fuzziness of 2 I'd like it to be calculated based on the length of the term, i.e. I want to use `AUTO` as specified here:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/common-options.html#fuzziness

Is this supported by Tire? If I set it to 'AUTO' as a string Tire crashes.

**Comment by karmi** [comment]
Hi, not sure, but have a look at https://github.com/elasticsearch/elasticsearch-ruby and https://github.com/elasticsearch/elasticsearch-rails, this gem is no longer recommended.

**Comment by Linuus** [comment]
Thank you. I used something like this instead:

```
[...]
query.boolean({:minimum_number_should_match => 1}) do |bool|
  bool.should { |m| m.match :_all, search_query.strip, fuzziness:  0.7 }
  bool.should { |m| m.string "title.autocomplete:#{search_query}", default_operator: 'AND' }
end
[...]
```

Which seems to work fine for me.
