### ISSUE TITLE
The persistance model assign random values to the ID field

### ISSUE THREAD

**Issue by codng** [karmi/retire#958]
When using the persistence model, the ID field gets assigned random values. There should be a way to increase its value as a counter of records, like it's supposed to be. so that ES can really be used as nosql database.

**Comment by karmi** [comment]
Hi, first of all, this gem is really, really "retired", so there's a little chance significant features will be added to it.

More importantly, ["stop using numbers as IDs"](http://postgres-bits.herokuapp.com/#54) :)

**Comment by codng** [comment]
I've read that using UUID is less performant, so it would be nice if it was optional. 
From your link it seems you're right, so gonna close this now. The new gem looks great but migrating to it is no easy task, sorry.
