### ISSUE TITLE
Allow to change type name

### ISSUE THREAD

**Issue by lennartkoopmann** [karmi/retire#96]
After looking in `Tire::Model::Naming` it seems like it is not possible to change the `document_type` name. It is possible with the `index_name` and should also be possible with the `document_type`. Currently it always is `klass.model_name.singular`.

**Comment by karmi** [comment]
Yeah, why not, while everybody can just overload `document_type`, it's indeed an unpleasant imbalance of the API.

**Comment by lennartkoopmann** [comment]
Thank you very much!
