### ISSUE TITLE
Crash when search query ends with special character (dash, colon)

### ISSUE THREAD

**Issue by Linuus** [karmi/retire#965]
Hi

I know this project is retired but I don't have time to migrate to the new gems at the moment, so hopefully someone can help me.

I use filters and analyzers which looks like this:

```
  {
    analysis: {
      analyzer: {
        default: {
          type: 'custom',
          tokenizer: 'standard',
          filter: ['standard', 'lowercase', 'asciifolding']
        },
        autocomplete: {
          type: 'custom',
          tokenizer: 'standard',
          filter: ['lowercase', 'asciifolding', 'edge_ngram']
        }
      },
      filter: {
        edge_ngram: {
          type: 'edgeNGram',
          min_gram: 4,
          max_gram: 25
        }
      }
    }
  }
```

Then when I search I do this:

```
bool.should { |s| s.string "title.autocomplete:#{search_query}", default_operator: 'AND', analyzer: 'default' }
```

When my `search_query` ends with a dash, colon or similar it crashes  with a big error:

```
400 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed
...
SearchParseException[[myindex_development_20140515160944][3]: from[-1],size[-1]: Parse Failure [Failed to parse source
....
```

If I remove the autocomplete search part above it works.
If I add a space to the end of the query everything works fine.

Why is this happening? Do I need to escape some characters?

It seems weird to just throw a space character at the end...

**Comment by karmi** [comment]
You shouldn't use the query string query unless you need all the power of Lucene syntax. Have a look at match query.

You need to escape special characters like [.

The actual error message is at the end of the error, so post it.

**Comment by karmi** [comment]
Also, are you sure that the 'search_query' is not empty?

**Comment by Linuus** [comment]
No, the `search_query` is not empty

I guess the escaping of reserved characters is the issue.
Error:
QueryParsingException[[departments_development_20140515160944] Failed to parse query [title.autocomplete:artikel -]]; nested: ParseException[Cannot parse 'title.autocomplete:artikel -': Encountered \"<EOF>\" at line 1, column 28.\nWas expecting one of:\n    <BAREOPER> ...\n    \"(\" ...\n    \"_\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"_\" ...\n    ]; nested: ParseException[Encountered \"<EOF>\" at line 1, column 28.\nWas expecting one of:\n    <BAREOPER> ...\n    \"(\" ...\n    \"_\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <NUMBER> ...\n    <TERM> ...\n    \"_\" ...\n    ]; }

How can I rewrite it to use match instead of string query?
This does not work:

```
bool.should { |m| m.match "title.autocomplete", search_query, default_operator: 'AND', analyzer: 'default' }
```

**Comment by Linuus** [comment]
Perhaps I cannot use `default_operator' on a match query?

**Comment by karmi** [comment]
Have you checked the documentation and the integration tests for match?

**Comment by Linuus** [comment]
Yes, I have tried :) The `default_operator` seems to be called `operator` in a match query.

My real query looks like this, rewritten with `match` and `operator` which seems to work:

```
query.boolean({minimum_number_should_match: 1}) do |bool|
  bool.should { |m| m.match :_all, search_query.strip, fuzziness:  0.7 }
  bool.should { |m| m.match "title.autocomplete", search_query, operator: 'AND', analyzer: 'default' }
  bool.should { |m| m.match "name.autocomplete", search_query, operator: 'AND', analyzer: 'default' }
end
```

From what I can see in the integration tests I don't need to manually create a boolean query here, right? It creates one automatically when match is called several times, right?

But...

Does it use 'should'?
How do I specify `minimum_number_should_match`?

EDIT:
I'll just use the above query as it works OK as far as I can see.
