### ISSUE TITLE
Elasticsearch 1.2.1, empty hash should be removed.

### ISSUE THREAD

**Issue by sdbondi** [karmi/retire#967]
When I use `filtered` and I don't happen to have any filters in the block (optionally filterable) I get an error on ES 1.2.1:

`ElasticsearchParseException[Expected field name but got START_OBJECT \"filtered\"]`

``` json
{
  "query":{
    "bool":{
      "should":[
        {
          "query_string":{
            "query":"name:*ma*"
          }
        },
        {
          "query_string":{
            "query":"description:*ma*"
          }
        }
      ]
    },
    "filtered":{} // HERE IS THE PROBLEM
  },      
  "sort":[
    {                    
      "created_at":"desc"
    }
  ],        
  "size":10,
  "from":0
}
```

Is this expected?

**Comment by sdbondi** [comment]
Hmm just noticed that an empty filtered is fine without a `bool` query: Could be an ES issue? I'll test with a previous version.

``` json
"query":{
 "filtered":{}
 },
 "sort":[
 {
 "created_at":"desc"
 }
 ],
 "size":10,
 "from":0
}
```

**Comment by karmi** [comment]
the nesting in your example is weird, the filtered query should be in another should or something like that.

**Comment by sdbondi** [comment]
Thanks for responding @karmi.
I want to filter out all the results from the optional query. I have many filters.
The ES api is still weird to me.

Here is my [abridged] query:

``` ruby
   self.tire.search(page: params[:page], per_page: params[:per_page]) do |s|
      s.query do |qry|
         qry.boolean do |b|
                b.should { string "company:*#{q}*" }
                b.should { string "description:*#{q}*" }           
           end 

           unless cost_events.blank? && fee.blank?
              qry.filtered do |f|
                  f.filter :terms, avg_cost_events_cd: cost_events unless cost_events.blank?
                  f.filter :terms, fee_cd: fee, execution: :and unless fee.blank?
                end
              end

            end
         end
      end
```

**Comment by sdbondi** [comment]
Even without filtered the the query fails with empty hashes:

`QueryParsingException[[(..)] [_na] query malformed, no field after start_object]`

``` json
{
  "query":{}, <- Fine without this
  "sort":[
    {
      "created_at":"desc"
    }
  ],
  "size":10,
  "from":0
}
```

The issue is that I have many optional filters and I don't want to have to check if I should call `s.query` only if I have any of my params not empty. Suppose that I can just check if params.blank? but what if I have other parameters that aren't filtered. Also that is stinky code.

I think this code worked with ES 1.0.0 - I'll spin up a docker instance of 1.0.0 and see. (can't now poor internet)

**Comment by sdbondi** [comment]
Not using `filtered` - which should be inside a query like [here](https://github.com/elasticsearch/elasticsearch/issues/1688#issuecomment-5415536) and instead just filtering in the search does what I wanted.

``` ruby
self.tire.search(page: params[:page], per_page: params[:per_page]) do |s|
      s.query do |qry|
         qry.boolean do |b|
                b.should { string "company:*#{q}*" }
                b.should { string "description:*#{q}*" }           
         end 
      end 

      s.filter :terms, avg_cost_events_cd: cost_events unless cost_events.blank?
      s.filter :terms, fee_cd: fee unless fee.blank?
end
```

I think I was using terms as a hash some of the time leading me to think that filter wasn't correct/working.
Was:
`s.filter :terms => avg_cost_events_cd: cost_events unless cost_events.blank?`
should be:
`s.filter :terms, avg_cost_events_cd: cost_events unless cost_events.blank?`

i.e as you probably suspected I was being a bit of a noob :P  So I suppose this is more of an elasticsearch/(re)tire docs/helpful error message issue. (Although, turns out it's pretty clear [here](http://karmi.github.io/retire/#section-Filtered_Search)) :smacks head:
