### ISSUE TITLE
Persistence module does not provide updating a record.

### ISSUE THREAD

**Issue by codomore** [karmi/retire#971]
I'm trying to user ES the persistance model, and do something simple like:
article = Article.find
article.content="somecontent"
article.save

It appears this is not supported.

**Comment by karmi** [comment]
I'm not sure what `Article.find` should do without an ID, and moreover, this gem is deprecated, use https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-persistence

**Comment by codomore** [comment]
I did in fact use Article.find(id), and it doesnt work .
